### ISSUE TITLE
Heavily buggy UI at Skia.Gtk

### ISSUE THREAD

**Issue by onionware-github** [unoplatform/uno#10210] opened 2022-10-21 12:16 UTC
### Current behavior

The UI of my app "OnionMedia", which looks fine in the Windows version, has severe bugs when running under Skia.Gtk. UI elements are blurry or missing, scrolling or window resizing doesn't work, and databinding doesn't work properly. The bugs appear on Windows and on Linux. It looks like that, very blurry and buggy and buttons/expanders/sliders often don't react to the user input:
![image](https://user-images.githubusercontent.com/91136545/197192438-5919555a-f58e-490c-a51a-d1f31b6d6790.png)
![image](https://user-images.githubusercontent.com/91136545/197193855-924fd668-673e-4202-8e4f-2bd1ee1fa73f.png)

Beta-Repo of OnionMedia: https://github.com/onionware-github/onionmedia-beta

### Expected behavior

The UI should look and feel like the Windows variant. It should look like this:
![image](https://user-images.githubusercontent.com/91136545/197192322-e83c647c-9756-48b1-9535-64741b47ad75.png)
![image](https://user-images.githubusercontent.com/91136545/197194039-3df18964-a382-47c1-be4e-ec9c6703c310.png)

### How to reproduce it (as minimally and precisely as possible)

Clone the OnionMedia Beta repository and run the Skia.Gtk version on Windows. (The bugs also appear on Linux. You can specify the start page in the App.xaml.cs from the Shared project.)

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia, Uno.UI.RemoteControl / Uno.WinUI.RemoteControl

### NuGet package version(s)

Uno packages => Version 4.5.12
Uno.CommunityToolkit packages => Version 7.1.100-dev.15.g12261e2626

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### IDE version

17.3.3

### Relevant plugins

ReSharper 2022.22.1

### Anything else we need to know?

I don't know why the Skia.Gtk version is so badly bugged, but it can't be shipped that way.

**Comment by jeromelaban** [comment] 2022-10-21 12:19
Thanks, this is a duplicate of https://github.com/unoplatform/uno/issues/9671. This particular case is caused by the use of rounded corners and as I mentioned, we're working on it.

**Closed by jeromelaban** 2022-10-21 12:19 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
