### ISSUE TITLE
[Calculator][Androi/iOS] The dot (.) button isn't visible on the landscape mode for Programmer and Scientific calculator

### ISSUE THREAD

**Issue by Hpancha** [unoplatform/uno#2166] opened 2019-11-22 21:02 UTC
### **Steps To Reproduce:**

1. Launch an UNO Calculator app.
2. Select **Scientific** or **Programmer** calculator.
3. Now put the app in landscape mode and observe the dot **(.)** button. 

### **Actual behavior:**

- The dot **(.)** is not visible on keypad when the app is in landscape mode.

### **Expected behavior:**

- User can clearly see all the button and the text written on it.

### **Attachments:**

![Scientific_Calculator](https://user-images.githubusercontent.com/51453677/69460140-5d71dd00-0d41-11ea-8cd2-3ab371a4feca.PNG)

![Programmer_Calculator](https://user-images.githubusercontent.com/51453677/69460147-606ccd80-0d41-11ea-9ef7-bac3bf900b90.PNG)

### **Device and Application Information:**
 - **OS Build:** ios and Android
 - **Build Version:** 1.2.0-uno.558
 - **Devices:**  iPhone XR (13.2), Samsung S10+ (9)

### **Note:**
- Refer the attached images to get better idea.

**Comment by robloo** [comment] 2019-11-22 22:47
The whole bottom of the app is cut off, you can only see the top of the other characters in the same grid row.

On my Android Samsung S10+ this is visible just fine in landscape mode. I would be curious to know what is drawing that 'swipe-up' handle at the bottom of your screen shot. Doesn't quite look like iOS to me (but I don't use iOS so am not sure). If it's an extension to Android that's probably what is doing it -- not Uno.

**Comment by jeromelaban** [comment] 2019-11-25 14:57
Indeed, there's some layout from the original calculator that does not fit there. An additional breakpoint should be added when the vertical size is this small.

**Comment by sakshi173** [comment] 2021-06-01 16:03
The issue is still is present.

**Comment by jeromelaban** [comment] 2021-06-01 16:05
This is not something we'll be able to fix without changing the buttons (maybe have ViewBox could help), as the original calculator was not meant to be displayed at this scale with this ratio.

**Comment by francoistanguay** [comment] 2021-06-26 18:18
Wont fix as it is an issue with original calculator.

**Closed by francoistanguay** 2021-06-26 18:18 UTC
Labels: area/eu, difficulty/medium, kind/bug, project/layout

**Comment by sakshi173** [comment] 2021-10-01 17:08
As per the above comment, its an issue with original calculator as well, closing it.
