### ISSUE TITLE
Wasm: FileOpenPicker's StorageFile throws exceptions during read

### ISSUE THREAD

**Issue by alove-kahua** [unoplatform/uno#5749] opened 2021-04-14 19:06 UTC
## Current behavior

While reading from a StorageFile's stream, an exception is thrown over and over.  It is handled on some level, but makes debugging other issues difficult as the browser debugger stops on it even when not catching caught exceptions.

## Expected behavior

No exception is thrown,

## How to reproduce it (as minimally and precisely as possible)
[StreamReadAsyncException.zip](https://github.com/unoplatform/uno/files/6313111/StreamReadAsyncException.zip)

1. Run the Wasm project.
2. Open the Developer Tools in Chrome.
3. On the Sources tab, ensure that the "Pause on exceptions" setting is turned on (The additional setting "Pause on caught exceptions" should be left unchecked).
4. Click the "Open File" button in the application and select a file from the dialog.

## Workaround

None.

## Environment

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment] 2021-04-15 20:11
@alove-kahua I was investigating this and unfortunately I don't see a way to avoid this behavior. According to the [W3 reference implementation](https://github.com/whatwg/streams/blob/0745219ca7b7f02ef104145b78ebebd99c0fd12c/reference-implementation/lib/readable-stream.js#L785-L801) it is the expected behavior that the exception is thrown on the promise while also handled by default. I checked the [chromium implementation here](https://github.com/refi64/chromium-tar/blob/82ebd6a0473341fa75dd3bbb2f584da99f5ac92c/third_party/blink/renderer/core/streams/readable_stream_reader.cc#L161-L199) and it seems to match this behavior. So this exception seems to be unavoidable, unfortunately...

**Comment by alove-kahua** [comment] 2021-04-16 14:33
@MartinZikmund Can it be caught so that it doesn't stop on the exception when "Pause on caught exceptions" is off?  My expectation with that setting off, it should stop on any handled exception.

**Comment by MartinZikmund** [comment] 2021-04-16 14:45
@alove-kahua I see I misread that, with that setting off it may be preventable. I will revisit this and let you know

**Comment by MartinZikmund** [comment] 2021-04-19 16:13
@alove-kahua Finally figured it out, it was a puzzle 😀 . PR is open, will be merged soon.

**Comment by alove-kahua** [comment] 2021-04-19 16:16
> @alove-kahua Finally figured it out, it was a puzzle 😀 . PR is open, will be merged soon.

Thank you, sir!

**Closed** 2021-04-20 00:22 UTC
Labels: difficulty/medium, kind/bug, project/winrt
