### ISSUE TITLE
AutoReverse in Double Animation doesn't work in WASM

### ISSUE THREAD

**Issue by Strypper** [unoplatform/uno#9290] opened 2022-07-16 03:10 UTC
### Current behavior

```
<Storyboard x:Name="Fade_Animation">
            <DoubleAnimation Storyboard.TargetName="ColorPalleteStatus"
							     Storyboard.TargetProperty="Opacity"
							     From="0"
							     To="1"
                                                             AutoReverse="True"
							     Duration="0:0:2" />
</Storyboard>
```
The above animation will fade in and fade out because of the AutoReverse property
In WinUI3: Animation do AutoReverse
In WASM : Animation Fade in but doesn't fade out

### Expected behavior

WASM do AutoReverse

### How to reproduce it (as minimally and precisely as possible)

Use the above code or try out from this sample on github 
https://github.com/Strypper/PixelArt

1. Create new art
2. Pick a color
3. Pick the same color again
4. The text will fade in to warn the user and fade out

### Workaround

No work around now

### Works on UWP/WinUI

Yes

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

Preview

### Anything else we need to know?

No

**Comment by jeromelaban** [comment] 2022-08-01 15:43
Thanks for the report. This is a duplicate of https://github.com/unoplatform/uno/issues/6027

**Closed by jeromelaban** 2022-08-01 15:43 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
