### ISSUE TITLE
[Gallery-4X][Android][ShadowContainer]Checkbox- checking  and unchecking of Checked and Unchecked box is not working properly.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#13557] opened 2023-09-07 18:29 UTC
### Current behavior

https://github.com/unoplatform/uno/assets/74563602/05f30412-d251-460f-9a23-23ca9f2fbb3f

### Expected behavior

https://github.com/unoplatform/uno/assets/74563602/9210c39b-2c9c-44ed-92b2-4e51c2cfc0dd

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallery app for 4X or 5X version for Android.
2. Click on “ShadowContainer” from the "Toolkit" list.
3. Go to Neumorphic section.
4. Choose 'Checkbox' option from the combo list.
5. Tap on checked and unchecked box option.
6. Notice that checking and unchecking is not changing every time.

### Works on UWP/WinUI

None

### Affected platforms

Android

**Comment by agneszitte** [comment] 2023-09-08 15:41
Please check with the latest packages if the issue is related to the Neumorphic Style itself, the control, or the ShadowContainer please

**Comment by Marc-Antoine-Soucy** [comment] 2023-09-08 16:59
I will continue to investigate monday, but here is the result of my investigation so far: 
What I did was replace the content of a page with 
```
<StackPanel Spacing="20" Margin="0,40,0,0">
				<!-- Enabled -->
				<CheckBox Content="Unchecked"
						  Style="{StaticResource NeumorphicCheckBoxStyle}"
						  Click="OnButtonClicked"/>
				<CheckBox Content="Checked"
						  IsChecked="True"
						  Click="OnButtonClicked"
						  Style="{StaticResource CheckBoxStyle}" />
				<CheckBox Content="Indeterminate"
						  IsChecked="{x:Null}"
						  Click="OnButtonClicked"
						  IsThreeState="True"
						  Style="{StaticResource NeumorphicCheckBoxStyle}" />

				<Button Style="{StaticResource NeumorphicSmallElevatedButtonStyle}"
						Content="Small"
						Click="OnButtonClicked"/>

				<Button Style="{StaticResource NeumorphicMediumElevatedButtonStyle}"
						Content="Medium with icon"
						Click="OnButtonClicked">
					<um:ControlExtensions.Icon>
						<PathIcon Data="M12 6.85714H6.85714V12H5.14286V6.85714H0V5.14286H5.14286V0H6.85714V5.14286H12V6.85714Z" />
					</um:ControlExtensions.Icon>
				</Button>

				<Button Style="{StaticResource NeumorphicLargeElevatedButtonStyle}"
						Content="Large with icon"
						Click="OnButtonClicked">
					<um:ControlExtensions.Icon>
						<PathIcon Data="M12 6.85714H6.85714V12H5.14286V6.85714H0V5.14286H5.14286V0H6.85714V5.14286H12V6.85714Z" />
					</um:ControlExtensions.Icon>
				</Button>


			</StackPanel>
```
And 
```
private void OnButtonClicked(object sender, RoutedEventArgs e)
{
	Console.WriteLine("Button was clicked!");
}
```
in the code behind.

So, what I can tell so far is that when you click on the neumorphism style of the checkbox, it fires the click event twice almost every time you click on it. This never happens with the material style. This, however, also happens on the neumorphism  style buttons. And I think it happens more often on the smaller buttons than on the smaller buttons. So, what my conclusion so far is that either it's a problem with the shadow, or a problem shared across several neumorphism style.

**Comment by Marc-Antoine-Soucy** [comment] 2023-09-08 17:02
Small update, this happens almost every time on the bigger buttons if you click close to the shadow

**Comment by sakshi173** [comment] 2023-09-08 18:48
@agneszitte , this issue is happening for  Neumorphic Style  checkbox  only , not with checkbox control.

**Comment by jeromelaban** [comment] 2023-09-15 14:40
Let's close this one in favor of https://github.com/unoplatform/uno/issues/13604.

**Closed by jeromelaban** 2023-09-15 14:40 UTC
Labels: kind/bug, platform/android 🤖, triage/untriaged, area/canary 🐤, difficulty/tbd
