### ISSUE TITLE
[WASM] NavigationView default icons differ from UWP

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#3470] opened 2020-06-30 13:37 UTC
## Current behavior

The default Menu/Back/Settings icons in NavigationView are different in Wasm than in Uwp

## Expected behavior

Icons should match Uwp

## How to reproduce it (as minimally and precisely as possible)

Load the attached project in Uwp and observe the icons (screenshot may be handy).  Launch the attached project in Wasm and observe changes in icons - Back and Menu are thicker, and Settings icon is filled in rather than outlined.

[NavigationView.zip](https://github.com/unoplatform/uno/files/4852147/NavigationView.zip)

## Environment

Nuget Package:
Uno.UI
Package Version(s):
3.0.0-dev.657
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment] 2020-06-30 13:54
Thanks for the report!

This issue is related to #3011, as the fonts are not the same. This is caused by a licensing issue that _may_ get resolved by https://github.com/microsoft/fluentui/issues/12488.

**Comment by alextrepa** [comment] 2020-08-17 19:10
This issue has been fixed https://github.com/unoplatform/uno/pull/3744

**Closed by alextrepa** 2020-08-17 19:10 UTC
Labels: kind/bug
