### ISSUE TITLE
The Localizer does not work with Desktop/Skia

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#16627] opened 2024-05-08 14:28 UTC
### Current behavior

The localizer will return the string key as result

SelectedPageText = _localizer["stringkey"]

-> SelectedPageText's value will be "stringkey"

### Expected behavior

Get the proper string value from the Resources.resw file

### How to reproduce it (as minimally and precisely as possible)

1- Create a blank project
2- Add a string in Resources.resw
3- Retrieve the string value with the localizer["stringkey"]

### Works on UWP/WinUI

Yes

### Affected platforms

Skia (Linux Framebuffer)

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment] 2024-05-08 17:17
May be a duplicate of https://github.com/unoplatform/uno/issues/16353

**Comment by ArchieCoder** [comment] 2024-05-08 17:21
![image](https://github.com/unoplatform/uno/assets/1608424/5a163f50-cce5-4beb-a925-6d64d80dd2b5)

**Comment by stephenhauck** [comment] 2024-05-13 18:56
The title kept getting set to the key name and not the value
![image](https://github.com/unoplatform/uno/assets/12648793/1f5b83dc-3d02-4b0e-8f38-e90d0e4e6dd4)
The loaded resource is correct
![image](https://github.com/unoplatform/uno/assets/12648793/fddfba8a-679d-4a74-817b-7e84890ce431)

This is your template code with the value simply changed ...
the variable tmp is set to the value "ApplicationName"
I feel like I'm missing something really simple here

I am building for iOS and Android only ...

**Comment by szv** [comment] 2024-05-19 13:05
Hi, I think I just had the same issue, when migrating to Uno 5.2.
For me using the `IStringLocalizer` just worked when building for Windows 10+ with WinAppSDK, but not for other platforms.
I replaced the usage of `IStringLocalizer` with `ResourceLoader.GetForViewIndependentUse()`, which fixed the problem for me.

**Closed** 2024-05-24 16:45 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd

**Comment by ArchieCoder** [comment] 2024-06-06 20:49
My Uno.Sdk is "5.3.0-dev.1873". How do I get the fix?

In Nuget, I have this output when I select Include prerelease:
![image](https://github.com/unoplatform/uno/assets/1608424/712fa14b-f753-4dad-8c22-20beb68b27c9)

**Comment by jeromelaban** [comment] 2024-06-07 01:18
@ArchieCoder this particular difficulty for upgrading packages will be address in uno 5.3 (only one version to update), but in the meantime this particular fix is in 4.1.24. You can change this in your Directory.Build.props [here in your project](https://github.com/unoplatform/uno.templates/blob/adae1be3e850dc74e16b6742be07ee5711ae2514/src/Uno.Templates/content/unoapp/Directory.Build.props#L29).
