### ISSUE TITLE
When the Uno UI builds a WPF application, it causes the generated application to fail to display Chinese

### ISSUE THREAD

**Issue by geenh** [unoplatform/uno#11051] opened 2023-01-25 14:29 UTC
### Current behavior

English：（Microsoft Translate）
![image](https://user-images.githubusercontent.com/100355054/214589668-3d0eee87-2f44-4dcc-8871-44e0dfb350b5.png)
When I build a WPF app, the display Chinese gets garbled characters

### Expected behavior

This MessageDialog will display the "确定" and “取消" buttons, and the button position shows garbled characters

### How to reproduce it (as minimally and precisely as possible)

var messageDialog = new MessageDialog("Hello World!", "确定")
{
Commands =
{
new UICommand("取消"),
new UICommand("确定"),
}
};
await messageDialog.ShowAsync();

### Works on UWP/WinUI

None

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Latest

### Affected platforms

Skia (WPF)

### IDE version

17.4.4

**Comment by jeromelaban** [comment] 2023-01-25 19:50
Thanks for the report. This is a duplicate of https://github.com/unoplatform/uno/issues/10801, please see for a workaround.

**Closed by jeromelaban** 2023-01-25 19:50 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
