### ISSUE TITLE
[WASM] String resources do not load in InterpreterAndAOT build for .net 5 if using location sub-code

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#5993] opened 2021-05-12 17:30 UTC
## Current behavior

Using a location subcode for a localization folder, such as en-US instead of en, prevents string resources from loading in an InterpreterAndAOT build when using .net 5.  Works in Interpreter mode and in netstandard2.0.

## Expected behavior

Strings should be available.

## How to reproduce it (as minimally and precisely as possible)

Launch the attached project in Interpreter and observe that clicking the button sets the string values correctly.  Launch with InterpreterAndAOT and observe that clicking the button returns empty strings.

[Net5WasmResources.zip](https://github.com/unoplatform/uno/files/6468011/Net5WasmResources.zip)

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
3.8.0-dev.130
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment] 2021-07-19 15:38
@peternary I am not able to reproduce the issue with the attached repro sample, both the Interpreter and InterpreterAndAOT builds are providing the same results:

![image](https://user-images.githubusercontent.com/5839577/126187039-af60d09e-0b71-4139-994f-6a4c4b640573.png)

Here are the logs that the ResourceLoader is providing:

![image](https://user-images.githubusercontent.com/5839577/126187113-76f03929-bad2-4939-b698-803d0933d62d.png)

You can try adding this to your application:
```
builder.SetMinimumLevel(LogLevel.Debug);
builder.AddFilter("Windows.ApplicationModel.Resources", LogLevel.Debug);
```

Which will provide more details.

**Comment by peternary** [comment] 2021-07-20 16:45
@jeromelaban I'm still getting this issue, even tried updating to latest Uno just in case.  Additional logging does not seem to be providing any more information.  I could generate a binlog, or try uploading my build someplace that you could take a look.

**Comment by jeromelaban** [comment] 2021-07-20 16:46
@peternary a binlog would help. Are you getting this with the exact same content from the repro you posted, or is it in your app ?

**Comment by peternary** [comment] 2021-07-20 16:48
Exact same content from the repro, based on observing it in our app.  I'll get that binlog for you shortly.

**Comment by peternary** [comment] 2021-07-20 19:12
@jeromelaban Okay, build log attached.  This is for exact same code as linked in the initial report.

[msbuild.zip](https://github.com/unoplatform/uno/files/6850708/msbuild.zip)

**Comment by jeromelaban** [comment] 2021-07-20 21:07
Thanks. I'm still not able to reproduce the issue, the resources are loaded properly. Could you provide a link to the dist folder or your built app?

**Comment by peternary** [comment] 2021-07-21 14:05
Dist folder uploaded here: https://ntlight.ninjatrader.com/resourcesTest/

**Comment by jeromelaban** [comment] 2021-07-21 14:24
Thanks for the upload. I'm still seeing the proper results. I'm starting to wonder if it's a culture specific issue. What's the `CultureInfo.CurrentCulture` and `CultureInfo.CurrentUICulture` value when running on your end ?

**Comment by peternary** [comment] 2021-07-21 16:45
I was getting 'en' in both cases.  Would you like me to test with netstandard2.0 as well?

**Comment by jeromelaban** [comment] 2021-07-21 17:50
Thanks for the report. It's likely to be this specific issue, not related to AOT: https://github.com/unoplatform/uno/issues/6469.

A workaround can be to change the `en-US` language resources to `en`.

**Comment by jeromelaban** [comment] 2021-09-08 12:45
Fixed in https://github.com/unoplatform/uno/pull/6909

**Closed by jeromelaban** 2021-09-08 12:45 UTC
Labels: kind/bug, project/resources, difficulty/medium
