### ISSUE TITLE
Create netstandard projects instead of shared projects when creating new applications via the Uno Platform Solution Template

### ISSUE THREAD

**Issue by staneee** [unoplatform/uno#1305] opened 2019-07-26 14:43 UTC
The xamarin.forms template project already USES the.net standard library. What about uno?

**Comment by ghuntley** [comment] 2019-07-26 18:40
Howdy @staneee. Uno can use netstandard or shared projects. Can you provide some more insights as to what you are trying to achieve?

**Comment by jeromelaban** [comment] 2019-07-26 18:50
Please see the reason for this in [the FAQ](https://github.com/unoplatform/uno/blob/master/doc/articles/faq.md#is-there-any-particular-reason-that-uno-uses-a-shared-project-and-is-it-possible-to-use-a-netstandard-project-instead)

**Comment by staneee** [comment] 2019-07-28 08:49
> Howdy @staneee. Uno can use netstandard or shared projects. Can you provide some more insights as to what you are trying to achieve?

I mean support creating project templates

**Comment by hansmbakker** [comment] 2020-04-15 15:25
> Vs4mac works better in this context, we hope vs4win will follow

Is this still the case? Functionally I find a `netstandard` project easier to work with than a shared project, too.

E.g. you can use it to add nuget packages in one place that are used by the code in the views (like a shared refit client, or model classes for example).

**Comment by jeromelaban** [comment] 2020-04-15 15:46
It's still the case, the issue for building cross-targeted projects is not yet fixed at this point in VS 2019.

**Comment by hansmbakker** [comment] 2020-04-15 16:27
Thank you for your fast reply!

**Comment by ToddGlodek** [comment] 2020-09-26 18:05
My business need is to create a hierarchy of libraries each maintained by a different team.  Each team would only have limited access to the source code for their portion of the project.  It would be ideal if we could deliver compiled libraries to the teams through [packages hosted on an Internet server using the NuGet Gallery Project](https://docs.microsoft.com/en-us/nuget/hosting-packages/overview).  I'm not sure the best way to go about this.

I'm have be experiencing difficulty configuring the shared project created by the new project template to reference another class library project that I have created.  I have tried adding 'Add New Project => Cross Platform Library (Uno Platform)' but it wont show up in the list of 'Other Projects' when I try to add a reference.  

Is this page telling me that...  "Rather than using the shared project created by the New Solution template that originally contained my App/MainPage I should instead create a NetStandard class library and move all those items there - so that I can split the code apart into a hierarchy of references".  Is there a better approach that I am just not seeing / would that approach even work ?

**Comment by jeromelaban** [comment] 2020-09-28 01:34
@ToddGlodek I'm not sure of what you mean by the "Other projects" list. Could you provide a screenshot of that UI ? Is it an issue when creating the library project, or referencing the new library project in a project head (iOS, Android, etc..) ?

**Comment by ToddGlodek** [comment] 2020-09-28 04:02
Its the references manager - where you add references to other projects within your solution.  The "New Solution" template creates everything in a shared project.  So now lets say your project gets large and you want to split it apart - so you can re-use some user control widgets across several projects..  Or, you want to write a test harness that runs a portion of the solution's code - so you want to put that in a separate library, Or, you want to split the code base up across diriment teams,  each maintaining a different branch of the hierarchy of libraries,

What's the best way to do it using your Shared/Head project solution architecture?  Intuitively, it seems like the best to do that is "Add => New Project => Cross Platform Library (Uno Platform)'.  I tried to reproduce the work-around steps in this post by  Christian Findlay [How to Move Uno Platform Pages to a Multi-Targeting Library](https://christianfindlay.com/2020/08/25/uno-multitargeting/).  But I didnt get it to work: when you attempt to add a  'Blank Page' it doesn't compile due to a "Generation Failed, error code Rejected",  Is this an officially supported technique ?  If so I will try it again later.

So for now I will keep plugging away with my evaluation by putting everything in the default Shared Project,

**Comment by jeromelaban** [comment] 2020-09-28 12:08
I get that you need libraries, and "Uno Cross-Platform" Class libraries are the way to separate across projects. 

Here's what visual studio will provide you this, when adding a library to the iOS project, for instance:
![image](https://user-images.githubusercontent.com/5839577/94430224-8cc35880-0161-11eb-9f83-258906783f51.png)

Adding Pages to the project is done this way:

![image](https://user-images.githubusercontent.com/5839577/94430309-a95f9080-0161-11eb-806b-aa1e76402dc5.png)

If you selected the XAML section, you will get the WPF flavor of XAML Page, which does not work work with Uno.

**Comment by MartinZikmund** [comment] 2021-05-31 18:49
This can be closed as the reasoning behind this is documented and there is also a cross-platform library template for Visual Studio.

**Closed by MartinZikmund** 2021-05-31 18:49 UTC
Labels: difficulty/tbd, kind/enhancement, project/core-tools
