### ISSUE TITLE
[skia][macOS] TextBox/RadioButtons/ComboBox/CheckBox/Button/InfoBar texts are not properly aligned vertically

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#16931] opened 2024-05-29 19:45 UTC
### Current behavior

The text is more at the top

See the text box at the left
<img width="286" alt="Screenshot 2024-05-29 at 3 24 00 PM" src="https://github.com/unoplatform/uno/assets/1608424/c422ccff-1879-4c64-a7f7-0c784c77a927">

### Expected behavior

I would expect the text to be vertically centered

### How to reproduce it (as minimally and precisely as possible)

Use this sample [UnoApp1.zip](https://github.com/unoplatform/uno/files/15490122/UnoApp1.zip) and click on Go to Second page to see the dialog, you will notice all the control texts are mostly not centered.

(Same as https://github.com/unoplatform/uno/issues/16930)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

Skia (macOS)

### IDE

Visual Studio 2022

### IDE version

Latest VS

**Comment by ArchieCoder** [comment] 2024-05-29 20:05
@ramezgerges I changed the title because I discovered that most controls have the wrong vertical alignment, see screenshot

<img width="502" alt="Screenshot 2024-05-29 at 4 03 25 PM" src="https://github.com/unoplatform/uno/assets/1608424/accc9775-3640-4cb0-9724-ec62330b162c">

**Comment by ArchieCoder** [comment] 2024-05-29 20:28
InfoBar message is affected also

![image](https://github.com/unoplatform/uno/assets/1608424/0090356a-ffe8-423b-ae45-38941dfbc84d)

**Comment by ArchieCoder** [comment] 2024-05-29 21:52
![image](https://github.com/unoplatform/uno/assets/1608424/adb79934-03b9-40ca-875a-5cdfaa09463a)

**Comment by ramezgerges** [comment] 2024-06-03 17:34
This is actually not a bug, but is a result of font differences between platforms and the way the text is vertically aligned. Text is top-aligned in all those examples, so the Text will be closer to the top. WinUI in fact does the same thing, but because the default font (Segoe UI) with the default font size is taller than the default font used on the MacOS target, it appears to be better centered, but it's actually a pure coincidence. If you make the FontSize smaller, it's start looking weird like the results you see above.

To deal with this, you can use a custom font file that's used on both WinUI and Uno. Also, you make text acutally vertically-centered, use `VerticalAlignment = "Center"` where applicable.

**Comment by jeromelaban** [comment] 2024-06-03 18:57
@ramezgerges It feels like we should be adjusting this so that we have the same rendering. Is this a value that is not aligned with WinUI's default templates? Or maybe `ContentControl`?

**Comment by jeromelaban** [comment] 2024-06-03 19:30
Looking at it further, as Ramez is mentioning, since the default fonts are not the same between platforms, the automatic sizing and alignment may not match.

Here's an example on WinUI, using the amazing Xaml Studio:

![image](https://github.com/unoplatform/uno/assets/5839577/e129e06c-7ffb-4540-b74f-9d03128dbdb6)

@ArchieCoder in order to have the same layout everywhere, you'd need to use the same font and size everywhere (something we're working on in https://github.com/unoplatform/uno/pull/15958), or to set the `ContentVerticalAlignment` as Ramez mentioned, which may help to some extents.

**Comment by ArchieCoder** [comment] 2024-06-03 20:51
@jeromelaban @ramezgerges 

I applied the Font using your Uno.Font nuget to use Roboto.

There are still drawing inconsistencies.

<img width="1048" alt="image" src="https://github.com/unoplatform/uno/assets/1608424/4c8b0212-e45e-4d99-a4b8-6fa90ad21974">

Open project and click on "Click here"

[UnoFontApp-master.zip](https://github.com/user-attachments/files/15539490/UnoFontApp-master.zip)
or 
https://github.com/ArchieCoder/UnoFontApp

**Comment by ArchieCoder** [comment] 2024-06-24 02:41
@ramezgerges @jeromelaban @ajpinedam Sorry to bring back again this issue, but as for now, this is an important one for my project.

There are inconsistencies between the 3 platforms: WinUI-Skia Windows-Skia Mac. I don't have access to Linux (I'm away from home).

I created a small project below where the UI properties come from Figma design. The font (open source) is included in the proejct. On Mac, aside of the vertical alignement, the font rendering seems off as well. I have the impression with Skia there is a bug with LineHeight and/or LineStackingStrategy. My project is ultra small so you can see the bugs easily.

WinUI (StackPanel good, Button good)
![WinUI](https://github.com/unoplatform/uno/assets/1608424/a7ae84ac-d84e-45b7-84ae-1d4dcd8afd7a)

Skia Windows (StackPanel not good, Button good)
![Skia Windows - StackPanel not good, Button good](https://github.com/unoplatform/uno/assets/1608424/7c0b4f90-c360-4e3c-b3f4-f18b40e21262)

Skia Mac (StackPanel not good, Button not good)
<img width="149" alt="Skia Mac - StackPanel not good, button not good" src="https://github.com/unoplatform/uno/assets/1608424/941cc357-1797-49c5-8ff8-8e939b251fcb">

Skia Windows vs Skia Mac side by side -> it feels the font on Mac renders differently
<img width="855" alt="Skia Mac vs Skia Windows" src="https://github.com/unoplatform/uno/assets/1608424/cb0e346c-bbcc-45b0-918f-33617f78f409">

Project
[UnoApp1.zip](https://github.com/user-attachments/files/15949100/UnoApp1.zip)

**Comment by ArchieCoder** [comment] 2024-06-25 02:48
I think I found one part of the problem and it is related to this one https://github.com/unoplatform/uno/issues/17283. I found a font that is very easy to distinguish when it works or not.

**Comment by jeromelaban** [comment] 2024-06-25 19:52
We're still working on this issue, variable fonts supports is causing trouble with the current sizing of controls. The font is different on every platform (the closest to Segoe UI), as we're mentioned previously, which makes the visual aspect different. We'll keep this issue updated as we know more.

**Comment by ArchieCoder** [comment] 2024-06-25 20:11
Ah, I didn't know that a **variable** font was also an issue.

**Comment by jeromelaban** [comment] 2024-07-11 15:54
Fixed by https://github.com/unoplatform/uno/issues/3954

**Closed by jeromelaban** 2024-07-11 15:54 UTC
Labels: kind/bug, area/textblock, difficulty/tbd, area/skia/text ✏️
