### ISSUE TITLE
Setting RadioButtons.SelectedIndex not working in Onloaded event or Page constructor

### ISSUE THREAD

**Issue by chingucoding** [unoplatform/uno#5886] opened 2021-05-02 12:43 UTC
## Current behavior

[Android]: Settings SelectedIndex on RadioButtons does not getting respected, visually, no item is being selectd.

## Expected behavior

Setting that property should be respected and visually visible.

## How to reproduce it (as minimally and precisely as possible)

Add RadioButtons:

```xaml
    <muxc:RadioButtons x:Name="ThemeRadioButtons">
        <RadioButton x:Uid="LightThemeOption"/>
        <RadioButton x:Uid="DarkThemeOption"/>
        <RadioButton x:Uid="SystemDefaultThemeOption"/>
    </muxc:RadioButtons>
```

And this as MainPage.xaml.cs:

```c#
    public sealed partial class MainPage : Page
    {
        public MainPage()
        {
            this.InitializeComponent();
            // Does not get respected
            ThemeRadioButtons.SelectedIndex = 0;

            Loaded += MainPage_Loaded;

        }

        private void MainPage_Loaded(object sender, RoutedEventArgs e)
        {
            // This does not get respected either
            ThemeRadioButtons.SelectedIndex = 0;
        }
    }
```

## Workaround

Calling UpdateLayout on the RadioButtons beforehand works as workaround.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Uno.UI: Version=3.7.3
Uno.UI.RemoteControl: Version= 3.7.3
Uno.Core: Version=2.3.0
Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.3 )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment] 2021-05-05 11:57
Seems like a duplicate of #5917

**Comment by chingucoding** [comment] 2021-05-05 18:28
Seems like it, sorry about the duplicate issue then.

**Comment by jeromelaban** [comment] 2021-05-06 11:40
No worries, it's kept opened because it may not be :)

**Closed** 2021-05-07 13:49 UTC
Labels: difficulty/tbd, kind/bug, triage/untriaged
