### ISSUE TITLE
Add Platform Selection support for VSIX templates

### ISSUE THREAD

**Issue by GF-Huang** [unoplatform/uno#4838] opened 2021-01-05 23:22 UTC
Such like me, only need target to `windows` and `linux`, I don't want install `xamarin` toolset. When I creating the project, it will tell me some error message about iOS project and Android project open failed.

**Comment by MartinZikmund** [comment] 2021-06-02 14:07
Duplicate of #3885

**Closed by MartinZikmund** 2021-06-02 14:07 UTC
Labels: area/solution-templates, kind/enhancement, project/core-tools, triage/untriaged
