### ISSUE TITLE
Resizing a Grid control with a GridSplitter doesn't cause TextBlocks to trim in WASM

### ISSUE THREAD

**Issue by jsinsel** [unoplatform/uno#5662] opened 2021-04-02 15:59 UTC
## Current behavior

Have a Grid control with two column definitions and a GridSplitter so the user can resize.  Place a TextBlock in one of the columns with TextTrimming="CharacterEllipsis".  When the user resizes to something smaller, the text doesn't add the ellipsis.

## Expected behavior

TextTrimming works when a Grid column is resized.

## How to reproduce it (as minimally and precisely as possible)

Attaching a test project. 
[App1.Shared.zip](https://github.com/unoplatform/uno/files/6250286/App1.Shared.zip)

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carldebilly** [comment] 2021-04-05 17:43
Source of the problem is found and fixed in [PR](https://github.com/unoplatform/uno/pull/5679).

**Closed** 2021-04-13 01:37 UTC
Labels: area/textblock, difficulty/challenging, kind/bug, platform/wasm, project/text
