### ISSUE TITLE
[Skia.GTK] The Chinese characters are garbled on linux

### ISSUE THREAD

**Issue by fangguoneng** [unoplatform/uno#8553] opened 2022-04-14 13:13 UTC
### Current behavior

The Chinese characters are garbled on linux
Screenshot:
![capture](https://user-images.githubusercontent.com/40819365/163397298-ea98e5bf-8667-4a1c-b610-9ce98467b9a5.png)
error log:
![log](https://user-images.githubusercontent.com/40819365/163397495-97612cb3-40d3-4117-9601-104246f8fa53.png)

### Expected behavior

should not happen.

### How to reproduce it (as minimally and precisely as possible)

[UnoDemo.zip](https://github.com/unoplatform/uno/files/8489403/UnoDemo.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### IDE version

17.1.0

**Comment by jeromelaban** [comment] 2022-04-14 13:21
Thanks for the report, this is a duplicate of https://github.com/unoplatform/uno/issues/6973

**Closed by jeromelaban** 2022-04-14 13:21 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
