### ISSUE TITLE
Bindings of a Control to itself using ElementName not working on Android and IOS 

### ISSUE THREAD

**Issue by harmanlamba** [unoplatform/uno#2485] opened 2020-01-15 21:23 UTC
## Current behavior

The bindings fail to load in IOS and Android, but they work in UWP. Essentially, the control called RadialGauge, has an X:Name of RootControl, and Binding to itself does not work. 

## Expected behavior

The bindings should work and the text should get displayed in the repro project.

## How to reproduce it (as minimally and precisely as possible)

Simply run the UWP project first, and see that the text loads. In contrast, deploy the IOS or Android head and the Bindings don't work successfully, and no text is displayed.

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.1.0-dev.716

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.4.3 )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

The link to the repro project is here:
https://drive.google.com/file/d/1e-LRMssrDJP8_vmMxmc0owU146oO_o34/view?usp=sharing

**Comment by jeromelaban** [comment] 2020-01-17 13:02
Thanks for the report! Can you try using `RelativeSource.Self` as a workaround ?

**Comment by harmanlamba** [comment] 2020-01-19 20:59
Hey @jeromelaban , I was not able to get ``` RelativeSource.Self``` to work. But I did find another workaround which was explicitly changing the DataContext of some controls (the labels in the repro attached), such that they don't get affected by external bindings. Essentially, doing this in the code behind, ```this.TypeOfValueLabel.DataContext = this.ValueLabel.DataContext = this;```

**Comment by jeromelaban** [comment] 2020-01-20 14:11
Thanks. The issue is not ElementName binding itself, but rather ElementName binding to a UserControl. I've documented the workaround in https://github.com/unoplatform/uno/issues/61.

I'll close this issue as a duplicate.

**Closed** 2020-01-20 14:13 UTC
Labels: kind/bug
