### ISSUE TITLE
Samples app on macOS throws exceptions on startup

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#3016] opened 2020-04-17 18:38 UTC
## Current behavior

When Samples app is launched on macOS, I get several exceptions in `RemoteControlClient.cs`, line 81:

```
System.UriFormatException: Invalid URI: Invalid port specified.
  at System.Uri.CreateThis (System.String uri, System.Boolean dontEscape, System.UriKind uriKind) [0x0007b] in /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/src/Xamarin.Mac/mcs/class/referencesource/System/net/System/UriExt.cs:55
  at System.Uri..ctor (System.String uriString) [0x00014] in /Library/Frameworks/Xamarin.Mac.framework/Versions/Current/src/Xamarin.Mac/mcs/class/referencesource/System/net/System/URI.cs:408
  at Uno.UI.RemoteControl.RemoteControlClient.<StartConnection>g__Connect|12_0 (System.String endpoint, System.Int32 port, System.Threading.CancellationToken ct) [0x000ca] in /Users/martinzikmund/dev/Uno/src/Uno.UI.RemoteControl/RemoteControlClient.cs:81
```

## Expected behavior

No exceptions ideally :-) .

## How to reproduce it (as minimally and precisely as possible)

Clone latest macOS samples app and run it.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment] 2020-04-17 18:46
This is caused by the remote control tooling, probably missing a port.

**Comment by jeromelaban** [comment] 2021-08-06 15:53
Fixed in recent builds

**Closed by jeromelaban** 2021-08-06 15:53 UTC
Labels: kind/bug, platform/macos, project/core-tools, difficulty/medium
