### ISSUE TITLE
x:Bind issue with long path fails to build

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#11280] opened 2023-02-11 04:47 UTC
### Current behavior

x:Bind with long path is fails to build an app with error related to "global" keyword. Can not translate exactly from russian sorry;)

Repro
[BindIssue.zip](https://github.com/unoplatform/uno/files/10712626/BindIssue.zip)

### Expected behavior

Successful build and work

### Workaround

Shorten path

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

WebAssembly, Android, iOS, macOS (AppKit), Mac Catalyst, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Linux Framebuffer), Skia (Tizen)

### Anything else we need to know?

Tried with 4.7.37 and latest dev build 4.8.0-dev.299

**Comment by Youssef1313** [comment] 2023-02-13 09:06
Pretty much looks like a duplicate of https://github.com/unoplatform/uno/issues/3261

Though you have a typo in the code:

```xml
            Text="{x:Bind local:App.Class.SubClass1.SubClass2.SubClass2.Message}" />
```

Should be:

```xml
            Text="{x:Bind local:App.Class.SubClass1.SubClass2.SubClass3.Message}" />
```

The corrected code still doesn't compile due to a bug or missing feature, but I thought it's worth noting this.

**Comment by FrozDark** [comment] 2023-02-13 09:18
Worth noting that even with OneTime mode it fails as well but if it has less than 4 parts of the binding path it builds

**Closed** 2023-02-21 15:33 UTC
Labels: kind/bug, triage/untriaged, area/code-generation, area/xBind, difficulty/tbd
