### ISSUE TITLE
[iOs/Android] SwipeControl, label of the SwipeItem is White instead of foreground

### ISSUE THREAD

**Issue by MaximeDion-Work** [unoplatform/uno#6524] opened 2021-07-21 18:43 UTC
## Current behavior

The label of the Swipe Item is white regardless of the specified foreground.

Android/iOS
![image](https://user-images.githubusercontent.com/64613932/126542430-be251854-29eb-4b4f-afa6-5632f11c1fd0.png)

## Expected behavior

The label of the Swipe Item is using the color specified in foreground.

UWP
![image](https://user-images.githubusercontent.com/64613932/126542467-617108b9-4b2b-4e07-9edf-6dfa40c7c998.png)

## How to reproduce it (as minimally and precisely as possible)

Apply a SwipeControl with swipe items.
Start swiping then release
Notice Lael are white

## Workaround

None

## Works on UWP/WinUI

Yes

## Environment

Nuget Package:

Uno.UI: 3.9.0-dev.307
Uno.SourceGenerationTasks 3.1.0
Uno.UI.RemoteControl: 3.9.0-dev.233

Nuget Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (Version 16.9.4)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by Xiaoy312** [comment] 2021-07-23 13:46
@MaximeDion-Work 
Can you provide a sample app to reproduce this issue?

**Comment by MaximeDion-Work** [comment] 2021-07-27 15:43
[Repro8.zip](https://github.com/unoplatform/uno/files/6886860/Repro8.zip)

**Comment by agneszitte-nventive** [comment] 2021-07-27 17:50
@jeromelaban / @MaximeDion-Work 
I was able to reproduce the issue only inside the Trade Zero project and while investigating I compared with my uno sample with the same code.
It's related to the fact that there is a default TextBlock style set for the project. If the default style is commented the issue is not visible anymore.
Continue to investigating.

Sample code :

```
<Grid>
		<Grid.RowDefinitions>
			<RowDefinition Height="Auto" />
			<RowDefinition Height="*" />
		</Grid.RowDefinitions>

		<!-- CommandBar -->
		<CommandBar Content="SwipeControl Sample" />

		<!-- ListView -->
		<ListView ItemsSource="ABCDEFGHIJKLMNOPQRSTUVWXYZ"
				  SelectionMode="None"
				  Grid.Row="1">
			<ListView.ItemTemplate>
				<DataTemplate>
					<SwipeControl x:Name="SwipeControl">

						<!-- Left -->
						<SwipeControl.LeftItems>
							<SwipeItems Mode="Reveal">

								<!-- Delete Stock Button -->
								<SwipeItem Text="Delete"
										   Foreground="Red"
										   Background="DarkBlue">
									<SwipeItem.IconSource>
										<PathIconSource Data="M1 16C1 17.1 1.9 18 3 18H11C12.1 18 13 17.1 13 16V4H1V16ZM14 1H10.5L9.5 0H4.5L3.5 1H0V3H14V1Z" />
									</SwipeItem.IconSource>
								</SwipeItem>
							</SwipeItems>
						</SwipeControl.LeftItems>

						<!-- Right -->
						<SwipeControl.RightItems>
							<SwipeItems Mode="Reveal">

								<!-- Locate Stock Button -->
								<SwipeItem Text="Locate"
										   Foreground="Green"
										   Background="DarkBlue">
									<SwipeItem.IconSource>
										<PathIconSource Data="M8 10C6.9 10 6 9.1 6 8C6 6.9 6.9 6 8 6C9.1 6 10 6.9 10 8C10 9.1 9.1 10 8 10ZM14 8.2C14 4.57 11.35 2 8 2C4.65 2 2 4.57 2 8.2C2 10.54 3.95 13.64 8 17.34C12.05 13.64 14 10.54 14 8.2ZM8 0C12.2 0 16 3.22 16 8.2C16 11.52 13.33 15.45 8 20C2.67 15.45 0 11.52 0 8.2C0 3.22 3.8 0 8 0Z" />
									</SwipeItem.IconSource>
								</SwipeItem>

								<!-- Trade Stock Button -->
								<SwipeItem Text="Trade"
										   Foreground="Green"
										   Background="DarkBlue">
									<SwipeItem.IconSource>
										<PathIconSource Data="M4.28571 0L0 4.43333H3.21429V12.2222H5.35714V4.43333H8.57143L4.28571 0ZM11.7857 15.5667V7.77778H9.64286V15.5667H6.42857L10.7143 20L15 15.5667H11.7857Z" />
									</SwipeItem.IconSource>
								</SwipeItem>
							</SwipeItems>
						</SwipeControl.RightItems>

						<Grid Background="Black"
							  BorderBrush="White"
							  BorderThickness="0,0,0,1">

							<!-- Label -->
							<TextBlock Text="{Binding}"
									   Foreground="White"
									   FontSize="16"
									   Margin="16" />
						</Grid>
					</SwipeControl>
				</DataTemplate>
			</ListView.ItemTemplate>
		</ListView>
	</Grid>
	```

**Comment by jeromelaban** [comment] 2021-07-27 17:52
@davidjohnoliver this might interest you

**Comment by davidjohnoliver** [comment] 2021-07-27 17:55
Sounds similar to this one: https://github.com/unoplatform/uno/issues/3443

**Comment by agneszitte-nventive** [comment] 2021-07-27 18:56
@MaximeDion-Work here is a workaround for the issue for now for Trade Zero (I did the tests for both Android and iOS):
```
<SwipeControl x:Name="SwipeControl">
				<SwipeControl.Resources>
					<!-- Workaround for https://github.com/unoplatform/uno/issues/6524 -->
					<!-- DependencyProperty precedences are not behaving exactly the same way as WinUI at the moment -->
					<!-- Related Issue : https://github.com/unoplatform/uno/issues/3443 -->
					<Style TargetType="TextBlock">
						<Setter Property="FontFamily"
								Value="{StaticResource TitilliumWebFontFamily}" />
						<Setter Property="FontWeight"
								Value="Normal" />
						<Setter Property="FontStyle"
								Value="Normal" />
						<Setter Property="LineStackingStrategy"
								Value="BlockLineHeight" />
						<Setter Property="TextTrimming"
								Value="CharacterEllipsis" />
						<Setter Property="TextWrapping"
								Value="Wrap" />
					</Style>
				</SwipeControl.Resources>
				
				...
				
			</SwipeControl>

```

@jeromelaban / @davidjohnoliver 
As the workaround is still valid, should I stop with this issue and we will take care of https://github.com/unoplatform/uno/issues/3443 after?
Or should I continue on the precedence issue?

**Comment by jeromelaban** [comment] 2021-07-27 20:57
if @MaximeDion-Work is ok with the workaround, let's close this issue and keep the original one (#3443)

**Comment by MaximeDion-Work** [comment] 2021-07-27 21:02
Yeah it work! Thank you guys!

**Closed** 2021-07-27 21:03 UTC
Labels: difficulty/tbd, kind/bug, triage/untriaged

**Comment by jeanplevesque** [comment] 2021-07-28 12:21
@jeromelaban the "original one" (#3443) is currently documented as if it were specific to WASM.
