### ISSUE TITLE
[Android] Packaging Version mismatch Issues

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#18099] opened 2024-09-02 15:21 UTC
### Current behavior

As I was archiving my Android app and updating the ApplicationDisplayVersion and ApplicationVersion to higher numbers, I started getting:    
```
Error NU1105 Unable to read project information for 'UnoApp': The property PackageVersion was expected to have a single value across all target frameworks, but instead had the following values: 2.0.0, 3.0.0 
```
It was after a while, I realized I also need to update the PackageVersion which isn't included in the .csproj with SingleProject.

### Expected behavior

PackageVersion should be included by default in the template.

### Works on UWP/WinUI

Yes

### NuGet package version(s)

"Uno.Sdk": "5.4.0-dev.234"

### Affected platforms

Android

### IDE

Visual Studio 2022

**Comment by Youssef1313** [comment] 2024-09-17 11:41
@morning4coffe-dev Could you send me a binlog? Preferrably from a command-line build

**Comment by Youssef1313** [comment] 2024-09-17 11:48
This is actually a duplicate of https://github.com/unoplatform/uno/issues/16618 which was fixed already in the templates themselves (and happens only in VS per comments in the issue)

**Closed** 2024-09-17 15:29 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd, triage/potentially-fixed, area/sdk
