### ISSUE TITLE
[WASM] System.InvalidOperationException: AcrylicBrush is ** not ** supported by the AssignAndObserveBrush.

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#7086] opened 2021-09-15 07:09 UTC
### Current behavior

```
System.InvalidOperationException: AcrylicBrush is ** not ** supported by the AssignAndObserveBrush. (Instead you have to use the AcrylicBrush.Subscribe().)
```
When switching to each view, several such exceptions appear.

### Expected behavior

without exceptions

### How to reproduce it (as minimally and precisely as possible)

The minimal xaml code that throws the exception. Date binding is required, exception is thrown only for a certain number of things

```xml
<views:ImportViewBase
    x:Class="Dedoose.Views.ImportView"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:views="using:Dedoose.Views"
    >
    <ScrollViewer>
        <ItemsControl
            ItemsSource="{Binding Items}"
            >
            <ItemsControl.ItemTemplate>
                <DataTemplate>
                </DataTemplate>
            </ItemsControl.ItemTemplate>
        </ItemsControl>
    </ScrollViewer>
</views:ImportViewBase>
```

### Workaround

I assume it has to do with scrollbars

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

```xml
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="5.0.0" />
    <PackageReference Include="ReactiveMarbles.ObservableEvents.SourceGenerator" Version="1.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="ReactiveUI.Uno" Version="16.2.6" />
    <PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI" Version="7.1.0-build.43.g15261a775c" />
    <PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls.Core" Version="7.1.0-build.43.g15261a775c" />
    <PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls.DataGrid" Version="7.1.0-build.43.g15261a775c" />
    <PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls.Layout" Version="7.1.0-build.43.g15261a775c" />
    <PackageReference Include="Uno.Microsoft.Xaml.Behaviors.Uwp.Managed" Version="2.0.3-uno.95" />
    <PackageReference Include="Uno.UI.WebAssembly" Version="3.11.0-dev.27" />
    <PackageReference Include="Uno.UI.RemoteControl" Version="3.11.0-dev.27" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="3.0.0-dev.142" />
    <PackageReference Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.3.0-dev.1" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="3.0.0-dev.142" />
```

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022, Visual Studio 2019

### IDE version

2022 preview 4, 2019 latest stable

**Comment by Youssef1313** [comment] 2021-09-15 07:16
Duplicate of #6989.

**Closed** 2021-09-15 12:07 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
