### ISSUE TITLE
WASM head not running in VS 2019 with default template

### ISSUE THREAD

**Issue by hawkerm** [unoplatform/uno#1731] opened 2019-10-05 18:21 UTC
## Current behavior
Started a new project in VS 2019 16.3.2 with the default Uno platform app project. Am able to run Android and UWP heads, but WASM head fails to load in Firefox and new Edge.  In new Edge, clearly get this error message:

```
An error occurred while starting the application.
DirectoryNotFoundException: C:\code\LD45\TheProjectName\TheProjectName.Wasm\bin\Debug\netstandard2.0\dist\
Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(string root, ExclusionFilters filters)

DirectoryNotFoundException: C:\code\LD45\TheProjectName\TheProjectName.Wasm\bin\Debug\netstandard2.0\dist\
Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(string root, ExclusionFilters filters)
Uno.Wasm.Bootstrap.Cli.Server.Startup.Configure(IApplicationBuilder app, IConfiguration configuration) in Startup.cs
Microsoft.AspNetCore.Hosting.ConventionBasedStartup.Configure(IApplicationBuilder app)
Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()

Show raw exception details
.NET Core 4.6.28008.01 X64 v4.0.0.0    |   Microsoft.AspNetCore.Hosting version 2.2.0-rtm-35687    |    Microsoft Windows 10.0.17763
```

Verified that `dist` directory indeed doesn't exist.

## Expected behavior
Base template to run 'Hello, World!' example.

## How to reproduce it (as minimally and precisely as possible)
See above.

## Environment
VS 2019 16.3.2
Windows 10 v17763.737

Uno Template Package: 1.45.0.1865

Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x] 2019 (version: 16.3.2)
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by hawkerm** [comment] 2019-10-05 18:36
Ah, this is related/possible duplicate of #1376.  I had .NET Core 2.2 installed but for VS 2017, you apparently need a different version of the SDK for VS 2019.  So, once I installed that version of the .NET Core 2.2 SDK, I was able to run the sample.

**Comment by hawkerm** [comment] 2019-10-05 18:38
I was also previously prompted to install the .NET 4.6.2 developer tools, but that showed up in the output with a link.

**Comment by mkwhalen** [comment] 2019-10-08 12:22
I can confirm that fixed the issue for me as well on VS 2019

**Comment by ghuntley** [comment] 2019-10-09 02:00
Ugh, that's no good folks. Thanks for letting us know that you ran into problems. Now that UnoConf is over I'll pickup https://github.com/unoplatform/uno/pull/1384 once again. Closing as duplicate of existing.

**Comment by ghuntley** [comment] 2019-10-09 02:01
If you see any inaccuracies in the getting started documentation, please send in a pull-request btw :)

**Closed by ghuntley** 2019-10-09 02:00 UTC
Labels: kind/bug, triage/duplicate
