### ISSUE TITLE
Android `App.xaml:` The type 'XamlControlsResources' was not found.

### ISSUE THREAD

**Issue by qcwgithub** [unoplatform/uno#8785] opened 2022-05-16 08:07 UTC
### Current behavior

In Android project App.xaml, it says 
````
Error	XLS0414	The type 'XamlControlsResources' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.
````

### Expected behavior

It should behaviour like what it does in UWP project:

You put mouse on 'XamlControlsResources', and it says 'Microsoft.UI.Xaml.Controls.XamlControlResources'

### Workaround

I didn't put App.xaml in .Shared project. I copied it to each platform.

### Works on UWP/WinUI

Yes

### Affected platforms

Android

### IDE

Visual Studio 2019

### IDE version

Microsoft Visual Studio Community 2019 Version 16.11.1

**Comment by jeromelaban** [comment] 2022-05-16 12:38
Thanks. This is a visual studio integration issue that we do not have control over at this point. The best resolution at this time is to select the UWP project in the top-left corner of the editor.

**Comment by MartinZikmund** [comment] 2023-07-27 10:47
Closing as duplicate of #8774

**Closed by MartinZikmund** 2023-07-27 10:47 UTC
Labels: kind/bug, area/solution-templates, difficulty/tbd
