### ISSUE TITLE
[android] no screen updating, no ProgressRing

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#3151] opened 2020-05-13 17:02 UTC
## Current behavior
 mainpage button event handler async method calls:
`uiProcesuje.Visibility = Visibility.Visible;`
`uiProcesuje.IsActive = !bIsEnabled;`
`uiReadAll.IsEnabled = false;`
(where uiProcesuje is ProgressRing, uiReadAll is one of buttons on screen - all buttons Enabled are set to false)

then awaits some method, which from time to time makes
`uiMsgCnt.Text = "batch " + iGuard.ToString(System.Globalization.CultureInfo.InvariantCulture) + sLastRun;`

On Windows, everything works as expected, but in Uno - no progressring, no text change, no disabling buttons.

Android:
![Screenshot_20200513-exporting](https://user-images.githubusercontent.com/23451507/81842032-a3b73480-954b-11ea-88e8-f77af7f1f08c.png)

Correct, UWP version:
![wp_ss_20200513_0005_exporting](https://user-images.githubusercontent.com/23451507/81842034-a44fcb00-954b-11ea-8b28-d8abe1fe86e6.png)

## Expected behavior
ProgressRing visible, text changing.

## Environment

Nuget Package:

Package Version(s):
2.1.0-dev.945, 2.1.37.
I didn't test with another packages.

Affected platform(s):

- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment] 2020-05-21 13:37
Can you make a simplified repo of this problem in form of XAML + cs code? I know there are samples in the description, but if you could add something more complete please?

**Comment by MartinZikmund** [comment] 2020-05-22 14:45
Are you referencing the Uno.Lottie package from the Android project?

**Comment by pkar70** [comment] 2020-05-22 15:23
No, I mean Uno version of my UWP app 'backupSMS'.
I just tried to publish it from Visual Studio, but it publishes only .Shared and .UWP, not .Droid subfolders :(

**Comment by pkar70** [comment] 2020-05-22 16:16
https://pkar70.visualstudio.com/BackupSMS/_git/BackupSMS , same https://github.com/pkar70/BackupSMS/tree/master/BackupSMS

**Comment by pkar70** [comment] 2020-05-22 16:20
Ok, I uploaded with Droid folder. But ignore "moje" folder :)

**Comment by MartinZikmund** [comment] 2020-05-23 16:47
@pkar70  I have tried to build the app, but it fails (in multiple places, like `Windows.Extensions.PermissionsHelper.AndroidPermissionAsync`), is it using a fork of Uno? If you made a simpler repo with a NuGet version of Uno, and just the code required to reproduce this, it would help a lot :-)

**Comment by pkar70** [comment] 2020-05-23 18:34
It is  full (whole) app, as I don't know if there is some interactions (e.g. accessing SMS storage destroys something)... 
Permissions: #3025, but previous version of it :)

I will return to this problem (and also #3025) next week. E.g. I will retest it in smaller app, with only progressring and simple `for(i=0; i<10;i++) { await Task.Delay(1000); uiItem.Text= i;} ` in button handler.

**Comment by pkar70** [comment] 2020-06-05 16:16
Windows.Extensions.PermissionsHelper.AndroidPermissionAsync is not neccessary, if you add (in Android setup) permissions for app. What else is not in current Uno?

**Comment by pkar70** [comment] 2020-06-09 09:23
Simplest repo:

MainPage.xaml:

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}" Name="uiGrid">
        <ProgressRing x:Name="uiProcesuje" HorizontalAlignment="Center" VerticalAlignment="Center" Visibility="Collapsed" Canvas.ZIndex="10000" />

            <Button Name="uiRun" Content="Test in MainPage" HorizontalAlignment="Center" Click="uiRunMP_Click" />
            <TextBlock Name="uiMsgCnt" Text="" HorizontalAlignment="Center" VerticalAlignment="Center" Margin="0,50,0,0"/>

    </Grid>


MainPage.xaml.cs:

        private void GuzikiEnable(bool bIsEnabled)
        {
            uiRun.IsEnabled = bIsEnabled;
            double dVal;
            dVal = (Math.Min(uiGrid.ActualHeight, uiGrid.ActualWidth)) / 2;
            // for Android
            if (dVal < 1) dVal = 100;

            uiProcesuje.Width = dVal;
            uiProcesuje.Height = dVal;

            uiProcesuje.Visibility = bIsEnabled ? Visibility.Collapsed : Visibility.Visible;
            uiProcesuje.IsActive = !bIsEnabled;
        }


        private void uiRUnMP_Click(object sender, RoutedEventArgs e)
        {
            GuzikiEnable(false);


            for(int i=0; i<10;i++)
            {
                Thread.Sleep(1000);
                uiMsgCnt.Text = i.ToString();
            }


            GuzikiEnable(true);
            uiMsgCnt.Text = "end - MainPage";
        }

No 'ticking' in uiMsgCnt, no disabling uiRun, no ProgressRing.

**Comment by MartinZikmund** [comment] 2020-06-09 09:57
@pkar70 thanks, will check it out later today!

**Comment by pkar70** [comment] 2020-06-11 14:26
Do you confirm problem?

**Comment by carldebilly** [comment] 2020-06-17 15:39
There is many problems with your sample:

## Real problem: `Thread.Sleep()`
On Android, there's no _compositor thread_.  That means all animations requires the UI Thread to run. Since you are blocking it with your `Thread.Sleep()`, you're not giving opportunity to the UI thread to execute and render it.

I changed your this in your code:
``` csharp
private async void uiRUnMP_Click(object sender, RoutedEventArgs e) // made the method `async`
{
  [...]
  await Task.Delay(1000); // Replacement for Thread.Sleep(1000);
  [...]
}
```

Result:
![progressring-pkarbug](https://user-images.githubusercontent.com/4174207/84918737-02ae2300-b08f-11ea-81f8-2058b572adfa.gif)

## Another problem: `Canvas.ZIndex`
Not really supported outside a `<Canvas>` on Uno. There an issue for this one: https://github.com/unoplatform/uno/issues/325

I'll close this issue as not a bug.

**Closed by carldebilly** 2020-06-17 15:39 UTC
Labels: kind/bug, triage/untriaged

**Comment by pkar70** [comment] 2020-06-17 17:41
Ok, I will check my app about  async/await etc. Because I put Thread.Sleep() in place where my app read SMS messages from store and exporting it (as real sample doesn't work without additions to Uno). Maybe generating several megabytes file and writing it can be used instead of this sleep...
