### ISSUE TITLE
[Gallery][iOS]Accelerometer- App crashes when click on ' Start observing Accelerometer reading Changes' Button.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#10217] opened 2022-10-21 19:58 UTC
### Current behavior

https://user-images.githubusercontent.com/74563602/197278195-6826427d-580c-46a3-bee0-0a81d1f922af.MOV

### Expected behavior

Gallery app should not crash.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "Accelerometer" from the "Non-UI Features" list.
4. Add some time duration in the 'Report Interval' section.
5. Click the 'Start observing Accelerometer reading Changes' button.
6. Update the time duration by clicking on the top or down arrow buttons on the Report Interval drop-down.
7. Notice that after a few seconds the Gallery app gets crashes.

### Affected platforms

iOS

**Comment by trungnt2910** [comment] 2022-10-22 11:06
There isn't any platform-specific code in this sample, so this should be a problem in the Uno library itself.

**Comment by ktos** [comment] 2022-10-23 19:14
Just started playing with Magnetometer sample, and the docs both in case of Magnetometer and Accelerometer (https://platform.uno/docs/articles/features/accelerometer.html) are saying that you should use Dispatcher, because updating the sensor's reading and displaying it may occur on two separate threads (and it's behaving the same way on UWP).

The Accelerometer sample is not using Dispatcher: https://github.com/unoplatform/Uno.Gallery/blob/master/Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/AccelerometerSamplePage.xaml.cs#L178-L181

I believe this crash may be the effect of this.

**Comment by trungnt2910** [comment] 2022-10-24 01:56
I somehow got lucky with the `Accelerometer` on UWP, Android, _and_ WASM and didn't need to use the dispatcher.
After working on the `PowerManager` (which raises events on background threads on UWP and Android) example I guess this might be the cause of the `Accelerometer` issue on iOS.

The view model should be changed to raise events on the main thread, something like this:

https://github.com/unoplatform/Uno.Gallery/blob/master/Uno.Gallery/Uno.Gallery.UWP/Views/SamplePages/PowerManagerSamplePage.xaml.cs#L112-L118

I don't have any iOS device so I can't test this fix.

**Comment by MartinZikmund** [comment] 2023-01-06 06:45
I'm sorry I didn't notice this issue earlier, but it cannot be fixed within Uno, but rather within the Gallery sample. As per the UWP docs and the UWP samples, the event handler should reschedule to Dispatcher thread if needed - https://github.com/microsoft/Windows-universal-samples/blob/ad9a0c4def222aaf044e51f8ee0939911cb58471/Samples/Accelerometer/cs/Scenario1_DataEvents.xaml.cs#L86 . The reason is that for high-throughput scenarios where you want to just process accelerometer events as they come, you definitely prefer to be on the background thread. This way the Dispatcher would get swamped with potentially hundreds of events and the app would start freezing.

**Closed** 2023-06-06 21:58 UTC
Labels: kind/bug, platform/ios, area/canary, difficulty/tbd
