### ISSUE TITLE
Miscalculates TextBlock width when it has a custom FontFamily

### ISSUE THREAD

**Issue by Avid29** [unoplatform/uno#7481] opened 2021-11-15 21:57 UTC
### Current behavior

TextBlock size is miscalculated when it has a custom font family.

![image](https://user-images.githubusercontent.com/9384045/141859015-8bc6c73b-c1c0-45af-b8b5-be74a471bbbc.png)

### Expected behavior

Account for Font when calculating TextBlock size

### How to reproduce it (as minimally and precisely as possible)

Use a TextBlock with a custom font family that is larger than average

### Workaround

With constant string you can specify the width yourself, however this isn't great for localization 

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia, Uno.UI.RemoteControl / Uno.WinUI.RemoteControl

### NuGet package version(s)

3.10.11

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.0.0

**Comment by jeromelaban** [comment] 2021-11-15 22:34
This is a duplicate of #693. You can try applying the workaround specified there.

**Closed by jeromelaban** 2021-11-15 22:34 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
