### ISSUE TITLE
[Gallery][WASM] "FlipView" is not listed in the components..

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#16359] opened 2024-04-18 20:15 UTC
### Current behavior

![Flipview issue](https://github.com/unoplatform/uno/assets/74563602/9eeea074-320e-48c3-a9a4-161ea6264b21)

### Expected behavior

![Flipview correct skia](https://github.com/unoplatform/uno/assets/74563602/6d9abdea-b925-49a4-9056-10360ab2e9e1)

### How to reproduce it (as minimally and precisely as possible)

Open Uno Gallery APP.
Tap Burger Menu.
Check out the 'FlipView' controls from the "Component" list.
Notice that 'FlipView' is not available in the 'Component" list.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by Youssef1313** [comment] 2024-04-21 16:27
Duplicate of https://github.com/unoplatform/Uno.Gallery/issues/1040

**Closed by Youssef1313** 2024-04-21 16:27 UTC
Labels: kind/bug, platform/wasm 🌐, triage/untriaged, area/canary 🐤, difficulty/tbd
