### ISSUE TITLE
[Gallery][Wasm] MediaPlayerElement  does not play for 'using a playlist' sample option

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#12652] opened 2023-06-20 04:27 UTC
### Current behavior

https://github.com/unoplatform/uno/assets/74563602/726103c0-43d9-473a-8a32-477ba5eca677

### Expected behavior

MediaPlayerElement should play a 'using a playlist' sample option.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right (if the menu is not already opened)
3. Click "MediaPlayerElement" from the "UI Components" list.
4. Launch the last sample:
5. "MediaPlayerElement sample using a Playlist.
6. Observe that the nothing is happening.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by agneszitte** [comment] 2023-06-26 16:02
Closing duplicate of https://github.com/unoplatform/uno/issues/12394 
(cc @jeromelaban, @sakshi173)

**Closed by agneszitte** 2023-06-26 16:02 UTC
Labels: kind/bug, platform/wasm, triage/duplicate, triage/untriaged, area/canary, difficulty/tbd
