### ISSUE TITLE
[WASM] Tapped event isn't called on nested child

### ISSUE THREAD

**Issue by davidjohnoliver** [unoplatform/uno#2843] opened 2020-03-19 19:58 UTC
## How to reproduce it (as minimally and precisely as possible)

1. Run the Windows Community Toolkit samples app. 
2. Navigate to the DataGrid sample.
3. Try to select one of the cells.

## Current behavior
Selection always ends up on the first cell.

The `DataGridCell.DataGridCell_PointerTapped` handler should be called, but isn't. Looking at the logs, `PointerDown` is raised for 4 views in the hierarchy (`DataGrid` handles pointer events at numerous levels), but `PointerUp` is only raised for 2 of them (`DataGridCell` not included). 

```
dotnet.js:1       DataGridRowsPresenter-919369"RowsPresenter": Dispatching event pointermove
dotnet.js:1 dbug: Windows.UI.Input.GestureRecognizer[0]
dotnet.js:1       Received a 'Move' for a pointer which was not considered as down. Ignoring event.
dotnet.js:1 dbug: Windows.UI.Xaml.UIElement.EventRegistration[0]
dotnet.js:1       DataGrid-917777"dataGrid": Dispatching event pointermove
dotnet.js:1 dbug: Windows.UI.Xaml.UIElement.EventRegistration[0]
dotnet.js:1       ScrollContentPresenter-8041"ScrollContentPresenter": Dispatching event pointermove
dotnet.js:1 dbug: Windows.UI.Xaml.UIElement.EventRegistration[0]
dotnet.js:1       DataGridCell-995873: Dispatching event pointerdown
dotnet.js:1 dbug: Windows.UI.Xaml.UIElement.EventRegistration[0]
dotnet.js:1       DataGridRow-995673: Dispatching event pointerdown
dotnet.js:1 dbug: Windows.UI.Xaml.UIElement.EventRegistration[0]
dotnet.js:1       DataGridRowsPresenter-919369"RowsPresenter": Dispatching event pointerdown
dotnet.js:1 info: Windows.UI.Xaml.UIElement.PointerCapture[0]
dotnet.js:1       DataGridRowsPresenter-919369"RowsPresenter": Capturing (Implicit) pointer Mouse/1
dotnet.js:1 dbug: Windows.UI.Xaml.UIElement.EventRegistration[0]
dotnet.js:1       DataGrid-917777"dataGrid": Dispatching event pointerdown
dotnet.js:1 dbug: Windows.UI.Xaml.UIElement.EventRegistration[0]
dotnet.js:1       ScrollContentPresenter-8041"ScrollContentPresenter": Dispatching event pointerdown
dotnet.js:1 dbug: Windows.UI.Xaml.UIElement.EventRegistration[0]
dotnet.js:1       TextBlock-995929: Dispatching event focus
dotnet.js:1 dbug: Windows.UI.Xaml.UIElement.EventRegistration[0]
dotnet.js:1       DataGridCell-995873: Dispatching event pointerleave
dotnet.js:1 dbug: Windows.UI.Xaml.UIElement.EventRegistration[0]
dotnet.js:1       DataGridRow-995673: Dispatching event pointerleave
dotnet.js:1 dbug: Windows.UI.Xaml.UIElement.EventRegistration[0]
dotnet.js:1       DataGridRowsPresenter-919369"RowsPresenter": Dispatching event pointermove
dotnet.js:1 dbug: Windows.UI.Xaml.UIElement.EventRegistration[0]
dotnet.js:1       DataGrid-917777"dataGrid": Dispatching event pointermove
dotnet.js:1 dbug: Windows.UI.Xaml.UIElement.EventRegistration[0]
dotnet.js:1       ScrollContentPresenter-8041"ScrollContentPresenter": Dispatching event pointermove
dotnet.js:1 dbug: Windows.UI.Xaml.UIElement.EventRegistration[0]
dotnet.js:1       DataGridRowsPresenter-919369"RowsPresenter": Dispatching event pointerup
dotnet.js:1 info: Windows.UI.Xaml.UIElement.PointerCapture[0]
dotnet.js:1       DataGridRowsPresenter-919369"RowsPresenter": Releasing (Any) capture of pointer Mouse/1
dotnet.js:1 dbug: Windows.UI.Xaml.UIElement.EventRegistration[0]
dotnet.js:1       DataGrid-917777"dataGrid": Dispatching event pointerup
dotnet.js:1 dbug: Windows.UI.Xaml.UIElement.EventRegistration[0]
dotnet.js:1       DataGridRow-995673: Dispatching event pointerenter
dotnet.js:1 dbug: Windows.UI.Xaml.UIElement.EventRegistration[0]
dotnet.js:1       DataGridCell-995873: Dispatching event pointerenter
dotnet.js:1 dbug: Windows.UI.Xaml.UIElement.EventRegistration[0]
dotnet.js:1       DataGridCell-995873: Dispatching event pointermove
dotnet.js:1 dbug: Windows.UI.Xaml.UIElement.EventRegistration[0]
dotnet.js:1       DataGridRow-995673: Dispatching event pointermove
```

## Expected behavior
Cell is selected successfully.

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.2.0-dev.109

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by dr1rrb** [comment] 2020-03-20 18:08
The issue is that as soon as we press the pointer, we get pointer _leave_ for the **Cell** and **Row**, so we won't receive the _up_:

```
VM71268:1 dispatch pointermove (Microsoft.Toolkit.Uwp.UI.Controls.DataGrid) to 957441
VM71269:1 dispatch pointermove (Windows.UI.Xaml.Controls.ScrollContentPresenter) to 8041
VM71313:1 dispatch pointerdown (Microsoft.Toolkit.Uwp.UI.Controls.DataGridCell) to 1035633
VM71314:1 dispatch pointerdown (Microsoft.Toolkit.Uwp.UI.Controls.DataGridRow) to 1035337
VM71315:1 dispatch pointerdown (Microsoft.Toolkit.Uwp.UI.Controls.Primitives.DataGridRowsPresenter) to 959033
VM71318:1 dispatch pointerdown (Microsoft.Toolkit.Uwp.UI.Controls.DataGrid) to 957441
VM71319:1 dispatch pointerdown (Windows.UI.Xaml.Controls.ScrollContentPresenter) to 8041
VM71320:1 dispatch focus (Windows.UI.Xaml.Controls.TextBlock) to 1035689
VM71329:1 dispatch pointerleave (Microsoft.Toolkit.Uwp.UI.Controls.DataGridCell) to 1035633
VM71330:1 dispatch pointerleave (Microsoft.Toolkit.Uwp.UI.Controls.DataGridRow) to 1035337
VM71331:1 dispatch pointermove (Microsoft.Toolkit.Uwp.UI.Controls.Primitives.DataGridRowsPresenter) to 959033
VM71332:1 dispatch pointermove (Microsoft.Toolkit.Uwp.UI.Controls.DataGrid) to 957441
VM71333:1 dispatch pointermove (Windows.UI.Xaml.Controls.ScrollContentPresenter) to 8041
VM71401:1 dispatch pointermove (Microsoft.Toolkit.Uwp.UI.Controls.Primitives.DataGridRowsPresenter) to 959033
VM71402:1 dispatch pointermove (Microsoft.Toolkit.Uwp.UI.Controls.DataGrid) to 957441
VM71403:1 dispatch pointermove (Windows.UI.Xaml.Controls.ScrollContentPresenter) to 8041
VM71416:1 dispatch pointerup (Microsoft.Toolkit.Uwp.UI.Controls.Primitives.DataGridRowsPresenter) to 959033
VM71419:1 dispatch pointerup (Microsoft.Toolkit.Uwp.UI.Controls.DataGrid) to 957441
VM71420:1 dispatch pointerenter (Microsoft.Toolkit.Uwp.UI.Controls.DataGridRow) to 1035337
VM71421:1 dispatch pointerenter (Microsoft.Toolkit.Uwp.UI.Controls.DataGridCell) to 1035633
dotnet.js:1 L: GC_MINOR: (Nursery full) time 7.23ms, stw 7.24ms promoted 204K major size: 94256K in use: 85055K los size: 8192K in use: 1092K
VM71504:1 dispatch pointermove (Microsoft.Toolkit.Uwp.UI.Controls.DataGridCell) to 1035633
VM71505:1 dispatch pointermove (Microsoft.Toolkit.Uwp.UI.Controls.DataGridRow) to 1035337
VM71506:1 dispatch pointermove (Microsoft.Toolkit.Uwp.UI.Controls.Primitives.DataGridRowsPresenter) to 959033
VM71507:1 dispatch pointermove (Microsoft.Toolkit.Uwp.UI.Controls.DataGrid) to 957441
VM71508:1 dispatch pointermove (Windows.UI.Xaml.Controls.ScrollContentPresenter) to 8041
```

And for instance if we press again on the same cell, we get some error logs which are actually notifications that those controls are already considering the pointer as pressed but they receive a pointer _down_ again, so they try to self recover from this invalid state:
```
dispatch pointerdown (Microsoft.Toolkit.Uwp.UI.Controls.DataGridCell) to 1035633
dotnet.js:1 fail: Windows.UI.Input.GestureRecognizer[0]
dotnet.js:1       Inconsistent state, we already have a pending gesture for a pointer that is going down. Abort the previous gesture.
VM86128:1 dispatch pointerdown (Microsoft.Toolkit.Uwp.UI.Controls.DataGridRow) to 1035337
dotnet.js:1 fail: Windows.UI.Input.GestureRecognizer[0]
dotnet.js:1       Inconsistent state, we already have a pending gesture for a pointer that is going down. Abort the previous gesture.
VM86129:1 dispatch pointerdown (Microsoft.Toolkit.Uwp.UI.Controls.Primitives.DataGridRowsPresenter) to 959033
VM86132:1 dispatch pointerdown (Microsoft.Toolkit.Uwp.UI.Controls.DataGrid) to 957441
VM86133:1 dispatch pointerdown (Windows.UI.Xaml.Controls.ScrollContentPresenter) to 8041
```

What's interesting also is that once the _ up_  reached the `DataGrid` we get _enter_  for **Cell** and **Row**. So my hypothesis for now is that those **Cell** and **Row** are actually replaced (Edit state) or overed by another element (Pressed state)  that cause the browser to dispatch a _leave/enter_  on those items.

**Comment by dr1rrb** [comment] 2020-08-28 18:44
This has been fixed by https://github.com/unoplatform/uno/pull/2874

**Closed by dr1rrb** 2020-08-28 18:44 UTC
Labels: kind/bug, triage/untriaged
