### ISSUE TITLE
Folder in solution with name "Uno" causes namespace resolution errors

### ISSUE THREAD

**Issue by FrancoisM** [unoplatform/uno#28] opened 2018-06-12 10:13 UTC
I'm trying to add Uno to an existing solution.
I "logically" created a Uno folder in the solution. I added MyApp.Uno.UPW, MyApp.Uno.iOS and MyApp.Uno.Shared projects with the proper nuget packages and references. 
When I build the iOS project I had an error like:

> The type or namespace name 'UI' does not exist in the namespace 'MyApp.Uno' (are you missing an assembly reference?)

I had to rename my folder to UnoApp and projects to MyApp.UnoApp.UWP etc to get it to compile.

**Comment by jeromelaban** [comment] 2018-06-16 19:01
Looks like the Uno source generators are missing some `global::` prefixes :)

**Comment by ghuntley** [comment] 2019-10-09 01:34
:wave: had the opportunity to dig into this and this is what I found.

1. File -> New "MyApp.Uno"
2. Update to latest pre-release of Uno.* packages
3. Building on WASM and Android results in

```
Error        CS0234        The type or namespace name 'Extensions' does not exist in the namespace 'MyApp.Uno' (are you missing an assembly reference?)        MyApp.Uno.Droid, MyApp.Uno.UWP, MyApp.Uno.Wasm, MyApp.Uno.iOS        C:\code\unoplatform\MyApp.Uno\MyApp.Uno\MyApp.Uno.Shared\App.xaml.cs        32        Active
```

4. Adding `global:: namespace` to ConfigureFilters resolves

```
        public App()
        {
            ConfigureFilters(global::Uno.Extensions.LogExtensionPoint.AmbientLoggerFactory);

            this.InitializeComponent();
            this.Suspending += OnSuspending;
        }
```

4. Android and WebAsm compile fine.
5. iOS untested, pending macOS configuration on Geoff's end due to Catalina release.

**Comment by peternary** [comment] 2019-10-10 12:10
I'm still getting this issue with latest Uno build.  Sample project attached.  
[Test2.Uno.zip](https://github.com/unoplatform/uno/files/3712438/Test2.Uno.zip)

**Comment by ghuntley** [comment] 2019-10-10 22:24
Sorry to hear that Peter, thank-you for attaching a test case - investigating.

**Comment by ghuntley** [comment] 2019-10-10 23:40
Howdy,

I was able to reproduce the issue in the above test case. The solution is to add `global::` to `ConfigureFilters` to your existing applications. See https://github.com/geoffreyhuntley/uno-28/commit/f15c8aa2c0f729a77474998da3c9c84a76d9efbe for a diff. 

The PR at https://github.com/unoplatform/uno/pull/1771 fixes the problem in the solution template generator and next time we publish a stable release that fix will be included. We currently don't automatically publish pre-release versions of the Visual Studio extension to the market place but do publish them as artifacts over at https://github.com/unoplatform/uno/pull/1213/files

I'll raise a item on the backlog for devops to investigate/implement if the Visual Studio market place supports the notion of publishing pre-releases.

**Comment by ghuntley** [comment] 2019-10-10 23:43
Let me know if this doesn't resolve your issues!

**Closed** 2019-10-22 01:53 UTC
Labels: kind/bug, kind/consumer-experience, priority/backlog, triage/needs-information
