### ISSUE TITLE
Calendar controls

### ISSUE THREAD

**Issue by bbrittonHHL** [unoplatform/uno#1933] opened 2019-10-22 15:08 UTC
We need all the calendar controls in WebAssembly for this project to be useful to us.
CalendarView
CalendarDatePicker

**Comment by jeromelaban** [comment] 2019-10-22 18:07
Thank for opening this issue! This is a duplicate of #365, I'll update it to include CalendarView as well.

**Closed by jeromelaban** 2019-10-22 18:07 UTC
Labels: triage/duplicate
