### ISSUE TITLE
[Gallery][Wasm] Scale animation is not the same as UWP

### ISSUE THREAD

**Issue by ebariche** [unoplatform/uno#5141] opened 2021-02-04 20:50 UTC
Wasm

![scale-anim](https://user-images.githubusercontent.com/33458222/106953675-a3c21a80-6700-11eb-8357-b35c8d08c1fc.gif)

UWP

![scale-anim-uwp](https://user-images.githubusercontent.com/33458222/106953700-b0467300-6700-11eb-9f4d-b04489e1f335.gif)

**Comment by dr1rrb** [comment] 2021-02-05 02:34
Duplicate of https://github.com/unoplatform/uno/issues/5111

**Closed** 2021-02-08 18:34 UTC
Labels: area/canary, kind/bug, triage/untriaged

**Comment by sakshi173** [comment] 2021-02-10 21:35
Verified, Issue is Fixed -- Closing
