### ISSUE TITLE
Bug: Popup Should be a Primitive

### ISSUE THREAD

**Issue by robloo** [unoplatform/uno#4140] opened 2020-09-24 17:39 UTC
## Current behavior

The Popup class is declared as follows:

https://github.com/unoplatform/uno/blob/5d9f9428a6812445540ceeda4036edb8c33a583c/src/Uno.UI/UI/Xaml/Controls/Popup/Popup.cs#L11-L15

## Expected behavior

Popup should be inside the Windows.UI.Xaml.Controls.Primitives namespace.

https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.primitives.popup?view=winrt-19041

Correcting this should also fix the implemented views docs [here](https://platform.uno/docs/articles/implemented-views.html) where Popup is listed as not-implemented.

## How to reproduce it (as minimally and precisely as possible)

N/A

## Workaround

N/A

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment] 2020-09-24 18:21
Thanks for the report. This issue is a duplicate of #134.

**Closed by jeromelaban** 2020-09-24 18:21 UTC
Labels: kind/bug, triage/untriaged
