### ISSUE TITLE
We must define base type in code-behind for DOGen to kick-in

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#9241] opened 2022-07-11 06:40 UTC
### Current behavior

Had a series of problems with Uno when I switched to using x:Bind everywhere:

```xml
<muxc:TabViewItem Header="File" IsClosable="False">
    <views:FileInteractionsView ViewModel="{x:Bind ViewModel.FileInteractions, Mode=OneTime}" />
</muxc:TabViewItem>
```
will throw:
```
C:\Users\haven\source\repos\HavenDV\Uno.Issues\setbinding\Uno\H.ReactiveUI.Apps.Uno.Skia.Wpf\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\MainView_d81367e8f936f2548465ab1397a9fc96.cs(81,41,81,51): error CS1061: 'DependencyObject' does not contain a definition for 'SetBinding' and no accessible extension method 'SetBinding' accepting a first argument of type 'DependencyObject' could be found (are you missing a using directive or an assembly reference?)
```

Also, second issue, it will throw series of NRE after run, but it will work

### How to reproduce it (as minimally and precisely as possible)

https://github.com/HavenDV/Uno.Issues/tree/main/setbinding
[Uno.Issues_setbinding.zip](https://github.com/unoplatform/uno/files/9081420/Uno.Issues_setbinding.zip)

1. Remove workaround(DependencyObjectExtensions.cs) from Uno project.
2. Remove `ItemGroup Label="GlobalUsings"` from Uno .csproj file.

### Workaround

Define the base type also in the code-behind (`.xaml.cs` file)

~~```cs~~
~~namespace H.ReactiveUI.Apps.Uno.Extensions;~~

~~public static partial class DependencyObjectExtensions~~
~~{~~
    ~~public static void SetBinding(~~
        ~~this DependencyObject dependencyObject,~~
        ~~string dependencyProperty,~~
        ~~BindingBase binding)~~
    ~~{~~
        ~~(dependencyObject as UIElement)?.SetBinding(dependencyProperty, binding);~~
    ~~}~~
~~}~~

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.4.13

### Affected platforms

WebAssembly, Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.3 preview 2

**Comment by dr1rrb** [comment] 2022-07-13 11:10
Hey, I unable to build your sample, I get some errors about "base" views:
```
1>C:\Src\Repro\9241\Uno.Issues-main\setbinding\H.ReactiveUI.Apps.WinUI\obj\x64\Debug\net6.0-windows10.0.18362.0\Views\MainView.g.i.cs(13,61,13,73): error CS0234: The type or namespace name 'MainViewBase' does not exist in the namespace 'HReactiveUI.Apps.Views' (are you missing an assembly reference?)
1>C:\Src\Repro\9241\Uno.Issues-main\setbinding\H.ReactiveUI.Apps.WinUI\obj\x64\Debug\net6.0-windows10.0.18362.0\Views\MessageInteractionsView.g.i.cs(13,76,13,103): error CS0234: The type or namespace name 'MessageInteractionsViewBase' does not exist in the namespace 'HReactiveUI.Apps.Views' (are you missing an assembly reference?)
1>C:\Src\Repro\9241\Uno.Issues-main\setbinding\H.ReactiveUI.Apps.WinUI\obj\x64\Debug\net6.0-windows10.0.18362.0\Views\FileInteractionsView.g.i.cs(13,73,13,97): error CS0234: The type or namespace name 'FileInteractionsViewBase' does not exist in the namespace 'HReactiveUI.Apps.Views' (are you missing an assembly reference?)
1>C:\Src\Repro\9241\Uno.Issues-main\setbinding\H.ReactiveUI.Apps.WinUI\obj\x64\Debug\net6.0-windows10.0.18362.0\Views\WebInteractionsView.g.i.cs(13,72,13,95): error CS0234: The type or namespace name 'WebInteractionsViewBase' does not exist in the namespace 'HReactiveUI.Apps.Views' (are you missing an assembly reference?)
1>C:\Src\Repro\9241\Uno.Issues-main\setbinding\H.ReactiveUI.Apps.WinUI\obj\x64\Debug\net6.0-windows10.0.18362.0\Views\PreviewDropView.g.i.cs(13,68,13,87): error CS0234: The type or namespace name 'PreviewDropViewBase' does not exist in the namespace 'HReactiveUI.Apps.Views' (are you missing an assembly reference?)
```

I suspect that some generators didn't ran properly on the `H.ReactiveUI.Apps.Core` project as I get this in the log:
```
2>CSC : warning CS8032: An instance of analyzer H.Generators.ConstructorGenerator cannot be created from C:\Users\David\.nuget\packages\viewbasegenerator\1.8.2\analyzers\dotnet\cs\ViewBaseGenerator.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Le fichier spécifié est introuvable..
2>CSC : warning CS8032: An instance of analyzer H.Generators.ViewBaseGenerator cannot be created from C:\Users\David\.nuget\packages\viewbasegenerator\1.8.2\analyzers\dotnet\cs\ViewBaseGenerator.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Le fichier spécifié est introuvable..
```

It might be the same issue for the bug your reported: the `DependencyObject` is actually an interface as we inherit from native view. We are then generating some code to add the missing methods. If generators are broken in the project, it might explain why you don't have the `SetBinding`

**Comment by HavenDV** [comment] 2022-07-13 11:18
I will remove the generators and give you an example without them

**Comment by HavenDV** [comment] 2022-07-13 11:42
Regarding the problem with starting generators: https://github.com/dotnet/roslyn/issues/61333
The generator requires Microsoft.CodeAnalysis 4.2.0, which is only supported from dotnet 6.0.300+.

**Comment by jeromelaban** [comment] 2022-08-01 17:36
Indeed, this is a duplicate of https://github.com/unoplatform/uno/issues/7404.

**Closed by jeromelaban** 2022-08-01 17:36 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
