### ISSUE TITLE
ARM64 support for Uno Platform Visual Studio VSIX

### ISSUE THREAD

**Issue by JaiganeshKumaran** [unoplatform/uno#12449] opened 2023-05-28 08:09 UTC
## What would you like to be added:
Currently the Uno Platform extension for Visual Studio (Windows) only works on x64.

## Why is this needed:
To build Uno Platform projects on Windows on ARM.

## For which Platform:

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [x] Solution Templates

**Comment by baskren** [comment] 2023-06-04 14:21
Might be a duplicate of [this](https://github.com/unoplatform/uno/issues/11888) issue?  If so @JaiganeshKumaran , can you upvote that issue as well so it will get some love?

**Closed** 2023-06-12 01:24 UTC
Labels: kind/enhancement, triage/untriaged, difficulty/tbd

**Comment by jeromelaban** [comment] 2023-06-29 14:12
The vsix version 4.9.16 is now published and contains support for arm64 Windows.
