### ISSUE TITLE
[Wasm] TimePicker and FlipView do not display

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#3650] opened 2020-07-28 18:23 UTC
## Current behavior

The TimePicker and the FlipView do not appear in Wasm

## Expected behavior

The TimePicker and the FlipView should appear in Wasm

## How to reproduce it (as minimally and precisely as possible)

Sample:
[WasmControls.zip](https://github.com/unoplatform/uno/files/4990378/WasmControls.zip)

## Environment

Nuget Package:
Uno.UI
Uno.UI.WebAssembly

Package Version(s): 3.0.0-dev.1117

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

No internal issue at the moment

**Comment by davidjohnoliver** [comment] 2020-07-29 14:02
The `TimePicker` issue is a duplicate of https://github.com/unoplatform/uno/issues/1978

**Closed** 2020-07-30 01:55 UTC
Labels: area/wasm, kind/bug, triage/untriaged
