### ISSUE TITLE
[Gallery][Playground][Wasm] CalendarDaterPicker and CalendarView-For Fluent, the year in the calendar is not fully displaying.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7667] opened 2021-12-17 13:33 UTC
### Current behavior

![CalendarDatePicker issue](https://user-images.githubusercontent.com/74563602/146551997-96594cde-f216-4f87-9669-ec617a56b1e8.png)

### Expected behavior

The year in calendar should display properly.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right..
3. Click "CalendarDatePicker" from the "Component" list.
4. Go to Decade view (2120-2029) of the calendar.
5. Observe that the year number is not displaying correctly.

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment] 2021-12-17 14:18
I'm not seeing this: 
![image](https://user-images.githubusercontent.com/5839577/146557829-f45c0d6b-821f-4412-8af2-d2a48dc6dd72.png)

On which OS/Browser did you do this?

**Comment by sakshi173** [comment] 2021-12-17 14:29
@jeromelaban I am checking on MS Edge Browser.

**Comment by carldebilly** [comment] 2022-02-02 20:27
I'm on Edge and can't reproduce either.

**Comment by sakshi173** [comment] 2022-02-03 13:23
@Xiaoy312, I am still am able to reproduce it. please check it.

https://user-images.githubusercontent.com/74563602/152350966-addc3441-c2ce-4a6b-9419-1872f13ccb6d.mp4

**Comment by carldebilly** [comment] 2022-03-02 18:44
No easy repro / unsure.  Closing it for now.

**Closed by carldebilly** 2022-03-02 18:44 UTC
Labels: kind/bug, platform/wasm, triage/untriaged, area/canary, difficulty/tbd, area/date-time-pickers

**Comment by sakshi173** [comment] 2022-03-16 17:56
Not able to reproduce the bug on any other system( I tried on my two personal laptop) due to that closing it.
