### ISSUE TITLE
[skia] Custom font is not working

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#17283] opened 2024-06-25 02:46 UTC
### Current behavior

Embedding a custom font like the free Ready to Party Font https://www.dafont.com/ready-to-party.font does not work.

### Expected behavior

Custom font should work.

### How to reproduce it (as minimally and precisely as possible)

Deploy the app with WinUI and skia (Windows or Mac)

[UnoApp1.zip](https://github.com/user-attachments/files/15963902/UnoApp1.zip)

### Works on UWP/WinUI

None

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

Skia (WPF), Skia (macOS)

### IDE version

Latest VS

**Comment by ArchieCoder** [comment] 2024-06-25 02:49
This is probably affecting https://github.com/unoplatform/uno/issues/16931

**Comment by Youssef1313** [comment] 2024-06-25 04:49
The ms-appx path in repro is not correct, causing a fallback to default font. It should be `ms-appx:///Assets/Fonts/party.ttf#Ready to Party` instead of `ms-appx:///UnoApp1/Assets/Fonts/party.ttf#Ready to Party`. Doing that change, the font is rendered correctly both on Skia and WinAppSDK

**Comment by Youssef1313** [comment] 2024-06-25 04:50
Closing as this seems to be working as expected. Let me know please if you still have additional problems

**Comment by ArchieCoder** [comment] 2024-06-25 11:43
I followed the instructions which mentioned the app name https://platform.uno/docs/articles/features/custom-fonts.html#adding-a-custom-font-in-the-app-assets-folder

![image](https://github.com/unoplatform/uno/assets/1608424/59adfde9-2b0e-4782-8d8b-9da1ae50b449)

**Comment by Youssef1313** [comment] 2024-06-25 11:46
Reopening as a doc issue

**Comment by luckypong** [comment] 2024-06-25 13:10
If I describe the project I am currently using:

Single Project is ms-appx:///Assets
Library or Shared Projects are ms-appx:///[MyApp]/Assets

After migrating to Single Project in Shared Projects, it was confirmed that the existing font could not be set, and the operation was confirmed after changing ms-appx:///Assets.

**Comment by jeromelaban** [comment] 2024-06-25 19:09
@ArchieCoder here's the updated doc. https://github.com/unoplatform/uno/pull/17301

**Closed** 2024-06-25 20:07 UTC
Labels: kind/bug, triage/untriaged, project/documentation 📖, difficulty/tbd, kind/documentation
