### ISSUE TITLE
Frame NavigationCacheMode.Disabled is not supported

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#4370] opened 2020-10-25 08:22 UTC
## Current behavior
There is no new .Page instance created when navigating back
- load attached in VS
- place breakpoint in MainPage.xaml.cs 37
- start iOS project
- navigate to new page
- navigate back -> new new MainPage object is created -> **wrong**
[UnoFrame.zip](https://github.com/unoplatform/uno/files/5434299/UnoFrame.zip)

## Expected behavior
New instance of .MainPage should be created (like with UWP)

## Environment
Latest UNO packages

Affected platform(s):

- [ x] iOS (I recommend checking other platforms as well)
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ x] Visual Studio 2019 (version: latest)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment] 2020-10-26 01:50
Thanks for the report.

At this point, Uno only supports `Enabled`, the most memory friend mode of the `NavigationCacheMode` property. In general, on iOS and Android, this is what gives the best performance as the UI does not need to be recreated.

I'll renamed this issue as `NavigationCacheMode.Disabled` is not supported, and mark it as a duplicate of https://github.com/unoplatform/uno/issues/4156.

**Closed by jeromelaban** 2020-10-26 01:50 UTC
Labels: kind/bug, triage/untriaged

**Comment by DierkDroth** [comment] 2020-10-26 04:29
Thanks for clarification, @jeromelaban
