### ISSUE TITLE
Uno.Material TimePicker MaterialTimePickerStyle with ClockIdentifier="24HourClock" error

### ISSUE THREAD

**Issue by iosub** [unoplatform/uno#4332] opened 2020-10-20 18:55 UTC
## Current behavior
in UWP
`<TimePicker
    ClockIdentifier="24HourClock"
    Style="{StaticResource MaterialTimePickerStyle}" />`
Generates error Parameter Invalid
## Expected behavior

it does work with   ClockIdentifier="12HourClock"

## How to reproduce it (as minimally and precisely as possible)

run the code above 

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [X ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by francoistanguay** [comment] 2021-03-17 14:24
TimePicker isnt yet supported but we're planning to tackle it in an upcoming release.

**Comment by MartinZikmund** [comment] 2021-06-10 08:35
@iosub If the error occurs in UWP, then the best place to report it would be https://github.com/microsoft/microsoft-ui-xaml

**Comment by Youssef1313** [comment] 2021-08-04 18:26
I can't reproduce any error here. Both 24HourClock and 12HourClock works fine for me.

**Comment by MartinZikmund** [comment] 2024-01-30 13:09
I think this can be closed as Youssef checked.

**Closed by MartinZikmund** 2024-01-30 13:09 UTC
Labels: kind/bug, project/styling 👔, difficulty/starter 🚀
