### ISSUE TITLE
The SwipeControl icon is not displayed.

### ISSUE THREAD

**Issue by PhilippeAudet-Stratejia** [unoplatform/uno#6377] opened 2021-07-01 16:28 UTC
## Current behavior

No icon is displayed when defined in the `<SwipeItem.IconSource>` tag when using this control on mobile devices.
![SwipeControlPathIcon3](https://user-images.githubusercontent.com/83981176/124165156-7c813680-da6f-11eb-894f-98fff9953443.png)

It does work though on a tactile windows device : 
![SwipeControlPathIcon2](https://user-images.githubusercontent.com/83981176/124164931-43e15d00-da6f-11eb-8190-aa52a5c4965b.png)

## Expected behavior

An icon should be displayed over the text of the swipe item when defined in the `<SwipeItem.IconSource>` tag.

## How to reproduce it (as minimally and precisely as possible)
Create a SwipeControl and define a swipe item with an icon. In the sample project, I added different icon types that work fine when used alone, but doesn't show up in the SwipeControl.

[SwipeControlDemo.zip](https://github.com/unoplatform/uno/files/6749534/SwipeControlDemo.zip)

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [x] Other:  The default packages installed with the visual studio extension template.

Nuget Package Version(s):
Uno.UI : v3.8.11
Uno.RemoteControl: v3.8.11
Uno.Core : v2.4.0

Affected platform(s):

- [x] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.3)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [x] Resharper (version: )

**Comment by jeromelaban** [comment] 2021-07-05 15:41
This was fixed in 3.7, but not backported to 3.8, let's reactivate https://github.com/unoplatform/uno/pull/6336 @carldebilly

**Comment by jeromelaban** [comment] 2021-07-07 18:33
https://github.com/unoplatform/uno/pull/6336 is merged but the project is going to have to move to 3.9 anyways, so can you ensure that the issue is fixed for you in 3.9-dev or in your canary ?

**Comment by PhilippeAudet-Stratejia** [comment] 2021-07-07 20:27
@jeromelaban I have tested on iOS and android with version 3.9.0-dev.197 and the control is working properly, thanks !

**Comment by jeromelaban** [comment] 2021-07-07 20:29
Excellent. I'll close this issue.

**Closed by jeromelaban** 2021-07-07 20:29 UTC
Labels: difficulty/tbd, kind/bug, triage/untriaged
