### ISSUE TITLE
how fix this 

### ISSUE THREAD

**Issue by AbdalaMask** [unoplatform/uno#9391] opened 2022-07-29 08:35 UTC
### Current behavior

![image](https://user-images.githubusercontent.com/37013638/181719211-8c8f69ee-5bc5-491e-834b-3bbbf52e2446.png)

**Comment by AbdalaMask** [comment] 2022-07-29 18:53
[NetStudio.Scada.Shared.zip](https://github.com/unoplatform/uno/files/9222599/NetStudio.Scada.Shared.zip)
  sample to watch
It works on all platforms except Android

**Comment by francoistanguay** [comment] 2022-07-30 01:24
Yo8 will need to provide more details if you want the team to consider it. No idea what the issue is form the description.

**Comment by AbdalaMask** [comment] 2022-07-30 04:19
> NetStudio.Scada.Shared.zip

**Comment by AbdalaMask** [comment] 2022-07-30 04:20
https://github.com/unoplatform/uno/files/9222599/NetStudio.Scada.Shared.zip
This tool has the problem

**Comment by francoistanguay** [comment] 2022-07-30 18:19
Will have this to close this issue. If you are able to provide a valid description as to what the issue is, with details about what are the expected and actual behaviors, we could then possibly look into it. 

Thank you.

**Closed by francoistanguay** 2022-07-30 18:19 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
