### ISSUE TITLE
Skia.Gtk don't display textblock

### ISSUE THREAD

**Issue by blackbutton** [unoplatform/uno#8292] opened 2022-03-10 09:39 UTC
### Current behavior

In my windows10, use dotnet cli and create unoapp-net6 project.
use vs2022, open this project and publish linux-x64
put the publish files to ubuntu20, then run it:

warn: Windows.UI.Xaml.UIElement[0]
      The BorderThicknessProperty dependency property does not exist on Uno.UI.Xaml.Core.RootVisual
fail: Windows.UI.Composition.CompositionObject[0]
      The member void CompositionObject.Dispose() is not implemented in Uno.
TextBlock don't display

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment] 2022-03-10 13:24
Thanks for the report. This issue is a duplicate of #6441.

**Closed by jeromelaban** 2022-03-10 13:24 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
