### ISSUE TITLE
[Android][iOS] WrapPanel fails to load

### ISSUE THREAD

**Issue by ramezgerges** [unoplatform/uno#13212] opened 2023-08-11 17:08 UTC
### Current behavior

WrapPanel is failing to load using the latest packages on Android and iOS. This seems to be a recent regression. On Android, here's a section of the stack trace:

```
System.InvalidOperationException: 'Failed to load WrapPanelTest.MainPage: Java.Lang.ClassNotFoundException: crc64b3f9d79751133e9d.WrapPanel
 ---> Java.Lang.ClassNotFoundException: Didn't find class "crc64b3f9d79751133e9d.WrapPanel" on path: DexPathList[[zip file "/data/app/~~c8JwHkQYCJNTZ5lKXGdN2g==/com.companyname.WrapPanelTest-drT9S-nWL2PDIuoV5GMJdg==/base.apk"],nativeLibraryDirectories=[/data/app/~~c8JwHkQYCJNTZ5lKXGdN2g==/com.companyname.WrapPanelTest-drT9S-nWL2PDIuoV5GMJdg==/lib/x86_64, /data/app/~~c8JwHkQYCJNTZ5lKXGdN2g==/com.companyname.WrapPanelTest-drT9S-nWL2PDIuoV5GMJdg==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]

  --- End of managed Java.Lang.ClassNotFoundException stack trace ---
java.lang.ClassNotFoundException: Didn't find class "crc64b3f9d79751133e9d.WrapPanel" on path: DexPathList[[zip file "/data/app/~~c8JwHkQYCJNTZ5lKXGdN2g==/com.companyname.WrapPanelTest-drT9S-nWL2PDIuoV5GMJdg==/base.apk"],nativeLibraryDirectories=[/data/app/~~c8JwHkQYCJNTZ5lKXGdN2g==/com.companyname.WrapPanelTest-drT9S-nWL2PDIuoV5GMJdg==/lib/x86_64, /data/app/~~c8JwHkQYCJNTZ5lKXGdN2g==/com.companyname.WrapPanelTest-drT9S-nWL2PDIuoV5GMJdg==/base.apk!/lib/x86_64, /system/lib64, /system_ext/lib64]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at crc64a352b6f848b4d68e.NativeApplication_ActivityCallbacks.n_onActivityStarted(Native Method)
	at crc64a352b6f848b4d68e.NativeApplication_ActivityCallbacks.onActivityStarted(NativeApplication_ActivityCallbacks.java:99)
	at android.app.Application.dispatchActivityStarted(Application.java:401)
	at android.app.Activity.dispatchActivityStarted(Activity.java:1404)
	at android.app.Activity.onStart(Activity.java:1922)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:345)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at crc6467d88aaa7548788d.BaseActivity.n_onStart(Native Method)
	at crc6467d88aaa7548788d.BaseActivity.onStart(BaseActivity.java:611)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1543)
	at android.app.Activity.performStart(Activity.java:8330)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3670)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7872)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

  --- End of managed Java.Lang.ClassNotFoundException stack trace ---
```

### Expected behavior

WrapPanel should load properly like on the other platforms

### How to reproduce it (as minimally and precisely as possible)

Repro: 
[WrapPanelTest.zip](https://github.com/unoplatform/uno/files/12323754/WrapPanelTest.zip)

Alternative instructions:
Create a new sample, install the community toolkit, and don't forget the conditional here: https://platform.uno/docs/articles/uno-community-toolkit.html?tabs=tabid-winui#referencing-the-windows-community-toolkit-from-a-cross-targeted-library.

```
<Page x:Class="WrapPanelTest.MainPage"
	xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
	xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
	xmlns:local="using:WrapPanelTest"
	xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
	xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
	xmlns:controls="using:CommunityToolkit.WinUI.UI.Controls"
	mc:Ignorable="d"
	Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">

	<controls:WrapPanel>
		<Rectangle Width="100" Height="100" Fill="Red" />
		<Rectangle Width="100" Height="100" Fill="Green" />
		<Rectangle Width="100" Height="100" Fill="Blue" />
		<Rectangle Width="100" Height="100" Fill="Yellow" />
		<Rectangle Width="100" Height="100" Fill="Orange" />
		<Rectangle Width="100" Height="100" Fill="Purple" />
		<Rectangle Width="100" Height="100" Fill="Gray" />
		<Rectangle Width="100" Height="100" Fill="Black" />
		<Rectangle Width="100" Height="100" Fill="White" />
		<Rectangle Width="100" Height="100" Fill="Pink" />
		<Rectangle Width="100" Height="100" Fill="Brown" />
		<Rectangle Width="100" Height="100" Fill="Cyan" />
		<Rectangle Width="100" Height="100" Fill="DarkGray" />
		<Rectangle Width="100" Height="100" Fill="LightGray" />
		<Rectangle Width="100" Height="100" Fill="Magenta" />
		<Rectangle Width="100" Height="100" Fill="Olive" />
		<Rectangle Width="100" Height="100" Fill="Lime" />
		<Rectangle Width="100" Height="100" Fill="Teal" />
		<Rectangle Width="100" Height="100" Fill="Navy" />
		<Rectangle Width="100" Height="100" Fill="Maroon" />
		<Rectangle Width="100" Height="100" Fill="Aquamarine" />
		<Rectangle Width="100" Height="100" Fill="BlueViolet" />
		<Rectangle Width="100" Height="100" Fill="CadetBlue" />
		<Rectangle Width="100" Height="100" Fill="Chocolate" />
		<Rectangle Width="100" Height="100" Fill="Coral" />
		<Rectangle Width="100" Height="100" Fill="CornflowerBlue" />
		<Rectangle Width="100" Height="100" Fill="DarkCyan" />
		<Rectangle Width="100" Height="100" Fill="DarkGoldenrod" />
	</controls:WrapPanel>
</Page>

```

### Works on UWP/WinUI

Yes

### NuGet package version(s)

Here's `Directory.Package.props`

```
<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">
    <PackageVersion Include="CommunityToolkit.WinUI.UI.Controls" Version="7.1.2" />
    <PackageVersion Include="Uno.CommunityToolkit.WinUI.UI.Controls" Version="7.1.200-dev.6.gf657bb2e91" />
  </ItemGroup>
  <ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) != 'windows'">
    <PackageVersion Include="Uno.CommunityToolkit.WinUI.UI.Controls" Version="7.1.200-dev.6.gf657bb2e9" />
  </ItemGroup>
  <ItemGroup>
    <!--<PackageVersion Include="CommunityToolkit.WinUI.UI.Controls" Version="7.1.2" />-->
    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
    <PackageVersion Include="Microsoft.Windows.Compatibility" Version="7.0.0" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.756" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.3.230602002" />
    <PackageVersion Include="SkiaSharp.Skottie" Version="2.88.3" />
    <PackageVersion Include="SkiaSharp.Views.Uno.WinUI" Version="2.88.3" />
    <!--<PackageVersion Include="Uno.CommunityToolkit.WinUI.UI.Controls" Version="7.1.200-dev.6.gf657bb2e91" />-->
    <PackageVersion Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
    <PackageVersion Include="Uno.Extensions.Logging.OSLog" Version="1.4.0" />
    <PackageVersion Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.4.0" />
    <PackageVersion Include="Uno.Resizetizer" Version="1.2.0-dev.32" />
    <PackageVersion Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="5.0.0-dev.1949" />
    <PackageVersion Include="Uno.UniversalImageLoader" Version="1.9.36" />
    <PackageVersion Include="Uno.Wasm.Bootstrap" Version="7.0.27" />
    <PackageVersion Include="Uno.Wasm.Bootstrap.DevServer" Version="7.0.27" />
    <PackageVersion Include="Uno.Wasm.Bootstrap.Server" Version="7.0.27" />
    <PackageVersion Include="Uno.WinUI" Version="5.0.0-dev.1949" />
    <PackageVersion Include="Uno.WinUI.RemoteControl" Version="5.0.0-dev.1949" />
    <PackageVersion Include="Uno.WinUI.Skia.Gtk" Version="5.0.0-dev.1949" />
    <PackageVersion Include="Uno.WinUI.WebAssembly" Version="5.0.0-dev.1949" />
    <PackageVersion Include="Xamarin.Google.Android.Material" Version="1.9.0.1" />
    <!-- Required to avoid warnings in 1.9.0.1 of Android.Material - https://github.com/xamarin/AndroidX/issues/727 -->
    <PackageVersion Include="Xamarin.AndroidX.Annotation" Version="1.6.0.3" />
  </ItemGroup>
```

### Affected platforms

Android, iOS

**Comment by Youssef1313** [comment] 2023-08-11 18:54
I took a quick look and I **think** the problem is that Uno.WCT only supports `net7.0`, so it may be pulling the reference API of Uno, and then wrong types could be pulled for the android head.

This is mostly a hypothesis though.

**Comment by agneszitte** [comment] 2023-08-14 16:20
> I took a quick look and I **think** the problem is that Uno.WCT only supports `net7.0`, so it may be pulling the reference API of Uno, and then wrong types could be pulled for the android head.
> 
> This is mostly a hypothesis though.

cc @jeromelaban

**Comment by jeromelaban** [comment] 2023-08-14 18:50
It would be interesting to know if the community toolkit binaries in the output are indeed the ones from wasm/reference. We may be forced to build a net8.0 version of WCT. This particular behavior of nuget is really problematic...

**Comment by Youssef1313** [comment] 2023-08-15 05:23
I can confirm this is already fixed and was caused by the package shipping binaries for `net7.0` only. This is fixed in https://github.com/unoplatform/Uno.WindowsCommunityToolkit/commit/3d58e4a38f3f987eac65983e4d7763bcbb2ae206.

@jeromelaban Can you push a new version to NuGet.org?

**Comment by Youssef1313** [comment] 2023-08-15 20:06
I think we can close this.

**Closed by Youssef1313** 2023-08-15 20:06 UTC
Labels: kind/bug, project/third-party, area/windows-community-toolkit, difficulty/medium

**Comment by agneszitte** [comment] 2023-08-15 20:07
Yes confirmed for Gallery iOS/Android when I tested locally with latest Uno WCT 7.1.200-dev.13+ef3f523648
