### ISSUE TITLE
[Skia] Inconsistent `ImageBrush` behavior

### ISSUE THREAD

**Issue by srb-milestone** [unoplatform/uno#10740] opened 2022-12-15 16:44 UTC
### Current behavior

This XAML code gives a different result, depending on the platform:

```
<Grid>
        <Button CornerRadius="50" 
                Width="300" 
                Height="300">
            <Button.Template>
                <ControlTemplate>
                    <Grid>
                        <Ellipse>
                            <Ellipse.Fill>
                                <ImageBrush ImageSource="/Assets/thispersondoesnotexist.com.jpg"/>
                            </Ellipse.Fill>
                        </Ellipse>
                    </Grid>
                </ControlTemplate>
            </Button.Template>
        </Button>
    </Grid>
```

Skia.Gtk:
![image](https://user-images.githubusercontent.com/30240105/207914325-7f6d4520-635b-44a6-b191-046715fb9c20.png)

Skia.WPF:
![image](https://user-images.githubusercontent.com/30240105/207914497-93dfca59-2aca-4413-8e17-129e45e6bb07.png)

### Expected behavior

On Windows:
![image](https://user-images.githubusercontent.com/30240105/207917655-de9b4b69-4e93-4832-8ac0-adc24dbc93b8.png)

On Wasm:
![image](https://user-images.githubusercontent.com/30240105/207917569-887fd92b-ee5d-4115-97d4-64c340fb1e0f.png)

On Android:
![image](https://user-images.githubusercontent.com/30240105/207918039-17b3477c-2888-42c1-89ed-8a5f03f575c7.png)

### How to reproduce it (as minimally and precisely as possible)

Run the attached app:

[UnoImageBrushBug.zip](https://github.com/unoplatform/uno/files/10238958/UnoImageBrushBug.zip)

### Works on UWP/WinUI

Yes

**Comment by FrozDark** [comment] 2022-12-15 17:44
Which version of Uno did you use?
It's a duplicate of https://github.com/unoplatform/uno/issues/10740 but it's closed and I didn't check it out

**Comment by srb-milestone** [comment] 2022-12-15 23:00
Using .NET 7.0 with the following versions:

![image](https://user-images.githubusercontent.com/30240105/207984695-2ca2d7f5-d2c9-4836-a132-3d939425bc19.png)

**Comment by MartinZikmund** [comment] 2023-08-24 08:31
Some basic progress for this one is in [dev/mazi/imagebrush-skia-scaling](https://github.com/unoplatform/uno/tree/dev/mazi/imagebrush-skia-scaling), but several things are missing:

- Applying alignment
- Ensuring the `BorderLayerRenderer` does not apply its own logic to this
- The image is tiling when `UniformToFill` - see `ImageBrush_Stretch` for example

**Closed** 2023-11-03 08:22 UTC
Labels: kind/bug, area/skia ✏️, project/shapes-brushes 🔶, project/media 📺, difficulty/medium 🤔
