### ISSUE TITLE
[iOS] Stretched filled ellipse not displaying 

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno#2542] opened 2020-01-27 19:07 UTC
## Current behavior

Stretched filled ellipse not displaying on iOS

[iOS]
![image](https://user-images.githubusercontent.com/16295702/73205195-88e0c180-410e-11ea-9093-e72b1e28f577.png)

## Expected behavior

Stretched filled ellipse should display correctly on all platforms

[UWP]
![image](https://user-images.githubusercontent.com/16295702/73205235-9d24be80-410e-11ea-8597-2490548b2287.png)

## How to reproduce it (as minimally and precisely as possible)
_**[Sample repro solution in attachment of this issue]**_

`<Grid Background="DarkBlue">

		<Grid Height="74"
			  Width="74"
			  VerticalAlignment="Center"
			  HorizontalAlignment="Center">

			
			<Ellipse VerticalAlignment="Stretch"
					 HorizontalAlignment="Stretch"
					 Fill="White" />

			
			<Ellipse VerticalAlignment="Stretch"
					 HorizontalAlignment="Stretch"
					 Stroke="Red"
					 StrokeThickness="2"
					 Fill="Transparent"
					 Margin="2" />
		</Grid>
	</Grid>
`

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.1.0-dev.878

Affected platform(s):

- [X] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: 16.4.1)
- [ ] for Mac (version: )

Related issue: https://nventive.visualstudio.com/Umbrella/_workitems/edit/171681

## Anything else we need to know?

Another bug related to Ellipse on Android: #2547

**Comment by agneszitte-nventive** [comment] 2020-01-27 19:12
[EllipseNotVisibleOniOS.zip](https://github.com/unoplatform/uno/files/4118879/EllipseNotVisibleOniOS.zip)
Sample repro solution

**Comment by dr1rrb** [comment] 2020-01-27 19:43
This bug is most probably the root cause of https://github.com/unoplatform/uno/issues/2441

**Comment by agneszitte-nventive** [comment] 2020-01-27 20:00
As a reminder @dr1rrb / @carldebilly, for this particular issue, there is no animation.

**Comment by carldebilly** [comment] 2020-02-04 15:52
@agneszitte-nventive 
It has not been tested yet, but the package [Uno.UI v`2.1.0-dev.1090`](https://www.nuget.org/packages/Uno.UI/2.1.0-dev.1090) contains fixes related to this issue and it should be tested again on this version.

**Comment by agneszitte-nventive** [comment] 2020-02-04 17:33
@carldebilly Sample solution tested with https://www.nuget.org/packages/Uno.UI/2.1.0-dev.1090 and it's still the same.

**Comment by carldebilly** [comment] 2020-02-04 18:32
Ok thanks @agneszitte-nventive

**Comment by carldebilly** [comment] 2020-02-07 14:49
Fixed by PR #2608 - will be present in package [`Uno.UI v2.1.0-dev.1166`](https://www.nuget.org/packages/Uno.UI/2.1.0-dev.1166)

**Closed by carldebilly** 2020-02-07 14:49 UTC
Labels: kind/bug, kind/regression
