### ISSUE TITLE
[SVG - Android] Failed to load SVG image - System.Xml.XmlException: Invalid character in the given encoding.

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno#15866] opened 2024-03-12 21:31 UTC
### Current behavior

`Failed to load SVG image - System.Xml.XmlException: Invalid character in the given encoding` happening when loading the MainPage of the sample app on Android.

```
[Choreographer] Skipped 54 frames!  The application may be doing too much work on its main thread.
[monodroid-assembly] open_from_bundles: failed to load assembly Svg.Model.dll
[monodroid-assembly] open_from_bundles: failed to load assembly ShimSkiaSharp.dll
Loaded assembly: /data/data/com.companyname.UnoSvgSample/files/.__override__/Svg.Model.dll [External]
Loaded assembly: /data/data/com.companyname.UnoSvgSample/files/.__override__/ShimSkiaSharp.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly System.Runtime.InteropServices.RuntimeInformation.dll
Loaded assembly: /data/data/com.companyname.UnoSvgSample/files/.__override__/System.Runtime.InteropServices.RuntimeInformation.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly Svg.Custom.dll
Loaded assembly: /data/data/com.companyname.UnoSvgSample/files/.__override__/Svg.Custom.dll [External]
[monodroid-assembly] open_from_bundles: failed to load assembly ExCSS.dll
Loaded assembly: /data/data/com.companyname.UnoSvgSample/files/.__override__/ExCSS.dll [External]
[DOTNET] fail: Uno.UI.Svg.SvgProvider[0]
[DOTNET]       Failed to load SVG image.
[DOTNET]       System.Xml.XmlException: Invalid character in the given encoding. Line 1, position 1.
[DOTNET]          at System.Xml.XmlTextReaderImpl.Throw(Exception e)
[DOTNET]          at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
[DOTNET]          at System.Xml.XmlTextReaderImpl.Throw(Int32 pos, String res)
[DOTNET]          at System.Xml.XmlTextReaderImpl.InvalidCharRecovery(Int32& bytesCount, Int32& charsCount)
[DOTNET]          at System.Xml.XmlTextReaderImpl.GetChars(Int32 maxCharsCount)
[DOTNET]          at System.Xml.XmlTextReaderImpl.ReadData()
[DOTNET]          at System.Xml.XmlTextReaderImpl.SwitchEncoding(Encoding newEncoding)
[DOTNET]          at System.Xml.XmlTextReaderImpl.SwitchEncodingToUTF8()
[DOTNET]          at System.Xml.XmlTextReaderImpl.ParseXmlDeclaration(Boolean isTextDecl)
[DOTNET]          at System.Xml.XmlTextReaderImpl.Read()
[DOTNET]          at System.Xml.XmlTextReader.Read()
[DOTNET]          at Svg.SvgTextReader.Read() in /_/externals/SVG/Source/SvgTextReader.cs:line 66
[DOTNET]          at Svg.SvgDocument.Create[SvgDocument](XmlReader reader) in /_/externals/SVG/Source/SvgDocument.cs:line 363
[DOTNET]          at Svg.SvgDocument.Open[SvgDocument](Stream stream, Dictionary`2 entities) in /_/externals/SVG/Source/SvgDocument.cs:line 299
[DOTNET]          at Svg.Model.SvgExtensions.Open(Stream stream) in /_/src/Svg.Model/SvgExtensions.IO.cs:line 329
[DOTNET]          at Svg.Skia.SKSvg.Load(Stream stream) in /_/src/Svg.Skia/SKSvg.Model.cs:line 63
[DOTNET]          at Uno.UI.Svg.SvgProvider.<>c__DisplayClass22_0.<LoadSvgAsync>b__0()
```

### Expected behavior

The application should not throw an exception while using an SVG file for Image control like it is currently working on Windows, WASM, Skia, and iOS.

### How to reproduce it (as minimally and precisely as possible)

- Open the sample app attached here ([UnoSvgSample.zip](https://github.com/unoplatform/uno/files/14578876/UnoSvgSample.zip))
- Build and launch the app for Android
- Noticed the exception mentioned above in the output when the MainPage is displayed and that the SVG is not visible like on the other platforms

-----
In MainPage.xaml
```
    <Image Source="ms-appx:///UnoSvgSample/Assets/unologo.svg"
           Height="80"
           Width="80" />
```
In UnoSvgSample.csproj
```
  <ItemGroup>
    <Content Include="Assets\unologo.svg" />
  </ItemGroup>
  <ItemGroup>
    <None Remove="Assets\unologo.svg" />
  </ItemGroup>
```

### Workaround

N/A

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.WinUI : 5.1.87

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.9.2

**Comment by agneszitte** [comment] 2024-03-12 21:32
cc @MartinZikmund

**Comment by MartinZikmund** [comment] 2024-03-13 04:08
The encoding mentioned in the error might be the pointer to the problem. Is it this specific SVG that does not work? Or all SVGs throw?

**Comment by agneszitte** [comment] 2024-03-13 15:40
> The encoding mentioned in the error might be the pointer to the problem. Is it this specific SVG that does not work? Or all SVGs throw?

@MartinZikmund let me try with other more simple svg (that does not use style or other additional specific data to see)

**Comment by agneszitte** [comment] 2024-03-14 19:22
> > The encoding mentioned in the error might be the pointer to the problem. Is it this specific SVG that does not work? Or all SVGs throw?
> 
> @MartinZikmund let me try with another more simple SVG (that does not use style or other additional specific data to see)

@MartinZikmund I did more tests with multiple SVG, and even for the simpler one that uses only one path data, I still get the same exception on Android (working well on the other platforms).

Here are the tests that I did + the sample solution attached here is ready for you so you can test it on your side
[UnoSvgAndroidTests.zip](https://github.com/unoplatform/uno/files/14607073/UnoSvgAndroidTests.zip)
```
  <StackPanel>
    
    <!-- [TEST 1 - Exception for Android - Uno Platform Logo Colored Svg that uses style and linearGradient -->
    <Image Source="ms-appx:///UnoSvgAndroidTests/Assets/unologo.svg"
           Height="80"
           Width="80" />

    <!-- [TEST 2 - Exception for Android - Uno Platform Logo number 2 Colored Svg that uses style and linearGradient -->
    <Image Source="ms-appx:///UnoSvgAndroidTests/Assets/unologo2.svg"
           Height="80"
           Width="100" />

    <!-- [TEST 3 - Exception for Android - OpenSource Colored Svg that uses no style and no linearGradient, only multiple path data -->
    <Image Source="ms-appx:///UnoSvgAndroidTests/Assets/undraw_opensource.svg"
           Height="80"
           Width="80" />

    <!-- [TEST 4 - Exception for Android - OpenSource Solid filled Svg that uses no style and no linearGradient, only one path data -->
    <Image Source="ms-appx:///UnoSvgAndroidTests/Assets/flowbite_opensource.svg"
           Height="40"
           Width="40" />
    
  </StackPanel>
```

>[!NOTE]
> Here is the Android emulator that I used for my tests
> ![image](https://github.com/unoplatform/uno/assets/16295702/31697cea-5e9e-4030-9b0c-9969f20cc760)

**Comment by MartinZikmund** [comment] 2024-03-16 04:21
@agneszitte @pictos So after quite a bit of debugging I finally have some answers 😂 . In the end Resizetizer is indeed causing the problem, even though I don't understand exactly why. If you build the sample above and extract the `apk`, you will find that **all** of the SVGs are included not only as `.svg` in the root `assets` folder:

![image](https://github.com/unoplatform/uno/assets/1075116/574ec23d-b385-4070-9f86-dc51b34e9fae)

But Resizetizer **also** generates `png` versions of them in `drawable` folders, even though at least two of them are explicitly "removed" in the `.csproj`:

![image](https://github.com/unoplatform/uno/assets/1075116/d3bed9a3-2e97-48f0-a621-3806051e5d06)

This is unfortunately a big problem because our code does the following:

![image](https://github.com/unoplatform/uno/assets/1075116/58599b20-1e34-403b-b771-7e961769a783)

`FindResourceIdFromPath` unfortunately does not include the file extension in the name which means it just searches for a resource with name `unosvgandroidtests_assets_flowbite_opensource` for example, so the condition of the `if` passes and it tries to read the `svg` from the `png` file -> which makes it fail, even though it should use the Android Asset instead. I could theoretically invert the `if` to give precedence to the asset instead, but there still are other issues:

1. We need to generate the Android resource names including their extension (I will take care of this)
2. We must add a way for the user to explicitly ignore a file or even better a wildcard pattern (like `Assets/Svg/**.svg`) and avoid processing it completely so that those drawables that could conflict will not be generated (plus so the `apk` does not contain duplicates unnecessarily when the user actually wants a SVG file) @pictos

**Comment by agneszitte** [comment] 2024-03-16 16:00
> @agneszitte @pictos So after quite a bit of debugging I finally have some answers 😂 . In the end Resizetizer is indeed causing the problem. 

In my head, if we are doing **[Scenario 1]** where we have a .svg in the path, Resizetizer should not generate any .png at all.

**[Scenario 1]**
Using a svg in the path of the Image control 
[Svg file build action = **Content**]
`<Image Source="ms-appx:///UnoSvgSample/Assets/unologo.svg" />`
Following this doc: [Using SVG images (platform.uno)](https://platform.uno/docs/articles/features/svg.html)

**VS** 

**[Scenario 2]**
Using a png in the path that uses an svg file underneath with Uno.Resizetizer (UnoImage) 
[Svg file build action = **UnoImage**]
`<Image Source="ms-appx:///UnoSvgSample/Assets/unologo.png" />`
Following this doc: https://platform.uno/docs/articles/external/uno.resizetizer/doc/using-uno-resizetizer.html?tabs=classlib%2CAndroid#unoimage

**Comment by nickrandolph** [comment] 2024-03-18 03:33
@agneszitte @MartinZikmund @pictos  can we confirm what the normal behavior is for Resizetizer. My understanding is that if you have an SVG it will be automatically picked up as UnoImage. The SVG shouldn't be included in the package, instead the corresponding png files generated by resizetizer are. @pictos  can you confirm this is the correct behaviour?

Assuming the above behaviour is correct, then we need to ensure that if someone changes the build action on an SVG to Content, then we respect this. We should not be generating PNG files (since it shouldn't be included as UnoImage) and the SVG should be packaged as the user would expect.

We shouldn't be using the way they reference the file to determine how the file is packages. However, it maybe that we can have an analyzer as part of Resizetizer that detects when user is referencing an SVG for a file that's being resizetized.

**Comment by pedrojesus-work** [comment] 2024-03-18 20:19
Svgs used as `UnoImage` shouldn't be in the final app, created this issue to track progress on Resizetizer side:

- https://github.com/unoplatform/uno.resizetizer/issues/218

**Comment by pedrojesus-work** [comment] 2024-03-19 20:46
After some investigation that behavior (pack the svg on final app) only happens if the `svg` used by `UnoImage` are inside the `Assets` folder otherwise just the generated images are packaged on final app. It sets the `svg` file to `AndroidAsset`, which isn't done by `Resizetizer`.

The workaround that I found is to not add `UnoImages` inside `Assets` folder or subfolders, couldn't find a way to remove it during the build yet, maybe @jeromelaban has any idea on how to remove it?

Here's the binlog if anyone wants to take a look.

[AssetSvgFile.zip](https://github.com/unoplatform/uno/files/14656434/AssetSvgFile.zip)

**Comment by nickrandolph** [comment] 2024-03-21 05:04
> After some investigation that behavior (pack the svg on final app) only happens if the `svg` used by `UnoImage` are inside the `Assets` folder otherwise just the generated images are packaged on final app. It sets the `svg` file to `AndroidAsset`, which isn't done by `Resizetizer`.
> 
> The workaround that I found is to not add `UnoImages` inside `Assets` folder or subfolders, couldn't find a way to remove it during the build yet, maybe @jeromelaban has any idea on how to remove it?
> 
> Here's the binlog if anyone wants to take a look.
> 
> [AssetSvgFile.zip](https://github.com/unoplatform/uno/files/14656434/AssetSvgFile.zip)

This would be a result of the template (probably in csproj of the application) including the svg as Content, as well as being included as UnoImage. This image shows the back.svg being included as both Content and UnoImage

![image](https://github.com/unoplatform/uno/assets/1614057/5b6207cb-9f96-4c1a-acca-8fa794e962c7)


@pedrojesus-work when you're attaching bin log, please don't use binlog generated by the Build Logging window in VS, as this is missing half the useful information required to diagnose most issues. In the following image there should be a Find in Files tab, which is useful for diagnosing the root cause of build related issues but is missing from the binlog generated by the Build Logging window
![image](https://github.com/unoplatform/uno/assets/1614057/8f517cf0-9f1d-4bf1-b520-db59e5bc7393)

**Comment by jeromelaban** [comment] 2024-03-21 15:32
Resizetizer should clean the `Content` item group automatically if the SVGs should not be included in the final layout, as they've been added to UnoImages.

**Comment by agneszitte** [comment] 2024-04-12 14:40
@jeromelaban, @pedrojesus-work (cc @MartinZikmund / @nickrandolph )
Can I have a little bit of a status for this issue, please
Fixes done in Resizetizers? If so, was it properly QA with latest packages?

**Comment by jeromelaban** [comment] 2024-04-12 14:49
@pedrojesus-work will know.

**Comment by pedrojesus-work** [comment] 2024-04-12 17:24
I thought I closed this issue already... As I mentioned [here](https://github.com/unoplatform/uno.resizetizer/issues/218) the work and progress will be on Resizetizer project.

> If so, was it properly QA with latest packages?
@agneszitte  The latest package (dev) should be good to test it

**Closed by pedrojesus-work** 2024-04-12 17:24 UTC
Labels: kind/bug, difficulty/medium 🤔, area/svg

**Comment by agneszitte** [comment] 2024-04-12 21:30
Thank @pedrojesus-work for the update, appreciated!
Next time don't hesitate to ask us to move the issues to others' repos, best to do that when we can to avoid creating additional issues ;) 
I will give it a try with latest dev packages and let you know

**Comment by Darsh0307** [comment] 2024-04-15 14:19
<img width="728" alt="Screenshot 2024-04-15 at 10 17 08 AM" src="https://github.com/unoplatform/uno/assets/90713481/5209c648-e82a-43b0-b39b-2112857e232b">

**Comment by MartinZikmund** [comment] 2024-04-18 08:49
the linked PR will be breaking, so it has to wait for a major release, But it is not crucial one right now anyway.

**Comment by Darsh0307** [comment] 2024-05-02 16:08
SVG working completely fine for all the platforms,

**Comment by Darsh0307** [comment] 2024-05-03 15:07
Its not working for Windows Unpackaged And packaged.  
https://github.com/unoplatform/uno/issues/16571


I used Blank template using wizard. 
"Uno.Sdk": "5.2.108"
Uno templates:- 5.2.31
Uno VSIX :- 5.2.46.54



I tested on following platforms:
Windows - Packaged [(Colour Issue)](https://github.com/unoplatform/uno/issues/16571)
Windows - Unpackaged  [(Colour Issue)](https://github.com/unoplatform/uno/issues/16571)
Android
iOS
MacCatalyst
WebAssembly (Chrome / Edge / Safari )
WebAssembly - IIS Express (Chrome / Edge / Safari )
Desktop (WSL)
Desktop (WSL2)
