### ISSUE TITLE
[Gallery][All Platform]Combobox- Fluent and cupertino - Down Arrow Icon on combo box is missing. 

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#13755] opened 2023-09-22 03:29 UTC
### Current behavior

![combobox issue](https://github.com/unoplatform/uno/assets/74563602/fce59574-cd4c-42cc-9290-cab64121a8dc)

### Expected behavior

![combobox correct](https://github.com/unoplatform/uno/assets/74563602/1ed7635b-1067-40ec-872c-1809f3faf082)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "Combobox" from the "Component" list.
4. Go to 'Fluent' or 'Cupertino' section
5. Notice that in the box for Combobox  down arrow Icon is missing.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Android, iOS, Skia (GTK on Linux/macOS/Windows)

**Comment by Youssef1313** [comment] 2023-09-22 12:13
The problem here is that the glyph color is set to transparent. Probably some problem with resources resolution? I haven't looked further.

**Comment by jeromelaban** [comment] 2024-06-12 15:01
Duplicate of https://github.com/unoplatform/uno/issues/15399

**Closed by jeromelaban** 2024-06-12 15:01 UTC
Labels: kind/bug, project/styling 👔, platform/all, area/canary 🐤, difficulty/medium 🤔
