### ISSUE TITLE
Error CS0006 BugTracker.dll not found in BugTracker, on all platforms, at the end of the tutorial

### ISSUE THREAD

**Issue by silviuo** [unoplatform/uno#12408] opened 2023-05-24 14:25 UTC
## On which page?
[Create a Single Page App with Uno Platform](https://platform.uno/docs/articles/getting-started-tutorial-2.html)

## What's wrong?
After implementing the changes in the tutorial the following error occurs on all platforms:
`error CS0006: Metadata file '...\BugTracker\obj\Debug\<platform specific net7.0 folder>\BugTracker.dll' could not be found`

The error does not occur in the state at the end of the Getting Started section, but only after the changes described in Setting up our Model and Setting up our Page sections.

#Notes:
-  on step 6 of Getting Started, I bumped Uno.Wasm.Bootstrap and Uno.Wasm.Bootstrap.DevServer from 7.0.19 to 7.0.24 (Uno.WinUI was already on the latest version; Uno.UI.WebAssembly was not installed), and I installed latest Refractored.MvvmHelpers 1.6.2 in the BugTracker project
- on step 9 of Setting up our Page, I used Microsoft.UI for Colors, not Windows.UI.

## Any feedback?
I also tested the already [completed tutorial code]() and these were the results:
- Android - ok
- iOS - ok after adding `--registrar:static` to mtouch args for iOS sim
- Skia - ok
- WASM - ok
- UWP - ok after updating the minumum target version to Win 10 build 17763 - initial error was `%userprofile%\.nuget\packages\microsoft.ui.xaml\2.8.1\buildTransitive\Common.targets(10,5): error : Microsoft.UI.Xaml nuget package requires TargetPlatformMinVersion >= 10.0.17763.0 (current project is 16299)`

Attached is the BugTracker solution in its final state at the end of the tutorial.

[BugTracker.zip](https://github.com/unoplatform/uno/files/11555498/BugTracker.zip)

**Comment by Robert-Louis** [comment] 2023-06-07 15:45
Following the tutorial I was not able to reproduced the isssue. But I found the root of the problem. 

The issue was cause by the the non-nullable declared as a error is nothing was assigned to them. It was because in the Directory.Build.props filled the property TreatWarningsAsErrors was set to true.  

That prevent the projects to build so the dll was not produced. 

In the current template the non nullable are only flag with warning. 

In the join project you can make the project build by disabling the TreatWarningsAsErrors.

**Closed** 2023-06-07 18:38 UTC
Labels: triage/untriaged, difficulty/tbd, kind/documentation

**Comment by agneszitte** [comment] 2023-06-08 14:29
@jeromelaban should the completed tutorial code here should be updated with the latest template and packages at some point?
https://github.com/unoplatform/Uno.GettingStartedTutorial/tree/master/src/Getting-Started-Tutorial-2/BugTracker

**Comment by jeromelaban** [comment] 2023-06-08 14:50
Yes, it's reguarly updated, but we should have that in our checklist.
