### ISSUE TITLE
Microsoft.UI.Xaml.Controls.NavigationView not displaying NavigationViewItems on non UWP platforms

### ISSUE THREAD

**Issue by s-beltz** [unoplatform/uno#5325] opened 2021-02-26 11:25 UTC
## Current behavior

Microsoft.UI.Xaml.Controls.NavigationView does not display NavigationViewItems on non UWP platforms.

UWP works as expected:
![image](https://user-images.githubusercontent.com/57802605/109292569-dad0ab00-782a-11eb-9b0f-3e3ffe2df4a2.png)

NavigationView on Android
![image](https://user-images.githubusercontent.com/57802605/109292512-c2f92700-782a-11eb-9681-f90e67e1299f.png)

NavigationView on WASM
![image](https://user-images.githubusercontent.com/57802605/109292741-21bea080-782b-11eb-9974-0b3cba05e159.png)

## Expected behavior

NavigationViewItems are shown also on non UWP platforms.

## How to reproduce it (as minimally and precisely as possible)

Start attached repro app: 
[UnoNavigationViewRepro_2021-02-26.zip](https://github.com/unoplatform/uno/files/6049215/UnoNavigationViewRepro_2021-02-26.zip)

## Workaround

We could not find a workaround. 

- Placing NavigationViewItems statically inside NavigationView without using NavigationView.MenuItemsSource did not work. 
- Setting MenuItemsSource and MenuItemTemplate in code behind did not work.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Uno.UI 3.5.1
Microsoft.UI.Xaml 3.5.0

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: ) 16.8.6
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Zof-R** [comment] 2021-02-26 14:08
Looks the same as #5267

**Comment by jeromelaban** [comment] 2021-03-01 22:14
Closing as a duplicate of https://github.com/unoplatform/uno/issues/5265

**Closed by jeromelaban** 2021-03-01 22:14 UTC
Labels: difficulty/tbd, kind/bug, triage/untriaged
