### ISSUE TITLE
ScrollViewer.ViewChanging doesn't fire on android

### ISSUE THREAD

**Issue by Henk7** [unoplatform/uno#78] opened 2018-06-29 18:24 UTC
<ScrollViewer VerticalScrollMode="Enabled" HorizontalScrollMode="Enabled"
        ViewChanged="ScrollViewer_ViewChanged" ViewChanging="ScrollViewer_ViewChanging">
        <Border Height="1000" Width="1000" Background="Red"/>
    </ScrollViewer>

The ScrollViewer_ViewChanged fires, the ScrollViewer_ViewChanging doesn't. 
Tried with 1.31.0-dev.91
[Repo inside](https://github.com/Henk7/Uno.QuickStart/commits/scrollviewer)

**Comment by jeromelaban** [comment] 2018-06-29 18:32
@Dissolute sounds familiar ?

**Comment by Dissolute** [comment] 2018-06-30 09:59
Yes, we haven't implemented it yet (for any platform).

@Henk7 Out of curiosity do you have a use case that requires ViewChanging?

**Comment by MartinZikmund** [comment] 2022-10-24 08:08
Duplicate of #6746

**Closed** 2022-10-24 08:08 UTC
Labels: kind/enhancement, platform/android, project/input, difficulty/challenging
