### ISSUE TITLE
[Gallery][Android/iOS]<ListView> In "SelectedItem" section the word "Foreground color" is missing.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5176] opened 2021-02-07 06:37 UTC
## Current behavior
![listview issue](https://user-images.githubusercontent.com/74563602/107138726-06bfd700-68e4-11eb-9906-a10932952e39.png)
## Expected behavior
![listview correct](https://user-images.githubusercontent.com/74563602/107138781-6322f680-68e4-11eb-90a6-d949542d2058.png)

## How to reproduce it

1. Open Uno Gallery APP for canary.
2. Click "ListView" option from Burger Menu.
3. Check "SelectedItem section.
4. Observe the "Foreground color" text is missing.

Version(s):
Version 1.4.3 (642) for iOS
Version 1.4.3 (400640) for Android

Device:
iphone 12 - 14.1
Samsung S8 - 8.0
Motorola g(7) – 9

Affected platform(s):
iOS
Android

**Comment by davidjohnoliver** [comment] 2021-02-08 20:27
Same issue as https://github.com/unoplatform/uno/issues/4686

**Comment by MartinZikmund** [comment] 2021-06-03 08:30
Duplicate of #4686

**Closed by MartinZikmund** 2021-06-03 08:30 UTC
Labels: area/canary, difficulty/tbd, kind/regression, platform/android, platform/ios, project/items
