### ISSUE TITLE
[WASM] TextBox binding does not work on mobile browsers (WebKit, Chrome)

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#6338] opened 2021-06-23 20:42 UTC
## Current behavior

The binding property value never gets set.

## Expected behavior

The binding property value should get set.

## How to reproduce it (as minimally and precisely as possible)

Add some text boxes with bindings (`x:Bind` or `Binding` - both do the same thing). Move between text boxes by tapping and entering values and notice that the bindings aren't updated.

You can see this behavior with Chrome on the desktop: load https://app.iratio.ca/test, then enter a first and last name. Click the "Sign Up" button and notice no errors are produced for the first and last name field.

Now press F12, select the `iPhoneX` device, refresh the page and repeat the same process, only "tapping" between fields (no tabbing with the keyboard - mouse is fine though to simulate taps). Notice that none of the text box fields get set and the error reported shows that none of the fields have been filled in.

The test project source is available here: https://github.com/mikernet/UnoTest

## Workaround

Set `UpdateSourceTrigger=PropertyChanged` on the binding.

## Environment

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): v3.7.7, v3.8.6, v3.9.0-dev.93

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment] 2021-06-23 20:54
Thanks for the report. 

It's easier to troubleshoot if you extract the issue in a standalone application. Are you able to do this ?

**Comment by mikernet** [comment] 2021-06-24 12:08
Updates the original post with a test app link and source code. I guess it had nothing to do with the pivot.

**Comment by mikernet** [comment] 2021-06-28 21:51
It appears this is related to the textbox not losing focus properly during touch events, since the textbox bindings work when they have `UpdateSourceTrigger=PropertyChanged` set.

**Comment by jeromelaban** [comment] 2021-07-05 15:23
Thanks for the update!

**Comment by MartinZikmund** [comment] 2021-07-06 07:20
Duplicate of #5618, I will copy the details there. Definitely something we need to prioritize soon, as it causes unexpected issues on mobile

**Closed by MartinZikmund** 2021-07-06 07:20 UTC
Labels: difficulty/tbd, kind/bug, platform/wasm, project/pointers
