### ISSUE TITLE
Image Source to null leads to an undefined behaviour

### ISSUE THREAD

**Issue by jp-weber** [unoplatform/uno#12454] opened 2023-05-29 11:08 UTC
### Current behavior

If there is currently no value for the image source in a ListView or an ItemsRepeater of a DataTemplate, or if it is deleted, this leads to an exception being thrown and often an image from the cache is used as the image source.

For example the purple items have an image source of null (red=> pride flag, green => uno logo):
<img src="https://github.com/unoplatform/uno/assets/10946850/d9eac779-0fe1-455a-8438-3a8a32ee5b68" alt="Screenshot_20230528-193005" width="470" />

The problem also existed at MAUI and was solved recently:
https://github.com/dotnet/maui/issues/8787
https://github.com/dotnet/maui/pull/13614

```
[DOTNET] [41m[30mfail[39m[22m[49m: Microsoft.UI.Xaml.Data.BindingExpression[0]
[DOTNET]       Failed to apply binding to property [DependencyPropertyDetails(UriSource)] on [Microsoft.UI.Xaml.Media.Imaging.SvgImageSource] (Object reference not set to an instance of an object.)
[DOTNET]       System.NullReferenceException: Object reference not set to an instance of an object.
[DOTNET]          at Microsoft.UI.Xaml.Media.ImageSource.InitFromUri(Uri uri) in C:\a\1\s\src\Uno.UI\UI\Xaml\Media\ImageSource.cs:line 116
[DOTNET]          at Microsoft.UI.Xaml.Media.Imaging.SvgImageSource.OnUriSourceChanged(DependencyPropertyChangedEventArgs e) in C:\a\1\s\src\Uno.UI\UI\Xaml\Media\Imaging\SvgImageSource.cs:line 59
[DOTNET]          at Microsoft.UI.Xaml.Media.Imaging.SvgImageSource.<>c.<.cctor>b__63_0(DependencyObject s, DependencyPropertyChangedEventArgs e) in C:\a\1\s\src\Uno.UI\UI\Xaml\Media\Imaging\SvgImageSource.Properties.cs:line 26
[DOTNET]          at Microsoft.UI.Xaml.PropertyMetadata.RaisePropertyChanged(DependencyObject source, DependencyPropertyChangedEventArgs e) in C:\a\1\s\src\Uno.UI\UI\Xaml\PropertyMetadata.cs:line 187
[DOTNET]          at Microsoft.UI.Xaml.DependencyObjectStore.InvokeCallbacks(DependencyObject actualInstanceAlias, DependencyProperty property, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence, Boolean bypassesPropagation) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 1894
[DOTNET]          at Microsoft.UI.Xaml.DependencyObjectStore.RaiseCallbacks(DependencyObject actualInstanceAlias, DependencyPropertyDetails propertyDetails, Object previousValue, DependencyPropertyValuePrecedences previousPrecedence, Object newValue, DependencyPropertyValuePrecedences newPrecedence) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 1800
[DOTNET]          at Microsoft.UI.Xaml.DependencyObjectStore.InnerSetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 507
[DOTNET]          at Microsoft.UI.Xaml.DependencyObjectStore.SetValue(DependencyProperty property, Object value, DependencyPropertyValuePrecedences precedence, DependencyPropertyDetails propertyDetails, Boolean isPersistentResourceBinding) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:line 437
[DOTNET]          at Microsoft.UI.Xaml.DependencyObjectExtensions.SetValue(Object instance, DependencyProperty property, Object value, Nullable`1 precedence) in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectExtensions.cs:line 326
[DOTNET]          at Uno.UI.DataBinding.BindingPropertyHelper.<>c__DisplayClass43_9.<InternalGetValueSetter>b__13(Object instance, Object value) in C:\a\1\s\src\Uno.UI\DataBinding\BindingPropertyHelper.cs:line 974
[DOTNET]          at Microsoft.UI.Xaml.Data.BindingExpression.SetTargetValue(Object value) in C:\a\1\s\src\Uno.UI\DataBinding\BindingExpression.cs:line 427
[DOTNET]          at Microsoft.UI.Xaml.Data.BindingExpression.<SetTargetValueSafe>g__SetTargetValueSafeWithTry|54_1(Object v, Boolean useTargetNullValue) in C:\a\1\s\src\Uno.UI\DataBinding\BindingExpression.cs:line 645
```

### Expected behavior

As with the UWP, zeroing the image source should not cause any problems.

### How to reproduce it (as minimally and precisely as possible)

If desired, i can gladly create an example project

### Workaround

As a workaround, the visibility of the control element can be deactivated, or a placeholder can be inserted.

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.8.39

### Affected platforms

Android, iOS

### IDE

Visual Studio 2022

### IDE version

17.6.2

### Anything else we need to know?

The problem also existed at MAUI and was solved recently:
https://github.com/dotnet/maui/issues/8787
https://github.com/dotnet/maui/pull/13614

**Comment by jeromelaban** [comment] 2023-05-29 12:48
Thanks for the report. This is indeed an issue for SvgImageSource. Note that this is unrelated to MAUI in any way.

## Note for contributors

SvgImageSource should be validating for null:
https://github.com/unoplatform/uno/blob/69356ccb8f8004d178209728c6169c6d463cff69/src/Uno.UI/UI/Xaml/Media/Imaging/SvgImageSource.cs#L59

And InitFromUri should also handle it properly:
https://github.com/unoplatform/uno/blob/69356ccb8f8004d178209728c6169c6d463cff69/src/Uno.UI/UI/Xaml/Media/ImageSource.cs#L114

**Comment by ajpinedam** [comment] 2023-06-07 01:42
Hi @jp-weber  I am working on this issue and even though we seem to know where the problem is, we are having difficulties reproducing it.


I have this page

```xaml
<ListView ItemsSource="{Binding [Items]}">
	<ListView.Header>
		<TextBlock Text="ListView with SVG ImageSource" />
	</ListView.Header>
	<ListView.ItemTemplate>
		<DataTemplate>
			<Grid ColumnSpacing="12">
				<Grid.RowDefinitions>
					<RowDefinition Height="Auto" />
					<RowDefinition Height="Auto" />
				</Grid.RowDefinitions>
				<Grid.ColumnDefinitions>
					<ColumnDefinition Width="90"/>
					<ColumnDefinition Width="*" />
				</Grid.ColumnDefinitions>

				<Image Source="{Binding ImageUrl}"
						VerticalAlignment="Center"
						Grid.RowSpan="2" />

				<TextBlock Text="{Binding Title}"
							Grid.Column="1"
							FontSize="18"/>

				<TextBlock Text="{Binding Subtitle}"
							Grid.Column="1"
							Grid.Row="1"
							Foreground="#5A5A5A"
							FontSize="12"/>
			</Grid>
		</DataTemplate>
	</ListView.ItemTemplate>
</ListView>
```

And this ViewModel, where we are intentionally setting the image to null for some of the items

```csharp
internal class ImageViewViewModel : ViewModelBase
{
	public IEnumerable<Item> Items { get; private set; }

	public ImageViewViewModel(CoreDispatcher dispatcher) : base(dispatcher)
	{
		Items = new List<Item>()
		{
			new() { Title = "Item 1", Subtitle = "Subtitle 1", ImageUrl = "ms-appx:///Assets/Formats/couch.svg" },
			new() { Title = "Item 2", Subtitle = "Subtitle 2", ImageUrl = "ms-appx:///Assets/Formats/home.svg" },
			new() { Title = "Item 3", Subtitle = "Subtitle 3", ImageUrl = "ms-appx:///Assets/Formats/couch.svg" },
			new() { Title = "Item 4", Subtitle = "Subtitle 4", ImageUrl = "ms-appx:///Assets/Formats/home.svg" },
			new() { Title = "Item 5", Subtitle = "Subtitle 5", ImageUrl = "ms-appx:///Assets/Formats/couch.svg" },
			new() { Title = "Item 6", Subtitle = "Subtitle 6", ImageUrl = null },
			new() { Title = "Item 7", Subtitle = "Subtitle 7", ImageUrl = "ms-appx:///Assets/Formats/couch.svg" },
			new() { Title = "Item 8", Subtitle = "Subtitle 8", ImageUrl = "ms-appx:///Assets/Formats/home.svg" },
			new() { Title = "Item 9", Subtitle = "Subtitle 9", ImageUrl = "ms-appx:///Assets/Formats/couch.svg" },
			new() { Title = "Item 10", Subtitle = "Subtitle 10", ImageUrl = "ms-appx:///Assets/Formats/home.svg" },
			new() { Title = "Item 11", Subtitle = "Subtitle 11", ImageUrl = "ms-appx:///Assets/Formats/couch.svg" },
			new() { Title = "Item 12", Subtitle = "Subtitle 12", ImageUrl = "ms-appx:///Assets/Formats/home.svg" },
			new() { Title = "Item 13", Subtitle = "Subtitle 13", ImageUrl = null },
			new() { Title = "Item 14", Subtitle = "Subtitle 14", ImageUrl = "ms-appx:///Assets/Formats/home.svg" },
			new() { Title = "Item 15", Subtitle = "Subtitle 15", ImageUrl = "ms-appx:///Assets/Formats/couch.svg" },
			new() { Title = "Item 16", Subtitle = "Subtitle 16", ImageUrl = "ms-appx:///Assets/Formats/home.svg" },
			new() { Title = "Item 17", Subtitle = "Subtitle 17", ImageUrl = "ms-appx:///Assets/Formats/couch.svg" },
			new() { Title = "Item 18", Subtitle = "Subtitle 18", ImageUrl = "ms-appx:///Assets/Formats/home.svg" },
			new() { Title = "Item 19", Subtitle = "Subtitle 19", ImageUrl = "ms-appx:///Assets/Formats/couch.svg" },
			new() { Title = "Item 20", Subtitle = "Subtitle 20", ImageUrl = null },
			new() { Title = "Item 21", Subtitle = "Subtitle 21", ImageUrl = "ms-appx:///Assets/Formats/couch.svg" },
			new() { Title = "Item 22", Subtitle = "Subtitle 22", ImageUrl = "ms-appx:///Assets/Formats/home.svg" },

		};
	}
}
```

But as you can see below, those items with Null ImageUrl are just empty. 

What am I missing here? Thanks

![image](https://github.com/unoplatform/uno/assets/1900897/bb8aaa5c-4dc1-455a-907c-b30e0b8c6f04)

**Comment by jp-weber** [comment] 2023-06-07 17:17
Hello @ajpinedam I have now uploaded my test application, where I can reproduce the error and after scrolling it becomes visible when an item (purple) suddenly gets an image or another image again.:
https://github.com/jp-weber/UnoAppSVGSourceNull/tree/master

The differences I see are that I use x:Bind, a SvgImageSource directly in the Image.Source and accordingly a Uri in the model.
```xaml
                        <Image.Source>
                            <SvgImageSource 
                                  UriSource="{x:Bind AccountSVGIcon, Mode=OneWay}" 
                                  RasterizePixelHeight="60" 
                                  RasterizePixelWidth="60" />
                        </Image.Source>
```

![bug](https://github.com/unoplatform/uno/assets/10946850/8f2841fb-4b72-4379-bda3-af6051b1ceb1)

**Comment by ajpinedam** [comment] 2023-06-08 18:14
Thanks @jp-weber .

FYI: I have updated the PR, and once merged, the fix will be available for you.

**Closed** 2023-06-14 13:35 UTC
Labels: kind/bug, triage/untriaged, project/media, difficulty/tbd
