### ISSUE TITLE
Binding of FontSize in a style does not work for iOS

### ISSUE THREAD

**Issue by zipswich** [unoplatform/uno#3655] opened 2020-07-29 03:21 UTC
## Current behavior

iOS head build fails with errors:
1>  E:\UNO\AppDebugUno\AppDebugUno\AppDebugUno.iOS\obj\iPhoneSimulator\Debug\g\XamlCodeGenerator\MainPage_4a5e751e5ab70fb750d0b3a433e70c70.g.cs(83,118,83,118): error CS1525: Invalid expression term ')'
1>  E:\UNO\AppDebugUno\AppDebugUno\AppDebugUno.iOS\obj\iPhoneSimulator\Debug\g\XamlCodeGenerator\MainPage_4a5e751e5ab70fb750d0b3a433e70c70.g.cs(84,9,84,14): error CS1024: Preprocessor directive expected
1>  E:\UNO\AppDebugUno\AppDebugUno\AppDebugUno.iOS\obj\iPhoneSimulator\Debug\g\XamlCodeGenerator\MainPage_4a5e751e5ab70fb750d0b3a433e70c70.g.cs(149,116,149,116): error CS1525: Invalid expression term ')'
1>  E:\UNO\AppDebugUno\AppDebugUno\AppDebugUno.iOS\obj\iPhoneSimulator\Debug\g\XamlCodeGenerator\MainPage_4a5e751e5ab70fb750d0b3a433e70c70.g.cs(150,7,150,12): error CS1024: Preprocessor directive expected

## Expected behavior

iOS head should build.

## How to reproduce it (as minimally and precisely as possible)

    
Xaml:
```
<Grid 
        x:Name="gridRoot" 
        VerticalAlignment="Top"
        Background="{ThemeResource ApplicationPageBackgroundThemeBrush}" 
          >
        <Grid.Resources>
            <Style TargetType="TextBlock" x:Name="textBlock">
                <!--iOS does not this-->
                <Setter Property="FontSize" Value="{Binding dTileFontSize}"/>
            </Style>
        </Grid.Resources>
        <TextBlock
            Margin="25"
            Text="Test"
            />
    </Grid>
```
C#:

```
        public double dTileFontSize
        {
            get
            {
                return 72;
            }
        }
```

## Environment

Nuget Package: Uno.UI

Package Version(s): 3.0.0-dev.1117

Affected platform(s): iOS

- [ x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Youssef1313** [comment] 2021-10-04 21:04
This isn't much related to iOS or FontSize specifically.

The fix is most likely to support "Binding" in this code path:

https://github.com/unoplatform/uno/blob/3b086ffd2c105a50816adee60af6cf1b40e88b37/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs#L4711

**Comment by Youssef1313** [comment] 2022-09-01 16:12
Looks like a duplicate of https://github.com/unoplatform/uno/issues/4826 ?

**Closed** 2022-09-01 17:17 UTC
Labels: kind/bug, area/code-generation, project/styling, project/binding, difficulty/medium
