### ISSUE TITLE
[Gallery][Catalyst] All the controls of 'Theme', 'Components', 'Features', 'Toolkit' the screen layout is not fully visible.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8689] opened 2022-05-04 18:10 UTC
### Current behavior

![Material](https://user-images.githubusercontent.com/74563602/166747472-b836e284-5ca3-44a1-8f2c-eb2d1c04b9ad.png)
![Cupertino](https://user-images.githubusercontent.com/74563602/166747505-55f8648a-fb7d-4fd4-a898-f200f8ea0f43.png)
![Fluent](https://user-images.githubusercontent.com/74563602/166747518-9e441969-4dde-42e0-a260-79903bce3873.png)
![Typography](https://user-images.githubusercontent.com/74563602/166747546-a36190a1-54c2-4096-8829-65f59bf62537.png)
![Commandbar ](https://user-images.githubusercontent.com/74563602/166747564-624c69c5-36ae-4218-a112-afadef919d14.png)
![Person picture](https://user-images.githubusercontent.com/74563602/166747589-487d9532-4f6b-4160-843b-1f4a5ce17c91.png)

### Expected behavior

![Material correct](https://user-images.githubusercontent.com/74563602/166749057-c09da263-68e8-42d7-b216-82c66c0a73b6.png)
![Cupertino Correct ](https://user-images.githubusercontent.com/74563602/166749091-f0e1fe07-f436-4617-9372-86a7e534169c.png)
![Fluent correct](https://user-images.githubusercontent.com/74563602/166749106-6956445f-938b-4d7d-8f70-1abdc8dd7ca4.png)
![Typography correct](https://user-images.githubusercontent.com/74563602/166749431-dc8653fc-4843-4cd3-b676-e35a05133221.png)
![Commandbar correct](https://user-images.githubusercontent.com/74563602/166749460-46b4c8f1-dae7-4642-96ac-eb87ed96ba44.png)
![Person picture correct](https://user-images.githubusercontent.com/74563602/166749489-860c4f6f-d722-4b83-889f-9b475e4c5952.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap any control option from the "Theme", "Component", "Features", "Toolkit" list.
4. Observe that the screen layout is not fully visible. (display as the screen is stretched on the right side).

### Anything else we need to know?

Affected Platform - Mac Catalyst

**Comment by jeromelaban** [comment] 2022-05-05 12:08
This issue is a duplicate of https://github.com/unoplatform/uno/issues/8687

**Closed by jeromelaban** 2022-05-05 12:08 UTC
Labels: kind/bug, platform/macos, triage/untriaged, difficulty/tbd
