### ISSUE TITLE
Binding issue with Nested ItemsControl / InvalidOperationException: The color ControlStrokeColorOnAccentSecondaryBrush is unknown

### ISSUE THREAD

**Issue by hawkerm** [unoplatform/uno#8077] opened 2022-02-12 23:14 UTC
### Current behavior

Was able to recreate a minimal reproduction of the issue I was seeing with my project where binding is working in a UserControl that's loaded on the main page of the app at the start, but not when it is loaded after as part of another list.

I did notice there is an error outputted in the console, but it seems completely unrelated to anything within the app code. However, it may be a starting point.

The code works as expected on UWP, and I was able to reproduce on my machine with the WPF and WASM heads.

The basic setup involves a custom user control which contains an ItemsControl and a binding with a converter. It works when the control is used directly, but doesn't work when the control is used within another ItemsControl with dynamically added items from the application.

Attached is the minimal reproduction project, see repro steps for details:

[UnoTestApp.ItemsControlBinding.zip](https://github.com/unoplatform/uno/files/8054683/UnoTestApp.ItemsControlBinding.zip)

### Expected behavior

Would expect the bindings to update and work in both scenarios across all project heads.

### How to reproduce it (as minimally and precisely as possible)

1. Download the reproduction project
2. Run UWP head, you should see 11 at the top and two buttons:
![image](https://user-images.githubusercontent.com/8959496/153731632-31e3fefc-b426-4a36-9931-4bdab0ffb0b4.png)
3. Clicking 'Is Top' button will change the alignment of the numbers:
![image](https://user-images.githubusercontent.com/8959496/153731648-4752aace-69f5-4b96-a813-772391864570.png)
4. Clicking 'Add Thing' will create a new data item which will use the same control and bindings to show the numbers '1 2 3':
![image](https://user-images.githubusercontent.com/8959496/153731659-6f20222f-6126-4946-a54f-b5201fe03892.png)
5. Re-clicking 'Is Top' will swap the alignment for both sets of numbers:
![image](https://user-images.githubusercontent.com/8959496/153731674-a94deb1b-bcf2-4684-af9f-94883777b691.png)
6. Now run the WPF or WASM heads and perform the same steps, you'll see that the '1 2 3' numbers don't respect the binding and remain stationary when the toggle button is pressed. The interesting thing is that the '1 1' binding still works fine in all cases which is using the same control/setup effectively.

For instance here in the WPF head the '1 2 3' should be next to the 'Is Top' button just like the screenshot above:

![image](https://user-images.githubusercontent.com/8959496/153731698-9bf3c7d5-b415-4ba5-b43e-4ced44ba575c.png)

### Workaround

None known.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.0.11 and 4.2.0-dev.43

### Affected platforms

WebAssembly, Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.0.5

### Anything else we need to know?

Was masked/found while working with other issues #4502 and #6700.

The console is outputting this info at the start:

```
warn: Uno.UI.ResourceResolver[0]
      Couldn't statically resolve resource DefaultRepeatButtonStyle
fail: Windows.UI.Xaml.BrushTransition[0]
      The member BrushTransition.BrushTransition() is not implemented in Uno.
fail: Windows.UI.Xaml.BrushTransition[0]
      The member TimeSpan BrushTransition.Duration is not implemented in Uno.
fail: Windows.UI.Xaml.Controls.ContentPresenter[0]
      The member BrushTransition ContentPresenter.BackgroundTransition is not implemented in Uno.
fail: Windows.UI.Composition.CompositionObject[0]
      The member void CompositionObject.Dispose() is not implemented in Uno.
```

And this stack when the toggle button is pressed/binding fails:
```
fail: Uno.UI.DataBinding.BindingPath+BindingItem[0]
      Failed to set the source value for [BorderBrush]
      System.InvalidOperationException: The color ControlStrokeColorOnAccentSecondaryBrush is unknown
         at Windows.UI.Colors.Parse(String colorCode) in C:\a\1\s\src\Uno.UWP\UI\Colors.cs:line 62
         at Windows.UI.Xaml.SolidColorBrushHelper.Parse(String colorCode) in C:\a\1\s\src\Uno.UI\UI\Xaml\SolidColorBrushHelper.cs:line 65
         at Uno.UI.DataBinding.BindingPropertyHelper.FastStringToBrushConvert(Type outputType, String input, Object& output) in C:\a\1\s\src\Uno.UI\DataBinding\BindingPropertyHelper.FastConvert.cs:line 557
         at Uno.UI.DataBinding.BindingPropertyHelper.FastStringConvert(Type outputType, String input, Object& output) in C:\a\1\s\src\Uno.UI\DataBinding\BindingPropertyHelper.FastConvert.cs:line 213
         at Uno.UI.DataBinding.BindingPropertyHelper.FastConvert(Type outputType, Object input, Object& output) in C:\a\1\s\src\Uno.UI\DataBinding\BindingPropertyHelper.FastConvert.cs:line 56
         at Uno.UI.DataBinding.BindingPropertyHelper.Convert(Func`1 propertyType, Object value) in C:\a\1\s\src\Uno.UI\DataBinding\BindingPropertyHelper.cs:line 1075
         at Uno.UI.DataBinding.BindingPropertyHelper.<>c__DisplayClass40_9.<InternalGetValueSetter>b__13(Object instance, Object value) in C:\a\1\s\src\Uno.UI\DataBinding\BindingPropertyHelper.cs:line 858
         at Uno.UI.DataBinding.BindingPath.BindingItem.SetSourceValue(ValueSetterHandler setter, Object value) in C:\a\1\s\src\Uno.UI\DataBinding\BindingPath.cs:line 718
```

Or this slightly different one sometimes:

```
fail: Uno.UI.DataBinding.BindingPath+BindingItem[0]
      Failed to set the source value for [BorderBrush]
      System.InvalidOperationException: The color ControlStrokeColorOnAccentSecondaryBrush is unknown
         at Windows.UI.Colors.Parse(String colorCode) in C:\a\1\s\src\Uno.UWP\UI\Colors.cs:line 62
         at Windows.UI.Xaml.SolidColorBrushHelper.Parse(String colorCode) in C:\a\1\s\src\Uno.UI\UI\Xaml\SolidColorBrushHelper.cs:line 65
         at Uno.UI.DataBinding.BindingPropertyHelper.FastStringToBrushConvert(Type outputType, String input, Object& output) in C:\a\1\s\src\Uno.UI\DataBinding\BindingPropertyHelper.FastConvert.cs:line 557
         at Uno.UI.DataBinding.BindingPropertyHelper.FastStringConvert(Type outputType, String input, Object& output) in C:\a\1\s\src\Uno.UI\DataBinding\BindingPropertyHelper.FastConvert.cs:line 213
         at Uno.UI.DataBinding.BindingPropertyHelper.FastConvert(Type outputType, Object input, Object& output) in C:\a\1\s\src\Uno.UI\DataBinding\BindingPropertyHelper.FastConvert.cs:line 77
         at Uno.UI.DataBinding.BindingPropertyHelper.Convert(Func`1 propertyType, Object value) in C:\a\1\s\src\Uno.UI\DataBinding\BindingPropertyHelper.cs:line 1085
         at Uno.UI.DataBinding.BindingPropertyHelper.<>c__DisplayClass40_9.<InternalGetValueSetter>b__13(Object instance, Object value) in C:\a\1\s\src\Uno.UI\DataBinding\BindingPropertyHelper.cs:line 858
         at Uno.UI.DataBinding.BindingPath.BindingItem.SetSourceValue(ValueSetterHandler setter, Object value) in C:\a\1\s\src\Uno.UI\DataBinding\BindingPath.cs:line 735
```

**Comment by jeromelaban** [comment] 2022-02-15 22:14
## Notes for contributors

After a bit of research, this issue seems to be caused by a DependencyProperty inheritance issue, where the `NameScope` is overriden by some parent scope as the control is used in the context of an ItemsControl. If the ElementName value is not on the UserControl, the binding works properly (e.g. `ThisPage` in the attached sample).

**Comment by jeromelaban** [comment] 2022-02-16 21:59
So, here's a workaround:

Instead of having this:
```xaml
<DataTemplate>
    <local:MyControl Data="{Binding}" IsTop="{Binding IsTop, ElementName=ThisPage}"/>
</DataTemplate>
```

You can wrap the content this way:
```xaml
<DataTemplate>
    <Grid>
        <local:MyControl Data="{Binding}" IsTop="{Binding IsTop, ElementName=ThisPage}"/>
    </Grid>
</DataTemplate>
```

The issue comes from the fast that the root of a `DataTemplate` gets its own namescope set, and it overrides the one already existing as `MyControl` is a XAML file as well.

**Comment by hawkerm** [comment] 2022-02-20 09:47
Thanks @jeromelaban, I can confirm the workaround is working in my full project as well. Once the fix hits the dev bits, I can update and double-check the fix, unless there's a nuget feed for PRs?

**Comment by jeromelaban** [comment] 2022-02-21 19:13
It's possible to use the nuget packages directly from the PRs (in the `NugetPackages/vslatest` artifact). The associated PR should be merged soon, so it'll be easier to validate :)

**Closed** 2022-02-25 01:41 UTC
Labels: kind/bug, project/binding, difficulty/tbd
