### ISSUE TITLE
Uno.ProjectTemplates.Dotnet::3.5.1

### ISSUE THREAD

**Issue by sigmarsson** [unoplatform/uno#5424] opened 2021-03-08 18:51 UTC
1. Updated the project templates to 3.5.1
![image](https://user-images.githubusercontent.com/43340959/110366642-dab08680-8046-11eb-8942-4bdd623794c6.png)

2. Created a Win UI specific project 
![image](https://user-images.githubusercontent.com/43340959/110366763-016ebd00-8047-11eb-9e55-4369c66691b9.png)

3.In the sln file white spaces were replaced with under scores therefore no projects can be loaded in the studio. 
![image](https://user-images.githubusercontent.com/43340959/110367017-6b876200-8047-11eb-939e-94c5854f2e73.png)

![image](https://user-images.githubusercontent.com/43340959/110367109-8bb72100-8047-11eb-9844-7c44dbac3aa3.png)

[Weather History.zip](https://github.com/unoplatform/uno/files/6103511/Weather.History.zip)

**Comment by jeromelaban** [comment] 2021-03-08 20:27
Thanks for the report! The `dotnet new` does not support spaces properly in the names. Use a `.` instead of the space.

Duplicate of https://github.com/unoplatform/uno/issues/806

**Closed by jeromelaban** 2021-03-08 20:27 UTC
Labels: difficulty/tbd, kind/bug, triage/untriaged
