### ISSUE TITLE
Wasm: ContentDialog Closing support

### ISSUE THREAD

**Issue by yowl** [unoplatform/uno#1495] opened 2019-09-06 16:21 UTC
## What would you like to be added:

The Closing event

## Why is this needed:
To get parity with UWP and allow scenarios where the closing should be prevented

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows

## Anything else we need to know?

See https://github.com/yowl/UnoStandardRefTest2/tree/contentdialog-closing for an example

**Comment by ghuntley** [comment] 2019-09-07 01:39
Looks like ContentDialog has implementations for all platforms:

- https://github.com/unoplatform/uno/blob/master/src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/ContentDialog.cs
- https://github.com/unoplatform/uno/blob/master/src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/ContentDialogClosingDeferral.cs
- https://github.com/unoplatform/uno/blob/master/src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/ContentDialogOpenedEventArgs.cs
- https://github.com/unoplatform/uno/blob/master/src/Uno.UI/Generated/3.0.0.0/Windows.UI.Xaml.Controls/ContentDialogClosingEventArgs.cs

Here's the implementation for ClosingEvent:

- https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Controls/ContentDialog/ContentDialogClosingEventArgs.cs

Thanks for providing the reproduction, going to pull it down now.

**Comment by ghuntley** [comment] 2019-09-07 04:39
Confirming that I've been able to reproduce this. Looking closer at the implementations it doesn't look like `Closing` OR `Closed` event is wired up for any platform.

![image](https://user-images.githubusercontent.com/127353/64469845-9526ab00-d17c-11e9-8ed6-6aa677a9698b.png)

Will need to come back to this but the fix should be somewhat straight forward:

```
Closed?.Invoke(this, new ContentDialogClosedEventArgs());
Closing?.Invoke(this, new ContentDialogClosingEventArgs());
+ appropriate tests ;-)
```

**Comment by yowl** [comment] 2019-09-07 14:13
Ok, please note the deferred action available from the closing event.  On phone so don't have the link, but its in the properties for the args .

Sent from my Windows 10 device

**Comment by jeromelaban** [comment] 2019-09-25 19:01
@davidjohnoliver is there some work left on this issue ?

**Comment by davidjohnoliver** [comment] 2019-09-25 19:01
> @davidjohnoliver is there some work left on this issue ?

No, I think we can close it.

**Closed by davidjohnoliver** 2019-09-25 19:01 UTC
Labels: area/android, area/ios, area/wasm, good first issue, kind/enhancement
