### ISSUE TITLE
Project sqllit WebAssembly not working

### ISSUE THREAD

**Issue by AbdalaMask** [unoplatform/uno#7469] opened 2021-11-13 06:39 UTC
### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

**Comment by AbdalaMask** [comment] 2021-11-13 06:40
https://user-images.githubusercontent.com/37013638/141499660-45ad82c1-96e0-41dc-a414-447cb20566b8.png

**Comment by AbdalaMask** [comment] 2021-11-13 06:41
![141499660-45ad82c1-96e0-41dc-a414-447cb20566b8](https://user-images.githubusercontent.com/37013638/141608977-f551ec5f-1042-42cb-b812-4f3967eb881d.png)

**Comment by jeromelaban** [comment] 2021-11-13 19:58
Duplicate of https://github.com/unoplatform/uno/issues/7469

**Closed by jeromelaban** 2021-11-13 19:58 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd

**Comment by AbdalaMask** [comment] 2021-11-14 05:32
How

**Comment by AbdalaMask** [comment] 2021-11-14 05:32
https://user-images.githubusercontent.com/37013638/141499660-45ad82c1-96e0-41dc-a414-447cb20566b8.png
