### ISSUE TITLE
[WASM] `AllowFocusOnInteraction` not working properly

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#5713] opened 2021-04-09 19:50 UTC
## Current behavior

In some cases, a control can improperly lose focus in WASM apps.  This can be an issue trying to interact with controls on a flyout.

## Expected behavior

Focus should behave as in UWP

## How to reproduce it (as minimally and precisely as possible)

Open the attached project in Uwp and notice that different options can be selected from the flyout on the second TextBox.  Open in Wasm and observe that these items are not selectable - the click event for each button fails to execute.

[EventOrder.zip](https://github.com/unoplatform/uno/files/6288127/EventOrder.zip)

## Workaround

Disabling the 'flyout.Hide()' call in the LostFocus event for the relevant TextBox lets button interactions in the flyout operate normally.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
3.7.0-dev.187

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by DierkDroth** [comment] 2021-06-13 14:48
@jeromelaban what would be the timeline for that issue?

**Comment by jeromelaban** [comment] 2021-06-14 11:42
The work for this is in progress, you can follow here #https://github.com/unoplatform/uno/pull/6184

**Comment by DierkDroth** [comment] 2021-06-14 11:43
Good to know. Thanks @jeromelaban

**Comment by DierkDroth** [comment] 2021-07-17 07:56
@jeromelaban I see #6184 is merged. Does this mean issue above should be resolved?

**Comment by MartinZikmund** [comment] 2021-07-17 10:15
@DierkDroth Still need to validate this and other related issues, but I have it on my backlog

**Comment by DierkDroth** [comment] 2021-07-17 10:17
Thanks for the update @MartinZikmund

**Comment by peternary** [comment] 2021-07-21 18:39
Sample issue in attached project: mouse over on either grid will cause a button to appear, and clicking the button will produce a flyout.  If you click to dismiss the flyout in UWP then the button will be hidden; if you click to dismiss the flyout in WASM then the button remains visible until the PointerExit event fires for the grid again.

[ButtonFocus.zip](https://github.com/unoplatform/uno/files/6858101/ButtonFocus.zip)

**Comment by DierkDroth** [comment] 2021-08-20 08:00
@jeromelaban when could we expect this being resolved? Thx

**Comment by MartinZikmund** [comment] 2021-08-24 15:32
@peternary @DierkDroth It seems there are two different issues in this one - which is higher priority - `ButtonFocus.zip` or `EventOrder.zip`? I would split the issue in two and address the two problems separately. 

For `EventOrder.zip` the problem points to `AllowFocusOnInteraction` as the cause of the problem - the property not being supported properly on WASM is the cause.

In case of `ButtonFocus.zip`, the problem is instead most likely cause by focus returning after flyout close not being properly supported yet.

**Comment by peternary** [comment] 2021-08-24 15:48
@MartinZikmund I believe the EventOrder issue is the higher priority of the two.

**Comment by MartinZikmund** [comment] 2021-08-24 16:08
Created #6852 for the button focus issue, will look into this one first

**Comment by DierkDroth** [comment] 2021-08-25 04:47
Thanks @MartinZikmund. Could you please add #6852 to our private Kanban as well? Thx

**Comment by MartinZikmund** [comment] 2021-08-31 12:05
Fix merged

**Closed by MartinZikmund** 2021-08-31 12:05 UTC
Labels: kind/bug, project/input, difficulty/challenging

**Comment by peternary** [comment] 2021-08-31 20:55
Confirmed fixed
