### ISSUE TITLE
[any-plat] x:Bind, mode=TwoWay not working

### ISSUE THREAD

**Issue by XiaotianNetlift** [unoplatform/uno#2668] opened 2020-02-17 23:56 UTC
## Current behavior
When the target property changed, `x:Bind, Mode=TwoWay` doesn't update the source property, essentially behaves like `OneWay`.

## Expeceted bahavior
When the target property changed, `x:Bind, Mode=TwoWay` binding should update the source property.

## How to reproduce it (as minimally and precisely as possible)
```
<CheckBox IsChecked="{x:Bind path_to_property, Mode=TwoWay}" />
```
[XBindRepro.zip](https://github.com/unoplatform/uno/files/4216731/XBindRepro.zip)

## Environment
Nuget Package: Uno.UI
Package Version(s): 2.1.0-dev.1254
Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows

Visual Studio: 2019
Relevant plugins: n/a

**Comment by jeromelaban** [comment] 2020-02-18 13:27
Duplicate of #2587

**Closed by jeromelaban** 2020-02-18 13:27 UTC
Labels: area/android, area/ios, area/wasm, kind/bug, triage/untriaged
