### ISSUE TITLE
[WASM] DataGrid RowDetailsTemplate working only 1st time for each row

### ISSUE THREAD

**Issue by rob-v** [unoplatform/uno#6656] opened 2021-08-04 12:50 UTC
## Current behavior

In DataGrid RowDetailsTemplate is displayed for a row first time you select that row. Next time it isn't displayed.

## Expected behavior

To display RowDetailsTemplate each time a row is selected like in UWP.

## How to reproduce it (as minimally and precisely as possible)

Run Uno.Samples\UI\WCTDataTreeTabSample\WCTDataTreeTabSample\WCTDataTreeTabSample.Wasm\WCTDataTreeTabSample.Wasm.csproj
Select DataGrid in left panel.
Click on 1st row then 2nd row.
Click again on 1st row - RowDetailsTemplate is not displayed. You can click on 3rd row - it is displayed, but again only this first time.

![UnoDataGridRowDetailsTemplate](https://user-images.githubusercontent.com/16348750/128183237-d28f87bf-4d62-4a49-adbb-5f93fbaf7960.gif)

## Works on UWP/WinUI

Yes

## Environment

Nuget Package:
- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Uno.Microsoft.Toolkit.Uwp.UI.Controls.DataGrid  7.1.0-build.6.g97596da45a

**Comment by jeromelaban** [comment] 2021-08-04 12:58
Thanks for the report! Can you try with an updated build of uno ? Preferably 3.10-dev ? This looks like a focus issue and we're made many changes around this recently.

**Comment by rob-v** [comment] 2021-08-04 13:06
I updated all Uno.* packages to 3.10.0-dev.156. It didn't help. btw I had to comment out this App.xaml.cs 215 after update:
The type or namespace name 'MaterialColorPalette' does not exist in the namespace 'Uno.Material'

**Comment by duke7553** [comment] 2021-12-22 20:33
@rob-v Just tested with the latest version of Uno.UI, and I'm pretty sure this can no longer be reproduced. And to fix that MaterialColorPalette error, you can replace line 215 with this:
```cs
this.Resources.MergedDictionaries.Add(new global::Uno.Material.MaterialColors());
``` 

Closing now.

FYI @jeromelaban

**Closed by duke7553** 2021-12-22 20:33 UTC
Labels: kind/bug, area/windows-community-toolkit, project/input, difficulty/tbd, area/focus
