### ISSUE TITLE
A -desktop only project fails applying styles to a templated control

### ISSUE THREAD

**Issue by mcNets** [unoplatform/uno#18157] opened 2024-09-09 14:50 UTC
### Current behavior

I've added a templated control to the project and set a default style in `Themes\Generic.xaml`, but the style is never set and `OnApplyTemplate` is never called.

I've added a minimum example following the steps in the [docs](https://platform.uno/docs/articles/guides/how-to-create-control-libraries.html#create-the-control).

[TestTemplatedControl.zip](https://github.com/user-attachments/files/16932324/TestTemplatedControl.zip)

Then I've created a new project with 2 tfm windows and desktop, the same example works in windows and fails in desktop.

[TestControl2.zip](https://github.com/user-attachments/files/16940814/TestControl2.zip)

### Expected behavior

The style to be applied to the control.

### Works on UWP/WinUI

None

### Affected platforms

Skia (GTK)

### IDE

Visual Studio 2022

### IDE version

17.12.0 Preview 1.0

**Comment by MartinZikmund** [comment] 2024-09-10 07:15
@mcNets possible duplicate of https://github.com/unoplatform/uno/issues/4424?

**Comment by mcNets** [comment] 2024-09-10 07:35
> @mcNets possible duplicate of #4424?

@MartinZikmund yes, it seems the same issue. 

Should I close this one?

Anyway, this is a very old issue (October 30, 2020), the documents should reflect this otherwise it can cause confusion.

https://platform.uno/docs/articles/guides/how-to-create-control-libraries.html#create-the-control

**Comment by MartinZikmund** [comment] 2024-09-11 11:20
Yes, we are in process of updating the docs to include this fact. CC @morning4coffe-dev . Closing as duplicate of #4424, hopefully we will resolve that one soon

**Closed by MartinZikmund** 2024-09-11 11:20 UTC
Labels: kind/bug, triage/needs-information, project/styling 👔, difficulty/tbd
