### ISSUE TITLE
[Android] Touch target of HyperlinkButton is too small

### ISSUE THREAD

**Issue by jcantin-nventive** [unoplatform/uno#3326] opened 2020-06-08 13:59 UTC
## Current behavior

On Android, the touch target does not extend below the text of the HyperlinkButton, even when the height of the button is greater than the height of the text.

## Expected behavior

On all platforms, the touch target of the button should extend to the full height of the button.

## How to reproduce it (as minimally and precisely as possible)

Launch this app: https://github.com/jcantin-nventive/touch-target
Try to tap on the area below the text of the button. This activates the Click event on UWP and iOS, but not Android - on Android, you must tap the area of the text or above the text.

## Environment

Nuget Package: Uno.UI

Package Version(s): 2.4.0

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.6.0 Preview 3.0)
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by francoistanguay** [comment] 2020-08-29 12:24
@davidjohnoliver  Has this been fixed by Fluent and Material support?

**Comment by davidjohnoliver** [comment] 2020-08-31 10:04
I'm not aware of this being fixed. There seems to be no Fluent style for `HyperlinkButton` (the template is basically just a TextBlock). 

I'm guessing the issue is with the way the hit target for the button is calculated, but needs investigation.

**Comment by agneszitte-nventive** [comment] 2022-01-11 16:41
This issue was not related to Fluent and Material.
It was just the touch target area that was not properly calculated for android for a standard HyperlinkButton style with Padding with previous Uno versions (tested with Uno.UI 2.4.0).

Closing the issue as it is now fixed with latest Uno stable version (Uno.UI 4.0.11)
[Tested related code sample with Uno.UI version 4.0.11 and Android emulator Pixel 3 XL - API 30 - Android 11)

**Closed by agneszitte-nventive** 2022-01-11 16:41 UTC
Labels: kind/bug, platform/android, project/styling, difficulty/medium, area/eu
