### ISSUE TITLE
[Gallery][Wasm]Transforms- Rotate box for 'scaleTransform' at the time of transform leaving few lines.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#11755] opened 2023-03-21 02:53 UTC
### Current behavior

![transform issue](https://user-images.githubusercontent.com/74563602/226507102-e00ba7a0-1db2-4312-b5b6-ae6bbb3fb851.png)
![transform issue 2](https://user-images.githubusercontent.com/74563602/226507113-da2c65d5-aa05-4574-9241-9483cbc0abc3.png)

### Expected behavior

The transform box should not leave any lines.

### How to reproduce it (as minimally and precisely as possible)

Open Uno Gallery APP
Tap Burger Menu on the left top right.
Tap "Transforms" from the "Features" list.
Go to 'ScaleTransform' section.
Observe that Rotate box for 'scaleTransform' at the time of transform leaving few lines.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment] 2023-03-21 11:27
This issue is a duplicate of https://github.com/unoplatform/uno/issues/5655, an issue we still cannot fix.

**Closed by jeromelaban** 2023-03-21 11:27 UTC
Labels: kind/bug, platform/wasm, triage/untriaged, area/canary, difficulty/tbd
