### ISSUE TITLE
[WASM]Custom fonts cannot be displayed normally in V3.0

### ISSUE THREAD

**Issue by Daoting** [unoplatform/uno#3656] opened 2020-07-29 03:50 UTC
## Current behavior
The html is:
`<p id="30114" xamltype="Windows.UI.Xaml.Controls.TextBlock" xamlhandle="30114" class="uno-textblock uno-frameworkelement uno-uielement" tabindex="-1" wrap="off" style="pointer-events: auto; color: rgb(157, 157, 157); font-style: normal; font-weight: normal; font-family: &quot;Segoe UI&quot;; font-size: 20px; text-align: left; letter-spacing: 0em; white-space: pre; position: absolute; top: 0px; left: 0px; width: 14px; height: 20px;"></p>`
`font-family` is wrong

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment] 2020-07-29 11:35
Thank for the report. Can you provide an code example of this issue and how you're setting the font ?

**Comment by Daoting** [comment] 2020-07-30 00:02
Fonts.css
```
@font-face {
    font-family: "DtIcon";
    src: url(Fonts/icon.woff2) format("woff2");
    font-weight: 400;
    font-style: normal
}
```
icon.woff2 exists.

The resource
```
    <win:FontFamily x:Key="IconFont">ms-appx:///Assets/Fonts/icon.ttf#DtIcon</win:FontFamily>
    <not_wasm:FontFamily x:Key="IconFont">ms-appx:///Assets/Fonts/icon.ttf#DtIcon</not_wasm:FontFamily>
    <wasm:FontFamily x:Key="IconFont">DtIcon</wasm:FontFamily>

    <TextBlock FontFamily="{StaticResource IconFont}" ... />
```
v2.4 can be displayed normally

**Comment by alextrepa** [comment] 2020-08-19 23:32
I investigated the issue and could not reproduce. Adding the fonts worked. I would need more details to investigate further.

**Comment by francoistanguay** [comment] 2020-08-27 03:24
@Daoting  Can you please provide a repo. Otherwise we'll close the issue and assume it's resolved.

**Comment by Daoting** [comment] 2020-09-11 07:19
Sorry @jeromelaban @alextrepa @carldebilly, I missed the prompt because I was busy with something else. I defined a font library to be used as icons, v2.4 shows normal:
![image](https://user-images.githubusercontent.com/29876815/92880820-f7298880-f440-11ea-9d1d-bcf1a75bfc35.png)

It became garbled after v3.0:
![image](https://user-images.githubusercontent.com/29876815/92881111-4374c880-f441-11ea-852d-18ebdc45593a.png)

Fonts.css
```
@font-face {
    font-family: "DtIcon";
    src: url(Fonts/icon.woff2) format("woff2");
    font-weight: 400;
    font-style: normal
}
```
icon.woff2 exists.

The resource
```
    <win:FontFamily x:Key="IconFont">ms-appx:///Assets/Fonts/icon.ttf#DtIcon</win:FontFamily>
    <not_wasm:FontFamily x:Key="IconFont">ms-appx:///Assets/Fonts/icon.ttf#DtIcon</not_wasm:FontFamily>
    <wasm:FontFamily x:Key="IconFont">DtIcon</wasm:FontFamily>
```

Used in xaml
    <TextBlock FontFamily="{StaticResource IconFont}" ... />

The fonts file
[icon.zip](https://github.com/unoplatform/uno/files/5207286/icon.zip)

**Comment by jeromelaban** [comment] 2020-09-11 13:12
@Daoting  Are you defining the resource in a library ?

**Comment by Daoting** [comment] 2020-09-14 00:06
[woff2 file](https://github.com/Daoting/dt/tree/master/Client/Dt.Shell.Wasm/Fonts)
[Fonts.css](https://github.com/Daoting/dt/blob/db67361184a00a9af61f67eb5cd2e1e6cd9066f3/Client/Dt.Shell.Wasm/WasmCSS/Fonts.css#L2)
[csproj file](https://github.com/Daoting/dt/blob/db67361184a00a9af61f67eb5cd2e1e6cd9066f3/Client/Dt.Shell.Wasm/Dt.Shell.Wasm.csproj#L28)
[Style resource](https://github.com/Daoting/dt/blob/db67361184a00a9af61f67eb5cd2e1e6cd9066f3/Client/Dt.Base/Themes/Global.xaml#L28)

**Closed** 2020-11-04 02:44 UTC
Labels: kind/bug, project/documentation, project/text

**Comment by alextrepa** [comment] 2020-11-04 02:55
@Daoting, thank you for taking the time to document your issue.  What you are trying to do is in fact not possible anymore.

With the introduction of Skia in Uno 3.0 it is not possible to target Wasm in a cross targeted library like you are doing. In a cross targeted libraries, you can now use a new prefix, `netstdref` which will target both Skia and Wasm. This prefix is suited for most cases.

In your case, since fonts do not work the same in Skia and Wasm, you should probably define the font directly in your wasm project. 

For more details, our documentation has been updated to help prevent this issue from happening again.  https://github.com/unoplatform/uno/blob/master/doc/articles/platform-specific-xaml.md
