### ISSUE TITLE
Docs HTML details and summary disclosure - expander absent

### ISSUE THREAD

**Issue by weitzhandler** [unoplatform/uno#13322] opened 2023-08-21 01:41 UTC
## On which page?
This is a general issue in the docs, the disclosure `details` and `summary` elements are styled in such way that the collapse arrow is invisible.

For example:

```md

<details>
  <summary>Long comment (collapsed for brevity)</summary>

  Lorem ipsum dolor sit amet
</details>
```

Output:

<details>
  <summary>Long comment (collapsed for brevity)</summary>

  Lorem ipsum dolor sit amet
</details>

## What's wrong?

The docs' css includes an override which sets `display: block` for these elements, and the expand/collapse arrow isn't present.

It seems that the website is using https://github.com/necolas/normalize.css which overrides the `summary` element.

The source of the issue is here:
https://github.com/unoplatform/uno/blob/master/doc/templates/uno/vendor/docfx.vendor.css#L13

## Additional info

While investigating the issue, I realized that the rest of the styles and stuff in the templates folder are really outdated compared to the new versions in docfx's source (https://github.com/dotnet/docfx/blob/main/templates/pdf.default/styles/docfx.vendor.css).

**Comment by weitzhandler** [comment] 2023-08-21 01:54
Maybe there's more than what I'm aware of, but it seems like the website styles have been overriden inline, not allowing for future style updates. Possible we can use the newer versions and have the old styles override them by an external file (not inline) and gradually dumping the unwanted settings from the external file, until we're left with what we're actually overriding.

Anyway for now, I'd like to ditch `summary` from this line:
https://github.com/unoplatform/uno/blob/master/doc/templates/uno/vendor/docfx.vendor.css#L13

**Comment by weitzhandler** [comment] 2023-09-26 11:51
@sasakrsmanovic I think it's this one:
https://github.com/unoplatform/uno/blob/e8befba2450ba358c10e96cb6b263ffccaa294f1/build/Uno.UI.Build.csproj#L29

**Comment by weitzhandler** [comment] 2023-10-09 12:48
A bit related: https://github.com/unoplatform/workshops-private/issues/59
We need to update not just the DocFx package but the underlying css and how they're constructed.

**Comment by alextrepa** [comment] 2023-10-25 13:38
@weitzhandler I've open a pull request to temporarily fix this issue. It will add the js and css map to prod which will help debugging those kind of issue in the future. It overrides the property from normalize.css and sets summary back to a list-item.

As I mention in the pull request. It's a temporary fix until we update docfx and bootstrap which are the root cause of the issue. There are plans to do so, but this will take time. Bootstrap 3.4 has normalize.css as a dependency (starting with bootstrap 4, it's no longer the case).

Is that fix okay with you for now.

**Comment by weitzhandler** [comment] 2023-10-25 14:06
Most likely that should work.
Please let me know when the change is ready to be tested.

**Comment by weitzhandler** [comment] 2023-10-30 06:57
Just tried this on the main website and it doesn't seem to be resolved:

![image](https://github.com/unoplatform/uno/assets/2716316/54c88d7c-ec8c-4456-a798-d441cd3fa033)

**Comment by weitzhandler** [comment] 2023-10-30 15:24
Verified with @jeromelaban and it works.

**Comment by agneszitte** [comment] 2023-11-02 22:04
Reopening the issue as it is still happening, see below
https://platform.uno/docs/articles/external/workshops/tube-player/modules/01-Getting-started/README.html

**Comment by agneszitte** [comment] 2023-11-03 15:42
> Reopening the issue as it is still happening, see below for the "Details instructions on obtaining a YouTube API key":
> ...

Was missing backport https://github.com/unoplatform/uno/pull/14107#issuecomment-1792658046
We will close the issue once the backport will be done and push to prod

**Comment by agneszitte** [comment] 2023-11-03 19:08
Pushed to prod after backport PR was merged.
Closing the issue as it is now tested and fixed.

**Closed by agneszitte** 2023-11-03 19:08 UTC
Labels: difficulty/medium 🤔, kind/documentation, area/website
