### ISSUE TITLE
[Gallery-4X][Wasm]Lottie- Lottie is missing

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#13157] opened 2023-08-08 03:59 UTC
### Current behavior

![lottie issue](https://github.com/unoplatform/uno/assets/74563602/0ea5d353-9883-4458-bdff-7724517dc6f1)

### Expected behavior

![lottie correct](https://github.com/unoplatform/uno/assets/74563602/d719e925-6dcc-49a5-8e28-1659be48a10c)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallry app
2. Click on “Lottie” from the "UI-Features" list.
3. Notice that the Lottie is missing.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly

**Comment by lesterbotello** [comment] 2023-08-12 15:45
@sakshi173 I'm not able to reproduce this in Chrome, Chrome Canary, Edge or Firefox. Any additional reproduction steps I can take to trigger this?

**Comment by sakshi173** [comment] 2023-08-14 00:00
this is for 4x canary build and it is happening in Chrome, MS edge too.

**Comment by lesterbotello** [comment] 2023-08-14 15:58
Thanks @sakshi173. I'm able to reproduce in the [4x site](https://unogallerycanary4x.z13.web.core.windows.net/?), but the issue doesn't seem to be present in the `legacy/4x` branch.

@agneszitte Does this mean this is actually fixed but needs to be redeployed?

**Comment by agneszitte** [comment] 2023-08-14 16:24
> Thanks @sakshi173. I'm able to reproduce in the [4x site](https://unogallerycanary4x.z13.web.core.windows.net/?), but the issue doesn't seem to be present in the `legacy/4x` branch.
> 
> @agneszitte Does this mean this is actually fixed but needs to be redeployed?

If you can test locally to rebase `canaries/4x `with latest `legacy/4x` to see if it is fixing the issue, please
If so please open a PR so `legacy/4x` is updated with latest and that should fix the canary build for this issue
If there is something else please let me know

**Comment by lesterbotello** [comment] 2023-08-14 19:54
This seems to be working correctly in both the `canaries/4x` and `legacy/4x` branches. Obviously, merging both branches results in the issue not being present as well there.

However, I can see the issue is reproducible here: https://unogallerycanary4x.z13.web.core.windows.net/?

**Comment by sakshi173** [comment] 2023-08-15 13:44
@agneszitte and @lesterbotello, as Lester said and I retested too, the defect is still reproducible for 4X Canary due to that the defect is still open, once it will be fixed for the canary build, I will close it.

**Comment by agneszitte** [comment] 2023-08-16 23:30
@Youssef1313 verifying if it is an AOT/Interpreter related issue for Gallery 4x

**Comment by Youssef1313** [comment] 2023-08-17 21:04
Should be fixed now.

![image](https://github.com/unoplatform/uno/assets/31348972/18474ea1-ccd0-428b-9c21-2692c5dd421a)

**Closed by Youssef1313** 2023-08-17 21:04 UTC
Labels: kind/bug, platform/wasm 🌐, triage/untriaged, area/canary 🐤, difficulty/tbd

**Comment by agneszitte** [comment] 2023-08-17 21:05
Thank you @Youssef1313, ready for QA @sakshi173

**Comment by sakshi173** [comment] 2023-08-17 22:10
Verified this issue is fixed, closing it.
