### ISSUE TITLE
[Android] TextBlock does not display line breaks unless TextWrapping is specified

### ISSUE THREAD

**Issue by jcantin-nventive** [unoplatform/uno#2352] opened 2019-12-17 20:25 UTC
## Current behavior

TextBlock only shows the first line before the line break.
We can work around this by specifying TextWrapping, but it shouldn't be necessary when the string already contains line breaks.

## Expected behavior

TextBlock displays line returns correctly.

## How to reproduce it (as minimally and precisely as possible)

Launch the app from [this repo](https://github.com/jcantin-nventive/textblock-line-breaks).

## Environment

Nuget Package: Uno.UI
Package Version(s): 1.45.0 and 2.1.0-dev.331

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [x] 2017 (version: 15.9.11)
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Youssef1313** [comment] 2021-08-04 09:13
I can't reproduce. @jeromelaban @MartinZikmund Was this fixed in past? or it's something wrong on my side?

**Comment by MartinZikmund** [comment] 2021-08-04 09:20
@Youssef1313 not sure, @JanKleprlik is currently looking into text wrapping related issues on Android, maybe he will know 🙂

**Comment by Youssef1313** [comment] 2021-08-04 11:23
@JanKleprlik Still didn't reproduce for me 😕 

![image](https://user-images.githubusercontent.com/31348972/128172579-aab0b4b2-62df-4320-af69-e763e072620d.png)

**Comment by jeromelaban** [comment] 2021-08-04 11:40
@Youssef1313 @JanKleprlik which versions of Android are testing with ?

**Comment by Youssef1313** [comment] 2021-08-04 11:42
Android 9.0 (API 28)

**Comment by JanKleprlik** [comment] 2021-08-04 11:43
Hm, I am unable to reproduce it in emulator with Android version 9.0. But on a physical device with Android 6.0 the problem occurs as described in the original post.

**Comment by jeromelaban** [comment] 2021-08-04 11:46
It could be because of a missing support from Android 6.0. Does it happen with a 6.0 emulator as well ?

**Comment by JanKleprlik** [comment] 2021-08-04 11:55
Yes, it does happen with the Android 6.0 emulator as well. I will try to find the API that might cause this.

**Comment by jeromelaban** [comment] 2021-08-04 12:35
I would not be surprised if it were a missing feature in previous android builds: https://github.com/unoplatform/uno/blob/3bff3470b445c91dd2a1150a7b90d218cc7a878b/src/Uno.UI/UI/Xaml/Controls/TextBlock/TextBlock.Android.cs#L699

**Comment by francoistanguay** [comment] 2022-02-02 00:56
Closing as it seems to be an Android 6 specific issue.

**Closed by francoistanguay** 2022-02-02 00:56 UTC
Labels: kind/bug, good first issue, platform/android, project/text, difficulty/starter, area/eu
