### ISSUE TITLE
[WASM] Binding in TooltipService.Tooltip.Content 

### ISSUE THREAD

**Issue by paulovila** [unoplatform/uno#9570] opened 2022-08-22 20:29 UTC
### Current behavior

```TooltipService.Content``` can be set to a literal, however, binding it to a property doesn't work.
see: https://github.com/paulovila/TooltipService 
![image](https://user-images.githubusercontent.com/888391/186012087-c9c958f0-baba-4d40-92f9-aa69dfc20ca0.png)

### NuGet package version(s)

4.5.0-dev.562

### Affected platforms

WebAssembly

**Comment by Youssef1313** [comment] 2022-08-24 18:49
- This is not Wasm specific.
- It reproduces only when Tooltip is used in attached property.
- The binding seems to work *initially*, ie, `Content` is set correctly. But on hovering the `TextBlock`, things go wrong and `Content` gets set to null.

**Comment by jeromelaban** [comment] 2022-08-24 18:51
It may be that the DataContext is synchronized explicitly in the TooltipService, and that it's not propagated again properly.

**Comment by Youssef1313** [comment] 2022-08-24 21:26
I got a fix for this by passing the ToolTip DataContext to the created Popup DataContext. However, this isn't fully correct because later updates DataContext won't reflect into Popup, and I don't seem to get `OnDataContextChanged` callbacks after we create the Popup.

**Comment by Youssef1313** [comment] 2022-08-25 11:24
Investigated this more. When we set `Popup.Child = this;` ('this' is the ToolTip), The `DataContext` gets set with `Local` precedence. So later when the `DataContext` changes, it's set with `Inheritance` precedence, but the old `Local` value takes has higher priority and is retrieved.

**Comment by jeromelaban** [comment] 2022-08-25 12:26
We had a similar behavior in Flyout, fixed with :

https://github.com/unoplatform/uno/blob/ce11d73288cfc59e9503ada917973d35911573b0/src/Uno.UI/UI/Xaml/Controls/Flyout/FlyoutBase.cs#L435-L443

**Closed** 2022-09-21 16:27 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
