### ISSUE TITLE
[Android] Flyout light-dismiss hitbox is incorrect

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno#2682] opened 2020-02-21 06:14 UTC
## Current behavior
Clicking outside of a flyout doesn't always dismiss it.

## Expected behavior
Clicking anywhere outside of a flyout should dismiss it.

## How to reproduce it (as minimally and precisely as possible)
- launch SamplesApp
- go to Flyout ->Flyout_Simple, 
- click on "Show Flyout Left"
- try to close it by clicking below it
  > doesnt work
  ![image](https://user-images.githubusercontent.com/2359550/75008501-2e552f80-5446-11ea-868f-cbd6933a272f.png)

## Environment
Nuget Package: Uno.UI
Package Version(s): 2fe65504 from master
Affected platform(s):
- [ ] iOS (not tested)
- [x] Android
- [ ] WebAssembly (not tested)
- [ ] Windows

Visual Studio: 2019
Relevant plugins: N/A

## Anything else we need to know?

**Comment by Youssef1313** [comment] 2021-08-23 08:22
The sample looks different from the image in issue and I couldn't reproduce.

https://user-images.githubusercontent.com/31348972/130414709-07832fc9-ddac-4b6e-af8e-fa1f9f059532.mp4

Was this already fixed?

**Comment by jeromelaban** [comment] 2021-08-25 12:30
Looks like it's been addressed by a popup-related PR. Let's close this then, Thanks for validating!

**Closed by jeromelaban** 2021-08-25 12:30 UTC
Labels: kind/bug, project/navigation-lifecycle, difficulty/starter, area/eu, area/popups
