### ISSUE TITLE
Text Alignment Issue

### ISSUE THREAD

**Issue by MelbourneDeveloper** [unoplatform/uno#3462] opened 2020-06-29 07:40 UTC
This issue is a stub that points to an issue on a private repo:
https://github.com/MelbourneDeveloper/UnoUdemyCourse/issues/8

Sorry that I couldn't move this issue directly into this repo. Github doesn't have that functionality. Next time I will create the issue here.

@francoistanguay @carldebilly @jeromelaban

**Comment by jeromelaban** [comment] 2020-06-29 12:32
Thanks for the issue. It would be best to copy the content of the issue here for all contributors to see.

**Comment by francoistanguay** [comment] 2020-08-26 23:29
Duplicate of #3471

**Closed by francoistanguay** 2020-08-26 23:29 UTC
Labels: area/layout, area/textblock, kind/bug, priority/backlog
