### ISSUE TITLE
[All] UnoEnableXamlFuzzyMatching flag doens't work in a project with shared project structure

### ISSUE THREAD

**Issue by Lee31416** [unoplatform/uno#12882] opened 2023-07-13 14:07 UTC
### Current behavior

The app builds just fine with the flag set to false in the shared.csproj and mobile.csproj and using fuzzy matching.

### Expected behavior

The app shouldn't build if the flag is false and we keep using fuzzy matching. 

### How to reproduce it (as minimally and precisely as possible)

1. Download this sample 
[UnoSampleFuzzy.zip](https://github.com/unoplatform/uno/files/12040256/UnoSampleFuzzy.zip)
2. Build the project

### Works on UWP/WinUI

No

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia, Uno.UI.RemoteControl / Uno.WinUI.RemoteControl

### NuGet package version(s)

latest stable 4.9.26

### Affected platforms

Android, iOS, Windows

### IDE

Visual Studio 2019

### IDE version

17.6.2

**Comment by Lee31416** [comment] 2023-07-13 14:49
@jeromelaban Exactly we wanted to prepare for the uno 5.0 update

**Comment by Lee31416** [comment] 2023-07-13 15:37
@jeromelaban I think we provided the wrong sample I'll provide another one soon

**Comment by Lee31416** [comment] 2023-07-13 16:05
@jeromelaban it seems that the issue was we were testing with the play button on visual studio but the fuzzy matching only gives errors when building from the build tab -> build solution
![image](https://github.com/unoplatform/uno/assets/72167772/27f15c4d-178a-48e9-83d0-de12a10cf6d9)

**Comment by Youssef1313** [comment] 2023-07-13 16:08
@Lee31416 This is very weird, and shouldn't really happen. Can you get binary logs for both cases? I'd like to see if the value of `UnoEnableXamlFuzzyMatching` differs somehow between these cases. Also, did you try to restart VS?

**Comment by Lee31416** [comment] 2023-07-13 16:13
@Youssef1313 I know how to generate a binlog for the build but do you know how to generate one with the play button case ?

**Comment by Lee31416** [comment] 2023-07-13 16:17
@Youssef1313 Restarting didn't do much but here's the binlog for the build case the other one is coming
[msbuild.zip](https://github.com/unoplatform/uno/files/12041566/msbuild.zip)

**Comment by jeromelaban** [comment] 2023-07-13 17:02
Thanks. @Lee31416 can you make sure to enable diagnostics logging, [as described here](https://platform.uno/docs/articles/uno-builds-troubleshooting.html) and recreate the binlogs?

**Comment by Lee31416** [comment] 2023-07-13 19:28
Here u go 
[msbuild.zip](https://github.com/unoplatform/uno/files/12043821/msbuild.zip)

**Comment by jeromelaban** [comment] 2023-07-13 19:33
Thanks. This build is failing for a good reason; it's likely that you're missing an ignorable for `ios`. Can you try again with it ?

**Comment by Lee31416** [comment] 2023-07-13 20:07
@jeromelaban Wow I feel stupid now with the ios in the ignorable the sample doesn't fail (even with fuzzy matching to false and building the solution from the build tab) which is what we were trying to reproduce in the sample in the first place

**Comment by jeromelaban** [comment] 2023-07-13 20:47
No worries :) Can you still provide a binlog of the build that works?

**Comment by Lee31416** [comment] 2023-07-13 20:58
[msbuild.zip](https://github.com/unoplatform/uno/files/12044393/msbuild.zip)
Here is the binlog from the working build on the sample

**Comment by jeromelaban** [comment] 2023-07-13 21:35
Thanks. I'm not able to reproduce what you're seeing, but I wonder if it's a net6 issue. Can you try setting your mobile project to `net7.0-*` ?

**Comment by Lee31416** [comment] 2023-07-14 13:05
@jeromelaban With dotnet7 it still builds with no error

**Comment by jeromelaban** [comment] 2023-07-14 13:20
Thanks.  Could you try using the command line ? With `dotnet build` and see if it changes the behavior?

**Comment by Lee31416** [comment] 2023-07-14 13:37
@jeromelaban I had 4 warnings instead of 2 but no errors and the warning were about package references

**Comment by Lee31416** [comment] 2023-07-14 14:17
[UnoSample.zip](https://github.com/unoplatform/uno/files/12051224/UnoSample.zip)
I'm sorry if there is some differences that I'm not aware of I didn't change anything else other than what we talked here like the ignorable and generating binlogs

**Comment by jeromelaban** [comment] 2023-07-14 14:31
I'm still getting the proper errors with your latest sources. @Youssef1313 are you getting errors when building the sample? This is very strange...

@Lee31416 could you make a video of your visual studio when building? I wonder if there's a code path that makes it fail differently.

**Comment by Youssef1313** [comment] 2023-07-14 14:49
@jeromelaban The last zip file builds for me:

![image](https://github.com/unoplatform/uno/assets/31348972/175a923e-8b7f-4f42-8771-811161c66f7d)

But that is expected because we have this:

https://github.com/unoplatform/uno/blob/8744f11d64e84b2441397971f106d8b5c98c0473/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs#L606-L607

**Comment by Youssef1313** [comment] 2023-07-14 14:52
@jeromelaban Are you getting errors for the above sample? 😕

**Comment by jeromelaban** [comment] 2023-07-14 15:25
@Youssef1313 yes it fails for me, saying that TextBlock cannot be found.

**Comment by jeromelaban** [comment] 2023-07-14 15:26
> But that is expected because we have this:

It should still be failing because of

https://github.com/unoplatform/uno/blob/8744f11d64e84b2441397971f106d8b5c98c0473/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.Reflection.cs#L649

**Comment by Youssef1313** [comment] 2023-07-14 15:27
@jeromelaban It's supposed to be resolved via `SearchClrNamespaces(fields[1])` not `SearchWithFuzzyMatching(fields[1])` I think.

**Comment by Youssef1313** [comment] 2023-07-14 15:28
We already have similar code in SamplesApp:

https://github.com/unoplatform/uno/blob/8744f11d64e84b2441397971f106d8b5c98c0473/src/SamplesApp/UITests.Shared/Windows_UI_Xaml_Controls/DatePicker/DatePicker_Features.xaml#L159

and we disable fuzzy matching:

https://github.com/unoplatform/uno/blob/8744f11d64e84b2441397971f106d8b5c98c0473/src/Directory.Build.props#L48

**Comment by Lee31416** [comment] 2023-07-14 15:33
So its only not failing on my computer ?

**Comment by Youssef1313** [comment] 2023-07-20 14:08
@Lee31416 If you are seeing that the code compiles successfully, then it's expected. I'm updating the docs in https://github.com/unoplatform/uno/pull/12947. Does the doc update solve the question?

**Comment by takla21** [comment] 2023-07-20 14:11
@Youssef1313 Although I'm not the OP, we had the same issue together, and yeah, that's what was missing on our side. I'm closing the issue.

**Closed by takla21** 2023-07-20 14:11 UTC
Labels: kind/bug, triage/untriaged, area/code-generation, difficulty/tbd
