### ISSUE TITLE
DispatcherQueue.TryEnqueue is not implemented

### ISSUE THREAD

**Issue by sigmarsson** [unoplatform/uno#6052] opened 2021-05-21 00:35 UTC
## Failed to raise 'TappedEvent': System.NotImplementedException: The member bool DispatcherQueue.TryEnqueue(DispatcherQueueHandler callback) is not implemented in Uno.

Just trying to operate on the DatePicker control in Chrome browser. 

![image](https://user-images.githubusercontent.com/43340959/119064865-9d6c5b80-b9dc-11eb-9bef-fbb02c3d5c59.png)

```
Failed to raise 'TappedEvent': System.NotImplementedException: The member bool DispatcherQueue.TryEnqueue(DispatcherQueueHandler callback) is not implemented in Uno.
         at Windows.System.DispatcherQueue.TryEnqueue(DispatcherQueueHandler callback) in C:\a\1\s\src\Uno.UWP\Generated\3.0.0.0\Windows.System\DispatcherQueue.cs:line 25
         at Microsoft.UI.Xaml.Controls.Primitives.LoopingSelector.SetScrollPosition(Double offset, Boolean useAnimation) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Primitives\LoopingSelector\LoopingSelector_Partial.cs:line 1905
         at Microsoft.UI.Xaml.Controls.Primitives.LoopingSelector.OnItemTapped(Object pSender, TappedRoutedEventArgs pArgs) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Primitives\LoopingSelector\LoopingSelector_Partial.cs:line 622
         at Microsoft.UI.Xaml.UIElement.InvokeHandler(Object handler, RoutedEventArgs args) in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.RoutedEvents.cs:line 865
         at Microsoft.UI.Xaml.UIElement.RaiseEvent(RoutedEvent routedEvent, RoutedEventArgs args, BubblingContext ctx) in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.RoutedEvents.cs:line 614
         at Microsoft.UI.Xaml.UIElement.SafeRaiseEvent(RoutedEvent routedEvent, RoutedEventArgs args, BubblingContext ctx) in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.RoutedEvents.cs:line 571
```

## Environment

```
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
    <PackageReference Include="Microsoft.Windows.Compatibility" Version="5.0.2" />
    <PackageReference Include="Ninject" Version="3.3.4" />
    <PackageReference Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.1.0-dev.1" />
    <PackageReference Include="Uno.WinUI.WebAssembly" Version="3.8.0-dev.198" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="3.8.0-dev.198" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="2.1.0" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="2.1.0" />
  </ItemGroup>
```

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [x] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 19.10 Pv 4)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by Youssef1313** [comment] 2021-08-09 17:53
Was it implemented in https://github.com/unoplatform/uno/commit/e6dfb039b045ddf17caa571ff06a0d6bfeb24084?

cc @carldebilly

**Comment by ajpinedam** [comment] 2021-08-13 04:58
Closing this ticket since I am unable to reproduce the specified error.  

`DispatchQueue.TryEnqueue()` method  for WASM.WinUI was implemented and merged into main branch. Seeing a different error though for which I created a new issue https://github.com/unoplatform/uno/issues/6746

cc: @jeromelaban

**Closed by ajpinedam** 2021-08-13 04:58 UTC
Labels: kind/bug, platform/wasm, project/core-tools, difficulty/medium
