### ISSUE TITLE
[WASM] x:Bind OneWay to static property generates incorrect code

### ISSUE THREAD

**Issue by rgonzalezVW** [unoplatform/uno#3463] opened 2020-06-29 08:23 UTC
## Current behavior

I'm trying to do a x:Bind to a property defined in a static instance of another class. If I use the default OneTime it works, if I change it to OneWay it works on UWP but generates incorrect code on WASM.

This is the incorrect code, that lacks property name in the last parameter.
`c1.SetBinding(global::Windows.UI.Xaml.Controls.TextBlock.TextProperty, new Windows.UI.Xaml.Data.Binding{ Mode = global::Windows.UI.Xaml.Data.BindingMode.OneWay,  }.Apply(___b =>  global::Uno.UI.Xaml.BindingHelper.SetBindingXBindProvider(___b, this, ___ctx => global::App1.MainPage.Instance.TestProp, null , new [] {})));`

## Expected behavior

Binding to a property defined in a static instance of another class should work on WASM, aswell as in UWP.

This is the correct code, with the property name in the last parameter (Obtained from a binding to a local property).
`c2.SetBinding(global::Windows.UI.Xaml.Controls.TextBlock.TextProperty, new Windows.UI.Xaml.Data.Binding{ Mode = global::Windows.UI.Xaml.Data.BindingMode.OneWay,  }.Apply(___b => global::Uno.UI.Xaml.BindingHelper.SetBindingXBindProvider(___b, this, ___ctx => TestProp, null , new [] {"TestProp"})));`

## How to reproduce it (as minimally and precisely as possible)

I've attached a simplified example. Do not mind that I'm binding to a static property in the same class, in the real code is done to a different class.
[App1.zip](https://github.com/unoplatform/uno/files/4844620/App1.zip)
## Environment

Nuget Package: Uno.Wasm.Bootstrap, Uno.UI

Package Version(s): 1.2.0, 2.4.4

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [x] Build tasks
- [ ] Solution Templates

Visual Studio:

- [x] 2017 (version: 16.6.2)
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment] 2020-06-29 11:38
Thanks for the report! 

Related to https://github.com/unoplatform/uno/issues/3261

**Comment by Youssef1313** [comment] 2021-08-13 13:00
I cannot reproduce with the attached repro after upgrading all packages for solution.

The code is generated properly:

![image](https://user-images.githubusercontent.com/31348972/129360729-079564b3-4dc4-4f44-8612-4f03c73e66cb.png)

This is likely a duplciate of #3261 which was fixed as @MartinZikmund in https://github.com/unoplatform/uno/issues/3261#issuecomment-852941591.

**Comment by Youssef1313** [comment] 2021-09-20 08:59
cc @MartinZikmund @jeromelaban to confirm if this can be closed.

**Comment by jeromelaban** [comment] 2021-09-20 13:28
If you can't repro, let's close this. Thanks for validating!

**Closed by jeromelaban** 2021-09-20 13:28 UTC
Labels: kind/bug, area/code-generation, area/xBind, project/binding, difficulty/medium
