### ISSUE TITLE
Adding custom resourcedictionary to Application-wide MergedDictionaries doesn't work

### ISSUE THREAD

**Issue by mterwoord** [unoplatform/uno#6399] opened 2021-07-06 10:54 UTC
[TestApp.ZIP](https://github.com/unoplatform/uno/files/6769450/TestApp.ZIP)
## Current behavior

See attached project. It contains a resource dictionary `MyTheme.xaml`. this contains a `Test_FontSize` style. (value = 40)
In the `App.xaml` this resource dictionary is added to the merged dictionaries. On the main page, FontSize is set to `{StaticResource Test_FontSize}`
Starting the Uwp head works fine. "Hello, world!" is shown in large text.
Starting the Gtk head, the logging says it cannot resolve the `Test_FontSize` style.
I dug in a bit. The `InitializeComponent()` method of the `App` class is not adding my custom dictionary, but is adding an instance of the Uwp ResourceDictionary to the merged dictionaries. (Ie, that one is empty).

## Expected behavior

As described.

## How to reproduce it (as minimally and precisely as possible)

See attached. Starting Uwp works fine, starting Gtk doesn't (Didn't test others).

## Workaround

Copying styles, but that doesn't help me.

## Works on UWP/WinUI

Yes

## Environment

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [X] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Uno.UI.*: 3.8.11
Uno.

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [X] Skia
  - [ ] WPF
  - [X] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by mterwoord** [comment] 2021-07-06 12:33
As a work-around, creating the dictionary in the code behinds constructor, and copying all resources works, so the resources themselves are fine.

**Comment by jeromelaban** [comment] 2021-07-20 20:13
This issue is actually a duplicate of https://github.com/unoplatform/uno/issues/3412, and can be fixed by adding ` : ResourceDictionary` at the end of the `MyTheme.xaml.cs` file.

I'll close this one as a duplicate, and discuss this in the other one.

**Closed by jeromelaban** 2021-07-20 20:13 UTC
Labels: difficulty/tbd, kind/bug, project/styling

**Comment by jeromelaban** [comment] 2021-07-20 20:19
I've streamed about this here (second half): https://www.youtube.com/watch?v=PVd35aQHwAk
