### ISSUE TITLE
[WASM] TabView tab sizing unreliable

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#4782] opened 2020-12-21 16:18 UTC
## Current behavior

Adding and removing Tabs from a TabView can cause various sizing issues with Tabs, especially when removing the rightmost tab.  Noticed issues include the add tab button (the '+' button) disappearing frequently, scrollbar sometimes disappearing, tabs shrinking to just the size of the 'x' button, and occasionally all tabs disappearing entirely.

## Expected behavior

Tab sizing should be consistent.

## How to reproduce it (as minimally and precisely as possible)

In the attached project, add several tabs and close the rightmost tab.  This process may need to be repeated a couple of times before sizing issues manifest.

[TabSizing.zip](https://github.com/unoplatform/uno/files/5725309/TabSizing.zip)

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
3.4.0-dev.358
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment] 2020-12-24 13:03
This is most likely caused by some item refresh in `ListViewBase`, but may also be caused by something on `TabView` side. There is a workaround for setting the list width here:

https://github.com/unoplatform/uno/blob/c3bb0573a63de9c30b7e44b0e6d12444754d3007/src/Uno.UI/Microsoft/UI/Xaml/Controls/TabView/TabView.cs#L1046

Maybe it is related

**Comment by davidjohnoliver** [comment] 2021-01-19 11:02
This is fixed on WASM by #4921.

There's a pending PR for WinUI on Windows to fix the bug when closing the last tab. https://github.com/microsoft/microsoft-ui-xaml/pull/3955

**Comment by peternary** [comment] 2021-01-20 18:51
Looking mostly resolved, noticed 1 outstanding issue: adding enough tabs to spawn a horizontal scrollbar and then removing tabs until the bar is no longer required does not reliably cause the scrollbar to disappear.

**Closed** 2021-02-03 19:18 UTC
Labels: kind/bug, project/items
