### ISSUE TITLE
UserControl constructor not called

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#3133] opened 2020-05-09 06:29 UTC
## Current behavior

When a `DataTemplate` has a child which derives from `UserControl` and it is constructed by `ContentControl` (via `ContentTemplateSelector`), the constructor of the type is not called. Instead, a generated constructor with `skipsInitializeComponents` is called from [here](https://github.com/unoplatform/uno/blob/3344ec53cb7aab34686d6dbf96ceae559173a333/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlFileGenerator.cs#L4126). Unfortunately this is a problem if the user control contains some required logic (for example setting the data context, which then means `Bindings` are broken).

## Expected behavior

Same as on UWP, the custom constructor should execute.

## How to reproduce it (as minimally and precisely as possible)

1. Create a custom `UserControl`
2. Create a `DataTemplate` containing the user control.
3. Create a `DataTemplateSelector` with this template.
4. Bind such a content that will select this template to a `ContentControl`
```
<ContentControl
        Content="{x:Bind Mode=OneWay}"
        ContentTemplateSelector="{StaticResource SettingsPaneTemplateSelector}" />
```
5. Set a breakpoint in the custom control's constructor.
6. Observe the constructor is not called.

## Environment

Nuget Package: latest

Package Version(s): latest

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment] 2020-05-09 14:33
Thanks Martin! This is a duplicate of #61.

**Closed by jeromelaban** 2020-05-09 14:33 UTC
Labels: kind/bug, triage/untriaged
