### ISSUE TITLE
[Gallery][Android]<TimePicker> TimePicker features are not working.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5366] opened 2021-03-01 22:10 UTC
## Current behavior

https://user-images.githubusercontent.com/74563602/109565653-c56cb280-7ab0-11eb-889e-cb5bb774dbb0.mp4

## Expected behavior
The clock should open to choose the time and select it.

## How to reproduce it (as minimally and precisely as possible)
How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "TimePicker" from the "Component" list.
4. Click on the "Set Time" option in the Default section.
5. Observe that the clock is not opening.

**Note:- Same issue is happening with Fluent as well.**
Version(s):
Version 1.4.3 (400738)
Mar 01, 2021 at 11:21

Device:
Samsung S8 - 8.0
Motorola g(7) – 9

Affected platform(s):
Android

**Comment by ajpinedam** [comment] 2021-03-14 18:33
Based on this comment: TimePicker will be broken for all the platforms (excluding iOS) until it is ported from WinUI:

https://github.com/unoplatform/uno/pull/4956/files?file-filters%5B%5D=.cs#r582971675

**Comment by Youssef1313** [comment] 2021-09-20 08:06
I can't reproduce this. Looks like this was fixed by https://github.com/unoplatform/uno/pull/5720?

**Comment by sakshi173** [comment] 2021-09-20 16:35
Yes @Youssef1313,  it is fixed. you can close it.

**Comment by Youssef1313** [comment] 2021-09-20 17:02
I don't have access to. @jeromelaban Can you close?

**Closed** 2021-09-21 01:12 UTC
Labels: platform/android, kind/regression, area/canary, area/date-time-pickers
