### ISSUE TITLE
Add support for StorageFile.GetThumbnailAsync

### ISSUE THREAD

**Issue by cryptotyler** [unoplatform/uno#12842] opened 2023-07-10 10:16 UTC
### Current behavior

I'm trying to get the thumbnail of a file loaded as a buffer on Dotnet 7 Minimal API Rest or given the path  But I am encountering this error. :
![image](https://github.com/unoplatform/uno/assets/53035239/ae7ddbc3-ad0b-4869-a568-e7e36f64f4a2)

While the same method is valid in WPF applications shared by Windows, I encounter this problem on the .NET WEB API.

https://learn.microsoft.com/en-us/windows/uwp/files/thumbnails
https://learn.microsoft.com/en-us/samples/microsoft/windows-universal-samples/filethumbnails/

### Works on UWP/WinUI

None

### Relevant plugins

Not

**Comment by jeromelaban** [comment] 2023-07-11 12:32
Duplicate of https://github.com/unoplatform/uno/issues/5637

**Closed** 2023-07-11 12:33 UTC
Labels: kind/enhancement, triage/untriaged, difficulty/tbd
