### ISSUE TITLE
[WASM] `NavigationView.PaneFooter` don't accept Icon

### ISSUE THREAD

**Issue by Dimigergo** [unoplatform/uno#8483] opened 2022-04-01 08:41 UTC
### Current behavior

NavigationView PaneFooter don't accept Icon on WASM

### Expected behavior

NavigationView PaneFooter accept Icon on WASM

### How to reproduce it (as minimally and precisely as possible)

In this repo, you can see that "Footer" does not have the OtherUser icon.

[NavigationView3.zip](https://github.com/unoplatform/uno/files/8396103/NavigationView3.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

WASM project:
Uno.WinUI.WebAssembly 4.2.0-dev.521
Uno.WinUI.RemoteControl 4.2.0-dev.521
Uno.Wasm.Bootstrap.DevServer 4.0.0-dev.103
Uno.Wasm.Bootstrap 4.0.0-dev.103
Uno.CommunityToolkit.WinUI.UI.Controls 7.1.100-dev.15.g12261e2626

WinUI project:
Microsoft.WindowsAppSDK 1.1.0-preview1
Uno.WinUI 4.2.0-dev.521
CommunityToolkit.WinUI.UI 7.1.2

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.1.2

**Comment by jeromelaban** [comment] 2022-04-01 12:42
Can you be more specific about the "does not accept icon" ? Is it because it does not show?

**Comment by Dimigergo** [comment] 2022-04-04 06:52
If I run the uploaded code in WASM:

![image](https://user-images.githubusercontent.com/11498949/161488586-48dcb26f-ec61-4572-b5d1-d8f306b0c6f4.png)

The OtherUser icon before the "Footer" is not shown.
In WinUI it is perfectly shown.

I use Windows 10 - 19041, if it is help more.

**Comment by jeromelaban** [comment] 2022-04-05 03:28
Thanks for the report. For some reason, the NavigationViewItem placed in the footer does not get styled properly. As a workaround, you use one of the named styles, like this:

```xaml
    <muxc:NavigationView.PaneFooter>
        <muxc:NavigationViewItem Content="Footer" Style="{StaticResource MUX_NavigationViewItemPresenterStyleWhenOnLeftPane}">
            <muxc:NavigationViewItem.Icon>
                <SymbolIcon Symbol="Accept" Foreground="Green"/>
            </muxc:NavigationViewItem.Icon>
        </muxc:NavigationViewItem>
    </muxc:NavigationView.PaneFooter>
```

You can find some of the styles here: 

https://github.com/unoplatform/uno/blob/5e0c3818f1badff1f148325e7c3ff7b53647d4a1/src/Uno.UI.FluentTheme.v2/Resources/Version2/PriorityDefault/NavigationView.xaml#L728-L742

## Note for contributors
It seems that we're missing a default style for this control, or that it should be set appropriately when being manipulated by the NavigationView. /cc @MartinZikmund

**Comment by Dimigergo** [comment] 2022-04-05 06:41
Thanks for the workaround, it is ok for the accept icon, but wrong for an other fontfamily icon fe.:

```
        <muxc:NavigationView.PaneFooter>
            <muxc:NavigationViewItem Content="{x:Bind Vm.Culture.NavItemLogout}"
                                     ToolTipService.ToolTip="{x:Bind Vm.Culture.NavItemLogout}"
                                     Style="{StaticResource MUX_NavigationViewItemPresenterStyleWhenOnLeftPane}">
                <muxc:NavigationViewItem.Icon>
                    <FontIcon FontFamily="{ThemeResource SymbolThemeFontFamily}" Glyph="&#xE748;"/>
                </muxc:NavigationViewItem.Icon>
            </muxc:NavigationViewItem>
        </muxc:NavigationView.PaneFooter>
```

![image](https://user-images.githubusercontent.com/11498949/161694112-cf510a15-902f-4b2b-af58-c0e208e3c8c5.png)

**Comment by jeromelaban** [comment] 2022-04-05 12:51
In this case, the issue is different. It's likely that the glyph that you're trying to use is not available.

For instance, if you use this it will work:
```xaml
<muxc:NavigationViewItem Content="test"
                            Style="{StaticResource MUX_NavigationViewItemPresenterStyleWhenOnLeftPane}">
    <muxc:NavigationViewItem.Icon>
        <FontIcon FontFamily="{ThemeResource SymbolThemeFontFamily}" Glyph="&#x3A3;"/>
    </muxc:NavigationViewItem.Icon>
</muxc:NavigationViewItem>
```

We have https://github.com/unoplatform/uno/issues/5734 for tracking this.

**Comment by Dimigergo** [comment] 2022-04-05 14:24
Thanks a lot!

**Comment by MartinZikmund** [comment] 2023-07-24 08:50
Closing as our new icon font contains many more icons, and the issue is not nav view related

**Closed by MartinZikmund** 2023-07-24 08:50 UTC
Labels: kind/bug, good first issue, area/navigationview, project/items, difficulty/medium, low-hanging-🍒
