### ISSUE TITLE
Will there be macOS support?

### ISSUE THREAD

**Issue by hansmbakker** [unoplatform/uno#66] opened 2018-06-24 21:05 UTC
Will there be support for macOS like Xamarin has?

**Comment by zomorango** [comment] 2018-06-26 10:48
Let wait to see, but its really nice to know that its great possibility :) nice work

**Comment by jeromelaban** [comment] 2020-04-13 02:06
I'm closing this issue as a duplicate of https://github.com/unoplatform/uno/issues/626. You can follow the updates there.

**Closed by jeromelaban** 2020-04-13 02:06 UTC
Labels: area/macos, kind/enhancement
