### ISSUE TITLE
[iOS] Controls defined on top of CommandBar are not displayed

### ISSUE THREAD

**Issue by Guidemarcus** [unoplatform/uno#8651] opened 2022-04-28 17:59 UTC
### Current behavior

Nothing is shown on top of a CommandBar

### Expected behavior

Controls defined on top of CommandBar should be visible

### How to reproduce it (as minimally and precisely as possible)

```xaml
<Page x:Class="ApplicationTemplate.Views.Content.DadJokesPage"
	  xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
	  xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
	  xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
	  xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
	  xmlns:toolkit="using:Uno.UI.Toolkit"
	  mc:Ignorable="d">
	<Grid Background="{StaticResource MaterialBackgroundBrush}">

		<Grid.RowDefinitions>
			<RowDefinition Height="Auto" />
			<RowDefinition Height="Auto" />
		</Grid.RowDefinitions>

		<Rectangle Fill="Red"
				   Height="30"
				   toolkit:VisibleBoundsPadding.PaddingMask="Top" />

		<CommandBar Content="Jokes"
					FontSize="24"
					Grid.Row="1"
					toolkit:VisibleBoundsPadding.PaddingMask="Top"
					Background="Blue"
					x:Uid="DadJokesPage_CommandBar" />
	</Grid>
</Page>
```

### Workaround

none found

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

uno.ui 4.2.6

### Affected platforms

iOS

### IDE

Visual Studio 2022

### IDE version

17.1.0

### Anything else we need to know?

![image](https://user-images.githubusercontent.com/17101674/165817469-8641ec3f-af3a-4af1-b613-fe9212483ef2.png)

**Comment by jeromelaban** [comment] 2022-04-28 19:06
Is the red rectangle shown even if the `CommandBar` is replaced by something else (but still with the visible bounds padding) ? Also, did you see it working in a previous uno version ?

**Comment by Guidemarcus** [comment] 2022-04-28 20:45
two rectangles, one on top of the other, are shown properly. Meaning I see them both

**Comment by jeromelaban** [comment] 2022-04-28 20:53
The padding property affects the contents of the command bar, not the background of the command bar. This issue is likely a duplicate of https://github.com/unoplatform/uno/issues/8650.

**Comment by francoistanguay** [comment] 2022-11-22 16:57
@kazo0  Is this even allowed in the Native Frame presenter?

**Comment by kazo0** [comment] 2022-11-22 17:25
You can't place anything above the native UINavigationBar that is rendered on the screen. You can have element behind the nav bar but you'd be leaving the bounds of the page if you wanted to go above the nav bar

**Comment by francoistanguay** [comment] 2023-01-03 20:11
Assume we can close this as it is not allowed by iOS.

**Closed by francoistanguay** 2023-01-03 20:11 UTC
Labels: kind/bug, platform/ios, triage/untriaged, difficulty/tbd
