### ISSUE TITLE
[Skia, WASM] Dialog (ShowAsync()) in MainPage.Loaded event

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#15207] opened 2024-01-25 09:09 UTC
## Current behavior
Calling `ContentDialog.ShowAsync()` in `MainPage.Loaded` event  does not showing dialog after app started (Only in Wasm project).

## Expected behavior

ContentDialog should be displayed.

## How to reproduce it (as minimally and precisely as possible)

Create project with blank Uno app  template and add code in MainPage.xaml.cs:
```
        public MainPage()
        {

            this.InitializeComponent();
            this.Loaded += async (s, a) =>
            {
                var dialog = new ContentDialog();
				dialog.XamlRoot = this.XamlRoot;
                await dialog.ShowAsync();
            };
       }
```

## Workaround

simple `await Task.Delay(1000); ` before calling  `await dialog.ShowAsync();` solve this issue

**Comment by Youssef1313** [comment] 2024-01-25 10:39
Looks like a duplicate of https://github.com/unoplatform/uno/issues/4550.

This should get fixed with lifecycle changes

**Comment by MartinZikmund** [comment] 2024-01-25 11:25
Yes, I separated the Skia WASM part from it so this one can be linked to your PR and closed with it

**Comment by MartinZikmund** [comment] 2024-01-25 11:25
I presume there is no good way to cover this with a test though, right?

**Comment by Youssef1313** [comment] 2024-01-25 12:20
> I presume there is no good way to cover this with a test though, right?

Maybe we could rely on the other lifecycle-related tests which could be covering the root cause of why ContentDialog doesn't work currently, even if not testing the specific exact scenario for ContentDialog

**Comment by morning4coffe-dev** [comment] 2024-06-04 12:09
@MartinZikmund @Youssef1313 Tested on all platforms (except iOS) with the `Uno.Sdk 5.3.0-dev.1827`, the issue seems to be fixed now.

**Closed** 2024-06-04 13:33 UTC
Labels: area/skia ✏️, project/navigation-lifecycle 🧬
