### ISSUE TITLE
[Skia] Chinese texts are not showing correctly for Skia.Gtk app

### ISSUE THREAD

**Issue by fergus-repo** [unoplatform/uno#8109] opened 2022-02-16 13:25 UTC
### Current behavior

![图片](https://user-images.githubusercontent.com/29976920/154270298-d98061c7-bb17-4b6f-aa2e-04856330a51b.png)

As shown in the exaple, when I build for Skia.Gtk, the chinese words does not showing correctly. Also have tried to save the XAML as UTF8 with signature, still has the same issue.

![图片](https://user-images.githubusercontent.com/29976920/154270776-0732e52d-6994-4407-9680-d89edd080a77.png)

If building for UWP or WSAM, the chinese words are showing correctly.

I am using VS 2022 17.0.6 with Uno 4.0.11.9

Could you have a look? Thanks.

### Expected behavior

The chinese words should show correctly.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### IDE version

17.0.6

**Comment by fergus-repo** [comment] 2022-02-16 15:11
Hello, which package to install?

I have tried to install these two packages in VS 2022:
PM> Install-Package Uno.UI.Skia.Gtk -Version 4.2.0-dev.73
PM> Install-Package Uno.UI.Lottie -Version 4.2.0-dev.73

Run again, and still have the issue.

**Comment by jeromelaban** [comment] 2022-02-16 15:16
Thanks, this means this is still an issue, and is a duplicate of this one: https://github.com/unoplatform/uno/issues/6973.

**Closed by jeromelaban** 2022-02-16 15:16 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
