### ISSUE TITLE
[Gallery][Skia.gtk/Wasm]SwipeControl- The word 'Accept' is truncating and word 'Open' and mail symbol are not visible.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#11541] opened 2023-03-02 04:06 UTC
### Current behavior

![swipecontrol issue 1](https://user-images.githubusercontent.com/74563602/222326896-5e187a33-c7a0-4c94-a498-2e5f4b9010ce.png)
![swipecontrol issue 2](https://user-images.githubusercontent.com/74563602/222326906-ce3c16fa-bbe1-43ce-9206-8144053f264c.png)
![swipecontrol issue 3](https://user-images.githubusercontent.com/74563602/222328181-6d0f4908-c11e-4269-abc9-42917d567a1a.png)

### Expected behavior

![swipecontrol correct 1](https://user-images.githubusercontent.com/74563602/222327238-954cd08f-68a7-4fa5-9dee-5ac123363949.png)
![swipecontrol correct 2](https://user-images.githubusercontent.com/74563602/222328367-19d232f5-3146-42ab-83c2-ca4237df7bea.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right.
3. Click "SwipeControl" from the "UI Components" list.
4. Swipe right side on the 'Swipe right' option.
5. Notice the 'Accept' word is truncating.
6. Go to 'Custom swipe in a ListView' option.
7. swipe right on any of the swipe Item.
8. Observe that the word 'Open' and the 'Mail symbol' are not visible.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Skia (GTK on Linux/macOS/Windows)

**Comment by Youssef1313** [comment] 2023-10-10 13:18
Duplicate of https://github.com/unoplatform/uno/issues/13360

**Closed by Youssef1313** 2023-10-10 13:18 UTC
Labels: kind/bug, platform/wasm 🌐, project/layout 🧱, area/canary 🐤, difficulty/medium 🤔, platform/gtk
