### ISSUE TITLE
`set` not called by binding process on a custom dependency property of a custom control  

### ISSUE THREAD

**Issue by christianfo** [unoplatform/uno#14504] opened 2023-11-21 21:24 UTC
### Current behavior

I have a custom control derived from `UserControl` with a custom dependency property `Text`. 
```
    public sealed partial class MyUserControl : UserControl
    {
        public MyUserControl()
        {
            this.InitializeComponent();
        }

        public string Text
        {
            get => (string)GetValue(TextProperty);
            set => SetValue(TextProperty, value); 
        }

        public static readonly DependencyProperty TextProperty =
            DependencyProperty.Register(nameof(Text), typeof(string), typeof(MyUserControl), new PropertyMetadata(""));
    }
}
```
My main page contains an instance of that control with the dependency property bound to a property in the main page code-behind:
```
     <local:MyUserControl Text="{x:Bind MyText, Mode=OneWay}"/>
```
with the main page code behind looking like this:
```
        public string MyText
        {
            get => text;
            set
            {
                text = value; 
                OnPropertyChanged(nameof(MyText)); 
            }
        }
        string text;

        public event PropertyChangedEventHandler? PropertyChanged;
        public void OnPropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }
```
On Windows, the `Text` dependency property setter is called whenever 'MyText` value changes. 
On Android and WASM, the `Text` property setter is never called. The value of that property appears to be correctly set internally in the binding code, but any code you may have in the setter is never run.

### Expected behavior

The setter (`set`) of the custom dependency property of my custom control to be called as part of the binding process, as it is when running the same code on Windows.  

### How to reproduce it (as minimally and precisely as possible)

[UnoApp8.zip](https://github.com/unoplatform/uno/files/13430976/UnoApp8.zip)

Custom control XAML:
```
<UserControl
    x:Class="UnoApp8.MyUserControl"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:UnoApp8">

    <StackPanel>
        <TextBox x:Name="TextBox"/>
        <TextBlock x:Name="CountBox"/>
    </StackPanel>
</UserControl>
```
Custom control code behind, with the `Text` dependency property. To make the repro easy, the `set` code sets the text in `TextBox` and shows how many times it is called in `CountBox`.
```
namespace UnoApp8
{
    public sealed partial class MyUserControl : UserControl
    {
        public MyUserControl()
        {
            this.InitializeComponent();
        }

        private int Count = 0;

        public string Text
        {
            get => (string)GetValue(TextProperty);
            set
            { 
                SetValue(TextProperty, value); 
                Count++;
                TextBox.Text = Text;
                CountBox.Text = $"set called {Count} time(s)";
            }
        }

        public static readonly DependencyProperty TextProperty =
            DependencyProperty.Register(nameof(Text), typeof(string), typeof(MyUserControl), new PropertyMetadata(""));
    }
}
```
The main page contains and instance of my custom control, and a button to set `MyText` and trigger the binding. 
```
<Page
    x:Class="UnoApp8.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:UnoApp8">
    <StackPanel HorizontalAlignment="Center" VerticalAlignment="Center">
        <Button Click="OnClick" Content="Click to set 'Some Text!'"/>
        <local:MyUserControl Text="{x:Bind MyText, Mode=OneWay}"/>
    </StackPanel>
</Page>
```
And the main page code-behind with the source property of the binding (`MyText`) looks like this:
```
using System.ComponentModel;

namespace UnoApp8
{
    public sealed partial class MainPage : Page, INotifyPropertyChanged
    {
        public MainPage()
        {
            this.InitializeComponent();
        }

        public string MyText
        {
            get => text;
            set
            {
                text = value; 
                OnPropertyChanged(nameof(MyText)); 
            }
        }
        string text;

        public event PropertyChangedEventHandler? PropertyChanged;
        public void OnPropertyChanged(string propertyName)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        public void OnClick(object sender, RoutedEventArgs e)
        {
            MyText = "Some Text!";
            System.Diagnostics.Debug.Assert(MyControl.Text == "Some Text!");
        }
    }
}
```
When running this example on Windows, clicking the button makes "Some text!" appears in `TextBox` and `CountBox` records the number of times `set` was called. Also note that `set` is called once with a `null` value at initialization.

When running this example in Android, the text does not appear in `TextBox` and no call to `set` is recorded. Note that the value of `MyText` is set internally by the binding code, as asserted is `OnClick`.

I tried changing `MyText` to a dependency property instead of using `INotifyPropertyChanged` but that did not fix the issue.

### Workaround

I expect to be able to use the property change callback on the dependency property and run the same code than I would have run in the setter. I will be confirming that this works indeed. 

### Works on UWP/WinUI

None

### NuGet package version(s)

    <PackageVersion Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
    <PackageVersion Include="Microsoft.Windows.Compatibility" Version="7.0.5" />
    <PackageVersion Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.22621.756" />
    <PackageVersion Include="Microsoft.WindowsAppSDK" Version="1.4.231008000" />
    <PackageVersion Include="Uno.Core.Extensions.Logging.Singleton" Version="4.0.1" />
    <PackageVersion Include="Uno.Extensions.Logging.OSLog" Version="1.7.0" />
    <PackageVersion Include="Uno.Extensions.Logging.WebAssembly.Console" Version="1.7.0" />
    <PackageVersion Include="Uno.Resizetizer" Version="1.2.1" />
    <PackageVersion Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="5.0.48" />
    <PackageVersion Include="Uno.UniversalImageLoader" Version="1.9.36" />
    <PackageVersion Include="Uno.Wasm.Bootstrap" Version="8.0.4" />
    <PackageVersion Include="Uno.Wasm.Bootstrap.DevServer" Version="8.0.4" />
    <PackageVersion Include="Uno.Wasm.Bootstrap.Server" Version="8.0.4" />
    <PackageVersion Include="Uno.WinUI" Version="5.0.48" />
    <PackageVersion Include="Uno.WinUI.Lottie" Version="5.0.48" />
    <PackageVersion Include="Uno.WinUI.DevServer" Version="5.0.48" />
    <PackageVersion Include="Uno.WinUI.WebAssembly" Version="5.0.48" />
    <PackageVersion Include="Xamarin.Google.Android.Material" Version="1.10.0.1" />

### Affected platforms

WebAssembly, Android

### IDE version

VS 17.7.6

### Anything else we need to know?

I have only tried this on Windows, Android, and WASM

**Comment by Youssef1313** [comment] 2023-11-22 03:15
Looks like a duplicate of https://github.com/unoplatform/uno/issues/9886 ?

**Comment by jeromelaban** [comment] 2023-11-22 13:38
@Youssef1313 indeed, it's a duplicate. Thanks for the report!

**Closed by jeromelaban** 2023-11-22 13:38 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
