### ISSUE TITLE
Using an x:Name on a UserControl in order to bind a custom dependency property is not working

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno#201] opened 2018-09-18 15:25 UTC
## I'm submitting a...

- Bug report (I searched for similar issues and did not find one)

## Current behavior
Using an x:Name on a UserControl in order to bind a custom dependency property is not working

## Expected behavior
The binding should work like for UWP

## Minimal reproduction of the problem with instructions
*STEPS TO REPRODUCE* : 
- Create a UserControl with some XAML code
- Create a custom dependency property in the UserControl's code behind
- Add an x:Name on the UserControl in the XAML
- Try to bind the custom dependency property in the code by using ElementName referring to the x:Name you just created

## Environment

```
Nuget Package: Uno.UI 1.40.0-dev.398

Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x] 2017 (version: 15.5.7)
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

No relevant plugins
```
## Screenshots

- UserControl
![image](https://user-images.githubusercontent.com/16295702/45696399-88efab00-bb31-11e8-82a8-bd9bed7baeb5.png)

![image](https://user-images.githubusercontent.com/16295702/45697334-94dc6c80-bb33-11e8-879d-58d63e1c98d0.png)

- UserControl Code Behind
![image](https://user-images.githubusercontent.com/16295702/45697663-4c717e80-bb34-11e8-94c6-07e0ff0a4250.png)

- Using the UserControl
![image](https://user-images.githubusercontent.com/16295702/45697975-f94bfb80-bb34-11e8-89f8-909987676ef0.png)

**Comment by jeromelaban** [comment] 2020-01-20 14:14
This issue is a duplicate of https://github.com/unoplatform/uno/issues/61, a workaround is available in that issue (`UnoSkipUserControlsInVisualTree`).

**Closed by jeromelaban** 2020-01-20 14:14 UTC
Labels: kind/bug, triage/most-wanted
