### ISSUE TITLE
ImageIcon doesn't render on Android and WPF

### ISSUE THREAD

**Issue by Strypper** [unoplatform/uno#9238] opened 2022-07-10 17:57 UTC
### Current behavior

```
<NavigationViewItem Content="{x:Bind Content}">
    <NavigationViewItem.Icon>
        <ImageIcon Source="{x:Bind ImageIconSource,
                                   Mode=OneWay}"/>
    </NavigationViewItem.Icon>
</NavigationViewItem>
```
WinUI 3: Render correct
WASM: Render correct
Android: Image not visible
WPF: Image not visible

WinUI 3 and WASM: 
![image](https://user-images.githubusercontent.com/32596308/178156453-686d5cb7-869b-473d-8ef9-df27d244b044.png)
Android:
![image](https://user-images.githubusercontent.com/32596308/178156479-0e4b4659-3042-4a30-b5d2-3291ac018186.png)

Project repo: [Pixel Art](https://github.com/Strypper/PixelArt)

### Expected behavior

WinUI 3: Render correct
WASM: Render correct
Android: Render correct
WPF: Render correct

### How to reproduce it (as minimally and precisely as possible)

User ImageIcon

### Workaround

No workaround

### Works on UWP/WinUI

Yes

### NuGet package version(s)

Latest Uno Platform version

### IDE

Visual Studio 2022

### IDE version

Preview

**Comment by MartinZikmund** [comment] 2022-07-29 09:00
This is caused by https://github.com/unoplatform/uno/issues/1982, which is currently in progress.

**Comment by MartinZikmund** [comment] 2022-11-10 06:11
This is now fixed

**Closed by MartinZikmund** 2022-11-10 06:11 UTC
Labels: kind/bug, project/media, difficulty/medium
