### ISSUE TITLE
[Gallery] Listing issue - Multiple controls display as selected in the Navigation view.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#7327] opened 2021-10-13 19:44 UTC
### Current behavior

![multiple selection gallery](https://user-images.githubusercontent.com/74563602/137202020-ca25487b-82bf-40cf-a7c6-2d1f41fab745.png)

### Expected behavior

Only the selected controls should display as Selected.

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Click Burger Menu on the left top right .
3. Click on multiple controls on the "component" list..
4. Observe that multiple controls display as selected in the Navigation view.

### Affected platforms

Android

**Comment by sakshi173** [comment] 2022-03-09 17:19
I repro this bug  with latest canary build and the issue is still present. 
Below are the screenshot and video from the latest canary build.
![Navigation issue](https://user-images.githubusercontent.com/74563602/157494479-01e29d64-cbeb-49a3-92df-47afb890682a.png)


https://user-images.githubusercontent.com/74563602/157495506-a239ccc6-7265-4ab4-a6b0-8192a248027b.mp4

**Comment by dr1rrb** [comment] 2023-01-26 16:29
This should have been fixed now, could you please validate if the issue is still present @sakshi173 ?

**Comment by sakshi173** [comment] 2023-01-30 19:49
Hi  @dr1rrb , I retested this bug and it is still present. Below is the screenshot from the current build.
![multiple controls](https://user-images.githubusercontent.com/74563602/215579592-4f92deac-3c15-48ad-919a-6b5edf0ea663.png)

**Comment by MartinZikmund** [comment] 2023-05-01 10:55
@sakshi173 can you check this in the latest canaries after the fix by @dr1rrb in #11966?

**Comment by sakshi173** [comment] 2023-05-12 13:51
@jeromelaban, I retest this issue and still it is present for Android and iOS platform, currently not able to verify for WASM build. Below is the screenshot from the latest canary build.
![multiple navigation display issue](https://github.com/unoplatform/uno/assets/74563602/4fbef5ee-eee2-494b-b705-f647b4a9f720)

**Comment by jeromelaban** [comment] 2023-05-12 20:42
Today's build is using 4.9.0-dev.1033, which is a bit "old", but later changes should not have any impact on this particular behavior @MartinZikmund @dr1rrb

**Closed** 2023-06-13 06:52 UTC
Labels: kind/bug, platform/android, area/skia, area/canary, difficulty/tbd, triage/potentially-fixed, project/themes-toolkit-gallery
