### ISSUE TITLE
Accept capitalized y/n in uno check

### ISSUE THREAD

**Issue by elibroftw** [unoplatform/uno#11221] opened 2023-02-07 04:07 UTC
## What would you like to be added:

Capital Y and capital N should be valid input for the y/n prompts in uno-check. 

## Why is this needed:

Subsciously used to typing with a capital letter plus the standard is Y/n for most cli tools implying that capital letters are accepted. 

## For which Platform:

- [ ] WebAssembly
- [ ] Android
- [ ] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [x] Windows
- [x] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

Yes the prompt should also need to updated to be [Y/n] from the current [y/n] to reflect the change that capital Y is a valid input.

**Comment by Youssef1313** [comment] 2023-02-07 08:36
Duplicate of https://github.com/unoplatform/uno.check/issues/121

**Closed by Youssef1313** 2023-02-07 08:36 UTC
Labels: kind/enhancement, triage/untriaged, difficulty/tbd
