### ISSUE TITLE
[Android] ComboBox does not work inside ContentDialogs

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#7285] opened 2021-10-05 19:06 UTC
### Current behavior

Clicking on the `ComboBox` to bring up the popup with the list of items does not work when it is inside a `ContentDialog`.

### How to reproduce it (as minimally and precisely as possible)

Put a `ComboBox` inside a `ContentDialog` and notice it does not work.

### Works on UWP/WinUI

Yes

### NuGet package version(s)

Uno.UI 3.11.0-dev.290

### Affected platforms

Android

**Comment by jeromelaban** [comment] 2021-10-06 12:41
Thanks for the report this is a duplicate of #2533. Can you validate that the workaround provided there works for you ?

**Closed by jeromelaban** 2021-10-06 12:41 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd

**Comment by mikernet** [comment] 2021-10-06 14:57
@jeromelaban That does not appear to have any effect. I did:

```cs
        protected override void OnLaunched(LaunchActivatedEventArgs e)
        {
            #if __ANDROID__
            Uno.UI.FeatureConfiguration.Popup.UseNativePopup = false;
            #endif
     
            // rest of launch init...
        }
```

Is that correct?

**Comment by mikernet** [comment] 2021-10-06 15:07
Alright, seems to be good now :)
