### ISSUE TITLE
[Android] Native combobox not opening when placed in contentDialogs

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno#11000] opened 2023-01-18 16:18 UTC
### Current behavior

![comboboxAndroid](https://user-images.githubusercontent.com/90481654/213227255-582932a9-6fe6-4a55-8668-cae6cdc4fc48.gif)

The combobox doesnt open.

### Expected behavior

![comboboxWindows](https://user-images.githubusercontent.com/90481654/213227706-b2699930-5ed1-4d1c-b8f8-e7133bb121c4.gif)
It should open like in windows.

### How to reproduce it (as minimally and precisely as possible)

[nativecombobox.zip](https://github.com/unoplatform/uno/files/10448368/nativecombobox.zip)

### Workaround

We can leave this: Uno.UI.FeatureConfiguration.Popup.UseNativePopup = true;
at false (the default state).
But, then we have this issue: https://github.com/unoplatform/uno/issues/10339

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

```
<PackageReference Include="Uno.WinUI" Version="4.6.39" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="4.6.39" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.6.39" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
    <PackageReference Include="Uno.WinUI.Lottie" Version="4.6.39" />
```

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

Version 17.4.1

### Anything else we need to know?

Issue is present on latest pre-release as well.

**Comment by Youssef1313** [comment] 2023-01-18 16:29
Duplicate of https://github.com/unoplatform/uno/issues/1583

**Comment by jeromelaban** [comment] 2023-01-18 16:50
It is indeed a duplicate. You can try the workaround and let us know.

**Closed** 2023-01-18 16:49 UTC
Labels: kind/bug, triage/duplicate, triage/untriaged, difficulty/tbd

**Comment by Marc-Antoine-Soucy** [comment] 2023-01-20 14:04
@jeromelaban  Yeah, I should have looked further in the past, and I would have found the issue. And yes, the workaround does work, but as mentioned in the issue, we would have prefer to not use the workaround because of this issue: https://github.com/unoplatform/uno/issues/10339.
