### ISSUE TITLE
Unable to LocalSettings in App ctor in Android

### ISSUE THREAD

**Issue by NGame1** [unoplatform/uno#1879] opened 2019-10-17 07:05 UTC
#Current behavior

        System.Reflection.TargetInvocationException: 'Exception has been thrown by the target of an invocation.'
on this line of my code
`        private static ApplicationDataContainer AppSettings => ApplicationData.Current.LocalSettings;
`when I'm calling it from ctor of App
```
        public App()
        {
            this.InitializeComponent();
            //Uno.UI.Toolkit.VisibleBoundsPadding.WindowPadding = Uno.UI.Toolkit.VisibleBoundsPadding.PaddingMask.Bottom;
            this.Suspending += OnSuspending;
            this.UnhandledException += App_UnhandledException;
            JsonConvert.DefaultSettings = () => new JsonSerializerSettings
            {
                PreserveReferencesHandling = PreserveReferencesHandling.Objects,
                Formatting = Formatting.Indented,
                ReferenceLoopHandling = ReferenceLoopHandling.Serialize,
                TypeNameHandling = TypeNameHandling.All
            };
            if (AppSettingsHelper.ApplicationTheme != 2)
            {
                if (AppSettingsHelper.ApplicationTheme == 0)
                    RequestedTheme = ApplicationTheme.Dark;
                else
                    RequestedTheme = ApplicationTheme.Light;
            }
        }
```

Nuget Package:

Package Version(s):

Affected platform(s):

- [ ] iOS (Not tested)
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows (Fine) 
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

**Comment by ghuntley** [comment] 2019-10-17 07:06
👋 confirmed. Tracking a fix over at https://github.com/unoplatform/uno/pull/1790.

**Comment by ghuntley** [comment] 2019-10-17 07:06
Closing as duplicate of https://github.com/unoplatform/uno/issues/1741

**Closed by ghuntley** 2019-10-17 07:06 UTC
Labels: kind/bug, triage/untriaged
