### ISSUE TITLE
Incorrect generation location for android string resources

### ISSUE THREAD

**Issue by BrianDT** [unoplatform/uno#4058] opened 2020-09-16 12:00 UTC
## Current behavior

If you have a development environment with a folder name that matches a language code for example D:\Development\SI\dev\’project’\’project’.Droid\ then the resource generation process creates obj\Debug\100\res\values-si folder for the resources_resw-strings.xml file containing the default en string values from D:\Development\SI\dev\’project’\’project’.Shared\Strings\en\Resources.resw. This means the strings are not found when the build runs in a English language environment.

## Expected behavior

The resources_resw-strings.xml should be generated to the obj\Debug\100\res\values folder

## How to reproduce it (as minimally and precisely as possible)

Create a project in a folder containing a to letter parent folder

## Workaround

Change the name of your development environment folder

## Environment

Nuget Package:

- [x ] Uno.UI 
Nuget Package Version(s):
3.0.17
Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

**Comment by MartinZikmund** [comment] 2021-06-02 11:30
Duplicate of #4657

**Closed by MartinZikmund** 2021-06-02 11:30 UTC
Labels: area/build, difficulty/tbd, kind/bug, platform/android, project/core-tools
