### ISSUE TITLE
MessageDialog on Android causes exception when user clicks outside dialog box

### ISSUE THREAD

**Issue by vskotatko** [unoplatform/uno#5114] opened 2021-02-02 22:15 UTC
## Current behavior

MessageDialog on Android causes exception when user clicks outside dialog box. On UWP, outside clicks are ignored.

Build and test this minimal app:
github.com/vskotato/MinMessage

## Workaround

None.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.0 preview 3.0)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

## Anything else we need to know?

System.NullReferenceException
  Message=Object reference not set to an instance of an object.

Stack Trace:
0xFFFFFFFFFFFFFFFF in System.Diagnostics.Debugger.Mono_UnhandledException_internal
0x1 in System.Diagnostics.Debugger.Mono_UnhandledException at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/corlib/System.Diagnostics/Debugger.cs:125,4

0x20 in Android.Runtime.DynamicMethodNameCounter.2

0x12 in System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:157,13

0x6 in System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__7_0 at /Users/builder/jenkins/workspace/archive-mono/2020-02/android/release/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1021,49

0xC in Android.App.SyncContext. at /Users/builder/azdo/_work/278/s/xamarin-android/src/Mono.Android/Android.App/SyncContext.cs:36,19

0xE in Java.Lang.Thread.RunnableImplementor.Run at /Users/builder/azdo/_work/278/s/xamarin-android/src/Mono.Android/Java.Lang/Thread.cs:36,6

0x8 in Java.Lang.IRunnableInvoker.n_Run at /Users/builder/azdo/_work/278/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-29/mcw/Java.Lang.IRunnable.cs:84,4

0x11 in Android.Runtime.DynamicMethodNameCounter.2

**Comment by jeromelaban** [comment] 2021-02-03 13:01
Thank you for the report.

The issue is that the returned value of the `ShowDialog` method can return null when dismissing the dialog:

![image](https://user-images.githubusercontent.com/5839577/106750421-d3d0c700-65f5-11eb-9ca6-c1ed9d649bfc.png)

You'll need to ensure that you perform null checking on the return value.

In order to catch those exceptions, you'll need to check the `Common Language Runtime Exceptions` box here:

![image](https://user-images.githubusercontent.com/5839577/106750591-07135600-65f6-11eb-9d7d-a266607bd1be.png)

**Comment by vskotatko** [comment] 2021-02-03 18:02
While I would never argue against checking for null or providing exception handling, please be aware that the Uno behavior is explicitly different from UWP. As evidence, please look at this example, provided by Microsoft:
[CompletedCallback.xaml.cs](https://github.com/microsoft/Windows-universal-samples/blob/master/Samples/MessageDialog/cs/CompletedCallback.xaml.cs)

Notice that they do not check for null and directly dereference the return value. Further, the documentation gives no mention of a possible null return value.

**Comment by jeromelaban** [comment] 2021-02-03 20:02
Indeed, the behavior is not the same, I'll keep the issue opened. In the meantime, you can validate for null as a workaround.

**Comment by vskotatko** [comment] 2021-02-03 22:02
Yes, I verified that checking for null is a workaround.

**Comment by Youssef1313** [comment] 2021-08-09 18:14
I think fixing https://github.com/unoplatform/uno/issues/1950 (being done in #6654) will also fix this issue. Can you confirm @jeromelaban ?

**Comment by jeromelaban** [comment] 2021-08-09 20:03
@Youssef1313 it may, let's retry with the sample once merged.

**Comment by Youssef1313** [comment] 2021-09-08 19:54
@vskotatko Can you try with the latest dev version? (currently `3.10.0-dev.685`)

**Comment by vskotatko** [comment] 2021-09-08 21:43
@Youssef1313 Eventually, I can try, but it will be a while. Thanks for addressing this.

**Comment by jeromelaban** [comment] 2022-01-27 18:56
Let's close this issue. You can reopen if it still happens.

**Closed by jeromelaban** 2022-01-27 18:56 UTC
Labels: kind/bug, project/input, difficulty/starter, area/eu
