### ISSUE TITLE
[Gallery][Android/iOS]ProgressRing/Bar and Lottie- ProgressRing, Bar and Lottie are missing.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#9658] opened 2022-08-29 20:24 UTC
### Current behavior

![Progressring- Photos](https://user-images.githubusercontent.com/74563602/187290563-dd669e4c-7457-40d2-b8d6-8e234ed2ed3f.png)
![Lottie](https://user-images.githubusercontent.com/74563602/187290574-8cf222ec-8132-4ebe-88bf-3e465ae0ae3d.png)

### Expected behavior

![Progressring correct](https://user-images.githubusercontent.com/74563602/187290901-eeddadd1-9ac0-43ac-b666-aec4dd1111dd.png)
![Lottie Correct](https://user-images.githubusercontent.com/74563602/187290914-85271fc8-c52d-487d-b0e6-6ea6c8b7c657.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "ProgressRing/Bar" from the "Component" list.
4. Observe that all ProgressRing and ProgressBare are missing.
5. Tap "Lottie" from the "Features" list.
6. Click on Lottie.
7. Observe that the Lottie is missing.

### Affected platforms

iOS, Android

**Comment by jeromelaban** [comment] 2022-09-01 12:52
This issue is a duplicate of https://github.com/unoplatform/Uno.Gallery/issues/399, where the app needs to be migrated to WinUI first for Lottie to work on the canary. Lottie works on the production build at this time.

**Closed by jeromelaban** 2022-09-01 12:52 UTC
Labels: kind/bug, platform/android, platform/ios, triage/untriaged, area/canary, difficulty/tbd, project/themes-toolkit-gallery
