### ISSUE TITLE
`ToggleSwitch` requires an animation workaround

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#16483] opened 2024-04-26 14:31 UTC
### Current behavior

To resolve #9507 we added a workaround in the `ToggleSwitch` style. This workaround should not be needed.

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment] 2024-04-26 14:56
Duplicate of https://github.com/unoplatform/uno/issues/13325

These workarounds may not be needed already, but we need to verify.

**Closed** 2024-04-26 14:56 UTC
Labels: kind/bug, triage/duplicate, area/skia ✏️, project/animations 🎡, difficulty/medium 🤔
