### ISSUE TITLE
`ItemsRepeater` gets corrupted on scrolling when some items are invisible

### ISSUE THREAD

**Issue by ramezgerges** [unoplatform/uno#16992] opened 2024-06-04 10:23 UTC
### Current behavior

This is supposed to be a list of all the even numbers from 0 to 999.

https://github.com/unoplatform/uno/assets/66218781/b8ffba83-439d-41d9-9404-ed0014e239f0

### How to reproduce it (as minimally and precisely as possible)

```csharp
public sealed partial class MainPage : UserControl
{
      public MainPage()
      {
	      this.InitializeComponent();
	      ir.DataContext = Enumerable.Range(0, 1000).Select(i => new VM(i.ToString(), i % 2 == 0)).ToList();
      }
}

public class VM(string value, bool isVisible)
{
public string Value => value;
public bool IsVisible => isVisible;
}
```

```xaml
<ScrollViewer Height="400">
  <ItemsRepeater x:Name="ir" ItemsSource="{Binding}">
    <ItemsRepeater.ItemTemplate>
      <DataTemplate>
        <Border Visibility="{Binding IsVisible}">
          <TextBlock Text="{Binding Value}" />
        </Border>
      </DataTemplate>
    </ItemsRepeater.ItemTemplate>
  </ItemsRepeater>
</ScrollViewer>
```

### Works on UWP/WinUI

None

**Comment by ramezgerges** [comment] 2024-06-04 10:24
cc. @dr1rrb

**Comment by dr1rrb** [comment] 2024-06-06 12:32
This is a duplicate of https://github.com/unoplatform/uno/issues/16771.

**Closed by dr1rrb** 2024-06-06 12:32 UTC
Labels: kind/bug, triage/untriaged, area/items-repeater, difficulty/tbd
