### ISSUE TITLE
[Skia][ScrollViewer] You can scroll content out of bounds when the content is too small

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno#12542] opened 2023-06-05 19:28 UTC
### Current behavior

When there the space taken by the the content of the scrollviewer is too small compared to the space given by the scrollviewer, you can scroll the content out of bounds. It can happen Horizontally: 
![SkiaScrollBug](https://github.com/unoplatform/uno/assets/90481654/41b97a7a-c811-4f6b-8893-038d521b59f4)

And vertically: 
![SkiaScrollBugVertical](https://github.com/unoplatform/uno/assets/90481654/9596708e-8dd9-4e56-a2d4-7930f544f729)

### Expected behavior

![windowsaaa](https://github.com/unoplatform/uno/assets/90481654/20b70e1f-806a-4044-b83b-eec92085fc7d)
It should behave like on windows where you can't scroll when the content has enough space in the scrollviewer

### How to reproduce it (as minimally and precisely as possible)

[BasicApp.zip](https://github.com/unoplatform/uno/files/11656026/BasicApp.zip)
- Open the app
- Scroll horizontally
- See that items that don't take enough space can be scrolled out of the window. 

This is the important part of the code: 
```
<Page.Resources>
        <Style x:Key="HorizontalScrollViewerStyle" TargetType="ScrollViewer">
            <Setter Property="HorizontalScrollMode" Value="Auto" />
            <Setter Property="HorizontalScrollBarVisibility" Value="Auto" />
            <Setter Property="VerticalScrollMode" Value="Disabled" />
            <Setter Property="VerticalScrollBarVisibility" Value="Hidden" />
            <Setter Property="Margin" Value="0,10" />
        </Style>
    </Page.Resources>


    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="*"/>
            <RowDefinition Height="*"/>
            <RowDefinition Height="*"/>
            <RowDefinition Height="*"/>
        </Grid.RowDefinitions>
        
        <ScrollViewer Style="{StaticResource HorizontalScrollViewerStyle}">
            <StackPanel Orientation="Horizontal" Spacing="8">

                <TextBlock Text="Hello, Uno platform!" FontSize="40" />

            </StackPanel>
        </ScrollViewer>
        
        <ScrollViewer Style="{StaticResource HorizontalScrollViewerStyle}" Grid.Row="1">
            <StackPanel Orientation="Horizontal" Spacing="8">

                <TextBlock Text="Hello, Uno platform! Does this still " FontSize="40" />

            </StackPanel>
        </ScrollViewer>
        
        <ScrollViewer Style="{StaticResource HorizontalScrollViewerStyle}" Grid.Row="2">
            <StackPanel Orientation="Horizontal" Spacing="8">

                <TextBlock Text="Hello, Uno platform! Does this still happpen when the " FontSize="40" />

            </StackPanel>
        </ScrollViewer>
        
        <ScrollViewer Style="{StaticResource HorizontalScrollViewerStyle}" Grid.Row="3">
            <StackPanel Orientation="Horizontal" Spacing="8">

                <TextBlock Text="Hello, Uno platform! Does this still happpen when the text is very long?" FontSize="40" />

            </StackPanel>
        </ScrollViewer>
    </Grid>
```

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

```
		<PackageReference Include="Uno.Resizetizer" Version="1.1.0" />
		<PackageReference Include="Uno.WinUI.Skia.Gtk" Version="4.10.0-dev.111" />
		<PackageReference Include="SkiaSharp.Views.Uno.WinUI" Version="2.88.3" />
		<PackageReference Include="SkiaSharp.Skottie" Version="2.88.3" />
		<PackageReference Include="Uno.WinUI.RemoteControl" Version="4.10.0-dev.111" Condition="'$(Configuration)'=='Debug'" />
		<PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.10.0-dev.111" />
```

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### IDE version

17.6.0

### Anything else we need to know?

I tested on other platforms and this seems to only be an issue on skia.

Related issues: https://github.com/unoplatform/uno/issues/8947
https://github.com/unoplatform/uno/issues/11659

**Comment by jeromelaban** [comment] 2023-06-19 15:01
Duplicate of https://github.com/unoplatform/uno/issues/8947

**Closed by jeromelaban** 2023-06-19 15:01 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
