### ISSUE TITLE
[Wasm][SkiaSharp] RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#1451] opened 2019-08-30 18:26 UTC
## Current behavior

In random cases, the runtime fails to render SKXamlCanvas content with the following error `RuntimeError: memory access out of bounds`.

## Expected behavior
The rendering does not fail.

## How to reproduce it (as minimally and precisely as possible)

No clear repro steps.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):
- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

## Anything else we need to know?

This issue may be related to an issue coming from the mono runtime. An updated from https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/105 may help solve this issue.

**Comment by jeromelaban** [comment] 2019-10-02 20:56
The skiasharp nuget packages have been updated to include the latest changes from the official skiasharp repo. Could you take it for spin and see if it helps?

Thanks!

**Comment by NorekZ** [comment] 2019-12-01 11:43
Hello,

I have the same issue. My dependencies are:

Uno.SkiaSharp.Views (1.68.0-uno.290)
Uno.SkiaSharp.Wasm (1.68.0-uno.290)
Uno.UI (2.1.0-dev.26)
Uno.Wasm.Bootstrap (1.0.8)

Sometimes it works (e.g. in anonymous window) but usually my canvas is blank and this error is in Chrome console:
![image](https://user-images.githubusercontent.com/22442049/69913405-9132be00-1437-11ea-986e-c84e531b4963.png)

Tried also on my phone, canvas is blank.

Thanks in advance!

**Comment by jeromelaban** [comment] 2020-02-04 18:36
I've been testing the latest release of emscripten, and unfortunately there are other issues that have been introduced. While this fixes the compilation of `libSkia`, there are runtime failures: 

```
Uncaught (in promise) LinkError: WebAssembly.Instance(): Import #0 module="e" function="f" error: function import requires a callable
    at convertJsFunctionToWasm (http://localhost:50720/dotnet.js:1:11783)
    at addFunctionWasm (http://localhost:50720/dotnet.js:1:12315)
    at addFunction (http://localhost:50720/dotnet.js:1:12457)
    at obj.<computed> (http://localhost:50720/dotnet.js:1:9771)
    at wasm-function[14019]:0x520cc2
    at wasm-function[14018]:0x520580
    at callRuntimeCallbacks (http://localhost:50720/dotnet.js:1:23383)
    at initRuntime (http://localhost:50720/dotnet.js:1:24164)
    at doRun (http://localhost:50720/dotnet.js:1:7121553)
    at run (http://localhost:50720/dotnet.js:1:7121832)
```

That are caused by some "trampoline-like" feature which seem to lookup for wasm exports that do not exist (and are not supposed to, in this case `_ZN12GrGlyphCache14HandleEvictionEyPv` which is an internal class method).

We do not see this dynamic mode support having a stable enough future considering the updates history, so we'll change the approach by enabling Wasm builds on Windows, you can follow the issue here: https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/165.

**Comment by peternary** [comment] 2020-02-19 18:20
Still getting this issue, even with FullAOT enabled.  Was able to reproduce error message in attached project, though it appears that rendering continues in the sample.

[CanvasTest.zip](https://github.com/unoplatform/uno/files/4226635/CanvasTest.zip)

**Comment by DierkDroth** [comment] 2020-02-27 13:24
@jeromelaban any progress on this issue?

**Comment by jeromelaban** [comment] 2020-03-02 19:31
Yes I do have update. It seems that the issue is related to the way the GC is handling some of the Skia unmanaged references.

In your sample, you can do two things:
- Either extract the `SKPaint` instances out of the `OnPaintSurface`, or make sure to dispose all the instances at the end of the scope. (the `using var` feature of C# 8.0 may be handy there). In your app, you should do the same for all disposable SkiaSharp types.
- Avoid using `Threading.Timer`, and use `DispatcherTimer`. The former is using javascript directly and is somehow slower than the latter:
```
_t = new DispatcherTimer();
_t.Interval = TimeSpan.FromMilliseconds(200);
_t.Tick += delegate
{
	Invalidate();
};
_t.Start();
```

There is definitely an underlying issue with the way the GC works, I'll a smaller repro and create a new one to track it.

**Comment by DierkDroth** [comment] 2020-03-03 07:43
>> There is definitely an underlying issue with the way the GC works, I'll a smaller repro and create a new one to track it.

Thanks for checking into @jeromelaban. I definitely would appreciate if you followed up with the MONO community as needed. It would be great if you referenced a link in case you filed a dedicated MONO issue report.

**Comment by peternary** [comment] 2020-03-17 15:37
Appears working in latest update

**Comment by DierkDroth** [comment] 2020-03-17 17:01
@jeromelaban believe you could close this one. Thx

**Comment by jeromelaban** [comment] 2020-03-17 22:32
Thanks for the update!

**Comment by peternary** [comment] 2020-03-25 15:01
Am still getting issue in Interpreter build, though it now takes longer to occur.  Already using fixes suggested here.

**Comment by DierkDroth** [comment] 2020-03-25 15:06
@jeromelaban I suggest re-opening this until we see a final solution from SkiaSharp or Mono.

**Comment by peternary** [comment] 2020-04-17 22:06
Attached a sample that reproduces the issue fairly reliably on my system.  Start the attached project in WASM and it will usually exhibit the issue immediately.  If not, open developer tools and reload the page with the cursor over one of the canvases.

The issue seems to have varying severity between restarts of the site.  Was not able to reproduce the problem in UWP.

[App38.zip](https://github.com/unoplatform/uno/files/4495450/App38.zip)

**Comment by DierkDroth** [comment] 2020-04-20 12:42
@jeromelaban as per @peternary's tests this is not an 'interpreter only' issue but occurs on AOT - although less frequently - as well. This makes it even more critical...

**Comment by jeromelaban** [comment] 2020-04-20 14:31
Thank you for the update. We're still waiting for the finalization of the SkiaSharp update to move forward.

**Comment by jeromelaban** [comment] 2020-05-04 01:58
We've integrated the latest release of SkiaSharp and Skia m80 into Uno.SkiaSharp in https://github.com/unoplatform/Uno.SkiaSharp/pull/18, but issue still persists, even after the adjustments from https://github.com/mono/mono/pull/19671.

I've been able to extract a smaller repro from @peternary repro which does not involve Skia or SkiaSharp, and created https://github.com/mono/mono/issues/19684, which seems like a very precise memory corruption from a yet unknown location.

**Comment by DierkDroth** [comment] 2020-05-04 04:44
@jeromelaban thanks a lot for your continued efforts on this serious issue.

Good: great that you have been able to isolate the issue to being a MONO issue and Skia/SkiaSharp is not part of the equation
Bad (in fact very bad): that MONO WASM is struggling with serious memory management issues shortly before they wanted to release BLAZOR during BUILD this month.

**Comment by DierkDroth** [comment] 2020-05-04 04:52
@jeromelaban curious: have you been able to isolate the issue for INTERPRETER only or AOT as well? Note: @peternary got it on AOT as well - less frequently though.

**Comment by jeromelaban** [comment] 2020-05-04 11:56
I was not able to reproduce the issue with AOT more specifically, but it may be the same issue. The memory layout under Full AOT is very different from the one under the interpreter making the issue harder to reproduce.

**Comment by DierkDroth** [comment] 2020-05-04 12:19
Thanks for clarification @jeromelaban

**Comment by jeromelaban** [comment] 2020-05-05 16:47
The issue is being fixed in https://github.com/mono/mono/pull/19709, and we'll be making a bootstrapper build that takes this change into account (https://github.com/unoplatform/Uno.Wasm.Bootstrap/pull/204).

If there is a lingering issue in AOT, we'll address it separately.

**Comment by DierkDroth** [comment] 2020-05-05 16:52
Excellent! Thanks @jeromelaban. @peternary  will run tests as the build is available

**Closed** 2020-05-06 02:29 UTC
Labels: area/skia, area/wasm, kind/bug
