### ISSUE TITLE
[Android] Grid.Columns.TextBlock not inside Column 

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#4431] opened 2020-10-30 16:30 UTC
## Current behavior
TextBlock.Text from one Grid.Column is not wrapped (extends to next column)

## Expected behavior
TextBlock.Text is wrapped.

## How to reproduce it (as minimally and precisely as possible)

        <Grid>
            <Grid.ColumnDefinitions>
                <ColumnDefinition/>
                <ColumnDefinition/>
            </Grid.ColumnDefinitions>
            <StackPanel Grid.Column="0" VerticalAlignment="Center" >
                <TextBlock x:Uid="uiSetLinksInfo" Margin="10,5,0,10" HorizontalAlignment="Center" Text="(links would open Wikipedia page in default browser)" />
            </StackPanel>
            <StackPanel Grid.Column="1" VerticalAlignment="Center" >
                <win:TextBlock x:Uid="uiSetAddLang" HorizontalAlignment="Left" TextWrapping="Wrap" Margin="10,40,0,0" Text="If you want me to add another language, please use FeedBack Hub" VerticalAlignment="Top"/>
            </StackPanel>
   </Grid>

## Environment

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
3.1.6
Affected platform(s):

- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: 16.7.2)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment] 2024-05-22 18:16
I think this should be fixed, can some validate please?

**Comment by agneszitte** [comment] 2024-05-22 22:07
@Darsh0307 can you validate the repro mentioned in the issue with latest version please

**Comment by Darsh0307** [comment] 2024-05-24 13:40
"Uno.Sdk": "5.3.0-dev.1492"
Uno.Templates.5.3.0-dev.82
It was a blank template project created using 
Tested on Windows Unpackaged 


<img width="1065" alt="Screenshot 2024-05-24 at 6 57 02 PM" src="https://github.com/unoplatform/uno/assets/90713481/81a143eb-435c-4c5a-a920-b3a62e7843d4">

**Comment by agneszitte** [comment] 2024-05-24 13:57
> "Uno.Sdk": "5.3.0-dev.1492" Uno.Templates.5.3.0-dev.82 It was a blank template project created using cli Tested on Windows Unpackaged

@Darsh0307 we need to have the details of your test on Android here please (in addition to make sure it is behaving the same on the other platforms as well). Also make sure to test what is explained in the **Current behavior** VS **Expected result** please

**Comment by Darsh0307** [comment] 2024-05-28 15:25
Uno.Sdk: 5.3.0-dev.1526
Uno.Templates. 5.3.0-dev.82


The application was created using cli and blank template. 
It was able to run on winows unpackaged , Web assembly and Android. 
If we clearly see this screenshot it will look like that there is a text wrap. 




![Image](https://github.com/unoplatform/uno/assets/90713481/7a83b879-a889-4a22-a15d-5200a4fe944c)


[AndroidTextWrap.zip](https://github.com/unoplatform/uno/files/15472316/AndroidTextWrap.zip)

**Comment by Darsh0307** [comment] 2024-06-03 08:31
@MartinZikmund  , The issue is not resolved.

**Comment by MartinZikmund** [comment] 2024-06-04 06:51
@Darsh0307 It seems to me it is resolved - the expected behavior is that the text is wrapped, which seems to be the case? 🤔

**Comment by Darsh0307** [comment] 2024-06-04 07:18
@MartinZikmund  , If the above screenshot seems to be the one which is expected according to you. Then i beleive so that the issue is solved. 

And the ulimately we can close the issue

**Closed** 2024-06-04 07:36 UTC
Labels: kind/bug, area/textblock, project/text 🔤, difficulty/medium 🤔, triage/potentially-fixed
