### ISSUE TITLE
OnNavigatedTo break x:bind (WASM - WPF - ANDROID)

### ISSUE THREAD

**Issue by Strypper** [unoplatform/uno#9239] opened 2022-07-10 18:04 UTC
### Current behavior

Code:
```
protected override void OnNavigatedTo(NavigationEventArgs e)
{
    base.OnNavigatedTo(e);
    artViewModel = new ArtPageViewModel((int)e.Parameter);
}
```
```
public class ArtPageViewModel
{
    public ArtPageDTO PageInfo { get; set; } = new ArtPageDTO();
    public ArtPageViewModel(int ArtTypeKey)
    {
        PageInfo.ArtDesigns = DemoArtAssets.GetDemoArtAssets(ArtTypeKey);
    }
}
```
```
<GridView Grid.Row="1"
          Margin="0,15,0,0"
          HorizontalAlignment="Center"
          ItemsSource="{x:Bind artViewModel.PageInfo.ArtDesigns, Mode=OneWay}"
          ItemTemplateSelector="{StaticResource ArtTemplateSelectorTemplate}"/>
```
WinUI3: Gridview load all the item inside from artViewModel.PageInfo.ArtDesigns
WASM & WPF & Android: the opposite 
WinUI3:
![image](https://user-images.githubusercontent.com/32596308/178156638-1e8f036b-aac3-45f5-9e7f-9eeaa9d43a62.png)

WASM & WPF & Android:
![image](https://user-images.githubusercontent.com/32596308/178156618-e667f63e-d2f6-4695-abc8-a323fb73e075.png)

Test repo:
[Pixel Art](https://github.com/Strypper/PixelArt)

### Expected behavior

All platform should be able to bind the data on the gridview

### How to reproduce it (as minimally and precisely as possible)

Assign value to any prop inside OnNavigatedTo

### Workaround

No work around

**Comment by MartinZikmund** [comment] 2022-07-11 06:31
I expect the problem here is caused by lifecycle differences - specifically in case of some targets, `x:Bind` is evaluated before `OnNavigatedTo`, which causes the bindings not to work. A solution will be to move the `x:Bind` evaluation to later (after `OnNavigatedTo`), but only in case navigation actually occurs (`Page` is in a `Frame`). Another workaround would be to reevaluate the bindings, but that would be a problem for `OneTime` ones.

**Comment by Strypper** [comment] 2022-07-12 17:03
Temporary work around by hard code the gridview itemssource

**Comment by jeromelaban** [comment] 2022-08-01 15:30
This is a duplicate of https://github.com/unoplatform/uno/issues/2872

**Closed by jeromelaban** 2022-08-01 15:30 UTC
Labels: kind/bug, project/navigation-lifecycle, difficulty/challenging
