### ISSUE TITLE
[WASM] Autofilled text/password boxes do not update layout/color correctly

### ISSUE THREAD

**Issue by mikernet** [unoplatform/uno#7466] opened 2021-11-12 00:39 UTC
### Current behavior

Although this issue manifests when using the `Material` theme, I posted it here as I believe it is inherently a problem with `Uno.UI.WebAssembly` and not something wrong with the theme itself.

When using the `Material` theme in dark mode, if the first page has a username and password box that is auto-filled by the browser, it shows up like this:

![image](https://user-images.githubusercontent.com/1700111/141388378-6aef301a-c444-4e31-a6e0-c14e6e4d24c2.png)

Besides the color, the placeholder text labels also render on top of the email and password. Once you click anywhere on the page or on one of the boxes, it fixes itself:

![image](https://user-images.githubusercontent.com/1700111/141388580-5ffdd2c8-68d7-4d4d-b04e-1162ea9961b7.png)

Tested on Edge and Chrome.

### How to reproduce it (as minimally and precisely as possible)

Put this on the first page that Uno WASM loads on app start, on a site that has saved credentials that auto-fill when the page loads:

```xml
<TextBox Name="EmailBox" PlaceholderText="Email" IsSpellCheckEnabled="false" InputScope="EmailSmtpAddress" Style="{StaticResource MaterialFilledTextBoxStyle}"/>
<PasswordBox Name="PasswordBox" PlaceholderText="Password" Margin="0,30,0,0" Style="{StaticResource MaterialFilledPasswordBoxStyle}"/>
```

### Environment

Uno.UI.WebAssembly

### NuGet package version(s)

v3.10.11, v4.x-dev.latest

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment] 2021-11-12 01:17
Thanks. This is a duplicate of https://github.com/unoplatform/uno/issues/5737, which we cannot fix until browsers support notifying applications of this auto-fill.

**Closed by jeromelaban** 2021-11-12 01:17 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd

**Comment by mikernet** [comment] 2021-11-12 01:36
@jeromelaban Some searching reveals solutions that are working for people. Are none of the workarounds suitable for use here?

**Comment by mikernet** [comment] 2021-11-12 04:01
Is it possible to just disable autofill for the fields (i.e. apply `autocomplete="off"`)?
