### ISSUE TITLE
[Skia] Support for WebView control

### ISSUE THREAD

**Issue by litch0** [unoplatform/uno#4681] opened 2020-12-07 23:26 UTC
## Current behavior
WebView Does nothing on Gtk

Create asample application using `dotnet new unoapp -o MyUnoApp` add
```XML
<WebView x:Name="webView1" Source="http://www.contoso.com"/>

        <Button x:Name="btn1" Content="Hover to Click"
          Click="OnClick1"
          Margin="5" Width="150"/>
```
and
```
private void OnClick1(object sender, EventArgs e){
            webView1.Navigate(new Uri("http://www.google.com"));
            System.Console.WriteLine("DONE");
            System.Console.WriteLine(webView1.CanGoBack);
        }
```
and when The app start or I click the button, the webview should display the google home page

## Expected behavior
WebView does nothing
![image](https://user-images.githubusercontent.com/57605930/101417176-0ac27f00-38ca-11eb-9d69-8d7be475770c.png)
and the terminal gives:
```
dotnet run
/home/litch0/repo/MyRepos/MyUnoApp/MyUnoApp.Skia.Gtk/MyUnoApp.Skia.Gtk.csproj : warning NU1701: Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
/home/litch0/repo/MyRepos/MyUnoApp/MyUnoApp.Skia.Gtk/MyUnoApp.Skia.Gtk.csproj : warning NU1701: Package 'SkiaSharp.Views 2.80.0' was restored using '.NETFramework,Version=v4.6.1, .NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, .NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 'net5.0'. This package may not be fully compatible with your project.
warn: Uno.UI.Runtime.Skia.GtkHost[0]
      Loading icon file [/home/litch0/repo/MyRepos/MyUnoApp/MyUnoApp.Skia.Gtk/bin/Debug/net5.0/Assets/StoreLogo.png] from Package.appxmanifest file
fail: Windows.UI.Composition.CompositionObject[0]
      The member void CompositionObject.Dispose() is not implemented in Uno.
fail: Uno.UI.RemoteControl.RemoteControlClient[0]
      Failed to connect to the server (System.TimeoutException: The operation has timed out.
         at Uno.UI.RemoteControl.RemoteControlClient.StartConnection() in C:\a\1\s\src\Uno.UI.RemoteControl\RemoteControlClient.cs:line 127)
```
## Environment

Nuget Package:

- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

.Net Version:
 .netcoreapp5.0 version 5.0.100

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [X] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Rider linux (Latest nightly Build )
- [X] Visual Studio Code (version: Build it from latest source )

## Usefull ScreenShots
![image](https://user-images.githubusercontent.com/57605930/101417422-73a9f700-38ca-11eb-8407-c1554770832b.png)

**Comment by jeromelaban** [comment] 2020-12-08 17:01
Thanks for the report! 

The WebView control is not yet supported under Skia based backend. You can follow the overall support for Skia in https://github.com/unoplatform/uno/issues/4309

The technical challenge for this control is the ability to display a system control over a Skia rendered canvas, which is not something we have worked on at this point.

**Comment by litch0** [comment] 2020-12-09 20:25
ok, does it have any way around?

**Comment by jeromelaban** [comment] 2020-12-09 20:35
Not at this point, no.

**Comment by litch0** [comment] 2020-12-09 23:29
Ok

**Comment by MartinZikmund** [comment] 2021-06-02 07:06
Duplicate of #4681, please see that issue for tracking

**Closed by MartinZikmund** 2021-06-02 07:06 UTC
Labels: area/skia, difficulty/tbd, kind/enhancement, platform/linux, project/media
