### ISSUE TITLE
WPF: Button with Image inside does not render.

### ISSUE THREAD

**Issue by olivegamestudio** [unoplatform/uno#5371] opened 2021-03-02 13:15 UTC
Add an image into a button, works on UWP but not WPF.

## Current behavior

No image shown.

## Expected behavior

Expected to see an image.

## How to reproduce it (as minimally and precisely as possible)

<UserControl
    x:Class="BattleForce2249.TitlePlayButton"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:BattleForce2249"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:Interactivity="using:Microsoft.Xaml.Interactivity" xmlns:Interactions="using:Microsoft.Xaml.Interactions.Core" xmlns:Media="using:Microsoft.Xaml.Interactions.Media"
    mc:Ignorable="d"
    d:DesignHeight="197"
    d:DesignWidth="678">
    <UserControl.Resources>
    </UserControl.Resources>

    <Button x:Name="PlayButton" FocusVisualPrimaryThickness="0" FocusVisualSecondaryThickness="0"
            FocusVisualPrimaryBrush="Transparent" FocusVisualSecondaryBrush="Transparent"
            Width="678" Height="197" Click="Play_Click" Background="Transparent"
            BorderThickness="0">
        <Button.Template>
            <ControlTemplate TargetType="Button">
                <Image x:Name="PlayImage" Source="Assets/Titles/playbutton.scale-100.png">
                    <Image.Resources>
                        <Storyboard x:Name="ImageLoaded">
                            <DoubleAnimation Storyboard.TargetName="PlayImage" Storyboard.TargetProperty="Opacity" From="0" To="1" Duration="0:0:2" />
                            <ObjectAnimationUsingKeyFrames Storyboard.TargetName="PlayImage" Storyboard.TargetProperty="Source" Duration="0:0:2" RepeatBehavior="Forever">
                                <DiscreteObjectKeyFrame KeyTime="0:0:0">
                                    <DiscreteObjectKeyFrame.Value>
                                        <BitmapImage UriSource="Assets/Titles/playbutton.scale-100.png"/>
                                    </DiscreteObjectKeyFrame.Value>
                                </DiscreteObjectKeyFrame>
                                <DiscreteObjectKeyFrame KeyTime="0:0:1">
                                    <DiscreteObjectKeyFrame.Value>
                                        <BitmapImage UriSource="Assets/Titles/playbutton2.scale-100.png"/>
                                    </DiscreteObjectKeyFrame.Value>
                                </DiscreteObjectKeyFrame>
                            </ObjectAnimationUsingKeyFrames>
                        </Storyboard>
                    </Image.Resources>
                    <Interactivity:Interaction.Behaviors>
                        <Interactions:EventTriggerBehavior EventName="Loaded">
                            <Media:ControlStoryboardAction Storyboard="{StaticResource ImageLoaded}" ControlStoryboardOption="Play" />
                        </Interactions:EventTriggerBehavior>
                    </Interactivity:Interaction.Behaviors>
                </Image>
            </ControlTemplate>
        </Button.Template>
    </Button>
</UserControl>

## Workaround

None.

## Environment

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [X] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [X] Resharper (version: )

**Comment by kazo0** [comment] 2022-02-14 16:53
Hi @olivegamestudio! 

It seems like there is an issue with assets using the `.scale-###` suffix. While I investigate the issue, a quick workaround should be to just remove the `.scale-100` suffix in your Images.

**Comment by kazo0** [comment] 2022-02-16 14:16
Closing for now as I cannot reproduce and looks to be working with latest Uno

**Closed by kazo0** 2022-02-16 14:16 UTC
Labels: kind/bug, area/skia, project/media, difficulty/medium
