### ISSUE TITLE
`SettingsCard` does not render content

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#17311] opened 2024-06-26 08:10 UTC
### Current behavior

In latest version of Uno, `SettingsCard` content no longer renders:

![image](https://github.com/unoplatform/uno/assets/1075116/fb7c7517-fbe6-45be-b979-f3072ad6f469)

### Expected behavior

Should render

![image](https://github.com/unoplatform/uno/assets/1075116/66363381-cf9e-416b-bdb5-fa7ce5f60076)

### How to reproduce it (as minimally and precisely as possible)

1. Check out https://github.com/MartinZikmund/uno-bug-repros/tree/bug/settings-no-content
2. Run the app on any Skia target (with Uno.WinUI `5.4.0-dev.121`)

### Works on UWP/WinUI

None

**Comment by morning4coffe-dev** [comment] 2024-06-28 12:17
I can replicate this issue only on Skia (I updated the description for it) and very interestingly only when there is only one Control placed in the content: 
![image](https://github.com/unoplatform/uno/assets/78549750/bdec7ece-79a5-404b-a9e3-ade4681aa22a)

When I put a `StackPanel` with more items, I can no longer reproduce the issue: 
![image](https://github.com/unoplatform/uno/assets/78549750/e2897d46-8968-46d5-87a0-9b40e2600c8f)

**Comment by agneszitte** [comment] 2024-07-03 21:06
@jeromelaban, @MartinZikmund just a note that SettingsCard is use as an example for the WCT documentation
https://platform.uno/docs/articles/uno-community-toolkit-v8.html?tabs=singleproj
So best if we could prioritize to fix this issue I think

**Comment by morning4coffe-dev** [comment] 2024-07-08 10:17
@MartinZikmund @agneszitte The issue is a regression caused by changes in https://github.com/unoplatform/uno/pull/16834 ![image](https://github.com/unoplatform/uno/assets/78549750/6e0cb7d2-e458-4d92-a01e-8b0f6032f403). I also validated this with https://github.com/unoplatform/uno/pull/17223, but the issue still persists. I checked with @Youssef1313 on this, and there will need to be more investigation to properly fix this. For now, we could implement a workaround or add a note to the documentation (https://github.com/unoplatform/uno/pull/17374) for users to add a `Grid`/`StackPanel` before adding content to the `SettingsControl`.

**Comment by agneszitte** [comment] 2024-07-08 15:46
> @MartinZikmund @agneszitte The issue is a regression caused by changes in #16834 I also validated this with #17223, but the issue still persists. I checked with @Youssef1313 on this, and there will need to be more investigation to properly fix this. For now, we could implement a workaround or add a note to the documentation (#17374) for users to add a `Grid`/`StackPanel` before adding content to the `SettingsCard`.

Thank you a lot @morning4coffe-dev for all the details, appreciated.
I synced with @jeromelaban and @Youssef1313 will be able to investigate this issue as a priority since it is a regression.

**Comment by Youssef1313** [comment] 2024-07-09 12:24
The root cause here is that `FrameworkElement` is `IEnumerable`.

https://github.com/CommunityToolkit/Windows/blob/0bab2c0359ab33b7ef9868496a2fe5175c5afe6b/components/Triggers/src/IsNullOrEmptyStateTrigger.cs#L120

When `Content` is ComboBox, `IsNullOrEmpty` should simply return false. But in our case because `FrameworkElement`s are `IEnumerable`s, it could end up returning true incorrectly.

I don't see any way to fix this without a breaking change, other than opening a PR for `CommunityToolkit/Windows` to adjust the logic for Uno specifically.

**Comment by Youssef1313** [comment] 2024-07-10 07:11
https://github.com/CommunityToolkit/Windows/pull/452 is now merged

**Closed by Youssef1313** 2024-07-10 07:11 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd

**Comment by agneszitte** [comment] 2024-07-10 21:27
@jeromelaban, @MartinZikmund, @Youssef1313 I think we need to keep that issue opened (with maybe a little lower priority for now) as it still needs to be properly fixed at some point.

@Arlodotexe left a comment [here](https://github.com/Youssef1313/Windows/blob/80f2ba93add7f82e6799ef80e1322fdf56a850a1/components/Triggers/src/IsNullOrEmptyStateTrigger.cs#L122) in the Windows Community Toolkit code to track this issue for cleanup later on.
https://github.com/CommunityToolkit/Windows/pull/452/files

**Comment by Youssef1313** [comment] 2024-07-11 02:02
The fix will be a breaking change to make FrameworkElement not IEnumerable which is tracked bt #8339
