### ISSUE TITLE
unoapp-winui wasm project doesn't display/render NavigationViewItem

### ISSUE THREAD

**Issue by Zof-R** [unoplatform/uno#5267] opened 2021-02-17 23:54 UTC
## Current behavior

NavigationViewItems inside NavigationView aren't displayed when running under Uno.Wasm, they are when running under UWP.

## Expected behavior

NavigationViewItems should be displayed/rendered when running under Uno.Wasm

## How to reproduce it (as minimally and precisely as possible)

- Create a project with `dotnet new unoapp-winui -o TestApp -ios=false -android=false -macos=false -sw=false -sg=false -wd=false`
- Edit App.xaml file as per https://platform.uno/docs/articles/features/fluent-styles.html
- Copy over Fonts.css as per https://platform.uno/docs/articles/uno-fluent-assets.html
- Edit MainPage.xaml to add a NavigationView with a few NavigationViewItems as per the attached sample project
[TestApp.zip](https://github.com/unoplatform/uno/files/5999236/TestApp.zip)

Note: Tested by running in debug mode in Visual Studio 2019 or alternatively with `dotnet run --project TestApp.Wasm`

## Workaround

Not exactly a workaround, but removing `<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />` from the App.xaml file the NavigationViewItems are then displayed appropriately.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [x] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Microsoft.WinUI 3.0.0-preview3.201113.0
Uno.Core 2.1.0
Uno.Ui 3.5.1
Uno.Wasm.Bootstrap 1.3.4
Uno.Wasm.Bootstrap.DevServer 1.3.4
Uno.WinUi.RemoteControl 3.5.1
Uno.WinUi.WebAssembly 3.5.1

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.8.5)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by IsmailHassani** [comment] 2021-02-18 17:12
This looks like the same bug as #5265 
Removing the ```<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls"/>``` does help.

**Comment by jeromelaban** [comment] 2021-03-01 22:15
Closing as a duplicate of https://github.com/unoplatform/uno/issues/5265

**Closed by jeromelaban** 2021-03-01 22:15 UTC
Labels: difficulty/medium, kind/bug, project/styling
