### ISSUE TITLE
[wasm] Multiline textbox red squiggly lines fixed positon while scrolling

### ISSUE THREAD

**Issue by morning4coffe-dev** [unoplatform/uno#11403] opened 2023-02-21 14:05 UTC
### Current behavior

When using the latest version of stable Microsoft Edge 110.0.1587.50(64bit) the multiline textbox red squiggly lines have fixed position while scrolling
https://user-images.githubusercontent.com/78549750/220366213-1fb756d3-0e0c-46e2-92cf-0130ed4bb597.mp4

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment] 2023-02-22 06:00
I'm not able to reproduce this (using same version of MS Edge)

**Comment by MartinZikmund** [comment] 2023-08-23 13:06
We were not able to reproduce this later anymore, closing for now.

**Closed by MartinZikmund** 2023-08-23 13:06 UTC
Labels: platform/wasm 🌐, area/external, difficulty/tbd
