### ISSUE TITLE
Page, Application is not recognized. But it compiles well.

### ISSUE THREAD

**Issue by OscarCBcn** [unoplatform/uno#5686] opened 2021-04-06 06:43 UTC
When creating a new project Uno everything compiles and the editor goes well (nothing underlined red). But as soon you add a new Page to Shared Project, everything goes underlined red. But it compiles well. It seems intellisense goes crazy.

## How to reproduce it (as minimally and precisely as possible)

Just create a new project uno with VS 2019 professional and then add a new Page to shared project.

## Workaround

No workaround found

## Environment

Nuget Package:

- [3.6.6 ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

Nuget Package Version(s): 

Affected platform(s):

- [X ] iOS
- [X] Android
- [X ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ X] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X ] Visual Studio 2019 (version: 16.9.2 )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:
![8W4yV](https://user-images.githubusercontent.com/82018878/113669486-255c0780-96b4-11eb-9a20-dba77c877e14.png)

**Comment by jeromelaban** [comment] 2021-04-06 11:32
Thanks for the report, this is a [duplicate of this issue here](https://github.com/unoplatform/uno/issues/1848), with [resolution steps here](https://platform.uno/docs/articles/get-started-wizard.html).

**Closed by jeromelaban** 2021-04-06 11:32 UTC
Labels: difficulty/tbd, kind/bug, triage/untriaged
