### ISSUE TITLE
Can't use Converter inside `ItemsRepeater`

### ISSUE THREAD

**Issue by iurycarlos** [unoplatform/uno#15593] opened 2024-02-22 12:42 UTC
### Current behavior

Using a converter inside a DataTemplate of an ItemsRepeater will generate nothing.
In the converter Convert method, Value is always NULL. 
ItemsControl works perfectly with the exact same code.

![image](https://github.com/unoplatform/uno/assets/6876973/2dba9fca-30c2-4a55-9c5d-774c7b76f836)

This is the console Output

![image](https://github.com/unoplatform/uno/assets/6876973/b6fe93d9-6a1c-48f7-9c4b-143c5ed62428)

### Expected behavior

Should work with a converter

### How to reproduce it (as minimally and precisely as possible)

The repro can be done by the attached project.
[ItemsRepConverter.zip](https://github.com/unoplatform/uno/files/14373896/ItemsRepConverter.zip)

Online Wizard generated code:

dotnet new unoapp -o ItemsRepConverter -id "com.companyname.ItemsRepConverter" -pub "O=ItemsRepConverter" -platforms "android" -platforms "wasm" -platforms "windows" -platforms "gtk" -cpm False -vscode False -pwa False -theme "fluent" -presentation "mvvm" -config false -di false -log "none" -nav "blank" -http false -loc false -server false -tests "none" -toolkit false -dsp false

### Works on UWP/WinUI

None

**Comment by Youssef1313** [comment] 2024-03-01 17:14
@iurycarlos Well, if there is a bug, it will be that the converter works for `ItemsControl` :)

This is WinUI behavior:

![image](https://github.com/unoplatform/uno/assets/31348972/098108bd-de0b-480d-802c-b6a4a1a49236)


And this is Uno's behavior (Gtk, at least):

![image](https://github.com/unoplatform/uno/assets/31348972/82be50d8-52ea-43c3-ab41-f1c96878bfe4)

**Comment by Youssef1313** [comment] 2024-03-01 18:41
Closing per discussion with @iurycarlos since it's not working on WinUI. The behavior difference I noticed is now moved to a separate issue #15713

**Closed by Youssef1313** 2024-03-01 18:41 UTC
Labels: kind/bug, project/binding 🪢, area/items-repeater, difficulty/medium 🤔

**Comment by dr1rrb** [comment] 2024-03-05 16:08
@iurycarlos, @Youssef1313 to have the same behavior on windows and uno, just remove the `.` in the binding (was not even aware that it was possible to do so ^^)

@iurycarlos To workaround your issue with the IR (both windows and Uno), just add an extra layer like a `Border`:

```csharp
<DataTemplate>
	<Border>
		<local:MyUserControl Margin="0,10,0,0" DataContext="{Binding ., Converter={StaticResource TestConverter}}" />
	</Border>
</DataTemplate>

```

**Comment by dr1rrb** [comment] 2024-03-06 05:53
BTW, the issue is not linked to the converter, but the binding to the `DataContext` that is overridden by the `ItemsRepeater`
