### ISSUE TITLE
[WASM] Style template ContentPresenters don't work without explicit Content/ContentTransitions/ContentTemplate bindings

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#6318] opened 2021-06-21 09:43 UTC
This code should work without explicit Content/ContentTransitions/ContentTemplate bindings for WASM(It works for other platforms).
```xml
<Style TargetType="ContentControl">
  <Setter Property="Template">
    <Setter.Value>
      <ControlTemplate TargetType="ContentControl">
        <ContentPresenter
            Content="{TemplateBinding Content}"
            ContentTransitions="{TemplateBinding ContentTransitions}"
            ContentTemplate="{TemplateBinding ContentTemplate}"
            />
      </ControlTemplate>
    </Setter.Value>
  </Setter>
</Style>
```

**Comment by jeromelaban** [comment] 2021-06-21 11:53
Thanks for the report, this is a duplicate of https://github.com/unoplatform/uno/issues/857.

**Closed by jeromelaban** 2021-06-21 11:53 UTC
Labels: difficulty/tbd, kind/bug, triage/untriaged
