### ISSUE TITLE
[Calculator][Wasm] Focus- Tab and Tab+ shift option is not working.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6431] opened 2021-07-08 18:31 UTC
## Current behavior
when pressing  Tab and Tab + shift key  on keyboard, Focus is not showing anywhere.

## Expected behavior
Focus should work.

## How to reproduce it (as minimally and precisely as possible)
1. Launch an UNO Calculator app.
2. Press Tab or Tab + Shift key on keyboard.
3. Observe that the Focus is not showing anywhere.

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Canary version:
1.2.4-canaries-dev.41

**Comment by MartinZikmund** [comment] 2023-05-01 10:40
This is not a bug in Uno, but rather an uninmplemented feature - https://github.com/unoplatform/calculator/blob/56f6a7c5d88db97b12867199ffb24fb88a4de2f1/src/Calculator.Shared/Controls/KeyboardShortcutManager.cs#L102 . Moving this to calculator repo

**Closed** 2023-05-01 10:42 UTC
Labels: kind/bug, platform/wasm, project/input, area/canary, difficulty/medium, area/focus
