### ISSUE TITLE
[WASM] Binding failure when DataContext instace is changed

### ISSUE THREAD

**Issue by Suriman** [unoplatform/uno#9493] opened 2022-08-13 10:19 UTC
### Current behavior

When the DataContext instance is changed in a loaded ContentControl, the bindings don't work.

### Expected behavior

The bindings show the new values.

### How to reproduce it (as minimally and precisely as possible)

Open the attached project and compile it for Wasm head. On the main page there are two buttons, the first reproduces the problem and the second button loads the content control correctly. 

### Workaround

Use the second way to open a ContentControl and change its DataContext instance.

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI 4.4.5

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.3.0 preview 2

### Anything else we need to know?

The buttons scenarios try to simulate a Prism framework navigation to a region to load a ContentControl
[WasmBindings.zip](https://github.com/unoplatform/uno/files/9331220/WasmBindings.zip)
.

**Comment by jeromelaban** [comment] 2022-08-15 13:55
Thanks. This is a duplicate of https://github.com/unoplatform/uno/issues/2872 that we have not tackled yet. It's caused by the fact that the original DataContext change happens after the control is loaded, and it never gets updated. 

Note that if you change the DataContext once more (without the `Bindings.Update()`), WinUI will also not update the `ViewModel` value because it's not observed.

In your specific sample, you can fix this by changing the following code:

```csharp
public sealed partial class FormView : FormViewBase
{
    public FormView()
    {
        this.InitializeComponent();

        // Refresh x:Bind when the DataContext changes.
        DataContextChanged += (s, e) => Bindings.Update();
    }

    public FormViewModel ViewModel => this.DataContext as FormViewModel;
}
```

**Closed by jeromelaban** 2022-08-15 13:55 UTC
Labels: kind/bug, platform/wasm, project/binding, difficulty/tbd
