### ISSUE TITLE
[WASM] Bootstrapper 2.0.2 refused to build AOT

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#5694] opened 2021-04-07 04:25 UTC
@jeromelaban, @peternary tried to build AOT using bootstrapper 2.0.2 as per [here](https://github.com/unoplatform/uno/issues/5647) and failed. Is that expected or do you need details?

**Comment by jeromelaban** [comment] 2021-04-07 11:39
Thanks, I'm assuming here that you are using `netstandard2.0` for your application and this target framework is not working properly for `FullAOT` in 2.0.2.

Here's a table of what is working currently:
- 1.3.6
  -  `netstandard2.0` :  `Interpreter`, `InterpreterAndAOT` and `FullAOT`
- 2.0.1
  -  `netstandard2.0` :  `Interpreter`
  -  `net5+` :  `Interpreter`, `InterpreterAndAOT` (minimally)
- 2.1-dev
  -  `netstandard2.0` :  `Interpreter`
  -  `net5+` :  `Interpreter`, `InterpreterAndAOT` (improved)

`FullAOT` will not be supported by the .NET team for the foreseeable future in `net5` and `net6` because of the lack of exception filters support, and the `netstandard2.0` target support will not evolve in future.

The .NET team is working actively on the AOT support for `net6`, and many scenarios are getting fixed in recent 2.1-dev bootstrapper builds.

If your scenario does not fall into the categories I mentioned here, please provide more details about the error you're referring to.

**Comment by DierkDroth** [comment] 2021-04-07 14:11
Thanks @jeromelaban 

To clarify: "1.3.6" does not support debugging + breakpoints whereas "2.0.1" and "2.1-dev" does, correct?

**Comment by jeromelaban** [comment] 2021-04-07 15:09
1.3.6 supports debugging but has some issues like the one you found.

`InterpreterAndAOT` mode is able to fallback to the interpreter for parts that cannot be AOTed, but the rest is AOTed completely.

The .NET team are not working on `FullAOT`, only `InterpreterAndAOT`.

**Comment by DierkDroth** [comment] 2021-04-08 10:56
@jeromelaban I just tried
- latest 2.0.X and
- latest 2.1-dev

On both I experienced that I could not start WASM interpreter without removing lines as per [here](https://github.com/unoplatform/uno/issues/2372#issuecomment-805829641).

And even worse: after removing those lines the app still would not start. Is that expected?

**Comment by jeromelaban** [comment] 2021-04-08 11:28
Thanks Dierk. `netstandard2.0` debugging is supported only on 1.3.6 with the issues I mentioned previously.

If you need debugging for bootstrapper 2.0 or later, using `net5.0` is the only way to do so. Also know there may also be a different set of issues with it as it is still a work in progress by the .NET team.

**Comment by DierkDroth** [comment] 2021-04-08 11:50
@jeromelaban to clarify:
- the most 'stable WASM branch' right now would be 1.3.6 (+ netstandard2.0) still, correct?
- however, I then had to remove the offending lines as per [here](https://github.com/unoplatform/uno/issues/2372#issuecomment-805829641)
- the real worst part is, that I no longer could set break points, no? That did work before, so we had a clear degradation here, no?

**Comment by jeromelaban** [comment] 2021-04-08 12:02
@DierkDroth 

The most stable for your combination is 1.3.6, yes. If you see a degradation, it's not caused by the bootstrapper itself, but rather by an evolving set of assemblies in your app or a dependent nuget package, which revealed an issue in the debugger bundled with the 1.3.6 bootstrapper.

Removing the lines disable the debugging feature of visual studio, so you can continue with that, or start the application without debugging (Ctrl+F5) as you may have already found out.

**Comment by DierkDroth** [comment] 2021-04-08 14:57
Thanks @jeromelaban. We'll stay on 1.3.6 for now until 2.X is stable enough and has at least debugger support which is comparable with what we have with 1.3.6.

**Closed** 2021-04-09 12:41 UTC
Labels: difficulty/tbd, kind/bug, triage/untriaged
