### ISSUE TITLE
[WASM] TimePicker flyout does not open

### ISSUE THREAD

**Issue by jsinsel** [unoplatform/uno#6658] opened 2021-08-04 13:47 UTC
## Current behavior

Add a TimePicker control to a view.  Clicking on the control does not open the flyout.  

## Expected behavior

Flyout opens as it does in UWP.

## How to reproduce it (as minimally and precisely as possible)

Attaching a sample project. 
[App1.Shared.zip](https://github.com/unoplatform/uno/files/6931714/App1.Shared.zip)

## Works on UWP/WinUI
Yes

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment] 2021-08-04 13:48
Thanks for the report! This is a duplicate of https://github.com/unoplatform/uno/issues/5553

**Closed** 2021-08-04 13:48 UTC
Labels: difficulty/tbd, kind/bug, triage/untriaged
