### ISSUE TITLE
Resource file .upri is generated with an incorrect language if there is any folder that equals to a language code in the full path of the file.

### ISSUE THREAD

**Issue by Suriman** [unoplatform/uno#9875] opened 2022-09-17 09:53 UTC
### Current behavior

The resource 'This is a resource value from a resource file' is only shown on WinUI head.

### Expected behavior

All heads show the resource.

### How to reproduce it (as minimally and precisely as possible)

Notice the DA folder in the attached project.
Open the attached project and compile it. Executing it WinUI it should show the text 'This is a resource value from a resource file'. Executing it in any other head does not show the text.
Rename the 'DA' folder to 'DD'. Rebuild the solution (so the source generators execute again). Now the text should show in all heads.

### Workaround

Make sure that there are not any language codes folders in the full path of the resources files.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

4.5.9

### Affected platforms

iOS, Android, WebAssembly, macOS, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Tizen)

### IDE

Visual Studio 2022

### IDE version

17.3.4

### Anything else we need to know?

See ZIP attached.
[ResourcesLanguageCodeInPathIssue.zip](https://github.com/unoplatform/uno/files/9591398/ResourcesLanguageCodeInPathIssue.zip)

**Comment by jeromelaban** [comment] 2022-09-19 12:33
Thanks for the report. This issue is a duplicate of https://github.com/unoplatform/uno/issues/7431.

**Closed by jeromelaban** 2022-09-19 12:33 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
