### ISSUE TITLE
[CalendarDatePicker][Playground]Wrong year display on Header for the selected year from the decade calendar and after that monthly and decade calendar does not work properly.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#6162] opened 2021-06-04 16:51 UTC
## Current behavior

https://user-images.githubusercontent.com/74563602/120836312-71e88580-c533-11eb-9cb6-6124e492e441.mp4

## Expected behavior
The Selected year should display on the Header for the Monthly calendar view.

## How to reproduce it (as minimally and precisely as possible)

1. Visit https://playgroundcanary.z19.web.core.windows.net/#4d789784
2. Click on Select a Date button.
3. Go to Monthly Calendar view for the current year.
4. Choose any month and date for that year.
5. Again go to Decade calendar view.
6. Click on any year on the decade calendar view.
7. Observe that some random year display instead of the selected year on the Header.

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [ ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by carldebilly** [comment] 2021-06-08 18:16
## Investigations
The problem seems caused by a NRE occuring in the `FocusItem()` method:
![image](https://user-images.githubusercontent.com/4174207/121236623-28b27180-c864-11eb-8fa1-08194e11c951.png)

**Comment by dr1rrb** [comment] 2021-06-10 15:16
Fixed by https://github.com/unoplatform/uno/pull/6197

**Closed by dr1rrb** 2021-06-10 15:16 UTC
Labels: area/canary, area/pickers, difficulty/medium, kind/bug, platform/wasm
