### ISSUE TITLE
ItemsWrapGrid is not working on WASM

### ISSUE THREAD

**Issue by takla21** [unoplatform/uno#4024] opened 2020-09-10 16:52 UTC
## Current behavior

When we use an itemsWrapGrid inside the ItemsPanelTemplate for ListView and ItemsControl, we only see the first item.
![wasm](https://user-images.githubusercontent.com/17461593/92766397-303ffb00-f364-11ea-9b58-231edd0824e0.jpg)

## Expected behavior

We should be able to see all items.
![uwp](https://user-images.githubusercontent.com/17461593/92766449-3afa9000-f364-11ea-95f3-e11a10a5d54b.jpg)

## How to reproduce it (as minimally and precisely as possible)

Download sample [ItemsWrapGrid.zip](https://github.com/unoplatform/uno/files/5203421/ItemsWrapGrid.zip)
Deploy on any heads (Android, iOS or Wasm)

## Workaround

N/A

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

Nuget Package Version(s): 3.1.0-dev.274

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.6.2)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by davidjohnoliver** [comment] 2020-09-10 19:11
Duplicate of https://github.com/unoplatform/uno/issues/468

**Closed by davidjohnoliver** 2020-09-10 19:11 UTC
Labels: area/wasm, kind/bug, triage/untriaged
