### ISSUE TITLE
Button and ToggleButton are not behaving correctly on MacOS/Catalyst

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#16755] opened 2024-05-16 19:03 UTC
### Current behavior

Button:
- No mouse move effect
- When a button is clicked, it keeps its state: black foreground and black borderline

ToggleButton:
- No mouse move effect
- When it is clicked, it can't be unclicked

I have the impression the check state can't be uncheck.

Update: even without a style on ToggleButton, the state does not toggle after the first click.

https://github.com/unoplatform/uno/assets/1608424/fb57bd7c-07b8-4025-b0b5-d7da185c04a0

### Expected behavior

It should behave like the Windows version
https://github.com/unoplatform/uno/assets/1608424/0f1bfc70-7991-44e9-a785-fef645aff7f5

### How to reproduce it (as minimally and precisely as possible)

Run my app

For the toggle button, I redefine colors in the MainPage.xaml directly

[UnoApp1.zip](https://github.com/unoplatform/uno/files/15339734/UnoApp1.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

5.2.132

### Affected platforms

MacOs / Catalyst

**Comment by jeromelaban** [comment] 2024-05-17 11:31
Thanks for the report this is a duplicate of https://github.com/unoplatform/uno/issues/12467

**Closed by jeromelaban** 2024-05-17 11:31 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd

**Comment by ArchieCoder** [comment] 2024-05-17 13:22
@jeromelaban Do I understand correctly that Mac Catalyst (for Uno) is just to have iOS and iPad apps only?

**Comment by agneszitte** [comment] 2024-05-22 14:54
@jeromelaban do we need to re-open this issue (or open a new one specifically?) for what seems like a regression for the **press state that stays pressed** even after the pointer is released, as https://github.com/unoplatform/uno/issues/12467 is only related to the support for over states.

_Related test details for Uno Calculator:_
I tested both the first and last builds available on TestFlight for both Uno Calculator and Uno Calculator Gallery and I am able to reproduce the same behavior below on all of them.
![macos-calculator- buttons-issue](https://github.com/unoplatform/uno/assets/16295702/6041467c-e993-43f9-add3-5feee38cfdc9)

Seems a regression for the fact that the buttons stay pressed as it does not happen on the build available on the App Store (submitted 3 months ago).
![macos-calculator-store version](https://github.com/unoplatform/uno/assets/16295702/7561c18f-0f97-4deb-8690-37017f8efefc)

**Comment by jeromelaban** [comment] 2024-05-22 15:10
@agneszitte this is a different issue, we can reference this one though.

**Comment by agneszitte** [comment] 2024-05-22 15:36
> @agneszitte this is a different issue, we can reference this one though.

I have opened https://github.com/unoplatform/uno/issues/16838 to avoid confusion in the details
