### ISSUE TITLE
Can't add project reference in 'Cross-Platform Library'

### ISSUE THREAD

**Issue by stefanolson** [unoplatform/uno#3909] opened 2020-08-29 20:38 UTC
## Current behavior

I am unable to add a reference to another project within a Cross-Platform Library

## Expected behavior

Should be able to create a reference to another project.

## How to reproduce it (as minimally and precisely as possible)

Create a new uno project. Within the project create a new 'Cross-Platform Library'. Right click on the new project, choose add project reference. Get the message "Missing value for TargetPlatformWinMDLocation property".

(Not sure how to include pre-built project in this report)

## Workaround

Temporarily move the `uap10.0.xxx` target framework to be at least second in the `TargetFrameworks` list.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: 16.7.2 )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [x] Resharper (version: 2020.2 )

**Comment by jeromelaban** [comment] 2020-09-01 13:07
Unfortunately, there's no good solution for this issue, as it causes a conflict between two VS features (add reference, and XAML intellisense).

This is caused by the fact that `uap10.0.16299` is the first target framework of the list. Changing this make adding references work, but then breaks XAML intellisense. This is the result of UWP not supporting sdk-style projects, and the use of MSBuild.Sdk.Extras to enable cross targeting.

Currently, the only workaround is to move set `netstandard2.0` as the first target framework, then add the reference.

**Comment by stefanolson** [comment] 2020-09-01 13:28
@jeromelaban Thanks. I've managed to get the reference in place now.  But when I try and build the first library, it failed due to not finding uap10.0.16299.  Now I think that just because it's got the wrong version as I don't have that SDK installed (got 18362), but I'm pretty sure that reference was created by Uno?  Is it possible for Uno to sense what SDKs are installed and use the correct version? Having said that, that's more minor than the above problem. Hopefully reading this will help anyone else who has the same issue.

Thanks!

**Comment by jeromelaban** [comment] 2020-09-01 14:02
Thanks for the update. It would probably be possible to determine which versions are available, though that logic may not be easy to determine.

In all cases, the support of .NET 5 for UWP/WinUI will change all this and it will become lots easier to work with.

**Comment by jeromelaban** [comment] 2022-12-02 02:56
While this issue is still valid for UWP, it's now fixed with WinAppSDK. Closing as evolution made its work.

**Closed by jeromelaban** 2022-12-02 02:56 UTC
Labels: kind/bug, area/vswin, area/solution-templates, project/core-tools
