### ISSUE TITLE
Source generator for `RoutedEventFlags`

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#8411] opened 2022-03-23 10:45 UTC
## What would you like to be added:

Currently reflection is used to generate `RoutedEventFlags` for each type.

## Why is this needed:

Perf.

## For which Platform:

All

**Comment by jeromelaban** [comment] 2022-03-23 12:05
Isn't it a duplicate of https://github.com/unoplatform/uno/issues/6879 ? See https://github.com/unoplatform/uno/pull/6937 for tentative implementation.

**Closed** 2022-03-23 13:53 UTC
Labels: kind/enhancement, project/core-tools, difficulty/medium
