### ISSUE TITLE
[Gallery][Wasm][Home Page] Dropdown menu from Navigation Bar appears without background table.

### ISSUE THREAD

**Issue by jhanvi03** [unoplatform/uno#17366] opened 2024-07-02 18:02 UTC
### Current behavior

When navigating from the 'Platform' dropdown to 'IDE & Tools' or anywhere else and then back to any of the dropdown from navigation bar than dropdown appears without the expected background table, leading to a disjointed and inconsistent user interface. the issue happens in both Dark and light mode.

https://github.com/unoplatform/uno/assets/173818531/f8194fd3-793c-40d0-9681-5c85f9aabdcc

https://github.com/unoplatform/uno/assets/173818531/16125b55-3c16-474c-a994-2a95678d3b17

### Expected behavior

The dropdown should always appear with background table in dark and light mode.

<img width="436" alt="image" src="https://github.com/unoplatform/uno/assets/173818531/d775f918-3d2a-463c-8062-5f4da85156ad">

<img width="513" alt="image" src="https://github.com/unoplatform/uno/assets/173818531/aad30eeb-af1d-4d1a-b274-9ccfa84ba94d">

### How to reproduce it (as minimally and precisely as possible)

1. Open the navigation bar.
2. Click on 'Platform'.
3. From the 'Platform' dropdown, select 'IDE & Tools'.
4. Go back to 'Platform' from the navigation bar.

### Works on UWP/WinUI

None

**Comment by ramezgerges** [comment] 2024-07-03 10:59
This is probably fixed by https://github.com/unoplatform/uno/pull/17289

**Comment by Youssef1313** [comment] 2024-07-03 16:36
@ramezgerges The issue is for Wasm.

**Closed** 2024-07-31 16:53 UTC
Labels: kind/bug, platform/wasm 🌐, triage/untriaged, difficulty/tbd

**Comment by jhanvi03** [comment] 2024-08-21 13:48
@Xiaoy312 @kazo0, I was testing pointers and found that sometimes the dropdown appears without a background. It doesn't happen every time, but it does occur occasionally.
![image](https://github.com/user-attachments/assets/2e3cc153-1ea0-48cb-b039-b3ec73e9ed50)
