### ISSUE TITLE
[WASM] Bugs in ComboBox with scrollbar

### ISSUE THREAD

**Issue by HavenDV** [unoplatform/uno#6514] opened 2021-07-20 17:23 UTC
## Current behavior

[WASM] ComboBox with scrollbar(with a lot of items) do not respond to mouse scrolling/have bugs with the appearance of the scrollbar. The problem only appears in prerelease versions after 3.8.13

## Expected behavior

As in 3.8.13

## How to reproduce it (as minimally and precisely as possible)

```xml
<ComboBox>
    <x:String>Test</x:String>
    <x:String>Test</x:String>
    <x:String>Test</x:String>
    <x:String>Test</x:String>
    <x:String>Test</x:String>
    <x:String>Test</x:String>
    <x:String>Test</x:String>
    <x:String>Test</x:String>
    <x:String>Test</x:String>
    <x:String>Test</x:String>
    <x:String>Test</x:String>
    <x:String>Test</x:String>
    <x:String>Test</x:String>
    <x:String>Test</x:String>
    <x:String>Test</x:String>
    <x:String>Test</x:String>
    <x:String>Test</x:String>
</ComboBox>
```

## Works on UWP/WinUI
Yes

## Environment

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.9.0-dev.355

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: latest)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment] 2021-07-20 20:57
Thanks for the report. This is a a duplicate of  https://github.com/unoplatform/uno/issues/6439

**Closed by jeromelaban** 2021-07-20 20:57 UTC
Labels: difficulty/tbd, kind/bug, triage/untriaged
