### ISSUE TITLE
[Gallery-5X and 4X][Wasm,iOS,Android] ShadowContainer-Button- Background color for the Disabled button is different from Figma.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#13451] opened 2023-08-30 03:08 UTC
### Current behavior

![Disabled button issue](https://github.com/unoplatform/uno/assets/74563602/c4e8bc00-bf79-4a2c-80fe-2e0bd453423a)

### Expected behavior

![disabled button correct](https://github.com/unoplatform/uno/assets/74563602/4b433e0f-4768-4ae1-895f-7719b1c73c08)

### How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallery app for 4X or 5X version.
2. Click on “ShadowContainer” from the "Toolkit" list.
3. Go to Neumorphic section.
4. Choose 'Button' option from the combo list.
5. Notice that the Disabled Button is not matching with Figma button.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Android, iOS

**Comment by agneszitte** [comment] 2023-09-01 15:48
duplicate of https://github.com/unoplatform/Uno.Gallery/issues/912 so closing this one

**Closed by agneszitte** 2023-09-01 15:48 UTC
Labels: kind/bug, platform/wasm 🌐, platform/android 🤖, platform/ios 🍎, triage/untriaged, area/canary 🐤, difficulty/tbd, project/neumorphism
