### ISSUE TITLE
[Android] `Pivot.Items` not shown

### ISSUE THREAD

**Issue by AbdalaMask** [unoplatform/uno#6987] opened 2021-09-07 16:22 UTC
### Current behavior

Not Show Pivot.Items to android

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

Android

### IDE

Visual Studio 2019

### Anything else we need to know?

 
![image](https://user-images.githubusercontent.com/37013638/132381549-9a780408-ed8a-45b6-ba0b-81904bd98231.png)

**Comment by MartinZikmund** [comment] 2023-07-14 08:08
@AbdalaMask  Unfortunately this issue is missing a repro and details. Closing for now, feel free to create a new issue with more details later.

**Closed by MartinZikmund** 2023-07-14 08:08 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd

**Comment by FrozDark** [comment] 2023-07-14 08:20
> @AbdalaMask Unfortunately this issue is missing a repro and details. Closing for now, feel free to create a new issue with more details later.

Might be a duplicate of https://github.com/unoplatform/uno/issues/11914
