### ISSUE TITLE
[Skia] WebView support

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8761] opened 2022-05-12 19:50 UTC
### Current behavior

![webview](https://user-images.githubusercontent.com/74563602/168155079-64342b08-33fb-4365-864a-002db1747f8e.png)

### Expected behavior

![webview correct](https://user-images.githubusercontent.com/74563602/168155110-4eba57cc-ccf1-4fed-8eff-a3a729269f31.png)

### How to reproduce it (as minimally and precisely as possible)

Launch the Uno.Gallry app on Skia.GTK.
Click on “WebView” from the "Features" list.
Notice that WebView screen is blank.

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by Youssef1313** [comment] 2023-01-30 12:09
Duplicate of https://github.com/unoplatform/uno/issues/4233

**Closed by Youssef1313** 2023-01-30 12:09 UTC
Labels: kind/bug, area/canary, difficulty/tbd, platform/gtk
