### ISSUE TITLE
Pivot TemplatedParent propagation is incorrect

### ISSUE THREAD

**Issue by amaid** [unoplatform/uno#7497] opened 2021-11-19 08:02 UTC
### Current behavior

The binding is not working when used in resource dictionary on an element inside a PivotItem. This is happening in WASM but working fine on UWP application.

### Expected behavior

The binding should work when used in resource dictionary on an element inside a PivotItem on both UWP and WASM. 

### How to reproduce it (as minimally and precisely as possible)

1. Create an empty uno project.
2. Create a resource dictionary with code behind (xaml.cs) file.
3. Create a pivot inside the control template of the style inside the ResourceDictionary.
4. Just to test and compare create three ListViews, one with binding outside the pivot, and two listviews inside the pivot, one with hardcoded ListViewItems(just to test if any data being displayed inside pivot or not) and one with the binding.
5. Create a templated control and give this style to the control, Create dependency property of DataType ObservableCollection or maybe simple list `TestList` and bind it to the ListView.

The binding outside pivot will work.

The xaml in the resource dictionary should like the following:
```xaml 
<ResourceDictionary
    x:Class="App5.Style.MyTestStyle"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App5">
    <Style x:Key="MyTestStyle" TargetType="local:MyControl">
        <Style.Setters>
            <Setter Property="Template">
                <Setter.Value>
                    <ControlTemplate TargetType="local:MyControl">
                        <Grid>
                            <StackPanel Spacing="10">
                                <TextBlock Text="Binding test outside the pivot." FontSize="20" FontWeight="Bold"/>
                                <ListView ItemsSource="{Binding TestList, RelativeSource={RelativeSource Mode=TemplatedParent}}"/>
                                <Pivot>
                                    <PivotItem Header="MyTestPivotItem">
                                        <Grid>
                                            <StackPanel Spacing="5">
                                                <TextBlock FontSize="20" FontWeight="Bold" Text="Binding test inside the pivot."/>
                                                <ListView>
                                                    <ListViewItem>Hard Coded Text 1</ListViewItem>
                                                    <ListViewItem>Hard Coded Text 2</ListViewItem>
                                                </ListView>
                                                <ListView ItemsSource="{Binding TestList, RelativeSource={RelativeSource Mode=TemplatedParent}}"/>
                                            </StackPanel>
                                        </Grid>
                                    </PivotItem>
                                </Pivot>
                            </StackPanel>
                        </Grid>
                    </ControlTemplate>
                </Setter.Value>
            </Setter>
        </Style.Setters>
    </Style>

    <Style BasedOn="{StaticResource MyTestStyle}" TargetType="local:MyControl"/>
</ResourceDictionary>
```

The MyControl.cs looks like this:

```csharp
public class MyControl : Control
    {
        public static readonly DependencyProperty TestListProperty =
            DependencyProperty.Register(nameof(TestList), typeof(ObservableCollection<string>), typeof(ObservableCollection<string>), new PropertyMetadata(null, null));

        public ObservableCollection<string> TestList
        {
            get { return (ObservableCollection<string>)GetValue(TestListProperty); }
            set { SetValue(TestListProperty, value); }
        }

        public MyControl()
        {
            DefaultStyleKey = typeof(MyControl);

            TestList = new ObservableCollection<string>()
            {
                "Test 1",
                "Test 2"
            };
        }
 }
 ```

The output on WASM and UWP will look like this:
![image](https://user-images.githubusercontent.com/15306909/142584485-f8dede4a-6f8f-41ca-92b6-6b19e01ccad4.png)

### Workaround

Set the `ItemsSource` manually in templated control `cs` file by naming the affected listview and getting it using GetTemplateChild.

```csharp
  public class MyControl : Control
    {
        public static readonly DependencyProperty TestListProperty =
            DependencyProperty.Register(nameof(TestList), typeof(ObservableCollection<string>), typeof(ObservableCollection<string>), new PropertyMetadata(null, null));

        public ObservableCollection<string> TestList
        {
            get { return (ObservableCollection<string>)GetValue(TestListProperty); }
            set { SetValue(TestListProperty, value); }
        }

        public MyControl()
        {
            DefaultStyleKey = typeof(MyControl);

            TestList = new ObservableCollection<string>()
            {
                "Test 1",
                "Test 2"
            };
        }

        protected override void OnApplyTemplate()
        {
            base.OnApplyTemplate();

            var listView = GetTemplateChild("PART_ListView") as ListView;
            listView.ItemsSource = TestList;
        }
    }
```

![image](https://user-images.githubusercontent.com/15306909/142585666-9d2ac56c-6d66-4f9c-8ba2-58d9ea5b1734.png)

### Works on UWP/WinUI

Yes

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022, Visual Studio 2019

### IDE version

4.8.04084

**Comment by amaid** [comment] 2021-12-03 16:18
> Thanks for the report. This looks like a TemplatedParent propagation issue.
> 
> As another workaround, you may try this:
> 
> ```
>                           <StackPanel Spacing="10">
>                                 <TextBlock Text="Binding test outside the pivot." FontSize="20" FontWeight="Bold"/>
>                                 <ListView x:Name="myList" ItemsSource="{Binding TestList, RelativeSource={RelativeSource Mode=TemplatedParent}}"/>
>                                 <Pivot>
>                                     <PivotItem Header="MyTestPivotItem">
>                                         <Grid>
>                                             <StackPanel Spacing="5">
>                                                 <TextBlock FontSize="20" FontWeight="Bold" Text="Binding test inside the pivot."/>
>                                                 <ListView>
>                                                     <ListViewItem>Hard Coded Text 1</ListViewItem>
>                                                     <ListViewItem>Hard Coded Text 2</ListViewItem>
>                                                 </ListView>
>                                                 <ListView ItemsSource="{Binding ItemsSource, ElementName=myList}"/>
>                                             </StackPanel>
>                                         </Grid>
>                                     </PivotItem>
>                                 </Pivot>
>                             </StackPanel>
> ```

Thanks @jeromelaban will try this workaround.

**Comment by jeromelaban** [comment] 2022-09-13 19:43
Duplicate of https://github.com/unoplatform/uno/issues/1621

**Closed by jeromelaban** 2022-09-13 19:43 UTC
Labels: kind/bug, triage/untriaged, project/core-tools, difficulty/tbd
