### ISSUE TITLE
[Android] When there is no backround on the rootgrid of the control template, when you click on a clickable control, it can raise the click event twice

### ISSUE THREAD

**Issue by Marc-Antoine-Soucy** [unoplatform/uno#13604] opened 2023-09-11 16:18 UTC
### Current behavior

![FatFingerDouble](https://github.com/unoplatform/uno/assets/90481654/c05dfe91-8fa1-46de-9d49-b9f7f853a55d)
This Happens mostly when you fat finger it, or if you press on the control, but outside of elements that have a background, the click event is raised twice. 

In the sample provided, you can see it happens for Button, ToggleButtons, and Checkboxes.

For clarification, for this to happen, there must simply be a grid, or something that has no background, in the controltemplate, which is bigger than the children elements. If you click on something inside that grid, but outside the children element, it will raise the click event twice. (This can easily happen with a touchscreen, since this will happen if any part of what touches the screen is outside the bounds of the children elements).  

### Expected behavior

I would expect the click event to be raised once, like on other platforms.

### How to reproduce it (as minimally and precisely as possible)

[BasicApp.zip](https://github.com/unoplatform/uno/files/12579346/BasicApp.zip)

### Workaround

Putting a transparentbackground on the rootgrid of the controlTemplate fixes this

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

```
<PackageReference Include="Uno.Resizetizer" Version="1.2.0-dev.32" />
<PackageReference Include="Uno.WinUI" Version="5.0.0-dev.2533" />
<PackageReference Include="CommunityToolkit.Mvvm" Version="8.1.0" />
<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
<PackageReference Include="Uno.Extensions.Logging.OSLog" Version="1.6.0" />
<PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="5.0.0-dev.2533" />
<PackageReference Include="Uno.WinUI.RemoteControl" Version="5.0.0-dev.2533" Condition="'$(Configuration)'=='Debug'" />
```

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.6.5

### Anything else we need to know?

This is the cause of this bug https://github.com/unoplatform/uno/issues/13557

**Comment by Xiaoy312** [comment] 2023-09-11 16:25
related?: #12632

**Comment by Xiaoy312** [comment] 2023-09-15 14:51
to accurately reproduce the issue, you need to click on area that has nothing in front of it
even a invisible (Foreground=Transparent or Opacity=0) view can block this issue from happening
hence a common workaround is to apply Foreground=Transparent on the root grid of the control
for the checkbox, usually you have to click the small space between the check-glyph and its border for this to happen

**Comment by FrozDark** [comment] 2023-09-19 09:00
Seems like a duplicate of https://github.com/unoplatform/uno/issues/12258

**Comment by MartinZikmund** [comment] 2023-10-23 08:37
Closing as duplicate of #12258

**Closed by MartinZikmund** 2023-10-23 08:37 UTC
Labels: kind/bug, platform/android 🤖, triage/untriaged, project/pointers 🖱️, difficulty/tbd
