### ISSUE TITLE
Make `ContentDialogPlacement.InPlace` available on `ContentDialog.ShowAsync`

### ISSUE THREAD

**Issue by BrianDT** [unoplatform/uno#10333] opened 2022-11-03 20:32 UTC
## What would you like to be added:
Currently the dialog content is not displayed correctly when ContentDialogPlacement.InPlace is used except on UWP.

## Why is this needed:
While it may be possible to use a full screen ContentDialog with the content adjusted to show in the correct place this can be hard to do if the dialog is not on a screen edge.

## For which Platform:

- [x] WebAssembly
- [x] Android
- [x] iOS
- [ ] macOS (AppKit)
- [ ] Mac Catalyst
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Linux Framebuffer
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

## Anything else we need to know?

Can be reproduced by running the sample located here:
https://github.com/BrianDT/UWPTemplatedContentDialogIssue.git

**Comment by BrianDT** [comment] 2022-11-03 20:34
In the sample above the dialog is displayed as:

![10333_WASM](https://user-images.githubusercontent.com/4189260/199828334-5e23b5ac-361f-4a14-9e6a-0dd94e212ee0.png)

Where is should be displayed like the UWP head as:

![10333_UWP](https://user-images.githubusercontent.com/4189260/199828448-fc379c06-be14-44f7-a4bb-e1622ef6f0b1.png)

**Comment by MartinZikmund** [comment] 2024-12-26 15:19
Duplicate of #3333, follow the other issue for progress

**Closed by MartinZikmund** 2024-12-26 15:19 UTC
Labels: kind/enhancement, difficulty/medium 🤔, area/popups 💬, area/porting 🖨️
