### ISSUE TITLE
[Gallery][Skia.Gtk/Wasm]CalendarDatePicker & Calendarview(Fluent)-Down arrow is missing to change year in a decreasing order.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#12399] opened 2023-05-24 02:38 UTC
### Current behavior

![Arrow sign for calendar issue](https://github.com/unoplatform/uno/assets/74563602/3d26f602-d101-4586-a44b-47cfddcfe490)

### Expected behavior

Down arrow  option should display to change year in decreasing order.

### How to reproduce it (as minimally and precisely as possible)

1. Tap Burger Menu on the left top right.
2. Tap "CalendarDatePicker" from the "UI component" list.
3. Go to Fluent section.
4. click on the calendar.
5. Notice that in the calendar to change the displayed year the down arrow is not present.

### Works on UWP/WinUI

None

### Affected platforms

WebAssembly, Skia (GTK on Linux/macOS/Windows)

**Comment by Youssef1313** [comment] 2023-05-24 06:59
Duplicate of https://github.com/unoplatform/uno/issues/12387

**Closed by Youssef1313** 2023-05-24 06:59 UTC
Labels: kind/bug, platform/wasm, triage/untriaged, area/canary, difficulty/tbd, platform/gtk
