### ISSUE TITLE
[Uno Figma Plugin] CornerRadius="12, 0, 0, 12" isn't created in Xaml

### ISSUE THREAD

**Issue by Plexois37** [unoplatform/uno#14414] opened 2023-11-14 14:15 UTC
### Current behavior

When a button in the Uno Platform Material Toolkit in Figma gets CornerRadius="12, 0, 0, 12" (upper/bottom left corners rounded) then for some reason the corresponding Xaml-Code for this corner radius isn't created when using the Uno plugin. If I give it CornerRadius="13, 0, 0, 13" or above or CornerRadius="11, 0, 0, 11" or below, it also works. Only 12 seems to be problematic for some reason. CornerRadius="0, 12, 12, 0" also works without any problem.

### Expected behavior

CornerRadius="12, 0, 0, 12" should show rounded corners on the upper/bottom left side and rectangular corners at the right sides when using the Uno plugin in Figma. But every corner is rounded because the CornerRadius property isn't created in the Xaml code.

### Workaround

setting CornerRadius to numbers that aren't 12 I guess

### Works on UWP/WinUI

None

**Comment by agneszitte** [comment] 2023-11-20 23:41
@jeromelaban / @MartinZikmund this issue should be moved to the Figma repo no ? (cc @carldebilly)

**Comment by iurycarlos** [comment] 2023-11-22 14:19
Hi @Plexois37!
Do you mind to say what component did you used?
FAB, BUTTON ? 

Also, did you changed the intance you created or did you changed the component also?

Figma Plugin detects overrides comparing instances to their components.
For that reason, changing a component will not produce overrides.

I didn't have success reproducing your issue. Maybe there's something else we need to verify.
Please, keep me informed. I will be happy to help!

![image](https://github.com/unoplatform/uno/assets/6876973/be4419dd-d3fc-49af-b246-41189213a753)

**Comment by carldebilly** [comment] 2023-12-18 20:57
Closed as no answer from user and unable to reproduce.

**Closed** 2023-12-18 20:57 UTC
Labels: kind/bug, difficulty/medium 🤔, area/figma
