### ISSUE TITLE
WinUI Android : Release build is flooded with "_x_ is generated by more than one managed type" errors

### ISSUE THREAD

**Issue by baskren** [unoplatform/uno#10722] opened 2022-12-12 21:59 UTC
### Current behavior

Any WinUI Android project build, in Release Configuration, is flooded with the following error: "_WinUI.Type_ is generated by more than one managed type.  Please change the [Register] attribute so that the same Java type is not emitted".

<details>
  <summary>Click me to see a small sample of the errors (1485 were generated when compiling the demo project):</summary>

```
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215: The Java type `crc64a5a37c43dff01024.NavigationView` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationView` generated by: Windows.UI.Xaml.Controls.NavigationView, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationView` generated by: Windows.UI.Xaml.Controls.NavigationView, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationView` generated by: Windows.UI.Xaml.Controls.NavigationView, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationView` generated by: Windows.UI.Xaml.Controls.NavigationView, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215: The Java type `crc64a5a37c43dff01024.NavigationViewItem` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationViewItem` generated by: Windows.UI.Xaml.Controls.NavigationViewItem, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationViewItem` generated by: Windows.UI.Xaml.Controls.NavigationViewItem, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationViewItem` generated by: Windows.UI.Xaml.Controls.NavigationViewItem, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationViewItem` generated by: Windows.UI.Xaml.Controls.NavigationViewItem, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215: The Java type `crc64a5a37c43dff01024.NavigationViewItemBase` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationViewItemBase` generated by: Windows.UI.Xaml.Controls.NavigationViewItemBase, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationViewItemBase` generated by: Windows.UI.Xaml.Controls.NavigationViewItemBase, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationViewItemBase` generated by: Windows.UI.Xaml.Controls.NavigationViewItemBase, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationViewItemBase` generated by: Windows.UI.Xaml.Controls.NavigationViewItemBase, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215: The Java type `crc64a5a37c43dff01024.NavigationViewItemHeader` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationViewItemHeader` generated by: Windows.UI.Xaml.Controls.NavigationViewItemHeader, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationViewItemHeader` generated by: Windows.UI.Xaml.Controls.NavigationViewItemHeader, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationViewItemHeader` generated by: Windows.UI.Xaml.Controls.NavigationViewItemHeader, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationViewItemHeader` generated by: Windows.UI.Xaml.Controls.NavigationViewItemHeader, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215: The Java type `crc64a5a37c43dff01024.NavigationViewItemSeparator` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationViewItemSeparator` generated by: Windows.UI.Xaml.Controls.NavigationViewItemSeparator, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationViewItemSeparator` generated by: Windows.UI.Xaml.Controls.NavigationViewItemSeparator, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationViewItemSeparator` generated by: Windows.UI.Xaml.Controls.NavigationViewItemSeparator, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationViewItemSeparator` generated by: Windows.UI.Xaml.Controls.NavigationViewItemSeparator, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215: The Java type `crc64a5a37c43dff01024.NavigationViewList` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationViewList` generated by: Windows.UI.Xaml.Controls.NavigationViewList, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationViewList` generated by: Windows.UI.Xaml.Controls.NavigationViewList, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationViewList` generated by: Windows.UI.Xaml.Controls.NavigationViewList, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a5a37c43dff01024.NavigationViewList` generated by: Windows.UI.Xaml.Controls.NavigationViewList, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215: The Java type `crc642a1e7e20b34a3939.NavigationViewItemPresenter` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc642a1e7e20b34a3939.NavigationViewItemPresenter` generated by: Windows.UI.Xaml.Controls.Primitives.NavigationViewItemPresenter, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc642a1e7e20b34a3939.NavigationViewItemPresenter` generated by: Windows.UI.Xaml.Controls.Primitives.NavigationViewItemPresenter, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc642a1e7e20b34a3939.NavigationViewItemPresenter` generated by: Windows.UI.Xaml.Controls.Primitives.NavigationViewItemPresenter, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc642a1e7e20b34a3939.NavigationViewItemPresenter` generated by: Windows.UI.Xaml.Controls.Primitives.NavigationViewItemPresenter, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215: The Java type `crc64a352b6f848b4d68e.DispatcherTimer_TickRunnable` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a352b6f848b4d68e.DispatcherTimer_TickRunnable` generated by: Microsoft.UI.Xaml.DispatcherTimer+TickRunnable, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a352b6f848b4d68e.DispatcherTimer_TickRunnable` generated by: Microsoft.UI.Xaml.DispatcherTimer+TickRunnable, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a352b6f848b4d68e.DispatcherTimer_TickRunnable` generated by: Microsoft.UI.Xaml.DispatcherTimer+TickRunnable, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a352b6f848b4d68e.DispatcherTimer_TickRunnable` generated by: Microsoft.UI.Xaml.DispatcherTimer+TickRunnable, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215: The Java type `crc64a352b6f848b4d68e.FrameworkElement` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a352b6f848b4d68e.FrameworkElement` generated by: Microsoft.UI.Xaml.FrameworkElement, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a352b6f848b4d68e.FrameworkElement` generated by: Microsoft.UI.Xaml.FrameworkElement, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a352b6f848b4d68e.FrameworkElement` generated by: Microsoft.UI.Xaml.FrameworkElement, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a352b6f848b4d68e.FrameworkElement` generated by: Microsoft.UI.Xaml.FrameworkElement, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215: The Java type `crc64a352b6f848b4d68e.UIElement` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a352b6f848b4d68e.UIElement` generated by: Microsoft.UI.Xaml.UIElement, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a352b6f848b4d68e.UIElement` generated by: Microsoft.UI.Xaml.UIElement, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a352b6f848b4d68e.UIElement` generated by: Microsoft.UI.Xaml.UIElement, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a352b6f848b4d68e.UIElement` generated by: Microsoft.UI.Xaml.UIElement, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215: The Java type `crc64a352b6f848b4d68e.DragRoot` is generated by more than one managed type. Please change the [Register] attribute so that the same Java type is not emitted.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a352b6f848b4d68e.DragRoot` generated by: Microsoft.UI.Xaml.DragRoot, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a352b6f848b4d68e.DragRoot` generated by: Microsoft.UI.Xaml.DragRoot, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a352b6f848b4d68e.DragRoot` generated by: Microsoft.UI.Xaml.DragRoot, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): error XA4215:   `crc64a352b6f848b4d68e.DragRoot` generated by: Microsoft.UI.Xaml.DragRoot, Uno.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null

```
</details>

### Expected behavior

Release build successfully completes

### How to reproduce it (as minimally and precisely as possible)

1. create minimum Uno.WinUI app via: `dotnet new unoapp -o AndroidRelease`
2. `cd AndroidRelease`
3. open newly minted `AndroidRelease.sln` in VisualStudio 2022
4. if not so already, change __Startup Project__ to __AndroidRelease.Mobile__
5. if not so already, change __device__ to an Android emulator or Android device
6. change the __Solution Configuration__ to __Release__
7. Attempt to Build solution

for your convenience, [here is a demo solution](https://github.com/baskren/UnoAndroidReleaseBuild)

### Workaround

None known at this time (please share if you have one)

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

    <PackageReference Include="Uno.WinUI" Version="4.6.19" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.6.19" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
    <PackageReference Include="Uno.WinUI.Lottie" Version="4.6.19" />
         <PackageReference Include="Xamarin.Google.Android.Material" Version="1.4.0.4" />
        <PackageReference Include="Uno.UniversalImageLoader" Version="1.9.36" />

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

Version 17.4.2

**Comment by baskren** [comment] 2022-12-12 22:04
FWIW:
```
Microsoft Visual Studio Enterprise 2022
Version 17.4.2
VisualStudio.17.Release/17.4.2+33122.133
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Enterprise

Architecture Diagrams and Analysis Tools   00476-80000-00000-AA587
Microsoft Architecture Diagrams and Analysis Tools

Visual C++ 2022   00476-80000-00000-AA587
Microsoft Visual C++ 2022

ADL Tools Service Provider   1.0
This package contains services used by Data Lake tools

ASA Service Provider   1.0

ASP.NET and Web Tools   17.4.326.54890
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.4.326.54890
Azure App Service Tools v3.0.0

Azure Data Lake Tools for Visual Studio   2.6.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Azure Functions and Web Jobs Tools   17.4.326.54890
Azure Functions and Web Jobs Tools

Azure Stream Analytics Tools for Visual Studio   2.6.5000.0
Microsoft Azure Stream Analytics Tools for Visual Studio

C# Tools   4.4.0-6.22565.8+53091686b435746d62a5df56abfab0e71203d83a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CleanBinAndObjCommand Extension   1.2.58
CleanBinAndObjCommand Visual Studio Extension Detailed Info

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Cookiecutter   17.0.22263.6
Provides tools for finding, instantiating and customizing templates in cookiecutter format.

Extensibility Message Bus   1.4.1 (main@2ee106a)
Provides common messaging-based MEF services for loosely coupled Visual Studio extension components communication and integration.

InstallAware Extension for Visual Studio   #113
InstallAware Extension for Visual Studio 2012, 2013, 2015 and 2017

Linux Core Dump Debugging   1.0.9.33020
Enables debugging of Linux core dumps.

Microsoft Azure Hive Query Language Service   2.6.5000.0
Language service for Hive query

Microsoft Azure Stream Analytics Language Service   2.6.5000.0
Language service for Azure Stream Analytics

Microsoft Azure Tools for Visual Studio   2.9
Support for Azure Cloud Services projects

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Mono Debugging for Visual Studio   17.4.19 (8c0a575)
Support for debugging Mono processes with Visual Studio.

Node.js Tools   1.5.40817.1 Commit Hash:66443775f9f3b1d8f8fee47af5002828b346688d
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   6.4.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Office Developer Tools for Visual Studio   17.0.32915.00
Microsoft Office Developer Tools for Visual Studio

Python - Django support   17.0.22263.6
Provides templates and integration for the Django web framework.

Python - Profiling support   17.0.22263.6
Profiling support for Python projects.

Python with Pylance   17.0.22263.6
Provides IntelliSense, projects, templates, debugging, interactive windows, and other support for Python developers.

Razor (ASP.NET Core)   17.0.0.2246202+61cc048d36a3fc9246d2f04625988b19a18ab8f0
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62207.28050
Microsoft SQL Server Data Tools

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript Tools   17.0.10921.2001
TypeScript Tools for Microsoft Visual Studio

UnoPlatformPackage Extension   1.0
UnoPlatformPackage Visual Studio Extension Detailed Info

Viasfora   4.4.212
Add color to your Visual Studio editor!

Visual Basic Tools   4.4.0-6.22565.8+53091686b435746d62a5df56abfab0e71203d83a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual C++ for Linux Development   1.0.9.33020
Visual C++ for Linux Development

Visual F# Tools   17.4.0-beta.22512.4+525d5109e389341bb90b144c24e2ad1ceec91e7b
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

VSPackage Extension   1.0
VSPackage Visual Studio Extension Detailed Info

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   17.4.0.301 (d17-4@96af3ae)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   17.4.0.138 (remotes/origin/d17-4@d36bba3cc9)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   17.4.2 (c457c97)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   13.1.0.1 (d17-4/13ba222)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: a96bde9
    Java.Interop: xamarin/java.interop/d17-4@fcc33ce2
    SQLite: xamarin/sqlite/3.39.3@23e1ae7
    Xamarin.Android Tools: xamarin/xamarin-android-tools/main@0be567a


Xamarin.iOS and Xamarin.Mac SDK   16.0.0.92 (3dd3dc52c)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
```

**Comment by jeromelaban** [comment] 2022-12-13 13:41
Thanks for the report. This is a duplicate of https://github.com/unoplatform/uno/discussions/9513 (caused by https://github.com/xamarin/xamarin-android/issues/7473). There is no fix for this at this time when using net7.

Here's [a bit of documentation](https://github.com/unoplatform/uno/blob/master/doc/articles/get-started-wizard.md#net-7-android-release-aot-build-fails-with-the-java-type-xxx-is-generated-by-more-than-one-managed-type) for workarounds.

**Closed by jeromelaban** 2022-12-13 13:41 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd

**Comment by baskren** [comment] 2022-12-13 14:31
Thanks for the response and work around, @jeromelaban .
