### ISSUE TITLE
[WASM] Cannot iterate through persisted files on startup

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#3384] opened 2020-06-16 17:33 UTC
## Current behavior

Attempting to iterate through existing files in Windows.Storage.ApplicationData.Current.LocalFolder on startup only lists files created in that session.  Using Directory.GetFiles does not return any results and StorageFolder.GetFilesAsync is not yet implemented (there is a PR to implement it [here](https://github.com/unoplatform/uno/pull/2774).)

## Expected behavior

It should be possible to accurately iterate through local storage even early in execution.

## How to reproduce it (as minimally and precisely as possible)

Launch the attached project in WASM - in the console observe that a single file is listed when searching for files from OnLaunched.  On first run, you will observe similar by clicking the button.  If you refresh the page, however, the OnLaunched will only list the file created in that session, while the button click will list files created in previous sessions.

[RetrieveFilesWasm.zip](https://github.com/unoplatform/uno/files/4788161/RetrieveFilesWasm.zip)

## Environment

Nuget Package:
Uno.UI
Package Version(s):
3.0.0-dev.500
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by DierkDroth** [comment] 2020-06-16 17:36
@jeromelaban that's the issue we came across today where managing multiple traces is still not working. We realize that there already is a [PR](https://github.com/unoplatform/uno/pull/2774), however it's not merged yet. 

Would be great if we could get that resolved. Thanks in advance

**Comment by DierkDroth** [comment] 2020-06-17 16:55
@jeromelaban I just wanted to let you know that @peternary is pulling his hair in an attempt to create traces in an reliable way. It may or may not work and he suspects the root cause is this issue.

Also: tracsing + timestamps is our primary tool to analyse the massive recent performance degradation which we experienced. Hence, I would appreciate if that issue could be addressed sooner than later.

**Comment by jeromelaban** [comment] 2020-06-19 21:15
The storage is working properly in the current implementation, but the missing part is the ability to determine when the storage is being restored properly.

To be able to read files, you'll need to ensure that you await on a `StorageFolder` async API, such as `StorageFolder.CreateFolderAsync`:

```csharp
var localFolder = Windows.Storage.ApplicationData.Current.LocalFolder;
var folder = await localFolder.CreateFolderAsync("myFolder", CreationCollisionOption.OpenIfExists);
File.WriteAllText(Path.Combine(folder.Path, "MyFile.txt"), DateTime.Now.ToLongDateString());
```

This will be fixed in #3413.

**Comment by DierkDroth** [comment] 2020-06-20 04:41
@jeromelaban I just ran more tests based on your comment above and found that simply adding this line to App.OnLaunched 
`await ApplicationData.Current.LocalFolder.CreateFolderAsync("tmp", CreationCollisionOption.OpenIfExists);`
will throw this error on the browser console
   Error synchronizing filesystem from IndexDB: Error: FS error

**Comment by jeromelaban** [comment] 2020-06-20 14:06
@DierkDroth both issues will be fixed by #3413.

**Comment by DierkDroth** [comment] 2020-06-20 14:13
@jeremiethibeault perfect, thanks!

**Comment by DierkDroth** [comment] 2020-06-23 05:30
@jeromelaban sorry not resolved: I'm still getting 
 Error synchronizing filesystem from IndexDB: Error: FS error (errno: 20) Uno.UI.js:2979

I double checked by disabling the cache

**Comment by carldebilly** [comment] 2020-06-23 21:31
@DierkDroth @peternary @jeromelaban 

As Jérôme said, you must use the _async_ feature of `Windows.Storage`. This is because [there's an await](https://github.com/unoplatform/uno/blob/2457d48f3c91f13c07213fe51707247f380186bd/src/Uno.UWP/Storage/StorageFolder.wasm.cs#L28) for the storage sync to be completed.

Once it's initialized, you can still continue to use _sync_ file access if you want.

**Closed by carldebilly** 2020-06-23 21:31 UTC
Labels: area/storage, kind/bug

**Comment by DierkDroth** [comment] 2020-06-24 07:46
@carldebilly  thanks for clarification.

**Comment by peternary** [comment] 2020-06-25 13:12
Confirmed working with the provided clarification
