### ISSUE TITLE
[Android] ItemsView shows only one Item

### ISSUE THREAD

**Issue by jp-weber** [unoplatform/uno#17822] opened 2024-08-03 13:23 UTC
### Current behavior

Currently only one or the first item is visible
![grafik](https://github.com/user-attachments/assets/fade8216-4570-4f92-a80e-f0009d526910)

### Expected behavior

Like on WinUI3, all items should be visible:
![grafik](https://github.com/user-attachments/assets/66d2e214-1137-48c9-989a-c7a90d69c6c0)

### How to reproduce it (as minimally and precisely as possible)

Model
```csharp
public class TestModel
{
    public string Title { get; set; }
}
```

UI
```xaml
  <Grid>
    <Grid.RowDefinitions>
      <RowDefinition Height="auto"/>
      <RowDefinition Height="*"/>
    </Grid.RowDefinitions>
    <StackPanel HorizontalAlignment="Center"
              VerticalAlignment="Center" Spacing="50">
      <TextBlock AutomationProperties.AutomationId="HelloTextBlock"
               Text="Hello Uno Platform"
               HorizontalAlignment="Center" />
    </StackPanel>
    <ItemsView 
             Grid.Row="1"
               HorizontalAlignment="Center"
               VerticalAlignment="Center">
      <ItemsView.ItemTemplate>
        <DataTemplate x:DataType="local:TestModel">
          <ItemContainer AutomationProperties.Name="{x:Bind Title}">
            <TextBlock Text="{x:Bind Title, Mode=OneWay}"/>
          </ItemContainer>
        </DataTemplate>
      </ItemsView.ItemTemplate>

    </ItemsView>
  </Grid>
```

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

5.3.90

### Affected platforms

Android

### IDE

Visual Studio 2022

### Anything else we need to know?

Tested on Android 10 and 14 with Emulator and real devices.

**Comment by Youssef1313** [comment] 2024-08-03 15:48
`ItemsView` is currently only supported on Skia

**Comment by Youssef1313** [comment] 2024-08-03 15:49
Duplicate of https://github.com/unoplatform/uno/issues/14091

**Closed by Youssef1313** 2024-08-03 15:49 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
