### ISSUE TITLE
[iOS] WinUI.TextBox causes app crash

### ISSUE THREAD

**Issue by baskren** [unoplatform/uno#9823] opened 2022-09-13 12:42 UTC
### Current behavior

Using WinUI.TextBox in an iOS Uno app causes app to immediately crash 

### Expected behavior

Applications should run when using WinUI.TextBox

### How to reproduce it (as minimally and precisely as possible)

[iOS_TextBoxFail.zip](https://github.com/unoplatform/uno/files/9557100/iOS_TextBoxFail.zip)

### Workaround

none

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

  <ItemGroup>
    <PackageReference Include="Uno.WinUI" Version="4.4.20" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="4.4.20" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.4.20" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
  </ItemGroup>

### Affected platforms

iOS

### IDE

Visual Studio for Mac

### IDE version

versions 17.3.4 or 17.4 preview - build 715

### Relevant plugins

none

**Comment by jeromelaban** [comment] 2022-09-13 13:25
Thanks for the report, duplicate of https://github.com/unoplatform/uno/issues/9430. This is fixed in latest builds (4.5 or later, 4.4 to be updated), where a build error will tell you what to do.

**Closed by jeromelaban** 2022-09-13 13:25 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
