### ISSUE TITLE
RenderTransform not working in TextBlock

### ISSUE THREAD

**Issue by iurycarlos** [unoplatform/uno#17202] opened 2024-06-18 13:58 UTC
### Current behavior

RenderTransform is not working when applied to a TextBlock.
The result is just the same with or without the transform.

### Expected behavior

Should work as in Microsoft Documentation, https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.media.scaletransform?view=winrt-26100

### How to reproduce it (as minimally and precisely as possible)

Just use the playground:

https://playgroundcanary.z19.web.core.windows.net/#9274dab9

### Environment

Tried in Desktop and also Wasm. Both fail.

### NuGet package version(s)

Both: playground and canary

**Comment by Youssef1313** [comment] 2024-06-18 16:09
This is XamlReader-specific issue.

**Comment by Youssef1313** [comment] 2024-06-18 16:09
Duplicate of https://github.com/unoplatform/uno/issues/16493

**Closed by Youssef1313** 2024-06-18 16:09 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
