### ISSUE TITLE
Use new Fluent Icons (Sun Valley refresh)

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#5734] opened 2021-04-12 13:40 UTC
## What would you like to be added:

Fluent UI icons are now open-source and MIT - https://github.com/microsoft/fluentui-system-icons. Could be used to get the modern "rounded" iconography in Uno. Plus has a lot of additional icons we currently miss - https://github.com/microsoft/fluentui-system-icons/blob/master/icons.md

## Why is this needed:

Staying in sync with WinUI

## For which Platform:

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by robloo** [comment] 2021-07-18 23:56
This was news to be but apparently "Segoe Fluent Icons" is actually what is replacing "Segoe MDL2 Assets" in Windows 11. However, this font is NOT open source from what I can find. The close equivalent, from a different team I believe, is the "Fluent UI System Fonts" as you mentioned above. Fluent UI is not equivalent to WinUI's Fluent theme.

#6493

**Comment by robloo** [comment] 2021-09-16 04:54
I have a project that can build a Segoe Fluent equivalent font now: https://github.com/robloo/SymbolIconManager. Hopefully it will replace Uno.Fonts as well.

Some help for mappings would be appreciated. Otherwise, I'll probably have an MIT licensed font we can use to close this within a few weeks tops.

**Comment by robloo** [comment] 2021-09-17 06:29
I have built an initial replacement for the Segoe Fluent font here:

https://github.com/robloo/SymbolIconManager/blob/main/Fonts/WinSymbols3.ttf

I think this is enough to close out the issue and add to Uno Platform -- there are well over 300 glyphs already. I'll probably add a few more tomorrow and then would like contributions. Anyone can contribute mappings here:

https://github.com/robloo/SymbolIconManager/blob/main/Source/Data/Mappings/SegoeFluent.json

Can we close the issue once this is committed? What do you want the file name and copyright details to be?

**Comment by robloo** [comment] 2021-09-19 02:43
I completed the Segoe Fluent font replacement as much as I can (I did a full pass of all 1404 glyphs). In total I mapped 627 which is a hundred or so under what Uno ships now with the Segoe MDL2 replacement. However, I don't think I missed anything significant (other than Shuffle and a few others that just don't have a replacement).

Please (anyone, but hopefully the Uno team) give the font at the link a try before a PR. It would be good to get some feedback in other real apps.

https://github.com/robloo/SymbolIconManager/blob/main/Fonts/WinSymbols3.ttf

**Comment by davidjohnoliver** [comment] 2021-09-28 10:14
> @davidjohnoliver @MartinZikmund Who can review this font on the Uno side? I would like some feedback before a PR.

@robloo I haven't had a chance to look at this yet. This will require a fairly thorough review as there's a lot of scope for hard-to-spot regressions. 

> I'm also not entirely sure how to add it to Uno so that it only works with Fluent v2 styles.

There's not really a way to do that. Also I'm not sure why you want to?

**Comment by MartinZikmund** [comment] 2021-09-28 10:26
> > I'm also not entirely sure how to add it to Uno so that it only works with Fluent v2 styles.
> 
> There's not really a way to do that. Also I'm not sure why you want to?

I think the reason would be that v2 styles and V1 styles have different border thickness/corner radii and the icon styling also matches a specific version. Not sure how to go about this, versioned font would be more accurate, but we don't yet have any facility to version it...

One approach would be to provide docs that would instruct users how to downgrade to old UWP/Fluent V1 icon font by manually replacing the TTF and CSS

**Comment by davidjohnoliver** [comment] 2021-09-28 15:55
> I think the reason would be that v2 styles and V1 styles have different border thickness/corner radii and the icon styling also matches a specific version. Not sure how to go about this, versioned font would be more accurate, but we don't yet have any facility to version it...

Re: icon styling in an aesthetic sense, all the glyphs referred to by the v1 styles are already sourced from Fluent UI System Icons in the current font, so nothing should change there. (Assuming any new font keeps the mappings [here](https://github.com/unoplatform/uno.fonts/blob/dev/djo%2Fdocs-sources/doc/font-mapping.md) for those glyphs.)

Re: pixel-level compatibility with border thickness etc, this is part of what needs testing. But we've just updated from v1 styles to v2 styles and we didn't need to change the font, so seemingly whatever works with v2 also works with v1.

**Comment by robloo** [comment] 2021-09-28 16:48
> This will require a fairly thorough review as there's a lot of scope for hard-to-spot regressions.

I don't think a really 'full' review is needed. The font is not created manually. Mapping between icons can be visually compared using the SymbolIconManager itself as well. My thinking here was to check the main ones -- such as CheckBox -- and spot check a few others. Then release only for v2 Styles and let the community spot additional differences. V2 Styles was just released so we wouldn't be breaking many existing apps.

> There's not really a way to do that. Also I'm not sure why you want to?

Because we don't want to risk breaking existing apps using Fluent version 1 and in-box 'classic' styles. This new font should be used only for Fluent version 2 to start until there is a lot of feedback. I highly doubt there is no way to do this. The font can be bundled along with the others and then changed ONLY in fluent v2 theme resources:

```
x:Key="SymbolThemeFontFamily">ms-appx:///Assets/Fonts/WinSymbols3.ttf#Regular</android:FontFamily
```

> I think the reason would be that v2 styles and V1 styles have different border thickness/corner radii and the icon styling also matches a specific version.

Yes this is the other reason as well. The design language between Segoe Fluent and Segoe MDL2 is drastically different. Apps really don't want to mix-and-match from a design perspective.

> Re: icon styling in an aesthetic sense, all the glyphs referred to by the v1 styles are already sourced from Fluent UI System Icons in the current font, so nothing should change there. (Assuming any new font keeps the mappings here for those glyphs.)

After having gone through the entire font I can tell you there are a lot of glyphs sourced from Line Awesome and WinJS Symbols as well. Saying that the existing Uno font already uses Fluent UI System Icons is not accurate in several cases. Additionally, your provided mappings (while helpful) were a tiny fraction of the overall mapping file. Some of them were also inaccurate so had to be corrected. Using the linked mapping as the source of truth isn't a good idea. This mapping is far more accurate and complete: https://github.com/robloo/SymbolIconManager/blob/main/Source/Data/Mappings/SegoeFluent.json

> Re: pixel-level compatibility with border thickness etc, this is part of what needs testing. 

Yes, agreed.

> But we've just updated from v1 styles to v2 styles and we didn't need to change the font, so seemingly whatever works with v2 also works with v1.

I disagree here. Again, the design language between v2 and v1 is quite a bit different. Long-term, the replacement fonts should reflect that difference in design. They really are not equivalent from a designer perspective.

**Comment by davidjohnoliver** [comment] 2021-09-28 17:38
@robloo 
> After having gone through the entire font I can tell you there are a lot of glyphs sourced from Line Awesome and WinJS Symbols as well. 

Yes, most definitely. But all the glyphs **referred to by the v1 styles** should have been sourced from Fluent UI System Icons.

> The font can be bundled along with the others and then changed ONLY in fluent v2 theme resources:

Yeah fair enough, it's probably doable to restrict it to v2. That doesn't mean it doesn't need to be thoroughly tested though. V2 is the new default, and will be used by existing apps that update to the latest versions of Uno (and WinUI 2 on Windows) that don't explicitly downgrade the style version.

> I disagree here. Again, the design language between v2 and v1 is quite a bit different. 

Just to clarify, I'm referring to pixel-alignment types of issues when I say that there don't seem to be style-version-specific adjustments needed.

**Comment by robloo** [comment] 2021-09-28 17:49
> Yes, most definitely. But all the glyphs referred to by the v1 styles should have been sourced from Fluent UI System Icons.

Ah, ok, I understand what you mean. In that sense they should be equivalent. However, I wasn't able to use the CheckBox custom SVG's because Apache -> MIT isn't doable. I can make custom pixel-perfect replacements though for the problem areas.

> That doesn't mean it doesn't need to be thoroughly tested though. V2 is the new default

Agreed for sure, as much testing as possible. However, again, due to the automated way the font was build I don't think this has to be quite so heavily tested. If a few glyphs are out of alignment they likely all are. Fixes apply everywhere.

> V2 is the new default, and will be used by existing apps that update to the latest versions of Uno (and WinUI 2 on Windows) that don't explicitly downgrade the style version.

Yes, however, I think a lot of apps explicitly downgrade to version 1 styles. That is almost mandatory until you are ready to update all custom styles as well. If you have a lot of internal apps that don't control this and just use the default, I understand caution.

> V2 is the new default, and will be used by existing apps that update to the latest versions of Uno (and WinUI 2 on Windows) that don't explicitly downgrade the style version.

Ok, I also understand you are referring heavily to the glyphs referenced in the style resources themselves as well. I was more thinking of the entire font.

**Comment by robloo** [comment] 2021-10-20 15:52
@davidjohnoliver Will there be any resistance to merging a PR if I open one in a few weeks to close this? There are over 800 icons in the replacement font now which is larger than Uno's existing font. It should be a better replacement across the board -- minus a few custom fonts.

**Comment by jeromelaban** [comment] 2021-10-20 18:59
Thanks for your work robloo, that's very nice. First, let's make an update in the uno.fonts repository. We'll then have to adjust uno and see the v1/v2 differences and changes in behavior.

**Comment by robloo** [comment] 2021-10-21 14:34
At one point it was planned to automate the font building process and release the tooling in Uno.Fonts. Without that, its the same information but duplicated that is in Uno itself. 

My plan was to add the new font .ttf to Uno itself and then switch to using it in the SymbolThemeFontFamily resource for Fluent v2 only. The font build process will remain in the separate repository for the SymbolIconManager.

**Comment by robloo** [comment] 2022-01-29 19:15
@jeromelaban Please let me know your latest thinking on these ideas. I think my biggest concern is the tool I ended up making is quite a bit more powerful than what you need here. It doesn't make much sense to pull that into Uno Fonts and it would also be an unnecessary duplication of code. Just using the font file is no different than what is done today. The tool is still MIT licensed and publicly available so there really isn't much risk on your end and it's not really a new dependency. It can also be made a submodule I suppose as well.

**Comment by MartinZikmund** [comment] 2022-03-04 10:01
@robloo While using the font file directly is of course just a partial solution to the overall issue, it would already bring in a lot of the missing glyphs we really need, so I would vote for bringing in the ttf at least as the first step, would that work?

**Comment by robloo** [comment] 2022-03-04 14:37
> While using the font file directly is of course just a partial solution

Why would this be only a partial solution? The tool is finished and freely available to all projects. It just isn't in Uno's repo and I think since the tool is general purpose this makes more sense.

> so I would vote for bringing in the ttf at least as the first step, would that work?

Thats what I have been trying to do 😃 Its the Uno team that doesn't seem to want to do this.

**Comment by MartinZikmund** [comment] 2022-03-04 15:59
@robloo I meant partial in the sense that the ttfs will need to be updated later (e.g. when MSFT updates the design language - but that might happen only in some longer timeframe now I guess). Are all the current Segoe UI Symbol glyphs in the font or are there missing pieces?

I definitely vote for bringing it in, as it will be a big improvement. What do you think @francoistanguay ?

**Comment by robloo** [comment] 2022-03-04 16:35
> Are all the current Segoe UI Symbol glyphs in the font or are there missing pieces?

Microsoft doesn't publicly release all glyphs they use in Segoe Fluent. Fluent UI System has many, and I use what I can, however windows specific icons like explorer are unavailable.

The mapping was current as of last year, would always appreciate a second review and patches for any gaps though. Overall coverage is currently wider than what Uno has.

**Comment by MartinZikmund** [comment] 2022-04-16 13:06
@robloo I have tried out the `WinSymbols3.ttf` in Samples app, but noticed some of the `SymbolIcon` symbols are not supported (showing rectangle) - for example `OpenPane`, `ClosePane`, etc. I would say we need to have coverage for Symbols, as that is what we support with the existing icon font. Is there a source where we could fill in these missing ones? I am happy to help out if you give me some pointers. In worst case we could use the older "MDL2" icons for those missing ones

**Comment by robloo** [comment] 2022-04-16 15:47
@MartinZikmund Yes, the tool was designed to make editing the fonts a lot easier. If you run the app itself and go to the Icon Mapping view you can edit things visually. The app is a utility though so is quite unpolished in places but the Icon Mapping view is the most user-friendly. The docs at the links below explain this in a bit more detail:

https://github.com/robloo/SymbolIconManager/blob/main/Docs/UserGuide.md
https://github.com/robloo/SymbolIconManager/blob/main/Docs/IconMapping.md#addingediting-a-mapping

Separately, if you want to just edit the mapping file directly you can in JSON: https://github.com/robloo/SymbolIconManager/blob/main/Source/Data/Mappings/SegoeFluent.json

If you just tell me the source Unicode point and font I can set all that up though. Microsoft continuously makes breaking changes in the Fluent UI System Icons repository so it almost never builds after a few months.

If you are doing a detailed comparison of the font be advised that the Fluent UI System Icons have a margin around the glyphs (from the SVG itself) while the Segoe Fluent Icon glyphs do not. This means the size will never be exactly the same right now. I have been debating ideas to improve this but so far it has been good enough.

**Comment by MartinZikmund** [comment] 2022-04-17 09:36
I will probably be able to get to this properly after 4.2 release, but my main concern would be to make sure the icons which are already supported by Uno icon font are also included in this new one, because apart from that your font has already better coverage overall.

Regarding the margin - is that uniformly the same everywhere? As then it could be easier to adjust.

**Comment by robloo** [comment] 2022-04-17 13:44
I would just note that I've already mapped all the matching glyphs I could find. I'm sure I missed a few but I would lower your expectations a bit in terms of full symbol coverage. Equivalents for some glyphs simply do not exist in Fluent UI System Icons.

In terms of glyph margin, this is uniform in the Fluent UI System Icons so there it is possible to remove it with a matrix transform in FontForge. However, the real problem is SegoeFluent which has inconsistent margins. Sometimes a glyph has some, most times it does not. Configuring this for each glyph is not trivial and would require manual steps as far as I see. I not willing to do that for each glyph.

**Closed** 2022-09-07 12:23 UTC
Labels: kind/enhancement, project/styling, difficulty/medium

**Comment by MartinZikmund** [comment] 2022-09-07 14:41
Hi @robloo! In the end designers took a different approach, @NVLudwig can provide more info, but AFAIK he and Dominique were using Illustrator with a font builder plugin and IcoMoon app to generate the resulting font files.

**Comment by NVLudwig** [comment] 2022-09-07 15:37
@robloo We used Fontlab8 to get the unicode mapping info of each glyph. We brought the info into illustrator to keep the mapping identical using the new glyphs

**Comment by robloo** [comment] 2022-09-07 15:52
Ok, thanks for the clarification. This was essentially all done manually in illustrator then. That slightly improves alignment and things. However, it still has maintainability issues I would think. Perhaps not if illustrator can generate an entire font and source files are easily editable. 

One of the points from the discussion before was community should be able to add symbols or fix things in a PR. That should then show change tracking ideally not in a binary blob.

Anyway, glad you all found something that works for you. The new icons will be an improvement.

**Comment by MartinZikmund** [comment] 2022-09-07 19:26
> Ok, thanks for the clarification. This was essentially all done manually in illustrator then. That slightly improves alignment and things. However, it still has maintainability issues I would think. Perhaps not if illustrator can generate an entire font and source files are easily editable. 
> 
> One of the points from the discussion before was community should be able to add symbols or fix things in a PR. That should then show change tracking ideally not in a binary blob.
> 
> Anyway, glad you all found something that works for you. The new icons will be an improvement. 

@robloo  I think the issue for automated glyph management is still open (different one)

**Comment by NVLudwig** [comment] 2022-09-08 15:17
@robloo Definitely interested in crowd sourcing this, it's a smart idea.
