### ISSUE TITLE
[Playground][Wasm] Numberbox- The Down arrow sign is not displaying correctly.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#9174] opened 2022-06-29 17:52 UTC
### Current behavior

![arrow sign playground issue - Outlook](https://user-images.githubusercontent.com/74563602/176502712-f441d448-e983-447a-bf20-dc5012a99525.png)

https://user-images.githubusercontent.com/74563602/176502576-17e9bb4f-af39-4bc8-8a04-6d4c38c5b0d8.mp4

### Expected behavior

![arrow sign playground - Outlook](https://user-images.githubusercontent.com/74563602/176502738-ebb1c508-21ea-4088-8f10-4366b24bc43c.png)

### How to reproduce it (as minimally and precisely as possible)

1. Visit https://playgroundcanary.z19.web.core.windows.net/#passwordbox
2. Go to the Snippets Listview.
3. Click on the 'Numberbox' snippets option.
4. Observe that the Down Arrow sign( to decrease number) is not properly displayed.

### Affected platforms

WebAssembly

**Comment by jeromelaban** [comment] 2022-06-29 17:54
This is a duplicate of https://github.com/unoplatform/uno/issues/8679. Let's follow the other one.

**Closed by jeromelaban** 2022-06-29 17:54 UTC
Labels: kind/bug, platform/wasm, triage/untriaged, area/canary, difficulty/tbd
