### ISSUE TITLE
Compiler error 'name 'Loading' does not exist in the current context' in Flyout generated code

### ISSUE THREAD

**Issue by ttustonic** [unoplatform/uno#9437] opened 2022-08-08 03:27 UTC
### Current behavior

I have a very simple Flyout test 
```
<Flyout ...>
    <Grid Background="{StaticResource PinkBrush}">
    </Grid>
```
It generates compiler error in generated page:
`The name 'Loading' does not exist in the current context	Barcode.Mobile (net6.0-android)	....\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.XamlGenerator.XamlCodeGenerator\SettingsFlyout_61cfbdd7716f90ec3755eae352edda7b.cs`

It works fine when I remove StaticResource= part.
I tried to reproduce the issue in the new clean UWP net6 project, installed all the same packages, but it works in the test project.

I noticed a difference, however. In the generated file in the real project, at the end of generated InitializeComponent, there's a part:
```
Loading += delegate
{
Bindings.UpdateResources();
}
```
which is not present in the test project.

### Expected behavior

No compiler error.

### Works on UWP/WinUI

Yes

### NuGet package version(s)

```
<PackageReference Include="Uno.Extensions.Serialization" Version="2.2.0-dev.79" />
<PackageReference Include="Uno.Extensions.Serialization.Http" Version="2.2.0-dev.79" />
<PackageReference Include="CommunityToolkit.Mvvm" Version="8.0.0" />
<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="6.0.0" />
<PackageReference Include="Uno.Extensions.Configuration" Version="2.2.0-dev.79" />
<PackageReference Include="Uno.Extensions.Core" Version="2.2.0-dev.79" />
<PackageReference Include="Uno.Extensions.Hosting.UWP" Version="2.2.0-dev.79" />
<PackageReference Include="Uno.Extensions.Logging.UWP" Version="2.2.0-dev.79" />
<PackageReference Include="Uno.Extensions.Navigation" Version="2.2.0-dev.79" />
<PackageReference Include="Uno.Extensions.Navigation.Toolkit.UI" Version="2.2.0-dev.79" />
<PackageReference Include="Uno.Extensions.Navigation.UI" Version="2.2.0-dev.79" />
<PackageReference Include="Uno.Material" Version="2.2.0" />
<PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI" Version="7.1.11" />
<PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls.DataGrid" Version="7.1.11" />
<PackageReference Include="Uno.Extensions.Serialization" Version="2.2.0-dev.79" />
<PackageReference Include="Uno.Toolkit.UI" Version="2.2.0" />
<PackageReference Include="Uno.Toolkit.UI.Material" Version="2.2.0" />
<PackageReference Include="Uno.UI" Version="4.4.13" />
<PackageReference Include="Uno.UI.RemoteControl" Version="4.4.13" Condition="'$(Configuration)'=='Debug'" />
<PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.4.13" />
<PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />
```

### Affected platforms

Android

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment] 2022-08-08 13:08
Thanks for the report. Could you provide a complete repro sample to make sure we're validating against the same issue?

**Comment by ttustonic** [comment] 2022-08-08 21:47
Hello
Here it is. To see the error, add
`Background="{StaticResource PinkBrush}" `
to the Grid in SettingsFlyout.xaml.
Sometimes it compiles OK after I clean solution and exit VS, but it comes back on the next compile.

Thanks, Tom

[FlyoutTest.zip](https://github.com/unoplatform/uno/files/9285211/FlyoutTest.zip)

**Comment by jeromelaban** [comment] 2022-08-15 17:31
Thanks, this helped, we can repro on our end.

**Comment by jeromelaban** [comment] 2022-08-16 20:27
The repro helped immensely, thanks. The issue is actually in the name of your class, where it matches another type in another namespace, causing the issue you've found.

As a workaround, you can name your flyout class differently, but you can also wait for https://github.com/unoplatform/uno/pull/9522 to be merged.

**Comment by ttustonic** [comment] 2022-08-16 22:44
This works, thanks!

**Closed** 2022-08-23 18:23 UTC
Labels: kind/bug, area/code-generation, project/binding, difficulty/medium
