### ISSUE TITLE
[iOS][Android][Wasm] The space between the text and the clear button is too wide

### ISSUE THREAD

**Issue by carlh98** [unoplatform/uno#2430] opened 2020-01-03 23:34 UTC
## Current behavior

When you put the focus on the TextBoxErrorControl, the clear button appears and the text is push too far from the clear button.

## Expected behavior

When you put the focus on the TextBoxErrorControl, the clear button appears and the text is moved next to the button

## How to reproduce it (as minimally and precisely as possible)

Sample:
[TextBoxAlignmentIssueSample.zip](https://github.com/unoplatform/uno/files/4021245/TextBoxAlignmentIssueSample.zip)

## Environment

Nuget Package:
Uno.UI

Package Version(s):
2.1.0-dev.509

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by carlh98** [comment] 2020-01-13 17:03
Framework work item:
https://dev.azure.com/nventive/Umbrella/_workitems/edit/170666

**Comment by carlh98** [comment] 2020-01-13 17:18
Framework work item:
https://dev.azure.com/nventive/Umbrella/_workitems/edit/169759

**Comment by carldebilly** [comment] 2020-02-04 15:52
@carlh98
It has not been tested yet, but the package [Uno.UI v`2.1.0-dev.1090`](https://www.nuget.org/packages/Uno.UI/2.1.0-dev.1090) contains fixes related to this issue and it should be tested again on this version.

**Comment by carlh98** [comment] 2020-02-04 16:22
@carldebilly 
There's a new regression for the sample TextBoxAlignmentIssueSample.zip with Uno.UI 2.1.0-dev.109, the control is present in the View Hierarchy but not visible in the app

**Comment by carldebilly** [comment] 2020-02-27 15:02
[PR #2679](https://github.com/unoplatform/uno/pull/2679) has been merged, producing `Uno.UI` v`2.1.0-dev.1371` which should be available soon on Nuget there: <https://www.nuget.org/packages/Uno.UI/2.1.0-dev.1371>. This issue could be fixed by those changes and need to be tested again with this version of `Uno.UI`.

**Comment by carlh98** [comment] 2020-02-27 18:56
@carldebilly 
With Uno.UI 2.1.0-dev.1371:
(Regression) In iOS, the TextBoxErrorControl does not appear on screen, you can click on the TextBoxErrorControl area where it's supposed to appear to show the tactile keyboard
(Same) In Android and Wasm it's the same as 2.1.0-dev.509

**Comment by carldebilly** [comment] 2020-03-04 15:55
# Invesgations result in the problem.
I found the cause of the problem: it's a **resource issue**.

==>  May be fixed by PR https://github.com/unoplatform/uno/pull/1766.  @davidjohnoliver ?

## Explanation
1. There's a **Default Style** on `<Button>` defined this way:
    ```xml
 	<Style x:Key="DefaultButtonStyle" TargetType="Button">
		<Setter Property="MinWidth"
				Value="128" />
 	</Style>
	<Style TargetType="Button"
		   BasedOn="{StaticResource DefaultButtonStyle}" />
    ```
    (more properties are defined... but they are not relevant to this bug)
2. The control is defined this way...
    ```xml
    <Button Style="{StaticResource DeleteButtonStyle}"
		Width="24"
		Padding="4,0,0,0"
		HorizontalAlignment="Right" />
    ```
3.  The `DeleteButtonStyle` is defined like that...
    ```xml
	<Style x:Key="DeleteButtonStyle"
		   TargetType="Button">
		<Setter Property="Width"
				Value="40" />
		<Setter Property="Padding"
				Value="0" />
		<Setter Property="Margin"
				Value="0" />
 	</Style>
    ```
**On UWP**, the result control will get a `MinWidth` of `0`... like if the `DeleteButtonStyle` were not having an implicit `BaseOn` on the default style, which is the case **on Uno Platform**. Actually, on Uno, the `<Button>` will have a `MinWidth=128`, causing the reported bug.

**Closed** 2020-06-03 18:20 UTC
Labels: area/ios, kind/bug, kind/regression
