### ISSUE TITLE
[Skia] `ComboBox` is not displaying items in popup when running on an RPi

### ISSUE THREAD

**Issue by highspeeder** [unoplatform/uno#7121] opened 2021-09-17 03:03 UTC
### Current behavior

https://platform.uno/docs/articles/getting-started-tutorial-2.html
I created a ComboBox according to the tutorial on the page above and ran it on Raspberrypi.
Combobox is displayed well, but the item doesn't seem to be bound.

MainPage.xaml
 <Page
    x:Class="UnoApp.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:converters="using:UnoApp.Converters"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:ios="http://nventive.com/ios"
    mc:Ignorable="d ios">

    <Page.Resources>
        <converters:StringFormatConverter x:Key="StringFormatConverter" />
    </Page.Resources>

    <Grid Background="{ThemeResource ApplicationPageBackgroundThemeBrush}" RowSpacing="8">
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" />
            <RowDefinition Height="Auto" />
            <RowDefinition Height="Auto" />
            <RowDefinition Height="Auto" />
            <RowDefinition Height="Auto" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>

        <StackPanel Grid.Row="0" Orientation="Horizontal" Background="LightGray" Padding="5">
            <Canvas Background="Blue" Width="10" x:Name="IssueTypeIndicator" />
            <TextBlock Text="{x:Bind Item.Id}" Margin="6,0" VerticalAlignment="Center" />
            <ComboBox x:Name="IssueTypeBox"
                    ItemsSource="{x:Bind IssueTypeList}"
                    SelectedItem="{x:Bind Item.Type, Mode=TwoWay}"
                    SelectionChanged="IssueType_SelectionChanged"
                    PlaceholderText="Enter the Issue Type"
                    HorizontalAlignment="Stretch"
                    Margin="10,0,0,0">
            </ComboBox>
        </StackPanel>
    </Grid>
</Page> 

MainPage.xaml.cs

```using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using UnoApp.Model;
using Windows.Foundation;
using Windows.Foundation.Collections;
using Windows.UI;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Controls.Primitives;
using Windows.UI.Xaml.Data;
using Windows.UI.Xaml.Input;
using Windows.UI.Xaml.Media;
using Windows.UI.Xaml.Navigation;

// The Blank Page item template is documented at http://go.microsoft.com/fwlink/?LinkId=402352&clcid=0x409

namespace UnoApp
{
    /// <summary>
    /// An empty page that can be used on its own or navigated to within a Frame.
    /// </summary>
    public sealed partial class MainPage : Page
    {
        public static readonly DependencyProperty IssueItemProperty =
            DependencyProperty.Register(nameof(Item), typeof(IssueItem), typeof(MainPage), new PropertyMetadata(default(IssueItem)));

        public IssueItem Item
        {
            get => (IssueItem)GetValue(IssueItemProperty);
            set => SetValue(IssueItemProperty, value);
        }

        public IssueType[] IssueTypeList => new []
        {
            IssueType.Bug,
            IssueType.Feature,
            IssueType.Issue,
            IssueType.Task
        };

        public IssueStatus[] StatusList => new[]
        {
            IssueStatus.Icebox,
            IssueStatus.Planned,
            IssueStatus.WIP,
            IssueStatus.Done,
            IssueStatus.Removed
        };
        
        public MainPage()
        {
            this.InitializeComponent();

            Item = new IssueItem
            {
                Id = 1232,
                Title = "Getting Started",
                Description = @"Create a page to enter Issues that we need to work on.

                                ## Acceptance Criteria
                                
                                - Display the issue Id
                                - Provide an ability to select the issue Type (i.e. Bug, Feature, etc)
                                - Include an Issue Title
                                - Include a full issue description with support for Markdown
                                - Include an issue effort
                                - Include an ability for a developer to update the Status (i.e Icebox, WIP, etc)
                                
                                ## Additional Comments
                                
                                We would like to have a visual indicator for the type of issue as well as something to visualize the effort involved",
                Effort = 3,
                Status = IssueStatus.WIP,
                Type = IssueType.Feature,
                CreatedAt = new DateTimeOffset(2019, 04, 03, 08, 0, 0, TimeSpan.FromHours(-8)),
                StartedAt = new DateTimeOffset(2019, 04, 30, 08, 0, 0, TimeSpan.FromHours(-8))
            };
        }



        protected override void OnNavigatedTo(NavigationEventArgs e)
        {
        }


        // Provides a unique color based on the type of Issue
        private void IssueType_SelectionChanged(object sender, SelectionChangedEventArgs args)
        {
            var color = Colors.Red;
            switch (IssueTypeBox.SelectedItem)
            {
                case IssueType.Feature:
                    color = Colors.Green;
                    break;
                case IssueType.Issue:
                    color = Colors.Blue;
                    break;
                case IssueType.Task:
                    color = Colors.Yellow;
                    break;
            }
            IssueTypeIndicator.Background = new SolidColorBrush(color);
        }
    }
}
```

IssueItem.cs in Model Folder

```using MvvmHelpers;
using System;
using System.Collections.Generic;
using System.Text;

namespace UnoApp.Model
{
    public class IssueItem : ObservableObject
    {
        private int id;
        public int Id
        {
            get => id;
            set => SetProperty(ref id, value);
        }

        private IssueType type;
        public IssueType Type
        {
            get => type;
            set => SetProperty(ref type, value);
        }

        private string title;
        public string Title
        {
            get => title;
            set => SetProperty(ref title, value);
        }

        private string description;
        public string Description
        {
            get => description;
            set => SetProperty(ref description, value);
        }

        private IssueStatus status;
        public IssueStatus Status
        {
            get => status;
            set => SetProperty(ref status, value);
        }

        private int effort;
        public int Effort
        {
            get => effort;
            set => SetProperty(ref effort, value);
        }

        private DateTimeOffset createdAt = DateTimeOffset.Now.ToLocalTime();
        public DateTimeOffset CreatedAt
        {
            get => createdAt;
            set => SetProperty(ref createdAt, value);
        }

        private DateTimeOffset? startedAt;
        public DateTimeOffset? StartedAt
        {
            get => startedAt;
            set => SetProperty(ref startedAt, value);
        }

        private DateTimeOffset? completedAt;
        public DateTimeOffset? CompletedAt
        {
            get => completedAt;
            set => SetProperty(ref completedAt, value);
        }
    }

    public enum IssueType
    {
        Bug,
        Issue,
        Task,
        Feature
    }

    public enum IssueStatus
    {
        Icebox,
        Planned,
        WIP,
        Done,
        Removed
    }
}
```

![1](https://user-images.githubusercontent.com/41020549/133715953-fc9fa0a2-060a-4ee0-9184-5dd61ea20062.PNG)

![2](https://user-images.githubusercontent.com/41020549/133715958-20071e8e-e4c4-42c0-a52b-978fa94b6ad1.PNG)

### Expected behavior

The bound Enum should be listed in the combobox.

### How to reproduce it (as minimally and precisely as possible)

1. Create an UnoPlatform project in Visual Studio 2019

2. Follow the tutorial on the above page.

3. Build and deploy, then run on Raspberry Pi 

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

in Solution:
![3](https://user-images.githubusercontent.com/41020549/133717446-894c09d0-5b8c-4b3e-a576-6cadf0e6c1fd.PNG)

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio Code

### IDE version

1.60.1

**Comment by jeromelaban** [comment] 2021-09-21 14:29
Thanks for the report. 

I'm not able to reproduce the issue. Can you specify which distribution you're using on the Pi ? This may be related to the default fonts installed on your device.

**Comment by highspeeder** [comment] 2021-09-23 01:50
well..
OS is rassbian 32bit full version(Released 2021-05-07),
In addition to the default font, 'sudo apt-get install ttf-mscorefonts-installer' was installed, and the uno-fluentui-assets.ttf font in the Asset folder in the Skia.Gtk project was also installed.

**Comment by highspeeder** [comment] 2021-09-23 01:50
> Thanks for the report.
> 
> I'm not able to reproduce the issue. Can you specify which distribution you're using on the Pi ? This may be related to the default fonts installed on your device.

well..
OS is rassbian 32bit full version(Released 2021-05-07),
In addition to the default font, 'sudo apt-get install ttf-mscorefonts-installer' was installed, and the uno-fluentui-assets.ttf font in the Asset folder in the Skia.Gtk project was also installed.

**Comment by highspeeder** [comment] 2021-09-23 02:11
FYI, UWP works just fine.
![1](https://user-images.githubusercontent.com/41020549/134445259-7667ae60-bfad-4a90-9727-dc477b48500b.PNG)

**Comment by jeromelaban** [comment] 2021-09-23 13:22
Thanks. Can you try running the Gtk head on Windows as well to see if something different happens for you ?

**Comment by highspeeder** [comment] 2021-09-24 01:37
On windows it works fine.

![1](https://user-images.githubusercontent.com/41020549/134605280-0f291cf1-f44b-4543-87e1-1174d77ebea0.PNG)

**Comment by jeromelaban** [comment] 2021-09-24 02:02
Thanks. On the Pi, what are you seeing in the console when you launch the app?

**Comment by highspeeder** [comment] 2021-09-24 23:33
![1](https://user-images.githubusercontent.com/41020549/134749413-70a9a855-c352-4e65-b798-e35c5037cfe8.PNG)
![2](https://user-images.githubusercontent.com/41020549/134749417-eb231821-3e14-4be7-8da9-328e52e06e31.PNG)
![3](https://user-images.githubusercontent.com/41020549/134749418-d52e8fe0-bc19-4be9-8960-03210c6c7f0e.PNG)
![4](https://user-images.githubusercontent.com/41020549/134749419-061cc7fe-b3a1-4812-a978-0a9d24a574cc.PNG)
![5](https://user-images.githubusercontent.com/41020549/134749420-d385e2c6-6bdd-4543-895b-b95596174545.PNG)

**Comment by highspeeder** [comment] 2021-09-25 15:51
> Thanks. On the Pi, what are you seeing in the console when you launch the app?

![1](https://user-images.githubusercontent.com/41020549/134749413-70a9a855-c352-4e65-b798-e35c5037cfe8.PNG)
![2](https://user-images.githubusercontent.com/41020549/134749417-eb231821-3e14-4be7-8da9-328e52e06e31.PNG)
![3](https://user-images.githubusercontent.com/41020549/134749418-d52e8fe0-bc19-4be9-8960-03210c6c7f0e.PNG)
![4](https://user-images.githubusercontent.com/41020549/134749419-061cc7fe-b3a1-4812-a978-0a9d24a574cc.PNG)
![5](https://user-images.githubusercontent.com/41020549/134749420-d385e2c6-6bdd-4543-895b-b95596174545.PNG)

**Comment by jeromelaban** [comment] 2021-09-27 00:21
Thanks. I would suspect this issue to be related to https://github.com/unoplatform/uno/issues/6441, where some fonts are not being resolved properly.

You may try overriding the `ComboBox` item template and [provide your own template](https://asp-net-example.blogspot.com/2017/01/uwp-combobox-itemtemplate-example.html), explicitly specifying a font family.

**Comment by highspeeder** [comment] 2021-09-29 01:04
> Thanks. I would suspect this issue to be related to #6441, where some fonts are not being resolved properly.
> 
> You may try overriding the `ComboBox` item template and [provide your own template](https://asp-net-example.blogspot.com/2017/01/uwp-combobox-itemtemplate-example.html), explicitly specifying a font family.

It works fine since I specify the font.

**Comment by highspeeder** [comment] 2021-09-29 03:41
I faced another problem.

SelectedItem is displayed in Combobox, but text does not appear when Combobox is clicked.
![1](https://user-images.githubusercontent.com/41020549/135199355-bac36523-3f4b-4797-adf4-ed16a20d2d48.PNG)

![2](https://user-images.githubusercontent.com/41020549/135199360-7cc60cff-d9a5-4dfa-8e81-7bea41b4de4b.PNG)

**Comment by jeromelaban** [comment] 2023-09-20 19:20
This is now fixed.

**Closed by jeromelaban** 2023-09-20 19:20 UTC
Labels: kind/bug, platform/linux 🐧, area/skia ✏️, area/popups 💬, triage/potentially-fixed, area/combobox
