### ISSUE TITLE
[WASM] Some ButtonNative UI Tests don't pass

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno#2664] opened 2020-02-17 20:31 UTC
## Current behavior 
Some Button UI Tests don't pass when using the VerifyTextBlockText method:
- ButtonNative_Button01_Validation
- ButtonNative_Button02_Validation
- ButtonNative_ToggleSwitch_Validation

> Message: 
      Expected: "No value"
      But was:  null
    
 > Stack Trace: 
    Button_Tests.VerifyTextBlockText(String text1, String text2, String text3) line 266
    Button_Tests.ButtonNative_Button02_Validation() line 299

## Expected behavior

All the UI Tests for Button should pass for WASM

## How to reproduce it (as minimally and precisely as possible)
Test for WASM (in **UnoSamples_Tests.Button_IsEnabled_Automated.cs**):
- [ ] ButtonNative_Button01_Validation
- [ ] ButtonNative_Button02_Validation
- [ ] ButtonNative_ToggleSwitch_Validation

## Environment

Nuget Package: Uno.UI

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [X] 2019 (version: 16.4.1)
- [ ] for Mac (version: )

## Anything else we need to know?
Related to PR #2553, WASM is ignored for now for these tests

**Comment by Youssef1313** [comment] 2021-08-22 06:58
It looks like those tests were never merged. Per https://github.com/unoplatform/uno/pull/2553#issuecomment-768258708, these behaviors are already tested. I'll add them locally and see if they passes.

**Comment by Youssef1313** [comment] 2021-08-22 07:08
I confirmed they're passing locally on Wasm. @MartinZikmund @davidjohnoliver Can we close this one?

**Comment by davidjohnoliver** [comment] 2021-08-30 16:32
Yes, let's close this.

**Closed by davidjohnoliver** 2021-08-30 16:32 UTC
Labels: kind/bug, platform/wasm, project/core-tools, difficulty/starter, area/eu
