### ISSUE TITLE
[Android] TextTrimming not always applied 

### ISSUE THREAD

**Issue by queequac** [unoplatform/uno#5185] opened 2021-02-08 21:59 UTC
TextBlock's TextTrimming is not always applied. This seems to be the case especially when placed somewhere within a Grid where the cell makes use of "auto" or within a StackPanel.

## Current behavior
Text is simply clipped at the end.
Note: A cell itself is correctly layouted (i.e. takes only a single line of space when row definition's height is set to "auto")

## Expected behavior
Text is trimmed correctly with end ellipses like under Windows/UWP.

## How to reproduce it (as minimally and precisely as possible)

```
<Grid HorizontalAlignment="Stretch" VerticalAlignment="Stretch">
    <Grid.RowDefinitions>
      <RowDefinition Height="Auto"/>
      <RowDefinition Height="*"/>
    </Grid.RowDefinitions>
      <TextBlock Grid.Row="0" TextTrimming="CharacterEllipsis" Margin="8,0,8,16">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra rhoncus accumsan. Fusce aliquam, nunc in commodo porta, justo sem accumsan ante, id laoreet lectus lectus ac velit. Aenean feugiat mauris ut ligula ornare, vel commodo dolor ullamcorper. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Fusce ut felis vel purus ultricies bibendum ac id eros. Donec at metus faucibus, suscipit ipsum ut, consectetur massa. Phasellus tempor, enim eget maximus ornare, nisl est consequat nisi, nec viverra lectus lacus sed odio. Maecenas arcu nibh, faucibus a aliquam sit amet, imperdiet at ex. Proin vestibulum velit in nibh volutpat, eu iaculis justo gravida. Nunc et orci mi. Morbi nunc velit, placerat sit amet urna et, mattis porta urna. Quisque sagittis mi eget vestibulum mollis.
      </TextBlock>
      <Border Background="Red" Margin="3" BorderThickness="2" BorderBrush="Blue" Grid.Row="1"/>
  </Grid>

```
## Workaround
Set the RowDefinition's Height to a fixed size or *. While the latter is not a good workaround at all, also the first solutions is not really good, since knowledge about the content's fontsize, padding, etc. has to be considered and hardcoded.

## Environment
Checked with Android 8 to 10, all have the same behavior.

Nuget Package:
- [X] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.4

Affected platform(s):

- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: 16.8.4 )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by jeromelaban** [comment] 2021-02-09 17:59
@carldebilly  Looks like this is related to #4231

**Comment by queequac** [comment] 2021-02-09 19:46
@jeromelaban Maybe it's related to Grid, maybe it is not.😉 As mentioned above, the layout looks correct and the StackPanel does also prevent end ellipses. Whenever the surrounding does not predetermine available space but the text itself has to provide its size, they seem to be missing.

**Comment by carldebilly** [comment] 2021-07-06 17:42
Not able to reproduce the problem.  It's probably fixed by https://github.com/unoplatform/uno/pull/5811

**Closed by carldebilly** 2021-07-06 17:42 UTC
Labels: difficulty/medium, kind/bug, project/text
