### ISSUE TITLE
WASM Can't subscribe to FrameworkElement.DataContextChanged

### ISSUE THREAD

**Issue by ToddGlodek** [unoplatform/uno#4189] opened 2020-09-30 21:48 UTC
This is bug report to raise the problem addressed by bug report (  #1296 ) but limited to WASM whereas #1296 deals with iOS/Android

Current behavior
When subscribing to DataContextChanged event I get the following build error

Error CS0123 No overload for 'ExtendedTextControl_DataContextChanged' matches delegate 'TypedEventHandler<DependencyObject, DataContextChangedEventArgs>'

Expected behavior
You should be able to subscribe to DataContextChanged event on Android and IOS

How to reproduce it (as minimally and precisely as possible)
Simple Subscribe to DataContextChanged on any Framework element and try to build

## Workaround
As suggested by  @abrull 
> I just realized that on Android and iOS in the even handler the sender is DependencyObject and on UWP the sender is FrameworkElement so I just created different event handlers for each platform

I did it like this...
`
        public DrawingSurface()
        {
            this.InitializeComponent();
            DataContextChanged += this.DrawingSurface_DataContextChanged;
        }

#if __WASM__
        private void DrawingSurface_DataContextChanged(DependencyObject sender, DataContextChangedEventArgs args)
#else
        private void DrawingSurface_DataContextChanged(FrameworkElement sender, DataContextChangedEventArgs args)
            
#endif
        {
        }
`
## Environment

Nuget Package:   version 2.0.0 (Monday, May 11, 2020 (5/11/2020) )

- [X ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ X] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [X ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X ] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment] 2020-10-01 11:34
Thank you for the report! This issue is a duplicate of https://github.com/unoplatform/uno/issues/2870

**Closed by jeromelaban** 2020-10-01 11:34 UTC
Labels: kind/bug, triage/untriaged
