### ISSUE TITLE
Converter triggers ConvertBack

### ISSUE THREAD

**Issue by paulovila** [unoplatform/uno#8061] opened 2022-02-10 16:16 UTC
### Current behavior

There is behavior difference in the converter uwp vs. wasm : 
if you checkout [InlineTimePicker-master.zip](https://github.com/unoplatform/uno/files/8492068/InlineTimePicker-master.zip)  run it and type in the text box the following:
**23:4** 

you'll see that wasm fires a ConvertBack but UWP fires a Convert 

UWP 23:4
```
#########InlineTimeConverter convert null
#########InlineTimeConverter convertback null
#########InlineTimeConverter convertback null
#########InlineTimeConverter convertback null
#########InlineTimeConverter convertback 23 40
#########OnTimeValueChanged 3 updated value=10/02/2022 23:40:00
#########InlineTimeConverter convert 23:40:00
```
WASM 23:4
```
dotnet.js:1 #########InlineTimeConverter convert null
dotnet.js:1 #########InlineTimeConverter convertback null
dotnet.js:1 #########InlineTimeConverter convertback null
dotnet.js:1 #########InlineTimeConverter convertback null
dotnet.js:1 #########InlineTimeConverter convertback 23 40
dotnet.js:1 #########OnTimeValueChanged 3 updated value=10/02/2022 23:40:00
dotnet.js:1 #########InlineTimeConverter convertback 23 40
```
### Expected behavior
The converter should fire Convert (as opposed to ConvertBack) as part of the keyboard interaction and the converter binding.
The expected result is that the text gets updated with the value that the converter proposes, regardless that the user is typing on that text box.

### Works on UWP/WinUI
yes

### Affected platforms

WASM

**Comment by jeromelaban** [comment] 2022-06-06 03:44
This issue is a duplicate of https://github.com/unoplatform/uno/issues/8061. Let's keep track there.

**Closed by jeromelaban** 2022-06-06 03:44 UTC
Labels: kind/bug, project/binding
