### ISSUE TITLE
WebAssembly: VisualState is not applied correctly

### ISSUE THREAD

**Issue by Alex-DE-74** [unoplatform/uno#7885] opened 2022-01-21 16:29 UTC
### Current behavior

Depending on IsEnabled property of the TextBox their background should be changed to yellow (disabled) and to default color (other states) as defined in VisualState. This is not the case for WebAssembly, but works for WPF and UWP. The example is attached.

### Expected behavior

This should work for WebAssebly to.

### How to reproduce it (as minimally and precisely as possible)

Start example and toggle button.

### Works on UWP/WinUI

Yes/Yes

### Environment

Windows 10.
Chrome & Edge

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

17.0.5

**Comment by Alex-DE-74** [comment] 2022-01-21 16:33
[UnoTestApp1.zip](https://github.com/unoplatform/uno/files/7915238/UnoTestApp1.zip)
Code example

**Comment by jeromelaban** [comment] 2022-01-24 14:00
Thanks for the report! This is a duplicate of https://github.com/unoplatform/uno/issues/7791

**Closed by jeromelaban** 2022-01-24 14:00 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd

**Comment by Alex-DE-74** [comment] 2022-01-24 16:12
Excuse me, but what ist sthe currently resolution/workaround for WASM?

Am Mo., 24. Jan. 2022 um 15:00 Uhr schrieb Jérôme Laban <
***@***.***>:

**Comment by jeromelaban** [comment] 2022-01-24 19:13
You can follow the mentioned issue for up to date information.

**Comment by Alex-DE-74** [comment] 2022-01-24 23:35
Thank you. I already follow up, but have don't see the fix is actually
available and there is no ETA.

Jérôme Laban ***@***.***> schrieb am Mo., 24. Jan. 2022,
20:13:
