### ISSUE TITLE
[Gallery][Android/Wasm/Skia/iOS] All components menu list is getting blank when scrolling the list up and down for NavigationView.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#11960] opened 2023-04-13 03:05 UTC
### Current behavior

https://user-images.githubusercontent.com/74563602/231636429-ed89cab8-4488-4958-864e-37353d259669.mp4

### Expected behavior

https://user-images.githubusercontent.com/74563602/231636467-724cd42d-2a7b-4bfa-abd9-5302e424ddfe.MP4

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP.
2. Expand the menu list in Ui component, Ui Features sections.
3. Scroll up and down on the screen.
4. Notice that the UI component list is getting blank in between multiple times.

### Works on UWP/WinUI

None

### Affected platforms

Android

**Comment by agneszitte** [comment] 2023-04-27 20:23
@jeromelaban and @dr1rrb
After further investigation and tests on Gallery seem like the issue was introduced with **Uno.UI 4.9.0-dev.49** (Not able to reproduce it with 4.9.0-dev.43)
- **Uno.UI 4.9.0-dev.49 related merge PR:** https://dev.azure.com/uno-platform/Uno%20Platform/_build/results?buildId=72249&view=results
- **Uno.UI 4.9.0-dev.49 related PR:** https://github.com/unoplatform/uno/pull/11671/files
- **Uno.UI 4.9.0-dev.49 related Issue:** https://github.com/unoplatform/uno.chefs/issues/259

Since NavigationView also uses StackLayout it introduced the issue for the control for Android 

I have a hard time reproducing the issue outside of Gallery at the moment, so if we can take a look together @dr1rrb it will be really appreciated!

**Comment by agneszitte** [comment] 2023-04-27 21:07
@jeromelaban and @dr1rrb
Here are some additional info for the repro rate and affected platforms:
- ❌**Android: 100% repro**

- ❔**WASM:** unable to reproduce it on WASM locally or even when testing with the latest Canary (If you can confirm @sakshi173 please). Is it an error, that in the title we have WASM mentioned? (As in the description of the issue we only have Android for the affected platforms)

- ❌**Skia.GTK: 100% repro**
![image](https://user-images.githubusercontent.com/16295702/234987834-bb62bef7-4cb0-47c8-95e0-50f0e1d78b1c.png)

- ❌**iOS: 100% repro**
![image](https://user-images.githubusercontent.com/16295702/234989498-cf77af4a-2d2d-4002-bbe3-9eec93fa11af.png)

- ✔️**Windows:** not affected

***Note: You need to go up and down a few times while scrolling the content of the NavigationView to easily reproduce the issue**

**Comment by sakshi173** [comment] 2023-04-27 21:48
@dr1rrb and @agneszitte, I am able to reproduce this bug for Wasm and attached is the video for Wasm, please let me know your views.

https://user-images.githubusercontent.com/74563602/234998292-1d2edbd9-90d7-48bb-a240-3a90d82e5a51.mp4

**Comment by dr1rrb** [comment] 2023-05-08 14:39
THis has been fixed by https://github.com/unoplatform/uno/pull/12101

**Closed by dr1rrb** 2023-05-08 14:39 UTC
Labels: kind/bug, platform/android, triage/untriaged, area/canary, difficulty/tbd
