### ISSUE TITLE
dotnet new unoapp generates an extra "WinUI" folder

### ISSUE THREAD

**Issue by Xiaoy312** [unoplatform/uno#10541] opened 2022-11-22 23:37 UTC
### Current behavior

dotnet new unoapp generates an extra "WinUI" folder

### Expected behavior

^ should not happen

### How to reproduce it (as minimally and precisely as possible)

```
dotnet new -i Uno.ProjectTemplates.Dotnet::4.6.19
dotnet new unoapp -n unoapp
dir unoapp
 Volume in drive D is Data
 Volume Serial Number is 84BF-0AC0

 Directory of D:\code\uno\tests\templates-tests\unoapp

11/22/2022  05:46 PM    <DIR>          .
11/22/2022  05:46 PM    <DIR>          ..
11/22/2022  05:46 PM             4,940 .vsconfig
11/22/2022  05:46 PM               255 unoapp-vsmac.slnf
11/22/2022  05:46 PM    <DIR>          unoapp.Mobile
11/22/2022  05:46 PM    <DIR>          unoapp.Server
11/22/2022  05:46 PM    <DIR>          unoapp.Shared
11/22/2022  05:46 PM    <DIR>          unoapp.Skia.Gtk
11/22/2022  05:46 PM    <DIR>          unoapp.Skia.Linux.FrameBuffer
11/22/2022  05:46 PM    <DIR>          unoapp.Skia.WPF
11/22/2022  05:46 PM            31,703 unoapp.sln
11/22/2022  05:46 PM    <DIR>          unoapp.Wasm
11/22/2022  05:46 PM    <DIR>          unoapp.Windows
11/22/2022  05:46 PM    <DIR>          WinUI                                    // <==
```

### NuGet package version(s)

Uno.ProjectTemplates.Dotnet::4.6.19

**Comment by Youssef1313** [comment] 2022-11-23 08:56
Duplicate of https://github.com/unoplatform/uno/issues/10503

**Closed** 2022-11-23 12:56 UTC
Labels: kind/bug, triage/untriaged, area/solution-templates, difficulty/tbd
