### ISSUE TITLE
Can not Create Android APK in release

### ISSUE THREAD

**Issue by imms20** [unoplatform/uno#10601] opened 2022-11-29 10:16 UTC
### Current behavior

Hi, 

i am using Visual studio 2022 Preview version on windows 10. Installed the latest uno template for creation of uno solution. When i change the mode to Release and try to build or deploy to android device or even i try to archive the solution, i get errors. 

I have also tried to update all the nuget packages to the latest preview or dev packages. Same story, cant build the apk. 

I have tried with both .net6 and .net7 as well. Not working

### NuGet package version(s)

    <PackageReference Include="Uno.WinUI" Version="4.6.19" />
    <PackageReference Include="Uno.WinUI.RemoteControl" Version="4.6.19" Condition="'$(Configuration)'=='Debug'" />
    <PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.6.19" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
    <PackageReference Include="Uno.WinUI.Lottie" Version="4.6.19" />

### Anything else we need to know?

1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: The managed type `Windows.UI.Xaml.Controls.NavigationView` exists in multiple assemblies: Uno.UI, Uno.UI, Uno.UI, Uno.UI. Please refactor the managed type names in these assemblies so that they are not identical.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: References to the type `Windows.UI.Xaml.Controls.NavigationView` will refer to `Windows.UI.Xaml.Controls.NavigationView, Uno.UI`.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: The managed type `Windows.UI.Xaml.Controls.NavigationViewItem` exists in multiple assemblies: Uno.UI, Uno.UI, Uno.UI, Uno.UI. Please refactor the managed type names in these assemblies so that they are not identical.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: References to the type `Windows.UI.Xaml.Controls.NavigationViewItem` will refer to `Windows.UI.Xaml.Controls.NavigationViewItem, Uno.UI`.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: The managed type `Windows.UI.Xaml.Controls.NavigationViewItemBase` exists in multiple assemblies: Uno.UI, Uno.UI, Uno.UI, Uno.UI. Please refactor the managed type names in these assemblies so that they are not identical.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: References to the type `Windows.UI.Xaml.Controls.NavigationViewItemBase` will refer to `Windows.UI.Xaml.Controls.NavigationViewItemBase, Uno.UI`.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: The managed type `Windows.UI.Xaml.Controls.NavigationViewItemHeader` exists in multiple assemblies: Uno.UI, Uno.UI, Uno.UI, Uno.UI. Please refactor the managed type names in these assemblies so that they are not identical.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: References to the type `Windows.UI.Xaml.Controls.NavigationViewItemHeader` will refer to `Windows.UI.Xaml.Controls.NavigationViewItemHeader, Uno.UI`.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: The managed type `Windows.UI.Xaml.Controls.NavigationViewItemSeparator` exists in multiple assemblies: Uno.UI, Uno.UI, Uno.UI, Uno.UI. Please refactor the managed type names in these assemblies so that they are not identical.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: References to the type `Windows.UI.Xaml.Controls.NavigationViewItemSeparator` will refer to `Windows.UI.Xaml.Controls.NavigationViewItemSeparator, Uno.UI`.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: The managed type `Windows.UI.Xaml.Controls.NavigationViewList` exists in multiple assemblies: Uno.UI, Uno.UI, Uno.UI, Uno.UI. Please refactor the managed type names in these assemblies so that they are not identical.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: References to the type `Windows.UI.Xaml.Controls.NavigationViewList` will refer to `Windows.UI.Xaml.Controls.NavigationViewList, Uno.UI`.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: The managed type `Windows.UI.Xaml.Controls.Primitives.NavigationViewItemPresenter` exists in multiple assemblies: Uno.UI, Uno.UI, Uno.UI, Uno.UI. Please refactor the managed type names in these assemblies so that they are not identical.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: References to the type `Windows.UI.Xaml.Controls.Primitives.NavigationViewItemPresenter` will refer to `Windows.UI.Xaml.Controls.Primitives.NavigationViewItemPresenter, Uno.UI`.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: The managed type `Microsoft.UI.Xaml.DispatcherTimer.TickRunnable` exists in multiple assemblies: Uno.UI, Uno.UI, Uno.UI, Uno.UI. Please refactor the managed type names in these assemblies so that they are not identical.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: References to the type `Microsoft.UI.Xaml.DispatcherTimer.TickRunnable` will refer to `Microsoft.UI.Xaml.DispatcherTimer.TickRunnable, Uno.UI`.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: The managed type `Microsoft.UI.Xaml.FrameworkElement` exists in multiple assemblies: Uno.UI, Uno.UI, Uno.UI, Uno.UI. Please refactor the managed type names in these assemblies so that they are not identical.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: References to the type `Microsoft.UI.Xaml.FrameworkElement` will refer to `Microsoft.UI.Xaml.FrameworkElement, Uno.UI`.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: The managed type `Microsoft.UI.Xaml.UIElement` exists in multiple assemblies: Uno.UI, Uno.UI, Uno.UI, Uno.UI. Please refactor the managed type names in these assemblies so that they are not identical.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: References to the type `Microsoft.UI.Xaml.UIElement` will refer to `Microsoft.UI.Xaml.UIElement, Uno.UI`.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: The managed type `Microsoft.UI.Xaml.DragRoot` exists in multiple assemblies: Uno.UI, Uno.UI, Uno.UI, Uno.UI. Please refactor the managed type names in these assemblies so that they are not identical.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: References to the type `Microsoft.UI.Xaml.DragRoot` will refer to `Microsoft.UI.Xaml.DragRoot, Uno.UI`.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: The managed type `Microsoft.UI.Xaml.DragView` exists in multiple assemblies: Uno.UI, Uno.UI, Uno.UI, Uno.UI. Please refactor the managed type names in these assemblies so that they are not identical.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: References to the type `Microsoft.UI.Xaml.DragView` will refer to `Microsoft.UI.Xaml.DragView, Uno.UI`.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: The managed type `Microsoft.UI.Xaml.ElementStub` exists in multiple assemblies: Uno.UI, Uno.UI, Uno.UI, Uno.UI. Please refactor the managed type names in these assemblies so that they are not identical.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: References to the type `Microsoft.UI.Xaml.ElementStub` will refer to `Microsoft.UI.Xaml.ElementStub, Uno.UI`.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: The managed type `Microsoft.UI.Xaml.NativeApplication` exists in multiple assemblies: Uno.UI, Uno.UI, Uno.UI, Uno.UI. Please refactor the managed type names in these assemblies so that they are not identical.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: References to the type `Microsoft.UI.Xaml.NativeApplication` will refer to `Microsoft.UI.Xaml.NativeApplication, Uno.UI`.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: The managed type `Microsoft.UI.Xaml.NativeApplication.ActivityCallbacks` exists in multiple assemblies: Uno.UI, Uno.UI, Uno.UI, Uno.UI. Please refactor the managed type names in these assemblies so that they are not identical.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: References to the type `Microsoft.UI.Xaml.NativeApplication.ActivityCallbacks` will refer to `Microsoft.UI.Xaml.NativeApplication.ActivityCallbacks, Uno.UI`.
1>C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\32.0.476\tools\Xamarin.Android.Common.targets(1438,3): warning XA4214: The managed type `Microsoft.UI.Xaml.ApplicationActivity` exists in multiple assemblies: Uno.UI, Uno.UI, Uno.UI, Uno.UI. Please refactor the managed type names in these assemblies so that they are not identical.

**Comment by jeromelaban** [comment] 2022-11-29 12:29
Thanks for the report. This is a duplicate of https://github.com/unoplatform/uno/discussions/10395, which is caused by a yet unreleased issue in .NET.

**Closed by jeromelaban** 2022-11-29 12:29 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
