### ISSUE TITLE
IOS:  No asset catalog available in new UNO project

### ISSUE THREAD

**Issue by MCAleckson** [unoplatform/uno#13182] opened 2023-08-09 15:04 UTC
### Current behavior

No asset catalog is automatically created in an IOS project, nor is it able to be added.

### Expected behavior

An asset catalog containing the required icons for Apple IOS distribution will be created when a new UNO project is created.  A new asset catalog should also be able to be added to the project.

### How to reproduce it (as minimally and precisely as possible)

Create a new UNO IOS project and see if there's an asset catalog in the project.  If not, try to add one.

### Workaround

None

### Works on UWP/WinUI

None

### Affected platforms

iOS

### IDE

Visual Studio 2022

### IDE version

17.7.0

### Anything else we need to know?

The resulting IPA file created does not contain necessary icons for App Store validation, and thus cannot be distributed.

**Comment by jeromelaban** [comment] 2023-08-14 20:48
Duplicate of https://github.com/unoplatform/uno.templates/issues/229

**Closed by jeromelaban** 2023-08-14 20:48 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
