### ISSUE TITLE
`Frame.Navigated` and page's `OnNavigatedTo` fire in a different order on android than on uwp.

### ISSUE THREAD

**Issue by DysnomianC** [unoplatform/uno#1863] opened 2019-10-16 05:28 UTC
## Current behavior

On uwp the `Frame.Navigated` event fires before `OnNavigatedTo`. On android they fire in the other order.

This was the cause of a difficult to track down bug in our project as we relied on setup that was done in the Frame Navigated event during the OnNavigatedTo page override. We can currently work around this issue by using some messy conditional compilation but this issue makes it difficult to port existing apps from uwp.

## Expected behavior

For Frame Navigated to fire before  OnNavigatedTo on android.

## How to reproduce it (as minimally and precisely as possible)

Run the sample project.
[NavTest.zip](https://github.com/unoplatform/uno/files/3732545/NavTest.zip)
Notice that in the debug log "Frame Navigated" and "OnNavigatedTo" are printed in a different order on android than uwp.

## Environment
Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:
- [x] 2019 (version: 16.3.5)

Relevant plugins:
Uno Platform Solution Templates - 1.45.0.1865

**Comment by MartinZikmund** [comment] 2019-10-16 11:35
I will have look at this

**Comment by MartinZikmund** [comment] 2019-10-31 19:53
I let my brother do this one, so he can try developing on Uno as well 😀

**Comment by jeromelaban** [comment] 2020-08-31 15:29
Closing as a duplicate of https://github.com/unoplatform/uno/issues/1863

**Comment by DierkDroth** [comment] 2020-10-14 17:46
@jeromelaban I just confirmed on iOS that the problem is even more widespread: .Loading and .Loaded is fired before .OnNavigatedTo which is wrong: on UWP they are fired after.

This raises a serious problem: with NavigationEventArgs in .OnNavigatedTo I'm supposed to pass "parameters" to the new frame. I needed those "parameters" when processing .Loading and/or .Loaded. What workaround would there be available.

BTW: believe the same problem exists on WASM

**Comment by MartinZikmund** [comment] 2020-10-14 18:09
@DierkDroth yes we are aware of this one - #2872 and #2895. It is however quite complex issue, so it will require quite a bit of work across all platforms

**Comment by MartinZikmund** [comment] 2023-06-02 13:51
This part of navigation lifecycle was adjusted in #9251

**Closed by MartinZikmund** 2023-06-02 13:51 UTC
Labels: kind/bug, platform/android, project/navigation-lifecycle, difficulty/starter, area/eu
