### ISSUE TITLE
 [All Platforms][CornerRadius] Edge case where Inner Radius doesn't match UWP when BorderThickness >= CornerRadius

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno#6891] opened 2021-08-27 13:08 UTC
### Current behavior

Edge case to fix on all platforms where Inner Radius doesn't match UWP when BorderThickness >= CornerRadius

![image](https://user-images.githubusercontent.com/16295702/131129906-f5d59954-3775-4f51-ab4f-62b489c63130.png)
![image](https://user-images.githubusercontent.com/16295702/131129985-2646db67-8a7b-401f-a4d9-d69e81abde2f.png)
![image](https://user-images.githubusercontent.com/16295702/131130024-7e623caa-52a3-454e-ae93-3a1f847a8981.png)
**_Android_**
![image](https://user-images.githubusercontent.com/16295702/131131644-99eb82f9-8cfa-41b0-9cb2-3131deb2cca2.png)

### Expected behavior

Inner Radius calculations should match UWP behaviors when BorderThickness >= CornerRadius

### How to reproduce it (as minimally and precisely as possible)

```
<StackPanel>
		<toolkit:ElevatedView Height="100"
							  Width="200"
							  Background="Yellow"
							  CornerRadius="15"
							  BorderBrush="#66121212"
							  BorderThickness="15"
							  Margin="30">
			<Grid Background="DeepPink"
				  CornerRadius="25">
				<TextBlock Text="Test with ElevatedView"
						   VerticalAlignment="Center"
						   HorizontalAlignment="Center" />
			</Grid>
		</toolkit:ElevatedView>

		<Grid Height="100"
			  Width="200"
			  Background="Orange"
			  CornerRadius="15"
			  BorderBrush="#66121212"
			  BorderThickness="15"
			  Margin="30">
			<Grid Background="Red"
				  CornerRadius="25">
				<TextBlock Text="Test with a Grid"
						   VerticalAlignment="Center"
						   HorizontalAlignment="Center" />
			</Grid>
		</Grid>
	</StackPanel>
```

### Workaround

N/A

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

3.10.0-dev.520

### Affected platforms

iOS, Android, WebAssembly, macOS, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Skia (Tizen)

### IDE

Visual Studio 2022

### IDE version

Version 17.0.0 Preview 2.1

### Relevant plugins

N/A

### Anything else we need to know?

See WinUI **CalculateRoundedCornersRectangle** for the logic

**Comment by MartinZikmund** [comment] 2022-10-27 12:16
Duplicate of #10263

**Closed by MartinZikmund** 2022-10-27 12:17 UTC
Labels: kind/bug, project/shapes-brushes, platform/all, difficulty/tbd
