### ISSUE TITLE
NavigationView - ItemInvoked not fired when settings item is selected

### ISSUE THREAD

**Issue by jabak** [unoplatform/uno#1606] opened 2019-09-25 17:57 UTC
## Current behavior

When selecting the navigationview settings item ItemInvoked eventhandler is not fired on Android

## Expected behavior

When selecting the navigationview settings item ItemInvoked eventhandler should be fired on Android as it does on Windows/UWP

## How to reproduce it (as minimally and precisely as possible)

* Start Visual Studio 2019
* Create new project using Uno Platform App Template

In shared projects mainpage.xaml paste in this:

```
<Grid>
<NavigationView x:Name="NavigationViewControl" PaneDisplayMode="Auto" IsSettingsVisible="True" ItemInvoked="OnItemInvoked">
           <NavigationView.MenuItems>
                <NavigationViewItem Content="First Item" x:Name="A" Icon="Accept"/>
                <NavigationViewItem Content="Second Item" x:Name="B" Icon="Save" />
                <NavigationViewItem Content="Third Item" x:Name="C" Icon="Calendar"/>
            </NavigationView.MenuItems>
        </NavigationView>
   </Grid>
```

In mainpage.cs paste in ths:

```
private void OnItemInvoked(object sender, NavigationViewItemInvokedEventArgs args)
{}
```

* Set a breakpoint at OnItemInvoked
* Make sure that the android project is set as Startup project
* Debug project
* Select Settings item

## Environment

Nuget Package:
Uno.UI 1.45.0

Package Version(s):

Affected platform(s):
- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [x ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by weitzhandler** [comment] 2020-01-02 05:39
I was able to reproduce this bug. It happens when `NavigationMenuItem` is generated from `ItemsSource`.
Related: #2418.

**Comment by weitzhandler** [comment] 2020-01-02 05:58
I have a similar issue (#2418).  
The item only changes selection when the left-side hook (area about 2mm on the left side of the `NavigationViewItem`).
This issue also occurs in the WASM head.

**Comment by weitzhandler** [comment] 2020-01-06 21:26
[Here](https://github.com/weitzhandler/Uno/tree/navigation-view)'s my fork of Uno. I added a [UI test](https://github.com/unoplatform/uno/compare/master...weitzhandler:navigation-view#diff-514ac5c8710aa9b965fbb5d18f64fd48) that reproduces the issue.

**Comment by weitzhandler** [comment] 2020-01-08 15:03
I'm willing to work on the issue, but I'd need some guidance on how to tackle platform specific issues, since the control renders just fine on UWP.
It might be the ZIndex that's avoiding mouse point capture.

**Comment by jeromelaban** [comment] 2020-01-08 21:05
@weitzhandler thanks for that! It's actually an issue that is in both `Selector`, `ListView` and `ListViewItem`, for which changing the `ListViewItem.IsSelected` property does not do anything, and it breaks navigation, I'll revalidate with your sample to make sure it fixes the issue correctly.

**Comment by weitzhandler** [comment] 2020-01-08 23:00
Should I PR my failing unit test?

**Comment by weitzhandler** [comment] 2020-01-09 00:36
Something that might be worth noticing though, I tried hooking up the [`ItemInvoked`](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.navigationview.iteminvoked) event, which was never fired.

**Comment by jeromelaban** [comment] 2020-01-09 01:17
Thanks for that, I'll make sure to check it.

**Comment by jeromelaban** [comment] 2020-01-13 21:30
@weitzhandler the issue you're having is actually https://github.com/unoplatform/uno/issues/2477, for which providing a DataTemplate of the type of the Item container (NavigationViewItem in this case) is properly supported by `ListView` control.

https://github.com/unoplatform/uno/pull/2462 will partially adress the issue you mentioned with the ItemsSource, but will not show the current selection. The original issue mentioned at the top is fixed by https://github.com/unoplatform/uno/pull/2462.

**Comment by weitzhandler** [comment] 2020-01-13 22:27
Thanks @jeromelaban!

**Closed** 2020-01-27 20:27 UTC
Labels: area/android, kind/bug
