### ISSUE TITLE
Custom ContentDialog doens't get the focus on a Skia project

### ISSUE THREAD

**Issue by mcNets** [unoplatform/uno#9546] opened 2022-08-19 14:55 UTC
### Current behavior

Hi, I'm using a custom ContentDialog to get a string from a USB RFID reader. The reader acts as a keyboard and I use the KeyUp event handler to get the value:

`KeyUp += RfidDialog_KeyUp;` 

It works fine in WinUI but in the Skia project focus seems to be hooked in the background frame. You can see the white rectangle focusing the settings button.

[Focus rectangle](https://i.imgur.com/qshqdFO.png)

If I press Tab key, focus alternates between Settings and User button but the ContentDialog never receives the focus so it never gets KeyUp events.

### How to reproduce it (as minimally and precisely as possible)

- Create Uno project using VS wizard and select Skia & Windows project.
- Add a couple of buttons to the MainPage.
- Add a custom ContentDialog
- Add a KeyUp event handler (this.KeyUp += YourEventHandler)
- Add a TextBox where to show the keystrokes. (I use a PasswordBox)
- Show up the dialog.
- MainPage keeps the focus.

### NuGet package version(s)

```
<PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />
<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="6.0.0" />
<PackageReference Include="Uno.Extensions.Hosting" Version="2.1.1" />
<PackageReference Include="Uno.WinUI.RemoteControl" Version="4.5.0-dev.428" Condition="'$(Configuration)'=='Debug'" />
<PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.5.0-dev.428" />
<PackageReference Include="Uno.WinUI.Skia.Gtk" Version="4.5.0-dev.428" />
```

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### IDE version

17.3.1

**Comment by mcNets** [comment] 2022-08-19 14:58
Issue opened: https://github.com/unoplatform/uno/discussions/9545

**Comment by MartinZikmund** [comment] 2022-10-23 07:32
Duplicate of #10135

**Closed by MartinZikmund** 2022-10-23 07:32 UTC
Labels: kind/bug, triage/untriaged, area/skia, project/input, difficulty/starter, area/focus
