### ISSUE TITLE
[WASM] Splashscreen sometimes displays the default Uno Splash

### ISSUE THREAD

**Issue by agneszitte** [unoplatform/uno#12208] opened 2023-05-08 21:02 UTC
### Current behavior

Launch a solution on WASM (created with the uno template with the blank or default or customized options)

- Sometimes it will display the proper splashscreen
![wasmsplash](https://user-images.githubusercontent.com/16295702/236933022-f137501e-f26c-4708-b9f9-05eb0175b748.PNG)

- But sometimes it will display the default Uno Splash
![wasmsplash2](https://user-images.githubusercontent.com/16295702/236933104-c446b2ad-f62f-416c-a611-5d9d60c75042.PNG)

### Expected behavior

Splashscreen should be consistent on WASM and display the proper one

### How to reproduce it (as minimally and precisely as possible)

Launch the solution on WASM
#
**Really hard to have a proper repro to replicate this issue and not able to give a specific repro rate either (really random)**

### Workaround

N/A

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

- Uno : 4.9.0-dev.282
- Uno.Resizetizer : 1.1.0-dev.29

### Affected platforms

WebAssembly

### IDE

Visual Studio 2022

### IDE version

Version 17.5.4

### Relevant plugins

N/A

**Comment by agneszitte** [comment] 2023-05-08 21:05
(cc @jeromelaban, @MartinZikmund, @nickrandolph, @pictos)

**Comment by pictos** [comment] 2023-05-08 21:07
I believe it's related to:

- https://github.com/unoplatform/uno.resizetizer/issues/110

@agneszitte can you share the project that you're using?

**Comment by agneszitte** [comment] 2023-05-08 21:13
@pictos any solution created with the template will do I think. It is really hard to repro as it is really random, saw it once last week with a sample app that I did a bunch of changes for another issue and I tried the same solution today numerous times and I am not able to reproduce it.

@nickrandolph if this issue is a duplicate of https://github.com/unoplatform/uno.resizetizer/issues/110, please close this one and we will follow the details on the other.

**Comment by pictos** [comment] 2023-05-08 23:16
@agneszitte, I asked because I couldn't reproduce the issue, so was wondering if I missed a small detail. Will work on this issue tomorrow

**Comment by nickrandolph** [comment] 2023-05-09 04:20
This is the same issue as we have on Resizetizer repo about wasm.

**Comment by pictos** [comment] 2023-05-09 13:18
Closing this one, since we already have an issue tracking this bug.

**Closed by pictos** 2023-05-09 13:18 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
