### ISSUE TITLE
[Gallery][Skia.GTK] Toggleswitch(Fluent)- when flipping the toggle switch, switch control is not displaying correctly.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8755] opened 2022-05-12 15:36 UTC
### Current behavior

![toggleswitch issue](https://user-images.githubusercontent.com/74563602/168113142-e87dd1d2-0e53-4189-84b7-2e6321ecb78b.png)

### Expected behavior

![toggleswitch correct](https://user-images.githubusercontent.com/74563602/168113153-aefe2217-66a1-4f62-b9c2-753b8f615e3f.png)

### How to reproduce it (as minimally and precisely as possible)

Launch the Uno.Gallry app on Skia.GTK.
Click on “Toggleswitch” from the "Component" list.
Go to 'Fluent' Section.
Flip toggleswitch for ON and OFF option.
Notice that, when flipping the toggle switch, the background color for switch control is not changing correctly.

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

**Comment by MartinZikmund** [comment] 2022-05-13 13:26
Duplicate of #8636 👍

**Closed by MartinZikmund** 2022-05-13 13:26 UTC
Labels: kind/bug, triage/untriaged, area/canary, difficulty/tbd, platform/gtk
