### ISSUE TITLE
[Gallery WASM] `NavigationView` animations broken with touch

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#17364] opened 2024-07-02 09:47 UTC
### Current behavior

When Gallery is used on iPad in browser, animations go haywire

Cc @morning4coffe-dev 

https://github.com/unoplatform/uno/assets/1075116/bc72d8c3-e7a0-457b-bb4a-a32893a5575a

### Expected behavior

Should not happen

### Works on UWP/WinUI

Yes

### Affected platforms

WebAssembly

**Comment by agneszitte** [comment] 2024-10-04 22:14
@MartinZikmund I think this issue is maybe a duplicate of https://github.com/unoplatform/uno/issues/10902 no ?

**Comment by morning4coffe-dev** [comment] 2024-10-12 07:42
@agneszitte Jup, I believe this was happening on iOS WASM on our side as well. I think we can close one of these issues.

**Closed** 2024-10-14 08:34 UTC
