### ISSUE TITLE
Skia - ListView placed in Grid's Row, handles click out of its bounds

### ISSUE THREAD

**Issue by sarosigy** [unoplatform/uno#8936] opened 2022-05-31 08:37 UTC
### Current behavior

On linux platform, creating a page like this:
```
    <Grid>
      <Grid.RowDefinitions>
        <RowDefinition Height="70" />
        <RowDefinition />
      </Grid.RowDefinitions>
      
      <StackPanel Grid.Row="0" Orientation="Horizontal">
        <TextBlock Text="Hello, world!" Margin="20" FontSize="30" />
        <Button Margin="20,30,20,10" Content="Refresh my items just dummy now" />
      </StackPanel>

      <Border Grid.Row="1" Margin="20" BorderBrush="Gray" BorderThickness="1" CornerRadius="2" >
        <ListView Margin="4" ItemsSource="{Binding Path=Items}" SelectionMode="Extended">

```
And then scrolling down, the button in the Grid's 0th row cannot be clicked, it selects a listview item instead:

![Screenshot_lvbounds1](https://user-images.githubusercontent.com/37872626/171113021-899fb664-5714-4785-9504-a54f0d73a4ce.png)
![Screenshot_lvbounds2](https://user-images.githubusercontent.com/37872626/171113065-1e3e0f37-a0af-493f-890f-bf05c92ad7a8.png)

### Expected behavior

Should not handle click if out of its bounds

### How to reproduce it (as minimally and precisely as possible)

Partial source is listed, full source at link:

[uno-lvtest-master.zip](https://github.com/unoplatform/uno/files/8805094/uno-lvtest-master.zip)

### Workaround

If the XAML blocks are swapped (first the ListView, then the rest) it works as expected

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

Uno.WinUI.Skia.Gtk Version="4.3.6"

### Affected platforms

Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio Code

### IDE version

1.67.2

### Relevant plugins

Uno Platform 0.4.0

**Comment by ramezgerges** [comment] 2023-07-06 12:12
I couldn't reproduce this on windows (Skia.Gtk).

**Comment by jeromelaban** [comment] 2023-07-10 18:29
Thanks! We may have fixed this with @dr1rrb's work on clipping.

**Comment by dr1rrb** [comment] 2023-07-17 21:40
> Thanks! We may have fixed this with @dr1rrb's work on clipping.

Yes this should been fixed by now. As @ramezgerges is not able to repro, we can close it. @sarosigy feel free to re-open it.

**Closed by dr1rrb** 2023-07-17 21:40 UTC
Labels: kind/bug, area/skia, project/pointers, difficulty/tbd

**Comment by sarosigy** [comment] 2023-07-18 06:26
It seems to be working fine. Thanks!
