### ISSUE TITLE
CommandBar issue on iOS using NativeDefaultCommandBar

### ISSUE THREAD

**Issue by s-beltz** [unoplatform/uno#5492] opened 2021-03-17 10:57 UTC
## Current behavior

It seems that there is a problem when defining a Style for a CommandBar that uses BasedOn="{StaticResource NativeDefaultCommandBar}" as described here: [https://platform.uno/docs/articles/controls/CommandBar.html](https://platform.uno/docs/articles/controls/CommandBar.html)

Android works fine, on iOS Background is not applied and Content is not visible at all. 

## How to reproduce it (as minimally and precisely as possible)

[UnoNavViewSample-CommandBar-2021-03-17.zip](https://github.com/unoplatform/uno/files/6155768/UnoNavViewSample-CommandBar-2021-03-17.zip)

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Uno.UI Version="3.6.0-dev.445"

Affected platform(s):

- [x] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.9.2)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by ajpinedam** [comment] 2021-03-20 17:48
@s-beltz 

Try adding `VisibleBoundsPadding.PaddingMask="Top"` on your `CommandBar` Style. It looks to me that your CommandBar could be hidden at the top.

```xml
    xmlns:xamarin="http://nventive.com/xamarin"
    xmlns:toolkit="using:Uno.UI.Toolkit"

    <Style x:Key="TitleCommandBar"
           TargetType="CommandBar"
           BasedOn="{StaticResource NativeDefaultCommandBar}">
           .....
           <!-- Xamarin (iOS and Android) -->
            <xamarin:Setter Property="(toolkit:VisibleBoundsPadding.PaddingMask)"
                            Value="Top" />
        </Style.Setters>
    </Style>
```

Down in the [docs](https://platform.uno/docs/articles/controls/CommandBar.html) for the `CommandBar` you can read the reason behind this.

**Comment by kazo0** [comment] 2022-01-11 19:07
@s-beltz Are you still able to reproduce this with the latest Uno packages?

**Comment by kazo0** [comment] 2022-01-12 18:00
@s-beltz For the issue of the native CommandBar not appearing when basing the style on the DefaultNative style. This is because, by default, we are not using the NativeFramePresenter which is required for iOS if you want to create a native CommandBar.

Simply adding this line to the `App.xaml.cs` constructor after the `InitializeComponent()` call should do the trick
`FeatureConfiguration.Style.ConfigureNativeFrameNavigation();`

This line will tell Uno to **not** use the default UWP styles for Frame, CommandBar, and AppBarButtion and use the native styles for those controls instead.

Now, there is still an issue with the Background color not being applied. Seems iOS 15 introduced a new way of dealing with the UINavigationBar's appearance. I will close this issue now and open a new one specifically for the Background issue.
https://developer.apple.com/forums/thread/682420

**Closed by kazo0** 2022-01-12 18:00 UTC
Labels: kind/bug, project/layout, difficulty/challenging, area/commandbar

**Comment by s-beltz** [comment] 2022-01-12 21:10
@kazo0 Thank you for your detailed explanation and the hint how to work around the issue. We will give it a try...
