### ISSUE TITLE
WASM ContentPresenter's default Foreground color is inconsistent with other platforms

### ISSUE THREAD

**Issue by NicolasChampagne** [unoplatform/uno#3505] opened 2020-07-06 18:21 UTC
## Current behavior

![WASM LightTheme ToggleSwitch](https://user-images.githubusercontent.com/49959074/84160935-b898c200-aa3c-11ea-884e-36e48a6e21b6.png)

## Expected behavior

![iOS ToggleSwitch Labels](https://user-images.githubusercontent.com/49959074/84161150-f695e600-aa3c-11ea-856b-e2edf05ae7be.png)

## How to reproduce it (as minimally and precisely as possible)
Open Uno.Material to go ToggleSwitch.xaml and remove line 441 

Foreground="{TemplateBinding Foreground}" 

Notice that other platforms do not need ^ this line attatched to their contentpresenter to display the applications primary color.

## Environment
 wasm

Nuget Package:
Uno 3.0.0-feature.styles-compat.216
Uno.Wasm.Bootstrap 1.0.10

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by davidjohnoliver** [comment] 2021-06-01 10:21
This is a duplicate of #857 , closing.

**Closed by davidjohnoliver** 2021-06-01 10:21 UTC
Labels: difficulty/tbd, kind/bug, platform/wasm, project/styling
