### ISSUE TITLE
[Android] ComboBox in ContentDialog throws exception

### ISSUE THREAD

**Issue by trungnt2910** [unoplatform/uno#7135] opened 2021-09-18 15:57 UTC
### Current behavior

On Android, when you try to expand a `ComboBox` that is a child of a `ContentDialog`, an error occurs: 

<details>
  <summary>Super long stacktrace</summary>
  
   
  ```
        Failed to raise 'PointerReleasedEvent': Android.Views.WindowManagerBadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@78dfb15 is not valid; is your activity running?
        at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x0006e] in <bd6bd528a8784b7caf03e9f25c9f0d7b>:0 
        at Java.Interop.JniPeerMembers+JniInstanceMethods.InvokeVirtualVoidMethod (System.String encodedMember, Java.Interop.IJavaPeerable self, Java.Interop.JniArgumentValue* parameters) [0x0002a] in <bd6bd528a8784b7caf03e9f25c9f0d7b>:0 
        at Android.Widget.PopupWindow.ShowAtLocation (Android.Views.View parent, Android.Views.GravityFlags gravity, System.Int32 x, System.Int32 y) [0x00067] in /Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-29/mcw/Android.Widget.PopupWindow.cs:2056 
        at Windows.UI.Xaml.Controls.Popup.OnIsOpenChangedNative (System.Boolean oldIsOpen, System.Boolean newIsOpen) [0x0000f] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Popup\Popup.Android.cs:68 
        at Windows.UI.Xaml.Controls.Popup.OnIsOpenChanged (System.Boolean oldIsOpen, System.Boolean newIsOpen) [0x00040] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Popup\Popup.WithPopupRoot.cs:79 
        at Windows.UI.Xaml.Controls.PopupBase+<>c.<.cctor>b__72_0 (Windows.UI.Xaml.DependencyObject s, Windows.UI.Xaml.DependencyPropertyChangedEventArgs e) [0x00000] in C:\a\1\s\src\Uno.UI\Mixins\DependencyPropertyMixins.g.cs:172 
        at Windows.UI.Xaml.PropertyMetadata.RaisePropertyChanged (Windows.UI.Xaml.DependencyObject source, Windows.UI.Xaml.DependencyPropertyChangedEventArgs e) [0x00000] in C:\a\1\s\src\Uno.UI\UI\Xaml\PropertyMetadata.cs:187 
        at Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks (Windows.UI.Xaml.DependencyObject actualInstanceAlias, Windows.UI.Xaml.DependencyProperty property, Windows.UI.Xaml.DependencyPropertyDetails propertyDetails, System.Object previousValue, Windows.UI.Xaml.DependencyPropertyValuePrecedences previousPrecedence, System.Object newValue, Windows.UI.Xaml.DependencyPropertyValuePrecedences newPrecedence, System.Boolean bypassesPropagation) [0x000e0] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:1681 
        at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks (Windows.UI.Xaml.DependencyObject actualInstanceAlias, Windows.UI.Xaml.DependencyPropertyDetails propertyDetails, System.Object previousValue, Windows.UI.Xaml.DependencyPropertyValuePrecedences previousPrecedence, System.Object newValue, Windows.UI.Xaml.DependencyPropertyValuePrecedences newPrecedence) [0x0005b] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:1591 
        at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue (Windows.UI.Xaml.DependencyProperty property, System.Object value, Windows.UI.Xaml.DependencyPropertyValuePrecedences precedence, Windows.UI.Xaml.DependencyPropertyDetails propertyDetails, System.Boolean isThemeBinding) [0x001b4] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:505 
        at Windows.UI.Xaml.DependencyObjectStore.SetValue (Windows.UI.Xaml.DependencyProperty property, System.Object value, Windows.UI.Xaml.DependencyPropertyValuePrecedences precedence, Windows.UI.Xaml.DependencyPropertyDetails propertyDetails, System.Boolean isThemeBinding) [0x0001a] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:439 
        at Windows.UI.Xaml.DependencyObjectStore.SetValue (Windows.UI.Xaml.DependencyProperty property, System.Object value) [0x00000] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:393 
        at Uno.UI.Controls.BindableView.SetValue (Windows.UI.Xaml.DependencyProperty dp, System.Object value) [0x00000] in C:\a\1\s\src\Uno.UI\obj\Release\monoandroid10.0\g\DependencyObjectGenerator\Uno_UI_Controls_BindableView_eefac468be1af0c618115e95339af76c.g.cs:47 
        at Windows.UI.Xaml.Controls.PopupBase.set_IsOpen (System.Boolean value) [0x00000] in C:\a\1\s\src\Uno.UI\Mixins\DependencyPropertyMixins.g.cs:161 
        at Windows.UI.Xaml.Controls.ComboBox.OnIsDropDownOpenChangedPartial (System.Boolean oldIsDropDownOpen, System.Boolean newIsDropDownOpen) [0x00028] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\ComboBox\ComboBox.cs:378 
        at Windows.UI.Xaml.Controls.ComboBox.OnIsDropDownOpenChanged (System.Boolean oldIsDropDownOpen, System.Boolean newIsDropDownOpen) [0x00000] in C:\a\1\s\src\Uno.UI\Mixins\DependencyPropertyMixins.g.cs:754 
        at Windows.UI.Xaml.Controls.ComboBox+<>c.<.cctor>b__138_1 (Windows.UI.Xaml.DependencyObject s, Windows.UI.Xaml.DependencyPropertyChangedEventArgs e) [0x00000] in C:\a\1\s\src\Uno.UI\Mixins\DependencyPropertyMixins.g.cs:748 
        at Windows.UI.Xaml.PropertyMetadata.RaisePropertyChanged (Windows.UI.Xaml.DependencyObject source, Windows.UI.Xaml.DependencyPropertyChangedEventArgs e) [0x00000] in C:\a\1\s\src\Uno.UI\UI\Xaml\PropertyMetadata.cs:187 
        at Windows.UI.Xaml.DependencyObjectStore.InvokeCallbacks (Windows.UI.Xaml.DependencyObject actualInstanceAlias, Windows.UI.Xaml.DependencyProperty property, Windows.UI.Xaml.DependencyPropertyDetails propertyDetails, System.Object previousValue, Windows.UI.Xaml.DependencyPropertyValuePrecedences previousPrecedence, System.Object newValue, Windows.UI.Xaml.DependencyPropertyValuePrecedences newPrecedence, System.Boolean bypassesPropagation) [0x000e0] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:1681 
        at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks (Windows.UI.Xaml.DependencyObject actualInstanceAlias, Windows.UI.Xaml.DependencyPropertyDetails propertyDetails, System.Object previousValue, Windows.UI.Xaml.DependencyPropertyValuePrecedences previousPrecedence, System.Object newValue, Windows.UI.Xaml.DependencyPropertyValuePrecedences newPrecedence) [0x0005b] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:1591 
        at Windows.UI.Xaml.DependencyObjectStore.InnerSetValue (Windows.UI.Xaml.DependencyProperty property, System.Object value, Windows.UI.Xaml.DependencyPropertyValuePrecedences precedence, Windows.UI.Xaml.DependencyPropertyDetails propertyDetails, System.Boolean isThemeBinding) [0x001b4] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:505 
        at Windows.UI.Xaml.DependencyObjectStore.SetValue (Windows.UI.Xaml.DependencyProperty property, System.Object value, Windows.UI.Xaml.DependencyPropertyValuePrecedences precedence, Windows.UI.Xaml.DependencyPropertyDetails propertyDetails, System.Boolean isThemeBinding) [0x0001a] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:439 
        at Windows.UI.Xaml.DependencyObjectStore.SetValue (Windows.UI.Xaml.DependencyProperty property, System.Object value) [0x00000] in C:\a\1\s\src\Uno.UI\UI\Xaml\DependencyObjectStore.cs:393 
        at Uno.UI.Controls.BindableView.SetValue (Windows.UI.Xaml.DependencyProperty dp, System.Object value) [0x00000] in C:\a\1\s\src\Uno.UI\obj\Release\monoandroid10.0\g\DependencyObjectGenerator\Uno_UI_Controls_BindableView_eefac468be1af0c618115e95339af76c.g.cs:47 
        at Windows.UI.Xaml.Controls.ComboBox.set_IsDropDownOpen (System.Boolean value) [0x00000] in C:\a\1\s\src\Uno.UI\Mixins\DependencyPropertyMixins.g.cs:737 
        at Windows.UI.Xaml.Controls.ComboBox.OnPointerReleased (Windows.UI.Xaml.Input.PointerRoutedEventArgs args) [0x0000f] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\ComboBox\ComboBox.cs:418 
        at Windows.UI.Xaml.Controls.Control+<>c.<.cctor>b__376_10 (System.Object sender, Windows.UI.Xaml.Input.PointerRoutedEventArgs args) [0x00000] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Control\Control.cs:905 
        at Windows.UI.Xaml.UIElement.InvokeHandler (System.Object handler, Windows.UI.Xaml.RoutedEventArgs args) [0x00105] in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.RoutedEvents.cs:916 
        at Windows.UI.Xaml.UIElement.RaiseEvent (Windows.UI.Xaml.RoutedEvent routedEvent, Windows.UI.Xaml.RoutedEventArgs args, Windows.UI.Xaml.UIElement+BubblingContext ctx) [0x0009a] in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.RoutedEvents.cs:650 
        at Windows.UI.Xaml.UIElement.RaisePointerEvent (Windows.UI.Xaml.RoutedEvent evt, Windows.UI.Xaml.Input.PointerRoutedEventArgs args, Windows.UI.Xaml.UIElement+BubblingContext ctx) [0x0000d] in C:\a\1\s\src\Uno.UI\UI\Xaml\UIElement.Pointers.cs:980 
        --- End of managed Android.Views.WindowManagerBadTokenException stack trace ---
      android.view.WindowManager$BadTokenException: Unable to add window -- token android.view.ViewRootImpl$W@78dfb15 is not valid; is your activity running?
      	at android.view.ViewRootImpl.setView(ViewRootImpl.java:679)
      	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:342)
      	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
      	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1378)
      	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1154)
      	at android.widget.PopupWindow.showAtLocation(PopupWindow.java:1121)
      	at crc64122dcf5ad656876d.UIElement.n_onNativeMotionEvent(Native Method)
      	at crc64122dcf5ad656876d.UIElement.onNativeMotionEvent(UIElement.java:57)
      	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:268)
      	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
      	at crc64a5a37c43dff01024.ListViewBase.n_dispatchTouchEvent(Native Method)
      	at crc64a5a37c43dff01024.ListViewBase.dispatchTouchEvent(ListViewBase.java:29)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
      	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
      	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
      	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
      	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
      	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
      	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
      	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
      	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
      	at crc64a5a37c43dff01024.NativeScrollContentPresenter.n_dispatchTouchEvent(Native Method)
      	at crc64a5a37c43dff01024.NativeScrollContentPresenter.dispatchTouchEvent(NativeScrollContentPresenter.java:83)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
      	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
      	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
      	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
      	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
      	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
      	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
      	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
      	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
      	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
      	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
      	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
      	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
      	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
      	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
      	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
      	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
      	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
      	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
      	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
      	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
      	at Uno.UI.TouchMotionTarget.dispatchToChild(UnoMotionHelper.java:53)
      	at Uno.UI.UnoMotionHelper.dispatchStaticTransformedMotionEventCore(UnoMotionHelper.java:419)
      	at Uno.UI.UnoMotionHelper.dispatchStaticTransformedMotionEvent(UnoMotionHelper.java:389)
      	at Uno.UI.UnoMotionHelper.dispatchStaticTransformedMotionEvent(UnoMotionHelper.java:331)
      	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:187)
      	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
      	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
      	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
      	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
      	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
      	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
      	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
      	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
      	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
      	at Uno.UI.UnoViewGroup.access$201(UnoViewGroup.java:14)
      	at Uno.UI.UnoViewGroup$TouchMotionTarget.dispatchToSuper(UnoViewGroup.java:311)
      	at Uno.UI.UnoMotionHelper.dispatchMotionEvent(UnoMotionHelper.java:191)
      	at Uno.UI.UnoViewGroup.dispatchTouchEvent(UnoViewGroup.java:324)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
      	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
      	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
      	at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2277)
      	at android.view.View.dispatchPointerEvent(View.java:10257)
      	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4438)
      	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4306)
      	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
      	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
      	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
      	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3999)
      	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
      	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4056)
      	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
      	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3906)
      	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3872)
      	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3880)
      	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3853)
      	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6247)
      	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6221)
      	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6182)
      	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6350)
      	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
      	at android.os.MessageQueue.nativePollOnce(Native Method)
        at Windows.UI.Xaml.DependencyObjectStore.RaiseCallbacks (Windows.UI.Xaml.DependencyObject actualInstanceAlias, Windows.UI.Xaml.DependencyPropert09-18 22:55:55.595 V/mono-stdout( 4382):       	at android.os.MessageQueue.next(MessageQueue.java:323)
      	at android.os.Looper.loop(Looper.java:136)
      	at android.app.ActivityThread.main(ActivityThread.java:6138)
      	at java.lang.reflect.Method.invoke(Native Method)
      	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
      	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
```
  
</details>

The options are not shown.

### Expected behavior

No error should occur.

### How to reproduce it (as minimally and precisely as possible)

```C#
        private async void ShowContentDialogButton_Click(object sender, RoutedEventArgs e)
        {
            var dialog = new ContentDialog();
            var box = new ComboBox();

            for (int i = 0; i < 10; ++i)
            {
                box.Items.Add(i);
            }

            dialog.Content = box;

            dialog.PrimaryButtonText = "OK";

            await dialog.ShowAsync();
        }
```

Call this code anywhere. (It also happens when the UI is built from XAML, anyway).

I've uploaded the project here.
[AndroidTests.zip](https://github.com/unoplatform/uno/files/7190203/AndroidTests.zip)

### Workaround

Found none.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Tested on 3.7.3 to 3.10.7.

### Affected platforms

Android

### IDE

Visual Studio 2019

### IDE version

16.11

### Anything else we need to know?

Copied this from somewhere...
> It seems you've come upon a known limitation related to Android PopupWindow - in short you cannot open a popup from a popup. In the concrete case the ComboBox dropdown is the second popup.  

Is that also the case for the Uno Platform?

**Comment by jeromelaban** [comment] 2021-09-18 22:30
This issue is likely a duplicate of https://github.com/unoplatform/uno/issues/2533. Try the workaround defined there and let us know.

**Closed by jeromelaban** 2021-09-18 22:30 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
