### ISSUE TITLE
Can't use a binding to a staticresource in a style

### ISSUE THREAD

**Issue by stefanolson** [unoplatform/uno#4850] opened 2021-01-08 01:47 UTC
## Current behavior

Error: Preprocessor directive expected. Code:
```
<local:BrandingAccessor x:Key="BrandingAccessor" />
    <Style TargetType="local:CustomControl1">
        <Setter Property="Background" Value="{Binding Source={StaticResource BrandingAccessor}, Path=Branding.InfoButtonBackgroundBrush}"/>
```

In output .cs file:
```
Setters = 
					{
						new global::Windows.UI.Xaml.Setter(global::UnoApp.CustomControl1.BackgroundProperty, __ResourceOwner_0, __ResourceOwner_1 => (Windows.UI.Xaml.Media.Brush)
						#Error // Binding could not be found.
						)
						,
					}
```

## Expected behavior

Should compile as it does in UWP.

## How to reproduce it (as minimally and precisely as possible)

Build enclosed project: [UnoApp.zip](https://github.com/unoplatform/uno/files/5784779/UnoApp.zip)

You'll see in mainpage.xaml that I can successfully reference the accessor from a staticresource:
`<Grid Background="{Binding Source={StaticResource BrandingAccessor}, Path=Branding.InfoButtonBackgroundBrush}">`

Just doesn't seem to work when in a style in a resource dictionary

## Workaround

None yet.

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [X] iOS
- [X] Android
- [X] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [X] macOS
- [X] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [X] Visual Studio 2019 (version: 16.8.3 )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment] 2021-06-04 16:49
Duplicate of #4850

**Closed by MartinZikmund** 2021-06-04 16:49 UTC
Labels: difficulty/tbd, kind/bug, project/binding
