### ISSUE TITLE
Manipulation with xaml component.

### ISSUE THREAD

**Issue by michalss** [unoplatform/uno#4245] opened 2020-10-10 16:18 UTC
Hi,

Is there a way how can i reach from c# code property of xaml component? For example i have textbox with specific name. I want to change content from c# code as normal xaml or xamaring applications? If i call this component directly from class it keep saying 
CS0103	The name 'txtText' does not exist in the current content

**Comment by michalss** [comment] 2020-10-10 18:37
ok it is connected to this bug : https://developercommunity.visualstudio.com/content/problem/776876/app-does-not-contain-a-definition-for-initializeco.html

This bug makes uno unusable at this moment you can write it, but you have no intellisence and names need to be right. Bad.. :(

**Comment by jeromelaban** [comment] 2020-10-13 12:08
This issue is a duplicate of #1848.

**Closed by jeromelaban** 2020-10-13 12:08 UTC
