### ISSUE TITLE
Button with BorderThickness=0 has a thin visible border

### ISSUE THREAD

**Issue by manfromarce** [unoplatform/uno#13348] opened 2023-08-22 10:47 UTC
### Current behavior

On all platforms except WinUi a very thin border is displayed for buttons with BorderThickness=0.
It's more noticeable on light theme with transparent background.

WinUi:
![image](https://github.com/unoplatform/uno/assets/45036600/6a5891a8-04f1-42d2-99bc-b74ed80cf51a)

WASM:
![image](https://github.com/unoplatform/uno/assets/45036600/d8289cf0-fe04-453c-a099-e509fc8c1311)

GTK:
![image](https://github.com/unoplatform/uno/assets/45036600/c872516b-ecb6-42ab-8b9f-72fee2ba45ef)

WPF:
![image](https://github.com/unoplatform/uno/assets/45036600/809d8104-5e55-43b9-b591-b730b9ea2078)

### Expected behavior

The border should be completely invisible.

### How to reproduce it (as minimally and precisely as possible)

http://playground.platform.uno/#227ea223

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.9.45

### Affected platforms

WebAssembly, Android, iOS, Mac Catalyst, Skia (WPF), Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment] 2023-08-22 12:22
@MartinZikmund is this related to the border workaround we included in the button style?

**Comment by MartinZikmund** [comment] 2023-09-05 08:37
Yes, this is duplicate of #7621, will be addressed very soon.

**Closed by MartinZikmund** 2023-09-05 08:37 UTC
Labels: kind/bug, triage/untriaged, project/shapes-brushes 🔶, difficulty/tbd
