### ISSUE TITLE
[WASM] Cannot perform AOT build

### ISSUE THREAD

**Issue by peternary** [unoplatform/uno#3128] opened 2020-05-08 15:33 UTC
## Current behavior

If you set the value, '<WasmShellMonoRuntimeExecutionMode>FullAOT</WasmShellMonoRuntimeExecutionMode>' in the Project.Wasm.csproj file then a build will always fail with, "Failed to generate AOT layout"

Note: this is also happening with projects using older versions of Uno packages.  Verified on second machine.

## Expected behavior

AOT build should finish

## How to reproduce it (as minimally and precisely as possible)

Attempt to build the attached project and build will fail.  This is just the default template with the FullAOT executionmode set.

[AotBuild.zip](https://github.com/unoplatform/uno/files/4599930/AotBuild.zip)

Sample MsBuild log: 
[results.log](https://github.com/unoplatform/uno/files/4599942/results.log)

## Environment

Nuget Package:

Uno.UI

Package Version(s):
All tested, but first noticed on 2.3.0-dev.139
Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment] 2020-05-08 16:23
This issue is caused by a recent update of the `emsdk` which causes the bootstrapper to fail. An issue already exists for it: https://github.com/emscripten-core/emsdk/issues/497. This will most likely be fixed soon.

As a temporary workaround,:
 - Open an WSL Ubuntu Shell
 - run 
```bash
cd `wslpath "your_path_to\AotBuild\AotBuild.Wasm\obj\emsdk-1.39.11\emsdk"`
```
 - Run
```bash
git reset 15ac4ffc1e47c956054d643c663e5dc60de81b47 --hard
```
 - Run 
```bash
./emsdk activate --embedded 1.39.11
```

The build should run afterwards.

**Comment by DierkDroth** [comment] 2020-05-08 17:04
Thanks for the workaround @jeromelaban. Much appreciated

**Comment by jeromelaban** [comment] 2020-05-08 18:11
The issue has been fixed in emsdk, you can now build normally.

**Closed by jeromelaban** 2020-05-08 18:11 UTC
Labels: kind/bug, triage/untriaged
