### ISSUE TITLE
Bindings.Update() works differently from UWP

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4040] opened 2020-09-13 15:28 UTC
## Current behavior

When `Bindings.Update()` is called, only active bindings are updated.

## Expected behavior

In UWP, it seems that all bindings (even those which were overwritten?) are updated.

## How to reproduce it (as minimally and precisely as possible)

Consider the following XAML:

```
<Button x:Name="Btn" Background="{x:Bind Color}" Click="Button_Click">Click</Button>
```

And code-behind:

```
public SolidColorBrush Color { get; private set; } = new SolidColorBrush(Colors.Red);

private async void Button_Click(object sender, RoutedEventArgs e)
{
    Btn.Background = new SolidColorBrush(Colors.Blue);
    await Task.Delay(1000);
    Color = new SolidColorBrush(Colors.Green);
    this.Bindings.Update();
}
```

Click the button. Observe it changes its color to blue (overwriting the binding). Then after one second, the button turns green on UWP, whereas it stays blue in Uno.

## Workaround

Do not use `Bindings.Update()` :-D .

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [x] Skia
  - [x] WPF
  - [x] GTK (Linux)
  - [x] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment] 2020-09-13 20:28
Duplicate of #https://github.com/unoplatform/uno/issues/3240, should be fixed by #https://github.com/unoplatform/uno/pull/4035.

**Closed by jeromelaban** 2020-09-13 20:28 UTC
Labels: area/binding, area/xBind, kind/bug

**Comment by MartinZikmund** [comment] 2020-09-14 13:23
@jeromelaban Sorry, searched for "Bindings", that's why I didn't find it

**Comment by jeromelaban** [comment] 2020-09-14 13:28
No worries 🙂 I generally tag x:Bind issues with area/xbind.
