### ISSUE TITLE
[Skia|WASM] [ListView] Sometimes selection background is not set on selected item

### ISSUE THREAD

**Issue by FrozDark** [unoplatform/uno#9415] opened 2022-08-03 13:57 UTC
### Current behavior

Tested a host a listview with random strings array as item source
Tried to select any item and some random times I get no visible selection highlight but event SelectionChanged is raised and SelectedItem property is changed
Often that happens when you scroll out of scope that items and get them back into the scope

### Expected behavior

Visible selection highlight on item

### How to reproduce it (as minimally and precisely as possible)

[UnoApp.zip](https://github.com/unoplatform/uno/files/9251934/UnoApp.zip)
Attached sample repro

### Workaround

-

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

WebAssembly, Skia (WPF), Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### Anything else we need to know?

Dunno if it the same behaviour in the mobile and MacOS platforms

**Comment by ramezgerges** [comment] 2023-08-12 08:51
I'm not sure exactly what the issue is, but does this get fixed by https://github.com/unoplatform/uno/pull/13094?

**Comment by ramezgerges** [comment] 2023-08-23 20:01
This seems to reproduce if the listview is scrolled too rapidly.

**Comment by ramezgerges** [comment] 2023-08-23 23:08
I'm not able to reproduce it in the repro, but I can reproduce it in our SamplesApp sample selector. The problem is that the template only contains a few visual states and doesn't include e.g. `Selected`. When the selected item is initially selected, the ListViewItem will go to the (not missing) `Pressed` state and then fail to go to the `Selected` or `SelectedPointerOver` states, but will keep the `Pressed` background, Once the internal VirtualizingPanel is scrolled far enough so that the ListViewItems are wiped and have to be recreated again, the selected ListViewItem will immediatly go to the missing `Selected` state and not get any background.

**Closed** 2023-09-11 17:32 UTC
Labels: kind/bug, platform/wasm 🌐, area/skia ✏️, area/listview 📃, project/items 🧾, difficulty/medium 🤔, low-hanging-🍒
