### ISSUE TITLE
Align `ItemTemplateSelector` behavior for `ListView/ComboBox/ItemsControl`

### ISSUE THREAD

**Issue by jeromelaban** [unoplatform/uno#363] opened 2018-11-16 18:28 UTC
## I'm submitting a...
- Bug report

## Current behavior
Providing a DataTemplateSelector to a ItemsControl, ListView or ComboBox does not call the same `SelectTemplateCore` overload. (e.g. ItemsControl calls [this](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.datatemplateselector.selecttemplate#Windows_UI_Xaml_Controls_DataTemplateSelector_SelectTemplate_System_Object_Windows_UI_Xaml_DependencyObject_) where as ListView calls [this](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.datatemplateselector.selecttemplate#Windows_UI_Xaml_Controls_DataTemplateSelector_SelectTemplate_System_Object_))

It also seems that in the context of the `ListView` if one overload returns the other is tentatively called.

## Expected behavior
The behavior is the same as UWP.

## Workaround
Have both `DataTemplateSelector.SelectTemplateCore` do the same thing, if the `container` parameter is not used.

## Environment
Nuget Package: 1.41.1

**Comment by chingucoding** [comment] 2021-08-19 17:37
Is this issue still accurate? All controls use the `DataTemplateHelper` except the `ItemTemplateWrapper`. Should we update the ItemTemplateWrapper to also use the `DataTemplateHelper`?

**Comment by davidjohnoliver** [comment] 2021-08-19 17:45
> Is this issue still accurate? All controls use the `DataTemplateHelper` except the `ItemTemplateWrapper`. Should we update the ItemTemplateWrapper to also use the `DataTemplateHelper`?

This is an older issue and it's possible it was fixed already, have you done some testing that indicates so?

As for `ItemTemplateWrapper`, that code has been imported directly from the WinUI source for ItemsRepeater, so it should stay as it is.

**Comment by chingucoding** [comment] 2021-08-19 17:47
I just searched for the SelectTemplate functions in code and found that there are only two occurences for it, i.e. `DataTemplateHelper` and `ItemTemplateWrapper`. That's why I concluded that the behavior should be the same since the controls reference the `DataTemplateHelper`.

**Comment by eriklimakc** [comment] 2022-10-18 19:22
I have tried to reproduce this issue but it didn't go forward. As mentioned by @chingucoding `DataTemplateHelper` is handling `DataTemplateSelector` for the controls and all of them had the same behavior on my test, for both overloads.

**Comment by morning4coffe-dev** [comment] 2024-09-29 10:17
@MartinZikmund I have tested this on all platforms (except iOS) and all seems to work the same as on WinUI. 

My project for reference:
[ItemTemplateSelector.zip](https://github.com/user-attachments/files/17178847/ItemTemplateSelector.zip)

![image](https://github.com/user-attachments/assets/1dab68b6-8786-4eac-84f3-2e985cd57d8e)

**Comment by MartinZikmund** [comment] 2024-09-30 09:45
Great, closing for now!

**Closed as completed by MartinZikmund** 2024-09-30 09:45 UTC
Labels: kind/bug, good first issue, project/items 🧾, difficulty/starter 🚀, triage/potentially-fixed
