### ISSUE TITLE
Move NavigationView to Microsoft.UI.Xaml namespace

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4015] opened 2020-09-09 17:24 UTC
## What would you like to be added:

Currently, the `NavigationView` is in the Windows.UI.Xaml namespace, while its implementation is based on WinUI. This is problematic, as a UWP app most likely use the `winui:` version in XAML, which will not work properly for Uno, where the `Microsoft.UI.Xaml.Controls.NavigationView` type does not exist.

## Why is this needed:

Make it easier to use `NavigationView`

## For which Platform:

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by robloo** [comment] 2020-09-09 17:47
It also needs to be updated to take advantage of the latest WinUI changes such as hierarchical navigation view. 

@MartinZikmund Are you planning on working on this? Otherwise, I have this on the to-do list I need for an app and can get it it in a week or so.

**Comment by jeromelaban** [comment] 2020-09-09 18:07
@robloo the latest navigation view uses the ItemsRepeater, which is still in progress (#3192). This issue is a duplicate of #3942.

**Closed by jeromelaban** 2020-09-09 18:07 UTC
Labels: area/navigationview, kind/enhancement
