### ISSUE TITLE
TranslationAnimation and  ScalarAnimation attributes fail compilation

### ISSUE THREAD

**Issue by zipswich** [unoplatform/uno#5829] opened 2021-04-26 19:22 UTC
## Describe the bug
```
    <animations:Implicit.ShowAnimations>
        <animations:TranslationAnimation Duration="0:0:1" To="0" From="0,200,0" />
        <animations:OpacityAnimation Duration="0:0:3" From="0" To="1.0"/>
    </animations:Implicit.ShowAnimations>
    <animations:Implicit.HideAnimations>
        <animations:ScalarAnimation Target="Translation.Y" Duration="0:0:1" From="-200"  To="0"/>
    </animations:Implicit.HideAnimations>
```
The above code in Xaml causes the VS compilation to throw the following errors:
`System.Exception: Processing failed for file UserControlMediaFileToastNotification.xaml (System.Exception: Unable to convert 0,200,0 for From with type string?`
`System.Exception: Unable to convert Translation.Y for Target with type string?`

- [x] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work: 6.1.0-build.207.gcac670e618

## Steps to Reproduce
1. Add the above code in an Xaml file.  In this case, it is a UserControl of a Uno XP library
2. Build the project.

- [ ] Can this be reproduced in the Sample App? (Either in a sample as-is or with new XAML pasted in the editor.) If so, please provide custom XAML or steps to reproduce. If not, let us know why it can't be reproduced (e.g. more complex setup, environment, dependencies, etc...) 

## Expected behavior
Build the project successfully.

## Environment

```
NuGet Package(s): 

  <ItemGroup Condition="'$(TargetFramework)' != 'uap10.0.18362'">
    <PackageReference Include="Uno.Microsoft.Toolkit" Version="7.1.0-build.2.g0e224f133a" />
    <PackageReference Include="Uno.Microsoft.Toolkit.Uwp" Version="7.1.0-build.2.g0e224f133a" />
    <PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI" Version="7.1.0-build.2.g0e224f133a" />
    <PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Animations" Version="7.1.0-build.2.g0e224f133a" />
    <PackageReference Include="Uno.Microsoft.Toolkit.Uwp.UI.Controls" Version="7.1.0-build.2.g0e224f133a" />
    <PackageReference Include="Uno.Microsoft.Toolkit.Uwp.Notifications" Version="6.1.0-build.207.gcac670e618" />
  </ItemGroup>

Device form factor:
- [x] Windows
- [ ] macOS
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms

Visual Studio 
- [ ] 2017 (version: )
- [ ] 2019 (version: ) 
- [x] 2019 Preview (version: 16.9.4)

```

**Comment by Youssef1313** [comment] 2021-08-09 08:19
Looks like a duplicate of https://github.com/unoplatform/uno/issues/6688.

**Closed** 2021-08-24 20:55 UTC
Labels: kind/enhancement, area/code-generation, area/xaml-reader, project/core-tools, difficulty/medium
