### ISSUE TITLE
Overwriting accent color via SystemAccentColor key does not work

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#3555] opened 2020-07-16 16:49 UTC
## Current behavior

When `SystemAccentColor` is overwritten, it is not applied to derived resources like `SystemColorControlAccentBrush`.

## Expected behavior

Should apply the color to all derived resources.

## How to reproduce it (as minimally and precisely as possible)

```
<Application
    x:Class="HealthApp.App"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:HealthApp">
    <Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls" />
            </ResourceDictionary.MergedDictionaries>
            <Color x:Key="SystemAccentColor">#E64A19</Color>
        </ResourceDictionary>
    </Application.Resources>
</Application>
```

On main page:

```
 <Grid Background="{ThemeResource SystemColorControlAccentBrush}"></Grid>
```

## Probable reason for the issue

In Generic.xaml, each theme has:
```
			<!-- Added manually (not part of UWP's SystemResources.xaml) -->
			<Color x:Key="SystemColorHighlightColor">#FF3399FF</Color>
			<Color x:Key="SystemAccentColor">#FF0078D7</Color>
			<SolidColorBrush x:Key="SystemColorControlAccentBrush"
					 Color="{StaticResource SystemAccentColor}" />
```

I guess the SystemAccentColor is set as StaticResource, and providing a custom one in does not overwrite it for `SystemColorControlAccentBrush`.

## Workaround

Define the `SystemColorControlAccentBrush` manually as well in App.xaml:

```
<Color x:Key="SystemAccentColor">#E64A19</Color>
<SolidColorBrush x:Key="SystemColorControlAccentBrush"
					 Color="{StaticResource SystemAccentColor}" />
```

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):

- [x] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

**Comment by MartinZikmund** [comment] 2020-11-02 18:01
@davidjohnoliver actually it seems this could just about making sure the `SystemColorControlAccentBrush` and related use `ThemeResource` instead of `StaticResource` when referencing the accent color, correct?

**Comment by davidjohnoliver** [comment] 2020-11-02 18:09
> @davidjohnoliver actually it seems this could just about making sure the `SystemColorControlAccentBrush` and related use `ThemeResource` instead of `StaticResource` when referencing the accent color, correct?

That should hopefully do it, yes.

**Comment by MartinZikmund** [comment] 2020-11-04 15:43
It turns out this actually does work in the end. Overwriting just the `Color` is not possible, not even in UWP.

What does work is to override the brushes:

```
<Application.Resources>
    <SolidColorBrush x:Key="SystemControlHighlightAccentBrush" Color="Red" />
    <SolidColorBrush x:Key="SystemColorControlAccentBrush" Color="Red" />
</Application.Resources>
```

This properly overrides accent color and highlight accent color and these are then even reflected on controls like `ToggleButton`

**Comment by davidjohnoliver** [comment] 2021-04-28 10:11
@MartinZikmund I'm not sure why you closed this issue? Putting the following `App.Resources` works on UWP, but not with Uno:
```
<Color x:Key="SystemAccentColor">HotPink</Color>
```

(eg to change checked background of `CheckBox`)

**Comment by MartinZikmund** [comment] 2021-04-28 10:15
Probably I did something wrong when testing on UWP back then. Reopening 👍

**Comment by jeromelaban** [comment] 2022-01-27 19:19
Fixed in Uno latest, single-file merged dictionaries allow for the resolution to work as intended when using the resource explicitly, but it won't override the color when defined in fluent styles (even in WinUI).

Closing for now.

**Closed by jeromelaban** 2022-01-27 19:19 UTC
Labels: kind/bug, project/styling, project/resources, difficulty/medium
