### ISSUE TITLE
Make sure TemplateBinding with attached DPs works with XamlReader

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#13121] opened 2023-08-04 10:31 UTC
> have you tested if the same works with XamlReader.Load?

_Originally posted by @Xiaoy312 in https://github.com/unoplatform/uno/pull/13002#pullrequestreview-1551332010_

**Comment by Xiaoy312** [comment] 2023-08-05 19:22
setup:
```
XamlHelper.LoadXaml<Style>("""
	<Style TargetType="ContentControl">
		<Setter Property="ScrollViewer.HorizontalScrollMode" Value="Disabled" />
		<Setter Property="Template">
			<Setter.Value>
				<ControlTemplate TargetType="ContentControl">
					<ScrollViewer x:Name="SUT" HorizontalScrollMode="{TemplateBinding ScrollViewer.HorizontalScrollMode}">
						<ContentPresenter />
					</ScrollViewer>
				</ControlTemplate>
			</Setter.Value>
		</Setter>
	</Style>
"""),
```
throws:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Exception: The property Windows.UI.Xaml.Controls.ContentControl.ScrollViewer.HorizontalScrollMode does not exist
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.BuildLiteralValue(XamlMemberDefinition member, Type propertyType) in D:\code\uno\framework\uno\src\Uno.UI\UI\Xaml\Markup\Reader\XamlObjectBuilder.cs:line 1207
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessNamedMember(XamlObjectDefinition control, Object instance, XamlMemberDefinition member, Object rootInstance) in D:\code\uno\framework\uno\src\Uno.UI\UI\Xaml\Markup\Reader\XamlObjectBuilder.cs:line 389
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.LoadObject(XamlObjectDefinition control, Object rootInstance, Object component, Boolean createInstanceFromXClass) in D:\code\uno\framework\uno\src\Uno.UI\UI\Xaml\Markup\Reader\XamlObjectBuilder.cs:line 233
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.AddCollectionItems(Object collectionInstance, IEnumerable`1 nonBindingObjects, Object rootInstance) in D:\code\uno\framework\uno\src\Uno.UI\UI\Xaml\Markup\Reader\XamlObjectBuilder.cs:line 1116
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessMemberElements(Object instance, XamlMemberDefinition member, PropertyInfo propertyInfo, Object rootInstance) in D:\code\uno\framework\uno\src\Uno.UI\UI\Xaml\Markup\Reader\XamlObjectBuilder.cs:line 733
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.ProcessNamedMember(XamlObjectDefinition control, Object instance, XamlMemberDefinition member, Object rootInstance) in D:\code\uno\framework\uno\src\Uno.UI\UI\Xaml\Markup\Reader\XamlObjectBuilder.cs:line 401
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.LoadObject(XamlObjectDefinition control, Object rootInstance, Object component, Boolean createInstanceFromXClass) in D:\code\uno\framework\uno\src\Uno.UI\UI\Xaml\Markup\Reader\XamlObjectBuilder.cs:line 233
   at Windows.UI.Xaml.Markup.Reader.XamlObjectBuilder.Build(Object component, Boolean createInstanceFromXClass) in D:\code\uno\framework\uno\src\Uno.UI\UI\Xaml\Markup\Reader\XamlObjectBuilder.cs:line 73
   at Windows.UI.Xaml.Markup.XamlReader.Load(String xaml) in D:\code\uno\framework\uno\src\Uno.UI\UI\Xaml\Markup\XamlReader.cs:line 15
   at Uno.UI.Helpers.XamlHelper.LoadXaml[T](String xaml, Dictionary`2 xmlnses) in D:\code\uno\framework\uno\src\Uno.UI\Helpers\XamlHelper.cs:line 82
   at Uno.UI.Helpers.XamlHelper.LoadXaml[T](String xaml, Boolean autoInjectXmlns) in D:\code\uno\framework\uno\src\Uno.UI\Helpers\XamlHelper.cs:line 66
   at Uno.UI.RuntimeTests.Tests.Windows_UI_Xaml_Markup.Given_XamlReader.When_TemplateBinding_AttachedProperty_AsdAsd2() in D:\code\uno\framework\uno\src\Uno.UI.RuntimeTests\Tests\Windows_UI_Xaml_Markup\Given_XamlReader.cs:line 208
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Uno.UI.Samples.Tests.UnitTestsControl.<>c__DisplayClass63_4.<ExecuteTestsForInstance>b__5() in D:\code\uno\framework\uno\src\SamplesApp\SamplesApp.UnitTests.Shared\Controls\UnitTest\UnitTestsControl.cs:line 807
   at Uno.Threading.FastTaskCompletionSource`1.GetResult() in D:\code\uno\framework\uno\src\Uno.Foundation\Uno.Core.Extensions\Uno.Core.Extensions.Threading\FastTaskCompletionSource.cs:line 285
   at Uno.Threading.FastTaskCompletionSource`1.CreateAsyncTask() in D:\code\uno\framework\uno\src\Uno.Foundation\Uno.Core.Extensions\Uno.Core.Extensions.Threading\FastTaskCompletionSource.cs:line 368
   at Uno.UI.Samples.Tests.UnitTestsControl.<>c__DisplayClass63_2.<<ExecuteTestsForInstance>g__InvokeTestMethod|2>d.MoveNext() in D:\code\uno\framework\uno\src\SamplesApp\SamplesApp.UnitTests.Shared\Controls\UnitTest\UnitTestsControl.cs:line 787
```

**Comment by Xiaoy312** [comment] 2023-08-06 01:23
the problem is two fold...:
1. XamlReader fails to read "attached.property" or "xmlnsed:attached.property" on Setter.Property
2. TemplateBinding somehow fails to read the value from this TemplateBinding...
	^ the BindingExpressionand and BindingPath had the proper path "ScrollViewer.HorizontalScrollMode"
	^ but, BindingItem.PropertyName is "ScrollViewer"!!

**Comment by Xiaoy312** [comment] 2023-09-05 20:34
Closing this issue, since the topic here is **parsing** of TemplateBinding of attached property in the context of XamlReader.
p2 from about comment will be tracked in another issue (see referencing issue above).

**Closed by Xiaoy312** 2023-09-05 20:34 UTC
Labels: area/xaml-reader
