### ISSUE TITLE
Build error SA1633 when compiling an Uno Platform library.

### ISSUE THREAD

**Issue by Suriman** [unoplatform/uno#9980] opened 2022-09-27 05:52 UTC
### Current behavior

In the library .csproj file, the 'TreatWarningsAsErrors' configuration is enabled and the 'XamlGeneratorAnalyzerSuppressions Include="StyleCop.CSharp.DocumentationRules-SA1633"' configure is also added, but the build error still appears.

### Expected behavior

It shouldn't give any compile errors.

### How to reproduce it (as minimally and precisely as possible)

Open the attached project and compile it. The SA1633 error should appear.

### Workaround

Add the SA1633 to the NoWarn configuration.

### Works on UWP/WinUI

No

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.WinUI 4.5.12

### Affected platforms

iOS, Android, WebAssembly, macOS, Skia (WPF), Skia (GTK on Linux/macOS/Windows), Windows

### IDE

Visual Studio 2022

### IDE version

17.3.4

### Anything else we need to know?

See attached file!
[SA1633CompilationError2.zip](https://github.com/unoplatform/uno/files/9652008/SA1633CompilationError2.zip)

**Comment by Youssef1313** [comment] 2022-09-27 06:01
@Suriman Can you try `<XamlGeneratorAnalyzerSuppressions Include="csharp-SA1633" />`?

**Comment by ADD-David-Antolin** [comment] 2022-09-27 06:26
The problem is in the generation of this file: 

https://github.com/unoplatform/uno/blob/master/src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs#L118

There are no supressions applied to that string so using <XamlGeneratorAnalyerSuppressions> does not make any difference.

**Comment by Youssef1313** [comment] 2022-09-27 06:33
@ADD-David-Antolin It looks like we are missing a call for `GenerateCSharpPragmaSupressions` around these lines https://github.com/unoplatform/uno/blob/7cc2df180fb8b5833f3f6e05b50ac8d4ed4a8e99/src/SourceGenerators/Uno.UI.SourceGenerators/BindableTypeProviders/BindableTypeProvidersGenerationTask.cs#L173-L175

**Comment by Youssef1313** [comment] 2022-09-27 06:36
There should be no need for the suppression actually. We don't mark the file as auto-generated which is wrong too. If it's marked as such, then SA1633 will not produce a diagnostic at all.

https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/6478404520b39f002ae0ce2d062f1474cf27b14f/StyleCop.Analyzers/StyleCop.Analyzers/DocumentationRules/FileHeaderAnalyzers.cs#L176

**Closed** 2022-09-29 12:06 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd

**Comment by ADD-David-Antolin** [comment] 2023-02-13 11:25
After updating to Uno 4.7 this error is happening again with your autogenerated class [LocalizationResources.cs](https://github.com/unoplatform/uno/blob/a6eda7c5d1ab8d2b34cfc443fbd54e9432b8cf16/src/SourceGenerators/Uno.UI.SourceGenerators/XamlGenerator/XamlCodeGeneration.cs#L409) which it is not marked as autogenerated.

**Comment by Youssef1313** [comment] 2023-02-13 11:29
@ADD-David-Antolin Thanks for raising this. I opened https://github.com/unoplatform/uno/pull/11291 to fix it.

**Comment by jeromelaban** [comment] 2023-02-13 13:38
@ADD-David-Antolin make sure to open new issues even if the symptoms look similar. We generally do not reopen older issues as they are generally effectively different.
