### ISSUE TITLE
When the name of a solution (based on Uno Template)  starts with numbers, it creates errors

### ISSUE THREAD

**Issue by iury-kc** [unoplatform/uno#8285] opened 2022-03-09 19:07 UTC
### Current behavior

Creating a new solution based on Uno Templates with a name that starts with numbers, it shows the following error:

![image](https://user-images.githubusercontent.com/100223422/157512039-48a7b923-6aee-4634-b437-632a5afdd34d.png)

Some of the folders aren`t created and the project remains incomplete.

Probably the error is related to the fact VS tries to add an underline symbol before the name.

### Expected behavior

As other MS Templates, the solution`s name must accept a name which starts with numbers.

### How to reproduce it (as minimally and precisely as possible)

Just create a new solution and give a name that starts with numbers, like 8888issueTest 

### Environment

Other

### Affected platforms

Solution Templates

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment] 2022-03-09 19:59
Thanks for the report, this is a duplicate of https://github.com/unoplatform/uno/issues/5009

**Closed by jeromelaban** 2022-03-09 19:59 UTC
Labels: kind/bug, triage/untriaged, area/solution-templates, difficulty/tbd
