### ISSUE TITLE
Wasm: ContentDialog Closing support

### ISSUE THREAD

**Issue by yowl** [unoplatform/uno#1494] opened 2019-09-06 16:21 UTC
## What would you like to be added:
The Closing event
## Why is this needed:
To get parity with UWP and allow scenarios where the closing should be prevented

## For which Platform:

- [ ] iOS
- [ ] Android
- [x ] WebAssembly
- [ ] Windows

## Anything else we need to know?

See https://github.com/yowl/UnoStandardRefTest2/tree/contentdialog-closing for an example

**Comment by ghuntley** [comment] 2019-09-07 01:28
Looks like GitHub raised two issues during creation. Closing this as duplicate of https://github.com/unoplatform/uno/issues/1495

**Closed by ghuntley** 2019-09-07 01:28 UTC
Labels: kind/enhancement, triage/untriaged
