### ISSUE TITLE
[ComboBox] SelectedIndex isn't taken into account

### ISSUE THREAD

**Issue by agneszitte-nventive** [unoplatform/uno#8557] opened 2022-04-15 02:02 UTC
### Current behavior

Use a simple ComboBox with two entries and precise the SelectedIndex property.
The SelectedIndex isn't taken into account, no item selected

![image](https://user-images.githubusercontent.com/16295702/163506790-1cafa1d7-8fe1-4366-b478-9604cbb6e13f.png)

### Expected behavior

Combobox SelectedIndex is taken into account like on UWP/WinUI and you can see the proper selected item

![image](https://user-images.githubusercontent.com/16295702/163506810-4b795019-104c-4a39-a485-2f1fc9c7d310.png)

### How to reproduce it (as minimally and precisely as possible)

```
    <ComboBox Header="Test ComboBox SelectedIndex:"
              SelectedIndex="1"
              VerticalAlignment="Center"
              HorizontalAlignment="Center">
        <x:String>Choice number 1</x:String>
        <x:String>Choice number 2</x:String>
    </ComboBox>
```

### Workaround

N/A 

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI 4.2.0-dev.622

### Affected platforms

iOS, Android, WebAssembly, Skia (GTK on Linux/macOS/Windows)

### IDE

Visual Studio 2022

### IDE version

Version 17.2.0 Preview 3.0

### Relevant plugins

N/A

**Comment by agneszitte-nventive** [comment] 2022-04-15 02:03
For info @jeromelaban, @carldebilly, @MartinZikmund, @kazo0 and @Xiaoy312.

**Comment by Youssef1313** [comment] 2022-04-15 09:46
I recall I had a PR previously that attempts to fix this bug, but someone (I think @davidjohnoliver) pointed out that it's more complex than what I did and code needs to be ported from internal sources.

**Comment by Youssef1313** [comment] 2022-04-15 09:49
Duplicate of https://github.com/unoplatform/uno/issues/4686.

PR where I attempted to fix this https://github.com/unoplatform/uno/pull/6775
Ignored tests were added in https://github.com/unoplatform/uno/pull/6786

**Closed** 2022-04-15 17:48 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
