### ISSUE TITLE
[WASM + i(Pad)OS] Performance

### ISSUE THREAD

**Issue by DierkDroth** [unoplatform/uno#10903] opened 2023-01-06 06:28 UTC
### Current behavior

I'm experiencing massive performance problems when running my (UNO WASM) app on iOS/iPadOS
- to understand what's going on I was using [Uno Gallery](https://gallery.platform.uno/) as reference and confirmed a similar behavior
- next I tried to isolate the source of trouble on using [this as a WASM benchmark](https://pspdfkit.com/webassembly-benchmark/) app
- I also tested if I could replicate the problem on Safari and Chrome on my MacBook Air

Tested platforms:
A) Dell Laptop (state of the art) + Windows 11 + Chrome (V8 engine)
B) iPhone (~2 years old) + iOS (latest) + Safari (and Chrome, which has the same WebKit engine)
C) iPad (~2 years old) + iPadOS (latest) + Safari (and Chrome, which has the same WebKit engine)
D) MacBook Air + MacOS (latest) + Safari (WebKit engine)
E) MacBook Air + MacOS (latest) + Chrome (V8 engine)

Results for the [WASM benchmark](https://pspdfkit.com/webassembly-benchmark/) (**no Uno nor .NET WASM involved**):
A) ~2650ms
B) ~3800ms
C) ~3800ms
D) ~4800ms
E) ~ 3400ms

WASM performance baseline:
- comparing D and E: WebKit is ~35% slower than V8
- no setup is grossly off, all setups are 'in the same ballpark'

However, the [Uno Gallery experience](https://gallery.platform.uno/) **(using UNO and .NET WASM)** is massively different. I preloaded Uno Gallery to browser cache, started it again and stopped the timer as the page was fully rendered
A) < 2 secs
B) ~13 secs
C) ~21 secs
D) ~15 secs
E) < 4 secs

Findings:
- **UNO WASM has a massive performance problem on the WebKit engine**
- this is not related to the pure WASM performance of the WebKit engine, but must be somewhere in the UNO or .NET WASM layer
- comparing B and C and understanding that more stuff is rendered on iPad than on iPhone suggests this might be related to rendering logic

What could be done to improve the UNO WASM performance on the WebKit engine?

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

**Comment by jeromelaban** [comment] 2023-01-09 22:05
Thanks for the benchmarks. 

We do not have any insights into what could be the issue. It may not be a WebAssembly specific issue, but rather a unknown DOM or Javascript issue.

**Comment by DierkDroth** [comment] 2023-01-10 04:50
Thanks for your feedback @jeromelaban 

@francoistanguay @jeromelaban to be clear: this means that UNO WASM is not an option for WebKit (iOS and iPadOS as well as the default browser on MacOS).

Using the UNO iOS/MacOS head instead would come with massive implications like:
- establishing the development/testing/deployment/support infrastructure for a different technology stack
- dealing with significant technical restrictions like no dynamic loading, which [is possible using WASM](https://github.com/unoplatform/uno/discussions/10564)
- deployment only through store which has massive economical implications and comes with legal restrictions
- ...

After all WebAssembly is the 'promise' for an universal execution platform and UNO WASM fills the gap on the UI layer perfectly - as demonstrated e.g. on the Chrome V8 engine. It would be a shame if UNO WASM would fall short on WebKit...

What could be done to analyze, understand and ultimately fix the problem?
Would a (paid) custom project be an option?

**Comment by jeromelaban** [comment] 2023-01-19 22:10
This issue has been identified as a duplicate of https://github.com/dotnet/runtime/issues/61373, where the Wasm JIT is significantly slower on specific code patterns. This is not an issue we can work on from our end, as it's likely a Safari issue at the root.

**Closed by jeromelaban** 2023-01-19 22:10 UTC
Labels: kind/bug, platform/wasm, difficulty/tbd

**Comment by DierkDroth** [comment] 2023-01-20 05:52
@jeromelaban thanks for looking into. Much appreciated

To clarify for my understanding: there (likely) would not be an issue if the compilation would be 100% AOT, correct?
So, apparently there still are JIT parts in place (AFAIK this still is true for exception handling on NET WASM?!?)

Would you know what the MS gameplan is regarding getting rid of the last JIT bits?

**Comment by SteveSandersonMS** [comment] 2023-01-20 10:37
> To clarify (for my understanding): there (likely) would not be an issue if the compilation would be 100% AOT, correct? So, apparently there still are JIT parts in place (AFAIK this still is true for exception handling on NET WASM?!?)

No, that's not correct. .NET on WebAssembly uses a mixture of AOT and interpreted modes. There is not currently any JITting from CIL (.NET) bytecode to anything else, except if you count how the interpreter works. (In the future, we may add an actual JIT approach from CIL to WebAssembly, but that is not present in your existing code.)

When @jeromelaban refers to JIT above, I expect he is referring to how WebAssembly bytecode is JITted within browsers to natively executable code, which is not an aspect of .NET.

**Comment by DierkDroth** [comment] 2023-01-20 10:50
@SteveSandersonMS thanks for following up.

Here is what I don't understand (still): if you're looking at [this WASM 'benchmark'](https://pspdfkit.com/webassembly-benchmark/) then it's clear that the Safari/WebKit WASM engine is not that far off Chrome's V8 engine (also, see details in my very first post above).

However, as it goes to UNO WASM (and BLAZOR WASM as well, I suppose) and my app (using UNO WASM), then the picture is very different: the apps are many times slower on Safari/WebKit than on Chrome.

Why is that and what could be done to resolve the issue?

**Comment by jeromelaban** [comment] 2023-01-20 13:55
> When @jeromelaban refers to JIT above, I expect he is referring to how WebAssembly bytecode is JITted within browsers to natively executable code, which is not an aspect of .NET.

Indeed, the JIT I mentioned is the browser's JIT. Thanks!

> Hence, I'm not sure I agree that JITing the WASM bytecode to the browsers native code would the source of trouble, since benchmark above shows that this would not cause the observed performance problem.

The benchmarks above are unfortunately a marketing tool for both Safari (here's [the reference](https://www.youtube.com/watch?v=1v4wPoMskfo)) and Chromium teams, meaning that they're optimized for the scenarios provided by the benchmark.

It's entirely possible that code generated by LLVM in certain parts of the C parts runtime are hitting a pattern that is not optimized in the JIT. We've seen this a while back with Chromium where large switch/case patterns (such as the one using inside the interpreter IL dispatch) would cause significant performance issues.

We hadn't finished compiling the data from our own investigations, but here's an excerpt:

<img width="839" alt="image" src="https://user-images.githubusercontent.com/5839577/213712909-3db9847e-04d2-4e55-9972-7e6b3472ffc9.png">

which shows (which Safari's limited profiling capabilities) methods like `mono_method_decode_row_raw` taking as much as 10x more time to finish under Safari that it does on Chrome on the same machine.

As is it coming from a browser component, seemingly raised by code generated by LLVM, this is not something that Uno can adjust on its own, and likely in a very limited way by the runtime team.

**Comment by DierkDroth** [comment] 2023-01-20 17:42
Thanks again for the insights @jeromelaban.

Sorry for follow up, but as @vargaz [mentioned here](https://github.com/dotnet/runtime/issues/60247#issuecomment-1025065213), there still is a lot of .NET code in place which is JITed from .NET CIL bytecode (and not from WASM bytecode) to native code - if I understand him correctly.

Would we know if the problem in fact is caused by performance issues of JITing WASM bytecode to native code and not rather by JITing .NET CIL bytecode to native code - whcih according @vargaz still is in place aplenty? 

If the former, then clearly the ball is in Apple's court, if the latter then that would be an issue which Microsoft could work on, no?

**Comment by SteveSandersonMS** [comment] 2023-01-20 18:01
>  there still is a lot of .NET code in place which is JITed from .NET CIL bytecode (and not from WASM bytecode) to native code

I don't think that is something that happens in a browser.

**Comment by jeromelaban** [comment] 2023-01-20 18:13
Indeed there isn't. The fact that methods called `jit` are present in call stacks is for code path reuse inside the runtime, as many parts on other platforms use the same mechanics between x86/x64/arm JIT and the IL interpreter.

Yes, there are parts that are still Interpreted when building with AOT, but it's not relevant to the current issue, as the parts that are slower in Safari are already AOTed to Wasm, or are just plain C code compiled to Wasm.

**Comment by DierkDroth** [comment] 2023-01-21 06:13
@SteveSandersonMS @jeromelaban thanks again.

Well, appears we're on Apple mercy ... or could hope that [EU regulations get us some healthy competition](https://www.theregister.com/2022/04/26/apple_ios_browser/) on iOS (on Mac there already is Chrom V8).
