### ISSUE TITLE
x:Load not working properly on WASM

### ISSUE THREAD

**Issue by s-beltz** [unoplatform/uno#5392] opened 2021-03-04 16:14 UTC
## Current behavior

We use x:Load in many of our more complex custom controls in order to enable different layout styles depending on the current state of the application (screen size/orientation, user preferences, etc.). 

On WASM heads (and lately also on Android) x:Load seems not to be working anymore. 
We see a lot of console output regarding x:Load like this:
> The property Load does not exist on Windows.UI.Xaml.Controls.ContentPresenter
dotnet.js:2297       
> The property Load does not exist on Microsoft.Toolkit.Uwp.UI.Controls.DataGrid
> ...

The complexity of these controls and their resprective templates is quite high. Thus it is not an option to realize all elements into the visual tree on control load and just bind Visibility. 

## Expected behavior

x:Load should be bindable (x:Bind) on all platforms. When x:Load is false the element needs to be removed from the visual tree.

## How to reproduce it (as minimally and precisely as possible)

[UnoItemsRepeaterRepro.zip](https://github.com/unoplatform/uno/files/6110213/UnoItemsRepeaterRepro.zip)
Start the WASM or Android head. The above mentioned output ("The property Load does not exist") will be visible in console log directly after start of the app. Clicking the button on the first Tab page will make the buttons disappear. But that might be another issue.

Additionally WASM shows messages that led us to wonder if the element gets removed from the visual tree after all:
>dotnet.js:1 fail: Windows.UI.Xaml.DependencyObjectStore[0]
dotnet.js:1       The property Load does not exist on Windows.UI.Xaml.Shapes.Ellipse
dotnet.js:1 warn: Windows.UI.Xaml.NameScope[0]
dotnet.js:1       ***The name [square] already exists in the current XAML scope***

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):
Uno.UI Version: 3.6.0-dev.180

Affected platform(s):

- [ ] iOS
- [x] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.8.6)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment] 2021-03-04 18:12
Thanks for the report. This feature is supported, and you're probably hitting a corner case.

Can you share a repro sample ?

**Comment by dr1rrb** [comment] 2021-04-23 14:22
The issue is that each time the `x:Load` goes to `true` changes a new instance is created, but the `Setter` continues to use the first one.

Listening to the instance change by adding `subject.ElementInstanceChanged += delegate { _bindingPath.DataContext = subject.ElementInstance; };` [here](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Setter.cs#L181) fixes the issue only partially.

Depending on when the visual state is activated, the `ElementInstanceChanged` will be raised to late, so the `Setter` will use the previous instance. To fix it we need to add a proper callback for the "dematerialize" in order to clean up the `Setter` as soon as possible, so on next activation it will cause materialization of the element properly (and use the update instance).

**Comment by jeromelaban** [comment] 2021-04-27 21:40
For this particular issue, https://github.com/unoplatform/uno/issues/5836 cannot be fixed easily as the Uno implementation differs too deeply to be fixed without a major refactoring.

For the particular sample attached, the workaround is to rely on events from controls, not through the properties event ordering.

Specifically, use `Loading="{x:Bind OnRectangleLoading}"` and `Loading="{x:Bind OnEllipseLoading}"` to update visual states, so the controls are ensured to be materialized properly after the `x:Load` state changed.

#5831 is needed for this workaround to work.

**Closed** 2021-04-28 17:12 UTC
Labels: area/xBind, difficulty/tbd, kind/bug, project/binding
