### ISSUE TITLE
NavigationView not working when using fluent styles

### ISSUE THREAD

**Issue by manfromarce** [unoplatform/uno#5265] opened 2021-02-17 22:00 UTC
## Current behavior

The NavigationView's panel isn't visible on Android. The back button and toggle button are visible but they do nothing when I press them.

## Expected behavior

NavigationView should work normally as in UWP.

## How to reproduce it (as minimally and precisely as possible)
Download the minimal repro solution and build it with Visual Studio: 
[MinimalSol.zip](https://github.com/unoplatform/uno/files/5998879/MinimalSol.zip)
I'm using Visual Studio's Android Emulator (Google Pixel 2 with Android 9,0).
I haven't tried yet if the problem also occurs on iOS.

## Environment

Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s): 3.5.1

Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: 16.8)
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

**Comment by IsmailHassani** [comment] 2021-02-17 22:35
This issue seems to happen on WPF and WASM head also.
I upgraded my project from version 3.4.0 to 3.5.1 when this behavior occurs.
If you take the source of the [dev branch](https://github.com/I-Synergy/I-Synergy.Framework/tree/features/dev) and update all Uno references to version 3.5.1 you'll notice this change.

**Comment by IsmailHassani** [comment] 2021-02-17 22:36
![image](https://user-images.githubusercontent.com/7172716/108276999-f546bc80-7178-11eb-9f0b-149be9c75c2c.png)

WASM head

**Comment by IsmailHassani** [comment] 2021-02-17 22:38
![image](https://user-images.githubusercontent.com/7172716/108277091-27f0b500-7179-11eb-9ab2-fce8ba0a75e1.png)

WPF head

**Comment by IsmailHassani** [comment] 2021-02-17 22:49
If i use the WinUI NavigationView [Net5.0 branch](https://github.com/I-Synergy/I-Synergy.Framework/tree/features/net5.0) this same behavior occurs, except that the header is visible.

![image](https://user-images.githubusercontent.com/7172716/108278042-b580d480-717a-11eb-9218-5507d19368c1.png)

**Comment by jeromelaban** [comment] 2021-02-18 12:53
@MartinZikmund does it sound familiar ?

**Comment by MartinZikmund** [comment] 2021-02-18 13:24
> @MartinZikmund does it sound familiar ?

Unfortunately not, first time I see this problem 🤔

**Comment by IsmailHassani** [comment] 2021-02-18 13:39
@MartinZikmund and @jeromelaban I can try to figure out from which version this started. Maybe we have a better starting point.

**Comment by IsmailHassani** [comment] 2021-02-18 14:52
@MartinZikmund and @jeromelaban As soon i switch from version 3.5.0-dev.498 to 3.5.1 i get this error.

**Comment by IsmailHassani** [comment] 2021-02-18 23:06
Another strange issue when applying the temporary workaround in #5267  is that the menu items in the PaneFooter don't look how they should. Maybe because the style is been ignored?

![image](https://user-images.githubusercontent.com/7172716/108433410-3eb10d80-7246-11eb-9dfd-5fd5a6a34b69.png)

**Comment by IsmailHassani** [comment] 2021-02-18 23:25
This is what it should look like (UWP head)
But the panefooter will only be shown correctly when i change muxc:NavigationViewItem to NavigationViewItem while Hot Reloading. Not directly from startup.

![image](https://user-images.githubusercontent.com/7172716/108434748-7620b980-7248-11eb-8324-1a3bc44e9583.png)

**Comment by IsmailHassani** [comment] 2021-02-27 11:10
Hi guys,
I tried the workaround from #5325 but was not happy about it because i need this styling for UWP which works fine.
So I came up with another workaround which allows conditional loading of this style.

**On the App.xaml i removed the line**
```
<XamlControlsResources xmlns="using:Microsoft.UI.Xaml.Controls"/>
```

**Inside the App.xaml.cs i adjusted the OnLaunched method from:**

```
        /// <summary>
        /// Invoked when the application is launched. Override this method to perform application initialization and to display initial content in the associated Window.
        /// </summary>
        /// <param name="args">Event data for the event.</param>
        protected override void OnLaunched(LaunchActivatedEventArgs args)
        {
#if NETFX_CORE || (NET5_0 && WINDOWS)
            switch (AnalyticsInfo.VersionInfo.DeviceFamily)
            {
                case "Windows.Desktop":
                    break;
                case "Windows.IoT":
                    break;
                case "Windows.Xbox":
                    ApplicationView.GetForCurrentView().SetDesiredBoundsMode(ApplicationViewBoundsMode.UseCoreWindow);
                    break;
            }
#endif

            ThemeSelector.SetThemeColor(_serviceProvider.GetRequiredService<IApplicationSettingsService>().Color.ToEnum(ThemeColors.Default));


            // Do not repeat app initialization when the Window already has content,
            // just ensure that the window is active
            if (!(Windows.UI.Xaml.Window.Current.Content is Frame rootFrame))
            {
                // Create a Frame to act as the navigation context and navigate to the first page
                rootFrame = new Frame();

                rootFrame.NavigationFailed += OnNavigationFailed;
                rootFrame.Navigated += OnNavigated;

                if (args.PreviousExecutionState == ApplicationExecutionState.Terminated)
                {
                    //TODO: Load state from previously suspended application
                }

                // Register a handler for BackRequested events and set the
                // visibility of the Back button
                SystemNavigationManager.GetForCurrentView().BackRequested += OnBackRequested;

                SystemNavigationManager.GetForCurrentView().AppViewBackButtonVisibility =
                    rootFrame.CanGoBack ?
                    AppViewBackButtonVisibility.Visible :
                    AppViewBackButtonVisibility.Collapsed;

                // Place the frame in the current Window
                Windows.UI.Xaml.Window.Current.Content = rootFrame;
            }

            if (!args.PrelaunchActivated)
            {
                if (rootFrame.Content is null)
                {
                    // When the navigation stack isn't restored navigate to the first page,
                    // configuring the new page by passing required information as a navigation
                    // parameter

                    var view = _serviceProvider.GetRequiredService<IShellView>();
                    rootFrame.Navigate(view.GetType(), args.Arguments);
                }

                // Ensure the current window is active
                Windows.UI.Xaml.Window.Current.Activate();
            }
        }
```

**and changed it with this:**

```
        /// <summary>
        /// Invoked when the application is launched. Override this method to perform application initialization and to display initial content in the associated Window.
        /// </summary>
        /// <param name="args">Event data for the event.</param>
        protected override void OnLaunched(LaunchActivatedEventArgs args)
        {
#if NETFX_CORE || (NET5_0 && WINDOWS)
            switch (AnalyticsInfo.VersionInfo.DeviceFamily)
            {
                case "Windows.Desktop":
                    break;
                case "Windows.IoT":
                    break;
                case "Windows.Xbox":
                    ApplicationView.GetForCurrentView().SetDesiredBoundsMode(ApplicationViewBoundsMode.UseCoreWindow);
                    break;
            }
#endif

            ThemeSelector.SetThemeColor(_serviceProvider.GetRequiredService<IApplicationSettingsService>().Color.ToEnum(ThemeColors.Default));


            // Do not repeat app initialization when the Window already has content,
            // just ensure that the window is active
            if (!(Windows.UI.Xaml.Window.Current.Content is Frame rootFrame))
            {
                // Create a Frame to act as the navigation context and navigate to the first page
                rootFrame = new Frame();

                rootFrame.NavigationFailed += OnNavigationFailed;
                rootFrame.Navigated += OnNavigated;

                if (args.PreviousExecutionState == ApplicationExecutionState.Terminated)
                {
                    //TODO: Load state from previously suspended application
                }

                // Add custom resourcedictionaries from code.
                var dictionary = this.Resources?.MergedDictionaries;
                
                if(dictionary is not null)
                {
                    foreach (var item in GetAdditionalResourceDictionaries())
                    {
                        if(!dictionary.Any(t => t.Source == item.Source))
                            this.Resources.MergedDictionaries.Add(item);
                    }
                }

                // Register a handler for BackRequested events and set the
                // visibility of the Back button
                SystemNavigationManager.GetForCurrentView().BackRequested += OnBackRequested;

                SystemNavigationManager.GetForCurrentView().AppViewBackButtonVisibility =
                    rootFrame.CanGoBack ?
                    AppViewBackButtonVisibility.Visible :
                    AppViewBackButtonVisibility.Collapsed;

                // Place the frame in the current Window
                Windows.UI.Xaml.Window.Current.Content = rootFrame;
            }

            if (!args.PrelaunchActivated)
            {
                if (rootFrame.Content is null)
                {
                    // When the navigation stack isn't restored navigate to the first page,
                    // configuring the new page by passing required information as a navigation
                    // parameter

                    var view = _serviceProvider.GetRequiredService<IShellView>();
                    rootFrame.Navigate(view.GetType(), args.Arguments);
                }

                // Ensure the current window is active
                Windows.UI.Xaml.Window.Current.Activate();
            }
        }

#if NETFX_CORE
        private IList<ResourceDictionary> GetAdditionalResourceDictionaries() =>
            new List<ResourceDictionary>()
            {
                new Microsoft.UI.Xaml.Controls.XamlControlsResources()
            };
#else
        private IList<ResourceDictionary> GetAdditionalResourceDictionaries() =>
            new List<ResourceDictionary>();
#endif
```

This extra piece of code will add the WinUI style dictionary if it's not already added. But only for UWP.
An extra benefit you get, you're now able to add additional resource dictionaries from code.
I preffered not to have to use this kind of hack, but it suits my purpose and solved my issues. 
All the heads will display your NavigationView correctly.

**Comment by IsmailHassani** [comment] 2021-02-27 11:14
Another note:
As you probably noted on the screenshots, the footer buttons are a little bit off. I don't know what has changed in this control, but on a sudden, the UI gets distorted.
I managed to fix this issue by creating an extra list of navigationitems and bound them to the **FooterMenuItemsSource** which displays them correctly.

**Comment by jeromelaban** [comment] 2021-03-01 22:14
This issue is caused by the `SplitView` style in Fluent themes being incorrect. To work around this issue, copy this style in your App.xaml resources:

https://github.com/unoplatform/uno/blob/0350e1330fcd5228cac3faddae5f427f41ddc1a4/src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml#L2021

using the `xamarin` namespace:
https://github.com/unoplatform/uno/blob/0350e1330fcd5228cac3faddae5f427f41ddc1a4/src/Uno.UI/UI/Xaml/Style/Generic/Generic.xaml#L11

Will be fixed by https://github.com/unoplatform/uno/pull/5367

**Closed** 2021-03-03 12:40 UTC
Labels: difficulty/medium, kind/bug, kind/regression, project/navigation-lifecycle
