### ISSUE TITLE
Uno Platform Solution Templates 3.7.3.3 Failed and Corrupted Visual Studio Installation

### ISSUE THREAD

**Issue by groogiam** [unoplatform/uno#5850] opened 2021-04-29 04:38 UTC
## Current behavior

Installing the extension failed and then required my visual studio installation to be repaired using the visual studio installer. 

## Expected behavior

Extension would install without failure.

## How to reproduce it (as minimally and precisely as possible)

1. Open Visual Studio
1. Extensions -> Manage Extensions
1. Goto Updates tab and update extension.
1. Close visual studio

## Workaround

Trying to install it a second time after repairing visual studio seems to have been successful. 

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [x] Other: Visual Studio 2019 Uno Platform Solution Templates VSIX

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [x] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [x] Resharper (version: ) 2021.1.2

## Anything else we need to know?

Logs from install attached.

[dd_VSIXInstaller_20210427233222_23ec.log](https://github.com/unoplatform/uno/files/6396338/dd_VSIXInstaller_20210427233222_23ec.log)
[dd_VSIXInstaller_20210427233227_4768.log](https://github.com/unoplatform/uno/files/6396339/dd_VSIXInstaller_20210427233227_4768.log)

**Comment by toddcarnes** [comment] 2021-07-03 05:08
I have tried repeatedly to install in Visual Studio 2019 v. 16.10.3, but it fails every time. The log file is attached.
[dd_VSIXInstaller_20210702215959_2f10.log](https://github.com/unoplatform/uno/files/6757862/dd_VSIXInstaller_20210702215959_2f10.log)

**Comment by jeromelaban** [comment] 2021-07-05 15:50
Thanks for the report. This error is a duplicate of https://github.com/unoplatform/uno/issues/6386, and is related to the fact that VS 2022 is installed on your machine. You can follow the other issue for more details.

**Comment by toddcarnes** [comment] 2021-07-07 02:19
I uninstalled everything, then tried again with only VS 2019 installed. Still doesn't work.

Log is attached.
[dd_VSIXInstaller_20210706191645_2f64.log](https://github.com/unoplatform/uno/files/6773837/dd_VSIXInstaller_20210706191645_2f64.log)

**Comment by toddcarnes** [comment] 2021-07-07 03:55
I figured it out. It's not enough to uninstall VS 2022. The installer is the problem. If you uninstall everything, including the installer. Then download the installer again fresh from the VS Community link. Then Uno will install for you after you've re-installed VS.

**Comment by jeromelaban** [comment] 2021-07-07 11:41
Thanks for the updated. We'll follow up with Microsoft to understand how this can work in the future.

**Closed** 2022-01-10 20:34 UTC
Labels: kind/bug, area/solution-templates, project/core-tools, difficulty/challenging
