### ISSUE TITLE
Automated approach to maintaining glyphs

### ISSUE THREAD

**Issue by ghuntley** [unoplatform/uno#967] opened 2019-05-28 14:30 UTC
## I'm submitting a...
- Feature request

## Current behavior

See https://github.com/nventive/Uno/pull/723#issuecomment-479035232

## Expected behavior

See https://github.com/nventive/Uno/pull/723#issuecomment-479035232

## Minimal reproduction of the problem with instructions

See https://github.com/nventive/Uno/pull/723#issuecomment-479035232

> We could, but I would vote for some automated approach - like maintaining a SVG file of used glyphs and completely ditch the winjs symbol font as it has different glyph positions as well as it no longer matches the new MDL2 symbols. This will take more effort though, as there are quite a lot of glyphs and each must be remade manually. So it would make sense to maintain two fonts at first - the winjs as default and new "Uno MDL2 Assets" font winch we will slowly update with new glyphs as necessary. It will also be easier as it was quite painful to replace the glyph in winjs font, whereas creating a new font from a glyph SVG file is quite simple and quick.

## Environment

Nuget Package:

Package Version(s):

Affected platform(s):
- [x] iOS
- [x] Android
- [x] WebAssembly
- [x] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )

**Comment by MartinZikmund** [comment] 2019-05-29 07:49
I think http://fontello.com/ could help us as a starting point to generate SVGs from TTF

**Comment by FrancoisM** [comment] 2019-05-29 09:38
Why generate SVG from ttf if you can use ttf?
Isn't SegMDL2.ttf sufficient? The list of available icons is [here](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font).

**Comment by MartinZikmund** [comment] 2019-05-29 09:55
I think the problem here is that MDL2 is licensed - so if we must create a custom Uno font which will be ours, but not particularly different from Segoe MDL2 as well. Or get Microsoft to give us license to use it directly :smile:

**Comment by FrancoisM** [comment] 2019-05-29 10:06
Where did you see it was licensed? I can't really find the info. And would that mean the only font is licenced or the icons are as well? If the icons are licensed you cannot use them even as svgs or in another font you'd create. 🤔

**Comment by MartinZikmund** [comment] 2019-11-04 08:51
This looks like a very nice, Windowsy new open-source icon font - https://icons8.com/articles/line-awesome-icon-font/?ref=producthunt

**Comment by kakone** [comment] 2020-04-19 13:35
> This looks like a very nice, Windowsy new open-source icon font - https://icons8.com/articles/line-awesome-icon-font/?ref=producthunt

I like the appearance of these icons. I can try to do a new font with a mix of these icons and winjs icons (with correct positions). I had made a [tool](https://github.com/kakone/SvgFont2Files/) for that. It takes an xlsx file as input (that describes the source file and unicode of each icon, and the corresponding destination unicode), and it generates a new SVG font file.
Here is a try with all SymbolIcon :
![unofont](https://user-images.githubusercontent.com/1640329/79689111-ff471880-8252-11ea-8518-6311cb418dbd.png)

**Comment by MartinZikmund** [comment] 2020-04-19 18:54
@kakone That sounds great! If you can do this, please match the icons with the Segoe MDL2 assets glyph positions (the winjs font currently in use has different positions than MDL2)

**Comment by kakone** [comment] 2020-04-24 18:04
I did [.ttf](https://github.com/kakone/SvgFont2Files/blob/master/SegoeMDL2AssetsAlternative/Uno.ttf) and [.woff2](https://github.com/kakone/SvgFont2Files/blob/master/SegoeMDL2AssetsAlternative/Uno.ttf) files by mixing _winjs_ and _Line Awesome_ icons, with the same glyph positions as Segoe MDL2. It is not ideal because a lot of icons are missing compared to Segoe MDL2 but it is much better than the _winjs_ font (the list of the icons are in this [.xlsx file](https://github.com/kakone/SvgFont2Files/blob/master/SegoeMDL2AssetsAlternative/font.xlsx)).

**Comment by robloo** [comment] 2020-08-01 00:33
Any updates on this? Honestly, Line Awesome fonts (optionally MIT licensed) seems the way to go at this point. Looking through the icons they are almost perfect. Now that this issue is assigned to @davidjohnoliver, and he's working on https://github.com/unoplatform/uno/pull/3663, I'm assuming the Uno team made the same call? At the moment I can't think of any other fundamental blockers (excluding missing controls) stopping most apps from using Uno without significant changes.

**Comment by kakone** [comment] 2020-08-01 08:22
I hoped a change about MDL2 licensing (see  this [thread](https://github.com/microsoft/fluentui/issues/12488#issuecomment-636997504) but there is nothing for the moment.
There is also a good new [fluent icon collection] (https://github.com/microsoft/fluentui-system-icons) but a lot of icons is missing compared to MDL2.
There is no ideal solution at the moment.

**Comment by davidjohnoliver** [comment] 2020-08-01 09:21
@robloo @kakone At the moment we're looking at Microsoft's recently-released[Fluent System Icons](https://github.com/microsoft/fluentui-system-icons) which are MIT-licensed as a base set. As @kakone notes they're not a 1:1 match for Segoe MDL2, but they're created for the Fluent design language, which is nice.

**Comment by robloo** [comment] 2020-08-01 14:55
@davidjohnoliver Nice! I wasn't aware of the fluent system icons. Is there a framework in place for putting all of this together? I'm thinking we need to:

1. Identify the glyphs used in control templates (checkbox, etc.) Then, using the fluent system icons as base, modify them to be pixel-perfect equivalent of the MDL2 font. We don't want to be changing margins/padding in control templates to customize them for Uno. This will make future updates to styles very quick and avoid regressions.
2. Import all Fluent System Icons and align them as best as possible with the Segoe MDL2 glyph positions. This does not have to be pixel perfect like #1 though so can be done much more quickly.
3. Import Line Awesome fonts to fill more of the gaps not covered by #2. Again, align glyph positions as best as possible but it doesn't have to be perfect.
4. Allow for designers and developers to re-create missing glyphs as needed (svg files) and have them built within the new font.

All together it seems like we will need a new toolset to automatically build an equivalent MDL2 font based on configuration files and input glyphs from multiple sources.

**Comment by robloo** [comment] 2020-08-14 15:32
Is this considered closed now?

**Comment by davidjohnoliver** [comment] 2020-08-14 15:35
> Is this considered closed now?

I don't think so, v1 of the font is available for use, but we still want to release the automated tooling to generate the font. cc @alextrepa

**Comment by MartinZikmund** [comment] 2024-05-23 01:09
All sources for our fonts are at https://github.com/unoplatform/uno.fonts , including source SVGs

**Closed by MartinZikmund** 2024-05-23 01:09 UTC
Labels: kind/enhancement, help wanted, platform/wasm 🌐, platform/android 🤖, platform/uwp 🪟, platform/ios 🍎, project/text 🔤, difficulty/medium 🤔
