### ISSUE TITLE
Find an easier way to integrate WinAppSDK workaround in Uno

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#14234] opened 2023-11-01 21:07 UTC
### What would you like to be added

https://github.com/unoplatform/uno.toolkit.ui/blob/main/src/winappsdk-workaround.targets

### Why is this needed

To avoid issues as this:

![image](https://github.com/unoplatform/uno/assets/1075116/ab5b0db5-1db4-4e76-9cc7-7ba94842cd63)

### For which platform

Windows

**Comment by jeromelaban** [comment] 2023-11-02 14:52
This is a duplicate of https://github.com/unoplatform/uno/issues/13483

**Closed by jeromelaban** 2023-11-02 14:52 UTC
Labels: kind/enhancement, difficulty/medium 🤔, area/winui
