### ISSUE TITLE
[Android] InitializeStaticLayoutInterop Failed at Android O (SDK targeted 29)

### ISSUE THREAD

**Issue by yinyue200** [unoplatform/uno#2650] opened 2020-02-14 13:29 UTC
## Current behavior

Hello world app targeted api 29 crashed

## Expected behavior

Hello world app successfully launch

## Environment

Nuget Package:

Package Version(s):
2.1.0-dev.1204
Affected platform(s):

- [ ] iOS
- [x] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: )
- [ ] for Mac (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment] 2020-02-14 19:11
Thank you for this issue, it is a duplicate of https://github.com/unoplatform/uno/issues/2016

**Closed by jeromelaban** 2020-02-14 19:11 UTC
Labels: kind/bug, triage/untriaged
