### ISSUE TITLE
[Android] TextBox KeyDown event => NullReferenceException

### ISSUE THREAD

**Issue by jp-weber** [unoplatform/uno#13522] opened 2023-09-06 08:52 UTC
### Current behavior

In my application I have a PasswordBox with a KeyDown event. In my Android app it crashes reproducibly when I press on key.

 System.NullReferenceException: 'Object reference not set to an instance of an object.'

https://github.com/unoplatform/uno/blob/da8fd161d721b67592deb770994a50b122b6ddf1/src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.Android.cs#L559

```
 	0xFFFFFFFFFFFFFFFF in Android.Runtime.JNIEnv.monodroid_debugger_unhandled_exception	C#
 	0x1A in Android.Runtime.JNINativeWrapper._unhandled_exception at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:12,5	C#
 	0x23 in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLIL_Z at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:331,26	C#
 	0xA in Microsoft.UI.Xaml.Controls.TextBox.OnEditorAction at C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\TextBox\TextBox.Android.cs:559,4	C#
 	0x1E in Android.Widget.TextView.IOnEditorActionListenerInvoker.n_OnEditorAction_Landroid_widget_TextView_ILandroid_view_KeyEvent_ at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Widget.TextView.cs:187,5	C#
 	0xD in Android.Runtime.JNINativeWrapper.Wrap_JniMarshal_PPLIL_Z at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/Android.Runtime/JNINativeWrapper.g.cs:330,5	C#
 	0x38 in Java.Interop.NativeMethods.java_interop_jnienv_call_boolean_method_a	C#
 	0x54 in Java.Interop.JniEnvironment.InstanceMethods.CallBooleanMethod at /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:11561,4	C#
 	0x3E in Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualBooleanMethod at /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:155,7	C#
 	0x29 in Android.Views.InputMethods.BaseInputConnection.PerformEditorAction at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.InputMethods.BaseInputConnection.cs:820,5	C#
 	0xD in Microsoft.UI.Xaml.Controls.TextBox.TextBoxInputConnection.PerformEditorAction at C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\TextBox\TextBox.Overrides.Android.cs:141,70	C#
 	0xB in Android.Views.InputMethods.BaseInputConnection.n_PerformEditorAction_I at /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw/Android.Views.InputMethods.BaseInputConnection.cs:808,4	C#
 	0x17 in Android.Runtime.DynamicMethodNameCounter.24	C#
```

### Expected behavior

No excepetion

### How to reproduce it (as minimally and precisely as possible)

1. TextBox with KeyDown event
2. Debug on Android emulator /phone 
3. Focus the control and press a button

### Works on UWP/WinUI

None

### NuGet package version(s)

Uno.WinUI 5.0.0-dev.2431

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.7.3

### Anything else we need to know?

In my opinion, the event still worked perfectly in 4.9 for Android.

**Comment by jeromelaban** [comment] 2023-09-06 11:54
Duplicate of https://github.com/unoplatform/uno/issues/13509

Thanks for the report!

**Closed by jeromelaban** 2023-09-06 11:54 UTC
Labels: kind/bug, project/input ⌨️, difficulty/tbd
