### ISSUE TITLE
[Gallery][Skia.GTK](MessageDialog) While clicking "Content Only", "Content and Title" and "Confirmation Prompt" button, code is throwing Exception.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5190] opened 2021-02-09 14:42 UTC
## Current behavior
![MD issue](https://user-images.githubusercontent.com/74563602/107379467-f1e96c00-6aba-11eb-85cd-e3dbda1e52b8.png)

## Expected behavior
![MD correct](https://user-images.githubusercontent.com/74563602/107379508-fca40100-6aba-11eb-873a-3ddceede531b.png)

## How to reproduce it (as minimally and precisely as possible)

1. Launch the Uno.Gallry app on Skia.GTK
2. Click on “MessageDialog” option from the  Features list.
3. Click  any button "Content Only", "Content and Title" and "Confirmation Prompt" .
4. Observe that after clicking button code is throwing Exception.

Nuget Package: Uno.UI.Skia.Gtk

Affected platform(s):
GTK (Linux)

IDE:
Visual Studio 2019 (version: )

**Comment by carldebilly** [comment] 2021-02-09 15:02
This is not implemented yet, tracked by this issue: https://github.com/unoplatform/uno/issues/4810

**Comment by MartinZikmund** [comment] 2021-06-04 16:57
Duplicate of #4810

**Closed by MartinZikmund** 2021-06-04 16:57 UTC
Labels: area/canary, difficulty/tbd, kind/regression, platform/linux, project/winrt

**Comment by sakshi173** [comment] 2021-07-06 14:25
The issue is fixed verified it, Now the code is not throwing exception
