### ISSUE TITLE
Previous page click problem

### ISSUE THREAD

**Issue by LiberRuth** [unoplatform/uno#18012] opened 2024-08-24 12:37 UTC
### Current behavior

[untitled.webm](https://github.com/user-attachments/assets/c03a56dd-4341-43c7-bd85-75e9da5f5651)

### Works on UWP/WinUI

None

### Affected platforms

Android

**Comment by morning4coffe-dev** [comment] 2024-08-25 10:16
@LiberRuth Thank you for reporting this, it is a duplicate of https://github.com/unoplatform/uno/issues/17906. Would you be able to test this on iOS by any chance?

**Comment by MartinZikmund** [comment] 2024-08-26 10:36
Closing as duplicate of #17906, I will try to test this on iOS too

**Closed by MartinZikmund** 2024-08-26 10:37 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
