### ISSUE TITLE
wasm: Cannot set ComboBox ItemTemplate from code

### ISSUE THREAD

**Issue by yowl** [unoplatform/uno#768] opened 2019-04-12 21:08 UTC
## I'm submitting a...

 - Bug report (I searched for similar issues and did not find one) 
 

## Current behavior
It is not possible to change the ItemTemplate from code

## Expected behavior
Should be possible and behave the same as UWP

## Minimal reproduction of the problem with instructions
Subclass and attempt to change the ItemTemplate with code like this in the ctor
```
            var xaml =
                @"<DataTemplate 
                xmlns=""http://schemas.microsoft.com/winfx/2006/xaml/presentation""
                xmlns:x=""http://schemas.microsoft.com/winfx/2006/xaml""    
                xmlns:local=""using:TheHub.Wasm.Controls.CheckableCombo"">
                <CheckBox local:MultiSelectComboBoxService.ComboBoxItemLoaded=""True""
                    IsChecked=""{Binding Path=(local:MultiSelectComboBoxService.IsChecked), Mode=TwoWay, RelativeSource={RelativeSource Self}}"" />
                </DataTemplate>";
            ItemTemplate = (DataTemplate)XamlReader.Load(xaml);
```
A complete example is at https://github.com/yowl/UnoMultiselectCombBox

In UWP you get the checkbox, in wasm its just empty and seems to break the binding to the ItemsSource.

## Environment

```
Nuget Package: 

Package Version(s): 
1.45.0-dev.1201

Affected platform(s):
- [ ] iOS
- [ ] Android
- [x ] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [ ] 2017 (version: )
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by yowl** [comment] 2019-04-12 23:01
Possibly the same as https://github.com/nventive/Uno/issues/183 ?

**Comment by jeromelaban** [comment] 2020-05-27 20:40
Closed as a duplicate of https://github.com/unoplatform/uno/issues/183

**Closed by jeromelaban** 2020-05-27 20:40 UTC
Labels: area/wasm, kind/bug, priority/backlog

**Comment by jeromelaban** [comment] 2020-06-01 19:54
The sample from this bug seems to be working properly as of Uno 3.0-dev, from a `DataTemplate` loading perspective.
