### ISSUE TITLE
Upload file from Webassembly 

### ISSUE THREAD

**Issue by michalss** [unoplatform/uno#4522] opened 2020-11-14 10:15 UTC
## What would you like to be added:
Is there a way to upload a file from Uno and Webassembly ? 
## Why is this needed:
well simple the fakt this is important feature to upload anything to server.

## For which Platform:

- [ ] iOS
- [X] Android
- [X] WebAssembly
- [X] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by jeromelaban** [comment] 2020-11-14 17:45
Thanks for your report! This is actually duplicate of this issue: #508. You can follow those issues for details.

**Closed by jeromelaban** 2020-11-14 17:45 UTC
Labels: kind/enhancement, triage/untriaged
