### ISSUE TITLE
Uno.UI regression: Buttons work erratically

### ISSUE THREAD

**Issue by SuperJMN** [unoplatform/uno#2035] opened 2019-11-06 15:52 UTC
## Problem
Given a simple calculator app. The calculator buttons do nothing most of times when they're clicked.

## Details
There seems to be a regression in Uno.UI, since there's a version in which things work perfectly and a newer version breaks the correct behavior.

## Repro steps

1. Clone the repo at https://github.com/SuperJMN/UnoSimpleCalc/
2. Checkout this commit to be sure the problem is there: **ab759ce435683b29ed7882d90e06e5d9544df116** (last commit as 11-06-2019)
3. Run the Web Assembly app. The buttons will work:
4. Update the Uno.UI package to any version between **2.0.512-dev.3446** and **2.0.512-dev.3728**
5. Run the Web Assembly app. The buttons will not work or will work erratically.

I did some research to isolate the regression. This is the table of results I have:

![image](https://user-images.githubusercontent.com/3109851/68313870-99584180-00b5-11ea-8800-e94a6b660dd5.png)

As you can see, the last version that worked is **2.0.324-dev.3171** and the first version that doesn't work is **2.0.512-dev.3446**. In the middle, the are some version in which the build is broken (denoated by **x**).

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by dr1rrb** [comment] 2019-11-06 16:36
Version 512 correspond to the merge of #1256 which is kind-of related to buttons clicks 😜 I'll try to have a look, but in the meantime, do you have anything in the logs?

**Comment by SuperJMN** [comment] 2019-11-06 16:49
This is the Chrome Console log I gathered. 

[localhost-1573058769818.log](https://github.com/unoplatform/uno/files/3815716/localhost-1573058769818.log)

Please, ignore the "Pressed X" entries. It's a `Console.WriteLine' we added to log when a command executes.

**Comment by dr1rrb** [comment] 2019-11-06 17:10
Actually I don't even get the "Pressed X" 😕 (even if I remove the `#if __WASM__`). 

I can see that the "pointerdown" and "pointerup" are dispatched to the managed code, and we get back the pointer capture / release sequence ... but nothing happen.

**Comment by paulovila** [comment] 2019-11-07 11:42
> Actually I don't even get the "Pressed X" 😕 (even if I remove the #if __WASM__).

You can use ```System.Diagnostics.Debug.WriteLine``` for debugging UWP

**Comment by dr1rrb** [comment] 2019-11-08 17:11
Ok so I looked a bit deeper, this is due to the `ViewBox` : coordinates of the pointer events are "scaled" accordingly, but when in `ButtonBase` we [validate if the pointer was released over the button](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Controls/Primitives/ButtonBase/ButtonBase.cs#L219), the `location.<X|Y>` might be greater than the `Actual<Width|Height>` (which are not "scaled").

**Comment by paulovila** [comment] 2019-11-13 14:13
That's a good start, the area of the button is clickable and the hovering is consistent, but the command is not being triggered

**Comment by dr1rrb** [comment] 2019-11-14 23:32
Hi @paulovila, on my side I don't have any issue with the command not being triggered, at least on WASM. If you have to opportunity to test with this fix https://github.com/unoplatform/uno/pull/2091 and let me know if it works also for you.

**Comment by paulovila** [comment] 2019-11-15 17:12
Hi @dr1rrb thanks, still no joy, I checked out dev/dr/TouchTrans and overwrote Uno.UI package , still the command doesn't get fired

**Comment by dr1rrb** [comment] 2019-11-19 21:35
> 
> 
> Hi @dr1rrb thanks, still no joy, I checked out dev/dr/TouchTrans and overwrote Uno.UI package , still the command doesn't get fired

Hi @paulovila , I just tried:
1. ```ps
   git checkout master
   git pull
   git clean -fdx
   ```
1. Open the "unoSimpleCalc.sln" in VS 2019
1. Manage nuget packages, and install latest dev version of Uno.UI [(2.0.512-dev.4021)](https://www.nuget.org/packages/Uno.UI/2.0.512-dev.4021)
1. Run "UnoSimpleCalc.Wasm", and I'm not able to reproduce the issue neither on Firefox, Edge nor Chrome

Are you able to give me more info on how you reproduce it?

**Comment by paulovila** [comment] 2019-11-19 21:56
It's working fine , I've tried in Chrome, en Edge, great job!

**Comment by dr1rrb** [comment] 2019-11-19 22:00
Great news, then I close this issue 😀

**Closed by dr1rrb** 2019-11-19 22:00 UTC
Labels: area/wasm, kind/bug, kind/regression

**Comment by SuperJMN** [comment] 2019-11-19 22:06
Great work! Thanks!
