### ISSUE TITLE
[Android][Auto Suggestion] Once keyboard is dismissed, it can't be re-opened

### ISSUE THREAD

**Issue by MaximeDion-Work** [unoplatform/uno#9004] opened 2022-06-10 12:34 UTC
### Current behavior

After giving focus to a `AutoSuggestBox` and then dismissing the keyboard, the keyboard won't re-appear when re-giving the focus to the `AutoSuggestBox` as long as the `AutoSuggestBox` popup is still present

![android_keyboard](https://user-images.githubusercontent.com/64613932/173069505-dbcbaa8b-5d2e-4cdf-bc6a-1380474a0bac.gif)

### Expected behavior

Keyboard should always appear when focus is given to `AutoSuggestBox`

### How to reproduce it (as minimally and precisely as possible)

1. Give focus to the `AutoSuggestBox`
2. Enter some text to make suggestions appear
3. Dismiss keyboard
4. Give back focus to the `AutoSuggestBox`
5. Notice keyboard doesn't come back

[AutoSuggestBoxFocusIssue.zip](https://github.com/unoplatform/uno/files/8959294/AutoSuggestBoxFocusIssue.zip)

### Workaround

None. But selecting a choice then regiving focus to `AutoSuggestBox` brings back the keyboard.

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI 4.3.0-dev.254

### Affected platforms

Android

### IDE

Visual Studio 2022

### IDE version

17.1.3

### Relevant plugins

None

### Anything else we need to know?

[DevOps Issue](https://dev.azure.com/nventive/TradeZero/_workitems/edit/257464)

**Comment by MaximeDion-Work** [comment] 2022-06-22 15:45
Don't know what was wrong but it's working now.

**Comment by MartinZikmund** [comment] 2022-07-01 02:58
@MaximeDion-Work the problem is caused by Android's native `Popup` implementation. The workaround is to disable the native popups and use managed implementation instead (which is in most cases better):

```csharp
FeatureConfiguration.Popup.UseNativePopup = false;
```

I will investigate whether it is possible to adjust the functionality for the native implementation as well.

**Comment by Marc-Antoine-Soucy** [comment] 2022-11-03 13:58
So, using this:  FeatureConfiguration.Popup.UseNativePopup = false; worked, (and I think it`s now the default, so we don`t even need to set it) but there is a small issue this created. It doesnt happen in a very simple repro app, but I noticed in a larger app that the combobox popup vertical alignment changed a bit in some combobox. 

![image](https://user-images.githubusercontent.com/90481654/199740381-93bec89d-d3c7-4415-a5c8-dbf60a33ec38.png)

**Comment by takla21** [comment] 2022-11-04 15:14
I've created this issue #10339 related to what @Marc-Antoine-Soucy has reported above. Since the original bug has been fixed, I'm closing this

**Closed by takla21** 2022-11-04 15:14 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd, area/autosuggestbox
