### ISSUE TITLE
[iOS] [Android] IsEnabled inheritance for visual states

### ISSUE THREAD

**Issue by carldebilly** [unoplatform/uno#1800] opened 2019-10-10 19:58 UTC
# Bug Report

## Current behavior
Setting `IsEnabled` to `false` on a parent control (ex: `<ContentControl>`) will effectively disable children controls, but they won't have the _disabled_ look (visual state).

## How to reproduce it (as minimally and precisely as possible)

``` xml
<ContentControl IsEnabled="False">
  <TextBox Text="Should be disabled and get a disabled look on all platforms." />
</ContentControl>
```
## More information
This problem was also present on Wasm, but has been fixed in PR #1799.

**Comment by Youssef1313** [comment] 2021-08-18 17:27
I can't reproduce this. Probably it was fixed? @carldebilly @MartinZikmund Can you confirm and close, or if it's still reproducible please provide more information.

**Comment by MartinZikmund** [comment] 2021-08-18 17:41
@Youssef1313 have you tested Android? I can check iOS later

**Comment by Youssef1313** [comment] 2021-08-18 18:05
Yeah I tested Android and seems to work. My best guess is that it was fixed in https://github.com/unoplatform/uno/commit/1b5b8c6a225aa5f5ab315ae00f1a0683a151c454

Specifically this line: https://github.com/unoplatform/uno/blame/26cdaeb7cf49d06d792f5cd3dbab3d9120295585/src/Uno.UI/UI/Xaml/FrameworkElement.cs#L654

**Comment by Youssef1313** [comment] 2021-08-18 20:09
btw, it got a wrong appearance on Wasm:

![image](https://user-images.githubusercontent.com/31348972/129965110-3226f984-8ab8-4214-a23b-22af4feaa9fd.png)


Here is what it looks in UWP:
![image](https://user-images.githubusercontent.com/31348972/129965196-801e03c0-1b04-42bf-89c0-596354e096c8.png)

**Comment by Youssef1313** [comment] 2021-10-04 09:05
@carldebilly It looks like everything here was fixed. I think this can be closed.

**Closed** 2021-10-04 12:48 UTC
Labels: kind/bug, platform/android, platform/ios, project/layout, difficulty/medium, area/eu
