### ISSUE TITLE
Accessing web API within WASM

### ISSUE THREAD

**Issue by ZeProgFactory** [unoplatform/uno#3250] opened 2020-05-26 19:48 UTC
We made several tests in order to access web API. We found no problems when in UWP context but when we are in WASM context we only could retrieve correctly short message (Date, time, number, ... ). As soon as the answer is a bit longer, we won’t get it on WASM. 
We are using the following code snippet:

```
#if __WASM__
            var innerHandler = new Uno.UI.Wasm.WasmHttpHandler();
#else
            var innerHandler = new HttpClientHandler();
#endif

   _httpClient = new HttpClient(innerHandler);
   var txt = await _httpClient.GetStringAsync(new Uri( "http://..."));
```
Any suggestions? We didn’t fin a running sample. So it would be nice to add one to the playground.

## For which Platform:

- [ ] iOS
- [ ] Android
- [X ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Windows

**Comment by jeromelaban** [comment] 2020-05-26 20:35
Thanks for the report! Do you see any error message in the browser debug console ?

**Comment by ZeProgFactory** [comment] 2020-05-26 21:43
Thanks, Jerome, for pointing me in the right direction …

In fact, the transmission was fine in every case, but as we try to display the result with an MessageDialog the underlaying JavaScript interprets the text. So short texts or numbers worked fine, but JSON and some character sequences broke the MessageDialog …
  
So for everybody our working “test display”:

    textBlock.Text = txt;
    var dlg = new MessageDialog(txt.Length.ToString());
    await dlg.ShowAsync();

A textblock has no problem digestion JSON, text , or other text snippets ...

Logs before the correction:
[now - OK -localhost-1590528021608.log](https://github.com/unoplatform/uno/files/4685136/now.-.OK.-localhost-1590528021608.log)
[TestDB - KO - localhost-1590527897147.log](https://github.com/unoplatform/uno/files/4685138/TestDB.-.KO.-.localhost-1590527897147.log)
[data - KO - localhost-1590528054187.log](https://github.com/unoplatform/uno/files/4685139/data.-.KO.-.localhost-1590528054187.log)
[I18n - KO - localhost-1590527988804.log](https://github.com/unoplatform/uno/files/4685140/I18n.-.KO.-.localhost-1590527988804.log)

**Comment by jeromelaban** [comment] 2020-05-27 00:40
Right! This is a case of invalid escaping inside of Uno in `MessageDialog`:
https://github.com/unoplatform/uno/blob/aaa4238952fca2a23e5b3f95ea22c5d933133e0e/src/Uno.UWP/UI/Popups/MessageDialog.wasm.cs#L19

The content should be escaped using `WebAssemblyRuntime.EscapeJs` :
https://github.com/unoplatform/uno/blob/6aa544c0e00a227cf68121786b9e56c0f46e47aa/src/Uno.Foundation/Runtime.wasm.cs#L381

**Comment by carldebilly** [comment] 2020-05-28 20:56
@jeromelaban Maybe a duplicate of #2501?

**Comment by ZeProgFactory** [comment] 2020-05-28 22:23
Regarding our basic problem: a UNO / WASM  / WS sample we made one: https://github.com/ZeProgFactory/UNO.Sample.Webservice 
Don't hesitate to ask for or add missing features, or give any feedback ...

**Comment by ZeProgFactory** [comment] 2020-05-28 22:23
> @jeromelaban Maybe a duplicate of #2501?

@carldebilly you are right, but the issue and how to work around / correct it are better documented in this exchange. Other wise you should add @jeromelaban comments to the other issue.

**Comment by jeromelaban** [comment] 2020-05-29 13:11
Indeed, let's close this issue and get the other one fixed instead.

**Closed by jeromelaban** 2020-05-29 13:11 UTC
Labels: good first issue, kind/bug, priority/backlog
