### ISSUE TITLE
Feedback on Single Location structure

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno#10685] opened 2022-12-08 07:51 UTC
### Current behavior

Using Uno.ProjectTemplates.Dotnet version 4.7.0-dev.566 from dev nuget feed
Ran "dotnet new unoapp -o SimpleApp" to create app

First run this blocked on restoring the Mobile app - I'm assuming this was just a delay due to packages needing to be downloaded the first time. For subsequent apps, the restore phase worked successfully.

Opening solution in VS there is a prompt indicating that one or more projects needs to be reloaded - it would be good to work out why this is being displayed (I've repeated this process a couple of times and I always get the reload prompt)
![image](https://user-images.githubusercontent.com/1614057/206386443-ab6a46cc-cb3e-4f41-94eb-0f86c0fb3166.png)

Projects all build successfully except server project that seems to have an un-processed conditional statement in Program.cs. ![image](https://user-images.githubusercontent.com/1614057/206386221-44ae4536-6981-4ca5-a7ad-5cb2cc4fe901.png)
Removing the <!--#if and #endif (but retaining the contents) doesn't fix build as the UseUnoFrameworkFiles method can't be resolved - The project and bootstramp package references were missing from server csproj (added in this image to get build to work)
![image](https://user-images.githubusercontent.com/1614057/206388197-da1848dd-d335-4be7-ac9f-db71f3e7e65a.png)

Windows target builds and runs fine but the launchSettings.json seems to belong to a wasm project
![image](https://user-images.githubusercontent.com/1614057/206388764-b0956e3d-9c71-4bb0-a3fe-823b0221a575.png)

Wasm target doesn't run when selected as startup project but if server project is selected it runs ok
![image](https://user-images.githubusercontent.com/1614057/206388893-c8eb3fee-5ecb-4d0c-904f-c4afa705a619.png)

WPF/GTk/Android/iOS all work fine

### Works on UWP/WinUI

None

**Comment by jeromelaban** [comment] 2022-12-08 13:22
Thanks @nickrandolph,

> Opening solution in VS there is a prompt indicating that one or more projects needs to be reloaded - it would be good to work out why this is being displayed (I've repeated this process a couple of times and I always get the reload prompt)

We cannot change this behavior, this is caused by the sdk-style project structure which changes the project definition once nuget packages are restored. The only way to fix this would be to use an actual SDK, which is not something that is to be considered at this point (it would require creating workloads).

> Windows target builds and runs fine but the launchSettings.json seems to belong to a wasm project

This is a visual studio issue, related to the use of single location content, where the "Properties" folder is not detected properly until nuget packages are restored. We may be able to work around it by adding yet another property in the wasm csproj, but otherwise, closing and reloading the solution does help.

> Wasm target doesn't run when selected as startup project but if server project is selected it runs ok

This is fixed in an updated (not yet released) version of the bootstrapper.

**Closed** 2022-12-20 00:49 UTC
Labels: kind/bug, area/solution-templates, project/core-tools, difficulty/tbd
