### ISSUE TITLE
[skia][macOS] Button height inconsistency in a page and ContentDialog

### ISSUE THREAD

**Issue by ArchieCoder** [unoplatform/uno#16930] opened 2024-05-29 19:43 UTC
### Current behavior

1- A button in a page does not have the same height as in a WinAppSDK

Mac:
<img width="286" alt="Screenshot 2024-05-29 at 3 24 00 PM" src="https://github.com/unoplatform/uno/assets/1608424/7042aa1d-4585-4967-ad32-894c72cf6107">

Windows:
<img width="214" alt="Windows" src="https://github.com/unoplatform/uno/assets/1608424/599be59e-5785-40c1-baba-c56e393a085a">

2- A button in a ContentDialog has a much smaller height

<img width="487" alt="Screenshot 2024-05-29 at 3 24 17 PM" src="https://github.com/unoplatform/uno/assets/1608424/729114ef-ac4e-4546-aa8d-f80ad7214b46">

### Expected behavior

Buttons should follow the same height as WinAppSDK

### How to reproduce it (as minimally and precisely as possible)

I created this sample app with the wizard without using the material design.

[UnoApp1.zip](https://github.com/unoplatform/uno/files/15490106/UnoApp1.zip)

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### Affected platforms

Skia (macOS)

### IDE

Visual Studio 2022

### IDE version

Latest VS

**Comment by ramezgerges** [comment] 2024-06-03 17:35
From your screenshots (and my testing), it doesn's seem that the button height is the problem (maybe a single pixel off?), but the problem is with text alignment and fonts, simialar to https://github.com/unoplatform/uno/issues/16931#issuecomment-2145767549. See also the discussion for TextBox text alignment in https://github.com/unoplatform/uno/issues/16568

**Comment by agneszitte** [comment] 2024-07-12 21:50
@jeromelaban, @ramezgerges what is the status of this issue now that https://github.com/unoplatform/uno/pull/15958 is merged?

**Comment by Youssef1313** [comment] 2024-07-12 21:55
@agneszitte This one is potentially fixed

**Comment by agneszitte** [comment] 2024-07-15 21:53
@Darsh0307 I recreated the sample repro @ArchieCoder initially shared for this issue while using latest template and latest stable (upcoming) 5.3 version so you can test it on all platforms. Thanks in advance.
[Isssue16930-RecommendedTestApp.zip](https://github.com/user-attachments/files/16240625/RecommendedTestApp.zip)

**Comment by Darsh0307** [comment] 2024-07-16 13:39
Hey @agneszitte  , I believe so that this issue seems to be solved in 5.3.28. I used the zip file which you have shared in the previous comment. 

![Screenshot 2024-07-16 at 9 37 28 AM](https://github.com/user-attachments/assets/dca3cf9f-8a8e-4258-a9fb-f313d9d4d9b1)

![Screenshot 2024-07-15 at 7 41 07 PM](https://github.com/user-attachments/assets/c4265acb-db13-4ad9-a8fc-205d180bb432)

**Comment by agneszitte** [comment] 2024-07-16 14:29
Closing this issue as normally fixed with latest changes. @ArchieCoder you will be able to have the fixes with the upcoming 5.3 release. Let us know if you have additional feedback after that. Thanks in advance.

**Closed by agneszitte** 2024-07-16 14:29 UTC
Labels: kind/bug, triage/potentially-fixed
