### ISSUE TITLE
Cannot see MediaPlayerElement or MediaPlayer in Mobile head

### ISSUE THREAD

**Issue by lukasf** [unoplatform/uno#11387] opened 2023-02-20 10:45 UTC
### Current behavior

After adding MediaPlayerElement for some basic media playback, the mobile head does not compile anymore.

Neither MediaPlayerElement nor MediaPlayer class are found:

error UXAML0001: The type {http://schemas.microsoft.com/winfx/2006/xaml/presentation}MediaPlayerElement could not be found
error CS0118: 'MediaPlayer' is a namespace but is used like a type

If I disable the Windows head, I also do not see MediaPlayer or MediaPlayerElement in Intellisense (C# or XAML).

I am surprised because both should be (basically) supported, according to docs. Am I missing something?

### Expected behavior

I can add MediaPlayerElement in XAML and successfully compile for Android and iOS. I can use the MediaPlayer property and the MediaPlayer class is available in Intellisense.

### How to reproduce it (as minimally and precisely as possible)

Create a new project using default Uno template. Add `<MediaPlayerElement x:Name="mpe" />` in MainPage.xaml. See how Mobile build fails. Disabling MacCatalyst does not help.

### Works on UWP/WinUI

Yes

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### Affected platforms

Android, iOS

### IDE

Visual Studio 2022

**Comment by Youssef1313** [comment] 2023-02-20 10:58
@lukasf I'm not able to reproduce these errors. Can you please attach a repro?

**Comment by lukasf** [comment] 2023-02-20 11:03
Sample: [TestApp1.zip](https://github.com/unoplatform/uno/files/10783652/TestApp1.zip)

Update on MediaPlayer: I can use the MediaPlayer class in code now. I found out that its name collides with a namespace "MediaPlayer" from the Microsoft.MacCatalyst dependency, which comes with the Mobile head. It is strange that they use such a name as root namespace. I had to declare an alias like this:

`using MPlayer = Windows.Media.Playback.MediaPlayer;`

I still cannot compile with MediaPlayerElement in XAML.

**Comment by Youssef1313** [comment] 2023-02-20 11:58
Thanks for the repro @lukasf

This was fixed in 4.8 by https://github.com/unoplatform/uno/pull/11071

@jeromelaban Do we want to backport this PR to 4.7?

**Comment by jeromelaban** [comment] 2023-02-20 12:58
@lukasf It was indeed fixed in Uno 4.8-dev builds. You can use one of the prerelease packages from nuget, or wait for the next version of Uno.

**Closed** 2023-02-20 13:07 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd

**Comment by lukasf** [comment] 2023-02-20 15:45
Thank you. Indeed it works with latest 4.8 prerelease!
