### ISSUE TITLE
TimePicker binding not working on Android and iOS

### ISSUE THREAD

**Issue by CBrunet2212** [unoplatform/uno#10738] opened 2022-12-15 14:55 UTC
### Current behavior

on iOS: When creating a TimePicker and binding it's Time property to a TimeSpan in the viewModel with a two-way binding, the initial value of the TimePicker will be correct but changing the time in the picker will not change the value of the TimeSpan in the viewmodel as it should with a two-way binding.

on Android: we have the same problem but the initial value of the TimePicker is not correct (it uses the local time)

### Expected behavior

Interacting with the TimePicker with a two-way binding would allow us to change the TimeSpan it is bound to in the ViewModel

### How to reproduce it (as minimally and precisely as possible)

[UnoApplicationTemplate-main.zip](https://github.com/unoplatform/uno/files/10238066/UnoApplicationTemplate-main.zip)

### Workaround

A workaround I found was to create a behaviour with 2 properties, one on which I bind a reference to the Time Property of the control and a trigger so that whenever this property changes, it changes the second property of the behavior, which is bound to the TimeSpan in the viewModel, updating it whenever the control changes.

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

Uno.UI 3.11.16 (On our app)
Uno.Ui 4.4.20 (On the sample)

### Affected platforms

Android, iOS

### IDE

Visual Studio 2022

**Comment by ajpinedam** [comment] 2022-12-15 19:47
Android: This seems to be fixed on the latest Uno 4.7.0-dev.623 and the latest stable version 4.6.19. 

Unable to reproduce with either of these two versions.

https://user-images.githubusercontent.com/1900897/207950541-3411afd6-5cff-4d52-8a47-e79b82ebb201.mp4

Note: I was able to reproduce it with Uno 4.4.20

**Comment by ajpinedam** [comment] 2022-12-15 22:20
Confirmed this is also working for iOS when using the latest Uno 4.7.0-dev.623

![2022-12-15_05-16-00-PM](https://user-images.githubusercontent.com/1900897/207979549-b3e88173-2de9-4b11-8786-96c2ffac59b7.png)

**Comment by CBrunet2212** [comment] 2022-12-19 16:34
@ajpinedam 

Oh ok, sorry for not validating on the latest version that would be my bad.

So I have been asked to inquire on the possibility of backporting this to Uno.UI 3.11.16 as this is the version we are currently running on our project that considers this issue a blocker and I was also asked to inquire about an ETA for said port?

**Comment by jeromelaban** [comment] 2022-12-19 16:42
@CBrunet2212 You can create a backport request in the nventive repository, we'll see if it can be backported. You'll also need to ensure that you move to Uno 4.x to avoid future disruptions.

**Closed** 2022-12-20 18:27 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd, area/date-time-pickers
