### ISSUE TITLE
[macOS] native `DatePicker` should be implemented and be default

### ISSUE THREAD

**Issue by KSemenenko** [unoplatform/uno#5995] opened 2021-05-13 07:46 UTC
## Current behavior
Just add ``` <DatePicker />```
<img width="354" alt="Screenshot 2021-05-13 at 10 41 04" src="https://user-images.githubusercontent.com/4385716/118094789-de121680-b3d7-11eb-975e-6fe0f76bd733.png">

## Expected behavior
The picker should look normal, without strange objects.

## How to reproduce it (as minimally and precisely as possible)

Just create new project, add ``` <DatePicker />``` and run it on macOS.

## Environment
macOS 11.3.1
VS for MAC 

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [x] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version:8.9.9 )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment] 2021-05-13 12:07
Thanks for the report.

@carldebilly I think this is a duplicate of another one, right ?

**Comment by carldebilly** [comment] 2021-05-31 19:28
Yep it's a duplicate of #5345 and mentioned in #5482.

On iOS, the default mode is to use the native picker instead of this one. But for macOS, a change is required [on this line](https://github.com/unoplatform/uno/blob/7ffe996dcdcbaf937fb59fd2b1620c9d3379ae8f/src/Uno.UI/UI/Xaml/Controls/DatePicker/DatePicker.Flyout.cs#L59) to add support for `__MACOS__` native picker from the DatePicker.

**Comment by ajpinedam** [comment] 2022-01-13 05:07
Issue still present. Tested with Uno.UI 4.1.0-dev.305

**Comment by MartinZikmund** [comment] 2024-05-23 04:00
This is no longer relevant as we have a new macOS backend 🚀

**Closed by MartinZikmund** 2024-05-23 04:00 UTC
Labels: kind/bug, platform/macos 🍏, difficulty/medium 🤔, area/date-time-pickers
