### ISSUE TITLE
Uno.WinUI Transitive Asset handling differences between Windows and Skia.GTK 

### ISSUE THREAD

**Issue by brinko99** [unoplatform/uno#8639] opened 2022-04-27 22:41 UTC
### Current behavior

I have a Skia app that depends on a second Uno/Skia library that contains image references. I find that the Windows and Skia.GTK heads behave differently regarding transitive asset handling.

Transitive project resources are not copied to the Skia app's output folder in the same manner as with Windows.Desktop output folder.

Specifically, the Windows head copies transitive assets to `bin\<project name>\Assets\`. The Skia.GTK head combines all assets under a single `bin\Assets\` folder.

As it is, I cannot consistently reference assets with `ms-appx:///` from code.

Thanks as always.

### Expected behavior

Consistent behavior between the different heads is expected.

### How to reproduce it (as minimally and precisely as possible)

See attached
[UnoWinUI3 (transitive resources).zip](https://github.com/unoplatform/uno/files/8578205/UnoWinUI3.transitive.resources.zip)

### Environment

Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia

### NuGet package version(s)

4.1.8, 4.2.6

### Affected platforms

Skia (GTK on Linux/macOS/Windows), Windows

### IDE

Visual Studio 2022

**Comment by jeromelaban** [comment] 2022-04-27 23:45
Thanks for the report! This issue is a duplicate of https://github.com/unoplatform/uno/issues/2502, I've posted a workaround, let us know if this helps by answering in the other issue.

**Closed by jeromelaban** 2022-04-27 23:45 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
