### ISSUE TITLE
(When the Uno UI builds a WPF application, it causes the generated application to fail to display Chinese)Uno UI在生成WPF应用时，会导致生成的应用无法显示中文

### ISSUE THREAD

**Issue by geenh** [unoplatform/uno#11050] opened 2023-01-25 14:19 UTC
### Current behavior

![image](https://user-images.githubusercontent.com/100355054/214586594-8509c206-51ef-4a53-b15c-aeb3a05ba1a6.png)
在我生成WPF应用时，显示中文会出现乱码问题

### Expected behavior

这个MessageDialog会显示“确定”和“取消”两个按钮，而按钮位置显示的是乱码

### How to reproduce it (as minimally and precisely as possible)

var messageDialog = new MessageDialog("Hello World!", "确定")
            {
                Commands =
        {
            new UICommand("取消"),
            new UICommand("确定"),
        }
            };
            await messageDialog.ShowAsync();

### Works on UWP/WinUI

None

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

最新

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.4.4

**Comment by geenh** [comment] 2023-01-25 14:25
English：（Microsoft Translate）
Current behavior
![image](https://user-images.githubusercontent.com/100355054/214588417-1f5b5692-4caa-4dfd-917f-1a91cffa6caf.png)
When I build a WPF app, the display Chinese gets garbled characters

Expected behavior
This MessageDialog will display the "确定" and “取消" buttons, and the button position shows garbled characters

How to reproduce it (as minimally and precisely as possible)
var messageDialog = new MessageDialog("Hello World!", "确定")
{
Commands =
{
new UICommand("取消"),
new UICommand("确定"),
}
};
await messageDialog.ShowAsync();

Workaround
No response

Works on UWP/WinUI
None

Environment
Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

NuGet package version(s)
Latest

Affected platforms
Skia (WPF)

IDE
Visual Studio 2022

IDE version
17.4.4

Relevant plugins
No response

Anything else we need to know?
No response

**Comment by jeromelaban** [comment] 2023-01-25 15:33
Thanks for the report. This is a duplicate of https://github.com/unoplatform/uno/issues/10801, please see for a workaround.

**Closed by jeromelaban** 2023-01-25 15:33 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
