### ISSUE TITLE
Application should default to a theme-based background

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#6472] opened 2021-07-14 10:33 UTC
## Current behavior

When the `Page` has no background, the application's background is white on WASM.

## Expected behavior

Default background should match the system theme/app requested theme as on Windows.

Not sure on which level the actual background color is applied - whether on some of the internal elements, or on the `Frame`. I suspect it may come from the `ContentRoot` color. Further investigation will be needed.

## How to reproduce it (as minimally and precisely as possible)

Create a blank Uno app and remove `Background` from the `Page` and its root `Grid`. Launch the application on Windows and notice its background is black or white, depending on system theme/application requested theme. Compare to WASM, where it always is white.

## Workaround

Always make sure to set a background to a top level element.

## Works on UWP/WinUI

Yes

## Environment

Nuget Package:

- [ ] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

All

**Comment by davidjohnoliver** [comment] 2021-07-14 15:17
Duplicate of https://github.com/unoplatform/uno/issues/6393

And the same issue is present on Android and iOS, as discussed here: https://github.com/unoplatform/uno/issues/2522

**Closed** 2021-07-14 17:22 UTC
Labels: difficulty/medium, kind/bug, triage/untriaged
