### ISSUE TITLE
[Gallery][WASM/Skia.Gtk]TabBar- Close(X) Icon is missing for 'Bottom TopBar Sample Page' in Light theme 

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8226] opened 2022-03-03 18:00 UTC
### Current behavior
TabBar(Cupertino) for **WASM**
![Close icon missing](https://user-images.githubusercontent.com/74563602/156787463-a9c10e6e-3be0-45d1-9043-9e1e1ada13da.png)

### Expected behavior
The close Icon 'X' should visible in day mode.

TabBar(Cupertino) for **iOS**
![close Icon correct](https://user-images.githubusercontent.com/74563602/156628169-68bee2bd-6443-4df6-8bac-bb1dbdfb7aa6.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP .
2. Click/tap Burger Menu on the left top right.
3. Ensure that the Gallery app is in Day Mode.
4. Tap "TabBar" from the "Toolkit" list.
5. Go to Cupertino section.
6. Click on 'Show Bottom TabBar Sample' Button.
7. Observe that Close(X) Icon is not visible for 'Bottom TopBar Sample Page'.

### Affected platforms

WebAssembly

**Comment by sakshi173** [comment] 2023-04-03 02:13
@kazo0,I am still able to reproduce this bug, Please look into it.

**Comment by nguyeenvy** [comment] 2023-05-23 15:45
@sakshi173 @kazo0 I also cannot reproduce this issue on the https://gallery.platform.uno/ app.

This is what I see down below:



![Image](https://github.com/unoplatform/uno/assets/54756963/f8fa3e9e-b9eb-422f-a833-5d311a8cbeb8)

**Comment by nguyeenvy** [comment] 2023-05-23 16:22
@kazo0 Hello Steve, I just tested out the Canary build of the Gallery and it doesn't contain the mentioned issue. I think it can be closed as fixed.

**Comment by kazo0** [comment] 2023-05-23 16:23
Awesome!

I'll let @sakshi173 double check as confirmation and close it :)

**Comment by sakshi173** [comment] 2023-05-23 16:30
Hi @kazo0, @nguyeenvy, It is happening for both 'Material' and 'Cupertino',  Just now I retested the canary build and still the close button is not displaying. below is the video

https://github.com/unoplatform/uno/assets/74563602/01122c37-04de-4481-89fe-3048aacdbff1

**Comment by nguyeenvy** [comment] 2023-05-23 16:33
@sakshi173 Oh yeah I see, in Day mode it doesn't show. Okay thank you, I will check this out.

**Comment by nguyeenvy** [comment] 2023-05-23 18:27
@kazo0 @sakshi173 Hello, after investigating the difference between Uno Gallery's repo and Uno Toolkit UI's, I noticed that the main difference is that the X icon (in PNG format) is different in both projects. In Uno Gallery, the icon is white whereas in Uno Toolkit, it is black.

In both projects, the color doesn't change when we toggle between the Day and Night mode. The styles of those png icons do not change.

What type of fix would be appropriate for this? Should we make the X icon black in Uno Gallery like in Uno Toolkit UI or should we have 2 different png icons per repository (CloseIconDark and CloseIconLight) and make the app switch between those two whenever the Day/Night mode is toggled?

**Closed** 2023-06-01 15:21 UTC
Labels: kind/bug, platform/wasm, triage/untriaged, area/canary, difficulty/tbd
