### ISSUE TITLE
Adding Documentation on Hosting a WASM Project in ASP.NET Core 

### ISSUE THREAD

**Issue by mkwhalen** [unoplatform/uno#3659] opened 2020-07-29 13:51 UTC
## What would you like clarification on:

This doc should outline the steps needed to take an existing Uno.Wasm project for Visual Studio, Visual Studio for Mac, and .NET Core CLI.
## Concern?

- [x] Usage in industry
- [ ] Clarification of capabilities
- [ ] Getting started with Uno
- [ ] Developing with Uno
- [ ] Contributing to the Uno project
- [x] Publishing your application
- [ ] Support
- [ ] Other (please specify):

## For which Platform:

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] macOS
- [ ] Windows

**Comment by MartinZikmund** [comment] 2021-06-02 15:51
Duplicate of #4118

**Closed by MartinZikmund** 2021-06-02 15:51 UTC
Labels: difficulty/medium, project/documentation
