### ISSUE TITLE
Xamarin with Prism fails in Uno Platform

### ISSUE THREAD

**Issue by urodolf** [unoplatform/uno#2421] opened 2020-01-03 12:30 UTC
An application for Xamarin has been created using Prism to perform dynamic loading of modules and navigation between pages.
A project for Android, Ios, UWP and WPF is generated and the correct operation of the application is tested.
When a project is generated in Web Assembly using Uno Platform, the logo of Uno appears later the Xamarin logo apears in the browser, but when the application is loaded it goes blank.

Traces have been introduced in the program to see what their behavior is and it has been detected that it stops when navigating to the first page.
Prism-specific nugets have been created to use the same version of Xamarin as the rest of the application and to include the traces, but these traces never apear.

Package Version(s):
- Xamarin:
  - Xamarin.Forms Version 4.3.0.991250.
  - Xamarin Essentials Version 1.3.1
- Platform Target Frameworks: 
  - Uno Platform:
    - Uno.WasmBootstrap version 1.0.10
    - Uno.Wasm.Bootstrap.Cli version 1.0.0-dev.302
    - Uno.Xamarin.Forms.Platform version 4.3.0-uno.141
    - Uno.UI versin 2.1.0-dev.192
    - Microsoft.Extensions.Logging.Filter version 1.1.2
    - Microsoft.Extensions.Logging.Console version 1.1.1
- UWP Platform:
  - Microsoft.NetCore.UniversalWindowsPlatform version 6.2.9
  - TargetPlatformVersion = TargetPlatformMinVersion = 10.0.16299.0

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [x] WebAssembly renderers for Xamarin.Forms
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

Visual Studio:

- [ ] 2017 (version: )
- [x] 2019 (version: 16.4.2)
- [ ] for Mac (version: )

**Comment by jeromelaban** [comment] 2020-01-03 12:42
Thanks for the report! 

If there are no visible exceptions after the navigation occurs, this means there's something else that's blocking/crashing silently.

Could you try creating a sample that reproduces the issue ?

**Comment by Suriman** [comment] 2020-01-03 15:05
Hi, I'm a colleague of @urodolf. The sample that reproduces the issue is here. Thanks!
[Main1.zip](https://github.com/unoplatform/uno/files/4019554/Main1.zip)

**Comment by weitzhandler** [comment] 2020-01-07 00:48
BTW @urodolf 
check this: https://github.com/PrismLibrary/Prism/issues/1835
Prism doesn't offer official support for UWP.
I faced this issue and then switched to RxUI, which work with Rx.NET, a super powerful library on its own right, so I suggest you to consider looking at it. BTW, [here](https://github.com/weitzhandler/UnoRx)'s an RxUI template for Uno.

**Comment by Suriman** [comment] 2020-01-25 11:20
@jeromelaban 
Any news on when you will be able to address the solution to this problem? Any estimated date?

**Comment by jeromelaban** [comment] 2020-01-26 02:15
I took a look at your solution, and there are a few things to adjust.

First, make sure to read the result of a `NavigationService.NavigateAsync` call. The navigation exception will tell you want the issue may be.

In this case, the exception was a missing constructor in one of your solution assemblies, which generally need to all be added to the linker exclusion file. The best way to determine if an issue is related to the linker is to [disable the linker completely](https://github.com/unoplatform/Uno.Wasm.Bootstrap#linker-configuration-1). If the app works, enable the linker again and add assemblies to the `LinkerConfig.xml` files until the app works.

There's one thing that needs to be modified in the Uno WebAssembly renderers, as you should not need to add `Xamarin.Forms.Xaml` for the app to work.

Here's the content of the file I'm using:
```xml
<linker>
	<assembly fullname="Form1"/>
	<assembly fullname="Form2"/>
	<assembly fullname="Main"/>
	<assembly fullname="Main.Wasm"/>
	<assembly fullname="MainForm"/>
	<assembly fullname="DryIoc"/>
	<assembly fullname="Experimental"/>
	<assembly fullname="MainNavigation"/>
	<assembly fullname="MyControl"/>

	<assembly fullname="Xamarin.Forms.Core" />
	<assembly fullname="Xamarin.Forms.Platform.Uno" />
	<assembly fullname="Prism" />
	<assembly fullname="Prism.Forms" />
	<assembly fullname="Prism.DryIoc.Forms" />
	<!--<assembly fullname="DryIoc.Microsoft.DependencyInjection" />-->
	<assembly fullname="DryIoc" />

	<assembly fullname="Xamarin.Forms.Xaml"/>

	<assembly fullname="System.Core">
		<!-- This is required by Json.NET and any expression.Compile caller -->
		<type fullname="System.Linq.Expressions*" />
	</assembly>
</linker>
```

Note that disabling the linker completely is not a viable option as it makes the AOT process very long or impossible at this point.

**Comment by urodolf** [comment] 2020-01-30 18:01
@jeromelaban
Thanks for all.
We continue working with the sample and now we move some forms to another location and use they by nuget. This nugets use other nugets from third party. Our problem is that we do not know what we should reference in the LinkerConfig file for the UnoPlatform project to work, can you tell us how to know what we should reference in the LinkerConfig file?

**Comment by jeromelaban** [comment] 2020-01-30 19:05
@urodolf you pretty much need to look at the assemblies that are present in the `dist` folder, there's no other way to determine that at this point.

**Comment by urodolf** [comment] 2020-01-31 09:29
@jeromelaban we reference all files with extension clr in the LinkerConfig but when execute the application we have this error attached.
![Uno_error](https://user-images.githubusercontent.com/50919329/73528088-73bca900-4414-11ea-9222-652dc7b02bfe.PNG)
Thanks for your help.

**Comment by jeromelaban** [comment] 2020-01-31 15:17
@urodolf this looks like a mono issue. We're in the process of updating mono so that this of issue may get resolved. You can follow https://github.com/unoplatform/uno/pull/1497 for more details.

**Comment by urodolf** [comment] 2020-02-03 09:52
Thank you, we will wait for the resolution of the PR to continue with the tests.

**Comment by weitzhandler** [comment] 2020-04-08 05:17
There is some exciting news:
https://github.com/PrismLibrary/Prism/pull/2054

**Comment by Suriman** [comment] 2020-07-25 09:56
@jeromelaban Any news about this?

**Comment by jeromelaban** [comment] 2020-07-25 16:44
@Suriman You can use the [prism dotnet new templates](https://github.com/unoplatform/uno/blob/master/doc/articles/get-started-dotnet-new.md#uno-platform-blank-prism-application).

**Comment by francoistanguay** [comment] 2021-06-01 01:54
Should be fixed in latest Prism and Uno versions.

**Closed by francoistanguay** 2021-06-01 01:54 UTC
Labels: area/xf-wasm-renderers, difficulty/tbd, kind/bug, project/third-party
