### ISSUE TITLE
Build fails after Changing the Application Display Version 

### ISSUE THREAD

**Issue by trydalch** [unoplatform/uno#17873] opened 2024-08-08 00:37 UTC
### Current behavior

I update the MAUI Application Display Version from 1.0.0 to 1.0.1 and suddenly the build completely breaks. 

I've gotten a variation of errors. Sometimes it says that there's a version mismatch where some targets have 1.0.0 and others 1.0.1 (even though I have the property set to be the same for all targets) and other times it gives this error:

```
NETSDK1005	Assets file 'C:\...\project.assets.json' doesn't have a target for 'net8.0-ios'. Ensure that restore has run and that you have included 'net8.0-ios' in the TargetFrameworks for your project.	WereAllRelated.Uno (net8.0-ios)	C:\Program Files\dotnet\sdk\8.0.303\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets	
```

I change it back to 1.0.0 and then everything runs just fine. 

### Expected behavior

I expect the version to update and accept any three part version number

### How to reproduce it (as minimally and precisely as possible)

I don't run into this problem with a blank app. I'm not sure how to reproduce without putting our whole project up here.

### Workaround

I have no workaround, currently. 

### Works on UWP/WinUI

None

### Environment

Windows 11, VS 2022

### NuGet package version(s)

Uno.WinUI: 5.3.90
Uno.Toolkit.WinUI: 6.1.8
Uno.Toolkit.WinUI.Material: 6.1.8

### Affected platforms

Android, iOS

### IDE

Visual Studio 2022

### IDE version

Version 17.10.1

### Uno Versions
Uno SDK: 5.3.31
Uno Extension: 5.3.18.22

**Comment by francoistanguay** [comment] 2024-08-08 13:22
Can you please provide a Binlog with more details about Uno version you're using? https://platform.uno/docs/articles/uno-builds-troubleshooting.html#generating-msbuild-binary-log-files

**Comment by trydalch** [comment] 2024-08-08 16:52
Yes. Here's my binlog
[msbuild.zip](https://github.com/user-attachments/files/16551128/msbuild.zip)

I'm using:

Uno SDK: 5.3.31
Uno Extension: 5.3.18.22

**Comment by dansiegel** [comment] 2024-08-12 22:16
@trydalch Thanks for including the binlog. Unfortunately this raises more questions than it does answers. I'm afraid I'm unable to reproduce your issues with the Application Display Version. Technically for Android, iOS, & MacCatalyst this is handled by the respective .NET SDK's for Android, iOS & MacCatalyst and not actually by the Uno.Sdk so it's quite strange that you would have seen any sort of issue there. 

Your binlog did highlight a couple of other issues though. 

1) While it doesn't show up as the direct cause of the build failure you do have an interesting failure in the XamlCodeGenerator. I've shared this with @Youssef1313 and he's been unable to reproduce this or see any reason why this error would be encountered.
> CSC warning CS8785: Generator 'XamlCodeGenerator' failed to generate source. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'ArgumentException' with message 'The path is not of a legal form.'. 
2) The actual failure in the application seems to be related to an issue in Resizetizer. There is an active PR for Resizetizer that when done will ultimately update things in a way that would prevent this specific failure, but it's still very strange and I'll take a look deeper into it.

In the mean time if you're able to provide a sample application that reproduces the issue that would be very helpful for us as so far we're unable to see anything that would indicate an issue with the Application Display Version changes or reproduce any of the issues that you're encountering.

**Comment by trydalch** [comment] 2024-08-13 01:44
Hey @dansiegel.

That's interesting. I've been unsuccessful at reproducing with a sample application. It's very interesting that we only run into this issue if we change the application display version. I wonder if there's some mismatch somewhere. 

We may just create a new project and move our code over.

**Comment by dansiegel** [comment] 2024-08-14 21:05
@trydalch I'm going to close this issue for now as it seems that you're unable to reproduce the issue in another project as well. If you're able to provide any more context for us to be able to reproduce the issue certainly let us know and we can always reopen the issue.

**Closed by dansiegel** 2024-08-14 21:05 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
