### ISSUE TITLE
Can't bind an event to a source generated method in WebAssembly

### ISSUE THREAD

**Issue by DCorrBECare** [unoplatform/uno#17590] opened 2024-07-17 08:55 UTC
## Current behavior
If I try to bind an event to a source generated method i get `Uno.UI.SourceGenerators.XamlGenerator.XamlParsingException` while building for Wasm, the Windows build works fine.

## Expected behavior
I can bind by generated method to an event in Wasm

## Minimal reproduction of the problem with instructions
Build the attached project.
[UnoAppWithGenerators.zip](https://github.com/user-attachments/files/16262935/UnoAppWithGenerators.zip)

## Environment

Package Version(s): 
Uno.Sdk: 5.2.175

Affected platform(s):
- [ ] iOS
- [ ] Android
- [X] WebAssembly
- [ ] Windows
- [ ] Build tasks

Visual Studio
- [x] 2022 (version: 17.10.4)
- [ ] 2022 Preview (version: )
- [ ] for Mac (version: )

**Comment by jeromelaban** [comment] 2024-07-17 20:26
Thanks for the report. This issue is a duplicate of https://github.com/unoplatform/uno/issues/14409, and is related to a behavior of the C# compiler (https://github.com/dotnet/roslyn/issues/57239).

**Closed by jeromelaban** 2024-07-17 20:26 UTC
