### ISSUE TITLE
[WPF] Textbox Binding Incorrect and Not Notifying Converter as Expected

### ISSUE THREAD

**Issue by bstrother1** [unoplatform/uno#7696] opened 2021-12-28 15:44 UTC
### Current behavior

Textbox TwoWay Binding not loading initial set value on Constructor Set and Not Notifying Converter on Text Edit. Works on UWP. 

### Expected behavior

Expected WPF to react the same as UWP where UWP loads the initial value inside the Textbox, and upon LosingFocus triggers the NotifyPropertyChange within the TwoWay Binding. Instead this works in UWP but WPF does not load the initial set and does not react to the INotifyPropertyChange. 
[UnoConverterIncorrect.zip](https://github.com/unoplatform/uno/files/7785363/UnoConverterIncorrect.zip)
 

### How to reproduce it (as minimally and precisely as possible)

1) Have an MVVM Project
2) Have a Textbox
3) Two-Way Bind TextValue and Have an attached Converter

### Works on UWP/WinUI

Yes

### Environment

Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia

### NuGet package version(s)

WPF:
PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="6.0.0"
PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="6.0.0" 
PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" 
PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0"
PackageReference Include="Splat.Microsoft.Extensions.DependencyInjection" Version="14.1.17"
PackageReference Include="Uno.UI.Skia.Wpf" Version="4.0.11"
PackageReference Include="Uno.UI.RemoteControl" Version="4.0.11" Condition="'$(Configuration)'=='Debug'" 
PackageReference Include="Uno.UI.Adapter.Microsoft.Extensions.Logging" Version="4.0.11" 
PackageReference Include="ReactiveUI.Fody" Version="17.1.9"
PackageReference Include="ReactiveUI.Uno" Version="17.1.9" 

### Affected platforms

Skia (WPF)

### IDE

Visual Studio 2022

### IDE version

17.0.4

**Comment by mikebmcl** [comment] 2022-01-03 23:47
The problem is actually for all platforms except UWP, but I believe that it's a documentation bug (along with a potential feature request).

There are a few places in the sample you provided where you aren't using Reactive UI correctly. When those are cleared up, what's going on is that the default `UpdateSourceTrigger` for `Binding` is [UpdateSourceTrigger.Default](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.data.updatesourcetrigger?view=winrt-22000), which is identical to `UpdateSourceTrigger.PropertyChanged`. However, [for TextBox.Text](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.data.binding.mode?view=winrt-22000) UWP instead uses `UpdateSourceTrigger.LostFocus`.

Uno doesn't support `UpdateSourceTrigger.LostFocus` and so on all non-UWP platforms, `TextBox.Text` has the default value instead. The Uno [TextBox Class](https://platform.uno/docs/articles/implemented/windows-ui-xaml-controls-textbox.html) documentation doesn't mention that behavior difference and I think that not mentioning it is a bug that should be fixed.

As a result of the behavior difference, on non-UWP platforms, every change made to the TextBox.Text is sent immediately to the bound property, running through the value converter, if there is one, along the way.

In the case of the sample, it goes to the value converter immediately, where an attempt will be made to parse that changed text and whatever result comes from trying to parse it will be sent back to the TextBox. If that result is different than the text in the TextBox (i..e. what was just sent), then the TextBox.Text will be updated and, because of TwoWay binding, that change will then be sent back to the value converter.

In the sample it would end up sending that same value back and that would end the cycle, frequently undoing the user's attempted change. The sample doesn't use the overload of [decimal.TryParse](https://docs.microsoft.com/en-us/dotnet/api/system.decimal.tryparse?view=net-5.0#System_Decimal_TryParse_System_String_System_Globalization_NumberStyles_System_IFormatProvider_System_Decimal__) that takes a `NumberStyles` enum argument. Without allowing for the currency symbol, decimal marker, etc., e.g. by using (NumberStyles.Currency)[https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberstyles], the parse attempt will get to the currency symbol, e.g. $, and will fail. Also, it needs an appropriate `IFormatProvider` or the [parse attempt could fail](https://docs.microsoft.com/en-us/dotnet/standard/base-types/parsing-numeric) because it would be expecting a different currency symbol or a different decimal marker, etc.

For now, I think the documentation should be updated to note the difference in behavior for `TextBox.Text` binding because that's why things worked for you on UWP but not WPF.

It would be nice if Uno supported `UpdateSourceTrigger.LostFocus`, but I don't know how difficult that would be or even if it's something that's already been requested (I imagine it has) or is under development or is too difficult to implement across all of the platforms. It seems simple in theory, just subscribe to the LostFocus event, but things are rarely that easy and TextBox is quite difficult already.

**Comment by bstrother1** [comment] 2022-01-04 00:44
> The problem is actually for all platforms except UWP, but I believe that it's a documentation bug (along with a potential feature request).
> 
> There are a few places in the sample you provided where you aren't using Reactive UI correctly. When those are cleared up, what's going on is that the default `UpdateSourceTrigger` for `Binding` is [UpdateSourceTrigger.Default](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.data.updatesourcetrigger?view=winrt-22000), which is identical to `UpdateSourceTrigger.PropertyChanged`. However, [for TextBox.Text](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.data.binding.mode?view=winrt-22000) UWP instead uses `UpdateSourceTrigger.LostFocus`.
> 
> Uno doesn't support `UpdateSourceTrigger.LostFocus` and so on all non-UWP platforms, `TextBox.Text` has the default value instead. The Uno [TextBox Class](https://platform.uno/docs/articles/implemented/windows-ui-xaml-controls-textbox.html) documentation doesn't mention that behavior difference and I think that not mentioning it is a bug that should be fixed.
> 
> As a result of the behavior difference, on non-UWP platforms, every change made to the TextBox.Text is sent immediately to the bound property, running through the value converter, if there is one, along the way.
> 
> In the case of the sample, it goes to the value converter immediately, where an attempt will be made to parse that changed text and whatever result comes from trying to parse it will be sent back to the TextBox. If that result is different than the text in the TextBox (i..e. what was just sent), then the TextBox.Text will be updated and, because of TwoWay binding, that change will then be sent back to the value converter.
> 
> In the sample it would end up sending that same value back and that would end the cycle, frequently undoing the user's attempted change. The sample doesn't use the overload of [decimal.TryParse](https://docs.microsoft.com/en-us/dotnet/api/system.decimal.tryparse?view=net-5.0#System_Decimal_TryParse_System_String_System_Globalization_NumberStyles_System_IFormatProvider_System_Decimal__) that takes a `NumberStyles` enum argument. Without allowing for the currency symbol, decimal marker, etc., e.g. by using [NumberStyles.Currency](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberstyles), the parse attempt will get to the currency symbol, e.g. $, and will fail. Also, it needs an appropriate `IFormatProvider` or the [parse attempt could fail](https://docs.microsoft.com/en-us/dotnet/standard/base-types/parsing-numeric) because it would be expecting a different currency symbol or a different decimal marker, etc.
> 
> For now, I think the documentation should be updated to note the difference in behavior for `TextBox.Text` binding because that's why things worked for you on UWP but not WPF.
> 
> It would be nice if Uno supported `UpdateSourceTrigger.LostFocus`, but I don't know how difficult that would be or even if it's something that's already been requested (I imagine it has) or is under development or is too difficult to implement across all of the platforms. It seems simple in theory, just subscribe to the LostFocus event, but things are rarely that easy and TextBox is quite difficult already.

Thank you for the reply! Do you have a link to documentation or the corrected sample handy to showcase where ReactiveUI isn't being used correctly?

**Comment by bstrother1** [comment] 2022-01-04 06:41
> The problem is actually for all platforms except UWP, but I believe that it's a documentation bug (along with a potential feature request).
> 
> There are a few places in the sample you provided where you aren't using Reactive UI correctly. When those are cleared up, what's going on is that the default `UpdateSourceTrigger` for `Binding` is [UpdateSourceTrigger.Default](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.data.updatesourcetrigger?view=winrt-22000), which is identical to `UpdateSourceTrigger.PropertyChanged`. However, [for TextBox.Text](https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.data.binding.mode?view=winrt-22000) UWP instead uses `UpdateSourceTrigger.LostFocus`.
> 
> Uno doesn't support `UpdateSourceTrigger.LostFocus` and so on all non-UWP platforms, `TextBox.Text` has the default value instead. The Uno [TextBox Class](https://platform.uno/docs/articles/implemented/windows-ui-xaml-controls-textbox.html) documentation doesn't mention that behavior difference and I think that not mentioning it is a bug that should be fixed.
> 
> As a result of the behavior difference, on non-UWP platforms, every change made to the TextBox.Text is sent immediately to the bound property, running through the value converter, if there is one, along the way.
> 
> In the case of the sample, it goes to the value converter immediately, where an attempt will be made to parse that changed text and whatever result comes from trying to parse it will be sent back to the TextBox. If that result is different than the text in the TextBox (i..e. what was just sent), then the TextBox.Text will be updated and, because of TwoWay binding, that change will then be sent back to the value converter.
> 
> In the sample it would end up sending that same value back and that would end the cycle, frequently undoing the user's attempted change. The sample doesn't use the overload of [decimal.TryParse](https://docs.microsoft.com/en-us/dotnet/api/system.decimal.tryparse?view=net-5.0#System_Decimal_TryParse_System_String_System_Globalization_NumberStyles_System_IFormatProvider_System_Decimal__) that takes a `NumberStyles` enum argument. Without allowing for the currency symbol, decimal marker, etc., e.g. by using [NumberStyles.Currency](https://docs.microsoft.com/en-us/dotnet/api/system.globalization.numberstyles), the parse attempt will get to the currency symbol, e.g. $, and will fail. Also, it needs an appropriate `IFormatProvider` or the [parse attempt could fail](https://docs.microsoft.com/en-us/dotnet/standard/base-types/parsing-numeric) because it would be expecting a different currency symbol or a different decimal marker, etc.
> 
> For now, I think the documentation should be updated to note the difference in behavior for `TextBox.Text` binding because that's why things worked for you on UWP but not WPF.
> 
> It would be nice if Uno supported `UpdateSourceTrigger.LostFocus`, but I don't know how difficult that would be or even if it's something that's already been requested (I imagine it has) or is under development or is too difficult to implement across all of the platforms. It seems simple in theory, just subscribe to the LostFocus event, but things are rarely that easy and TextBox is quite difficult already.

Going to my example I am not experiencing this described behavior:

In the case of the sample, it goes to the value converter immediately, where an attempt will be made to parse that changed text and whatever result comes from trying to parse it will be sent back to the TextBox. If that result is different than the text in the TextBox (i..e. what was just sent), then the TextBox.Text will be updated and, because of TwoWay binding, that change will then be sent back to the value converter.

If I am understanding correctly it should be:

Text Entered -> ConvertBack -> Two Way Binding -> NotifyPropertyChange -> Convert

So when I type in 200 (Which is different from the current set value of 0.00M) it should toss it to ConvertBack (Which is does) I updated the ConvertBack to just return 100.00M since this is just an example ->It then hits the setter but it never hit that last Convert call. 

Updated Converter (Messy but gets the point across):
   public object Convert(object value, Type targetType, object parameter, string language)
        {
            System.Diagnostics.Debug.WriteLine("My text " + value.ToString());
            if (value != null)
            {
                decimal result = (decimal)value;
                return result.ToString("C");
            }
            else
            {
                return null;
            }
        }


        public object ConvertBack(object value, Type targetType, object parameter, string language)
        {
            System.Diagnostics.Debug.WriteLine("In here!!!");
            return 100.00M;
        }


        System.Diagnostics.Debug.WriteLine("My text " + value.ToString()); never hits. If I am understanding it should because the Default behavior acts identical to the PropertyChange Trigger and with:


        private decimal _EnteredAmount = 0.00M;

        public decimal EnteredAmount 
        {
            get { return _EnteredAmount; }
            set
            {
               _EnteredAmount = value;
               NotifyPropertyChanged();
            }
        }

which hits and sets the _EnteredValue correctly the Convert should run one final time. Sorry if I am incorrect in this assumption. Also if you could link me to documentation or a corrected example project for the ReactiveUI I would greatly appreciate it. Thank You!

**Comment by davidjohnoliver** [comment] 2022-01-06 16:24
> Uno doesn't support `UpdateSourceTrigger.LostFocus` and so on all non-UWP platforms, `TextBox.Text` has the default value instead. The Uno [TextBox Class](https://platform.uno/docs/articles/implemented/windows-ui-xaml-controls-textbox.html) documentation doesn't mention that behavior difference and I think that not mentioning it is a bug that should be fixed.
> 
> As a result of the behavior difference, on non-UWP platforms, every change made to the TextBox.Text is sent immediately to the bound property, running through the value converter, if there is one, along the way.

This is partially correct - the `UpdateSourceTrigger.LostFocus` is marked `NotImplemented` on Uno, and it's not possible to use it on any DP.

*However* TextBox.Text is special-cased to have similar behaviour to UWP. It's actually [marked as](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs#L204) UpdateSourceTrigger.Explicit by default, and the value is pushed in TextBox's [FocusStateChanged callback](https://github.com/unoplatform/uno/blob/master/src/Uno.UI/UI/Xaml/Controls/TextBox/TextBox.cs#L704). If you're noticing different behaviour, it could be a platform-specific bug.

**Comment by mikebmcl** [comment] 2022-01-13 05:33
TextBox.Text does work correctly. I was mislead by Intellisense!

@bstrother1 I'm attaching a sample that works. It took me a little while to create because I was trying to adapt the existing code that used Microsoft's dependency injection (which is supported; I just don't have enough experience with it to get it working quickly). I then came across [the official ReactiveUI samples](https://github.com/reactiveui/ReactiveUI.Samples), which includes an Uno sample that I was able to adapt to incorporate what you were trying to do and got it working. It works fine on UWP, WASM, Skia.Gtk, Skia.Wpf, and Android. I'm unable to test it on iOS, MacOS, and Skia.Tizen, but it compiles on all of them.

Also, the buttons at the bottom won't appear on screen on Skia.Gtk/WSL or any other Gtk build that runs on Wayland windowing system right now, but a PR that fixes that has already been accepted so it should display properly when using the current preview release Uno packages and with the next stable release.

Hope it helps!

[ReactiveUIUnoSample.zip](https://github.com/unoplatform/uno/files/7860137/ReactiveUIUnoSample.zip)

**Comment by bstrother1** [comment] 2022-01-13 07:44
> TextBox.Text does work correctly. I was mislead by Intellisense!
> 
> @bstrother1 I'm attaching a sample that works. It took me a little while to create because I was trying to adapt the existing code that used Microsoft's dependency injection (which is supported; I just don't have enough experience with it to get it working quickly). I then came across [the official ReactiveUI samples](https://github.com/reactiveui/ReactiveUI.Samples), which includes an Uno sample that I was able to adapt to incorporate what you were trying to do and got it working. It works fine on UWP, WASM, Skia.Gtk, Skia.Wpf, and Android. I'm unable to test it on iOS, MacOS, and Skia.Tizen, but it compiles on all of them.
> 
> Also, the buttons at the bottom won't appear on screen on Skia.Gtk/WSL or any other Gtk build that runs on Wayland windowing system right now, but a PR that fixes that has already been accepted so it should display properly when using the current preview release Uno packages and with the next stable release.
> 
> Hope it helps!
> 
> [ReactiveUIUnoSample.zip](https://github.com/unoplatform/uno/files/7860137/ReactiveUIUnoSample.zip)

Thanks for the response! That solution seems like a good work around to this issue but I still believe this is a bug with Uno binding.

**Comment by bstrother1** [comment] 2022-05-15 08:45
To add onto this it seems like UpdateTriggers, including PropertyChange do not function in the WPF build even in the latest release. Would appreciate if someone can confirm what I am seeing. ReactiveUI is a work around that is possible but has its own set of limitations.

**Comment by jeromelaban** [comment] 2022-06-06 03:56
This issue is quite interesting as it shows a behavior difference between "normal" Bindings and `x:Bind`.

In practice, the behavior you're observing on UWP/WinUI is not possible with a normal `Binding` because source updates (the ViewModel in this case) are ignored when a two-way binding is taking place.

Conversely, source updates during a two-way `x:Bind` are propagated back to the source, which triggers the invocation of the 
 `Convert` method on the converter (with in turn updates the target, `TextBox.Text` in this case). It's important to note these transient target updates are *not* triggering a source update which would otherwise cause another loop (since the converter in the sample does not support entering the currency and fails parsing, setting the TextBox to `$0.00`).
 
 https://github.com/unoplatform/uno/pull/8974 should fix it.

**Closed** 2022-06-06 13:00 UTC
Labels: kind/bug, project/input, difficulty/medium
