### ISSUE TITLE
`FindName` doesn't return things from resources

### ISSUE THREAD

**Issue by Youssef1313** [unoplatform/uno#7258] opened 2021-10-01 05:52 UTC
### Current behavior

From `PersonPicture` sample:

```xaml
    <Grid x:Name="rootGrid" Background="{ThemeResource ApplicationPageBackgroundThemeBrush}">
		<Grid.ColumnDefinitions>
			<ColumnDefinition/>
			<ColumnDefinition/>
			<ColumnDefinition Width="*"/>
		</Grid.ColumnDefinitions>

        <Grid.Resources>
			<CollectionViewSource x:Name="cvs"/>
			<Style TargetType="StackPanel">
				<Setter Property="Margin" Value="4" />
			</Style>
			<Style TargetType="TextBlock">
				<Setter Property="VerticalAlignment" Value="Center" />
				<Setter Property="Margin" Value="0,0,4,0"/>
			</Style>
		</Grid.Resources>

```

Calling `rootGrid.FindName("cvs")` returns null.

### Expected behavior

Shouldn't return null.

**Comment by MartinZikmund** [comment] 2023-07-19 06:40
Duplicate of #7043

**Closed by MartinZikmund** 2023-07-19 06:40 UTC
Labels: kind/bug, project/resources, difficulty/tbd
