### ISSUE TITLE
[Gallery][Android/iOS]<Flyout>In "Help" section, When clicking "Send Feedback" option, the Gallery app Freeze.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#5104] opened 2021-02-02 14:35 UTC
**How to reproduce it**
**Steps For iOS** (Issue is having in both Material and Fluent)

1. Open Uno Gallery APP for canary.
2. Click "Flyout" option from Burger Menu.
3. Click “Help” Button in “Nested MenuFlyout ” section.
4. Click "Send Feedback" option 
5. Observe the app freezes.

**Steps for Android** ( Issue is having in Material)

1. Open Uno Gallery APP for canary.
2. Click "Flyout" option from Burger Menu.
3. Click “Help” Button in “Nested MenuFlyout ” section.
4. Click "Send Feedback" option.
5. Click "settings" option.
6. Observe the app freezes.

**Actual Result:**
After clicking "settings" option in "Help" section the app freezes.

**Expected Result:**
After clicking "settings" option in "Help" section it should display nested flyout options.

**Attachment:
Current behavior**
![flyout freeze issue](https://user-images.githubusercontent.com/74563602/106614309-2ac49680-6539-11eb-88c2-d09479619c06.png)

**Expected behavior**
![flyout freeze correct](https://user-images.githubusercontent.com/74563602/106614318-2dbf8700-6539-11eb-86df-00e8b99cb89d.png)

**Version(s):**
Version 1.4.3 (642) for iOS
Version 1.4.3 (400640) for Android

**Device:**
iphone 12 - 14.1
Samsung S8 - 8.0
Motorola g(7) – 9

**Affected platform(s):**
iOS
Android

**Comment by jeromelaban** [comment] 2021-02-02 19:25
```
2021-02-02 14:24:41.272585-0500 Uno.Gallery[6118:13999222] \^[[41m\^[[30mfail\^[[39m\^[[22m\^[[49m: Windows.UI.Xaml.UIElement[0]
      Failed to raise 'PointerReleasedEvent': System.NullReferenceException: Object reference not set to an instance of an object
        at Windows.UI.Xaml.Controls.Popup.RegisterPopupPanelChild (System.Boolean force) [0x00012] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Popup\Popup.iOS.cs:88 
        at Windows.UI.Xaml.Controls.Popup.OnIsOpenChanged (System.Boolean oldIsOpen, System.Boolean newIsOpen) [0x0000b] in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Popup\Popup.iOS.cs:129 
        at Windows.UI.Xaml.Controls.PopupBase+<>c.<.cctor>b__68_0 (Windows.UI.Xaml.DependencyObject s, Windows.UI.Xaml.DependencyPropertyChangedEventArgs e) [0x00000] in C:\a\1\s\src\Uno.UI\Mixins\DependencyPropertyMixins.g.cs:138 
        at Windows.UI.Xaml.PropertyMetadata.RaisePropertyChanged (Windows.UI.Xaml.DependencyObject source, Windows.UI.Xaml.DependencyPropertyChangedEventArgs e) [0x00000] in C:\a\1\s\src

```

**Comment by robloo** [comment] 2021-02-03 19:38
Is this related to or a duplicate of #4795 I wonder?

**Comment by sakshi173** [comment] 2021-02-07 02:18
App is not freezing, but the nested flyout position is incorrect when Clicking the settings button. Due to that reason Reopening the Bug.
![nested flyout issue](https://user-images.githubusercontent.com/74563602/107134511-b84d1100-68c0-11eb-9b63-b8f93923480d.png)

**Comment by jeromelaban** [comment] 2021-02-08 14:55
The application is not freezing anymore, but the issue is not the same. I'll open a different issue for the flyout placement.

**Closed by jeromelaban** 2021-02-08 14:55 UTC
Labels: area/canary, kind/regression, platform/android, platform/ios

**Comment by sakshi173** [comment] 2021-02-10 21:27
Verified,  Freezing Issue is Fixed -- Closing
