### ISSUE TITLE
Nullable reference types break markup extensions

### ISSUE THREAD

**Issue by MartinZikmund** [unoplatform/uno#4591] opened 2020-11-22 12:53 UTC
## Current behavior

When a property of a markup extensions is a nullable reference type, XAML code generation fails.

## Expected behavior

Should not fail.

## How to reproduce it (as minimally and precisely as possible)

Create a simple extension:

```
public class Localize : MarkupExtension
{
    public string? Key { get; set; }

    protected override object ProvideValue()
    {
        return Key;
    }
}
```

Import namespace and use it on a `Page`:

```
<TextBlock Text="{extensions:Localize Key=Hello}" Margin="20" FontSize="30" />
```

And set `<Nullable>enable</Nullable>` and `<LangVersion>8.0</LangVersion>` in UWP and WASM project.

Notice that in UWP app compiles and "Hello" is displayed. In WASM, `AggregateException` is thrown with the following inner message:

> Unable to convert Hello for Key with type string? ---> System.Exception: Unable to convert Hello for Key with type string?

## Workaround

Avoid using nullable reference types in markup extensions.

## Environment

Nuget Package:

- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other: 

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [x] Build tasks
- [ ] Solution Templates

**Comment by Youssef1313** [comment] 2021-08-02 07:54
I'm not able to reproduce. @MartinZikmund Can you please check if this has been already fixed or attach a zipped repro? Thanks.

**Comment by Youssef1313** [comment] 2021-08-09 18:16
I don't know why I'm not able to reproduce, but the bug seems to indeed exist and being fixed in https://github.com/unoplatform/uno/pull/6691.

**Closed** 2021-08-24 20:55 UTC
Labels: kind/bug, area/code-generation, project/core-tools, difficulty/medium, area/eu
