### ISSUE TITLE
Error in Visual Studio when Project Name contains spaces

### ISSUE THREAD

**Issue by Ultra-max99** [unoplatform/uno#5928] opened 2021-05-05 01:29 UTC
## Current behavior

When creating a Uno Platform App which contains spaces in Visual Studio, ex "Example App" an error occurs, saying that the MacOS, UWP, Droid and iOS projects were unavailable because of some file missing.

## Expected behavior

The desired behavior would be no error, with a successful project creation.

## How to reproduce it (as minimally and precisely as possible)

Create a "Cross Platform App (Uno Platform)" using the template in Visual Studio, and give it a name with spaces, like so:
![image](https://user-images.githubusercontent.com/80412399/117088008-180f5880-ad06-11eb-98ad-578379680554.png)
The following errors will occur:
![image](https://user-images.githubusercontent.com/80412399/117088051-37a68100-ad06-11eb-9196-ea16ee97e7ec.png)
![image](https://user-images.githubusercontent.com/80412399/117088079-45f49d00-ad06-11eb-9e90-2be7d2f43927.png)
![image](https://user-images.githubusercontent.com/80412399/117088089-4f7e0500-ad06-11eb-8bd5-8b298b7b4b02.png)
![image](https://user-images.githubusercontent.com/80412399/117088100-5a389a00-ad06-11eb-9d07-98c04cb15a3d.png)

## Workaround

The only workaround is to not name your project with spaces.

## Environment

Affected platform(s):

- [x] Solution Templates

IDE:

- [x] Visual Studio 2019 (version: 16.9 )

**Comment by jeromelaban** [comment] 2021-05-05 01:56
Thanks for the report! This issue is a duplicate of https://github.com/unoplatform/uno/issues/806.

**Closed by jeromelaban** 2021-05-05 01:56 UTC
Labels: difficulty/tbd, kind/bug, triage/untriaged
