### ISSUE TITLE
NavigationView makes Uno 3.3 crash

### ISSUE THREAD

**Issue by vadd98** [unoplatform/uno#4605] opened 2020-11-24 21:56 UTC
## Current behavior

Inserting a NavigationView in a xaml and building a UWP, Windows Package or Wasm make the app crash as soon as the page with the NavigationView is reached.

## Expected behavior

NavigationView would have not to crash the app.

## How to reproduce it (as minimally and precisely as possible)

Insert a NavigationView in a xaml. Example of my code:
`<Page
    x:Class="App.MainPage"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    mc:Ignorable="d" xmlns:winui="using:Microsoft.UI.Xaml.Controls">

    <winui:NavigationView >
        <winui:NavigationView.MenuItems>
            <winui:NavigationViewItem Content="Main" Icon="Home" />
        </winui:NavigationView.MenuItems>
    </winui:NavigationView>

</Page>`

## Workaround

Nothing yet.

## Environment

Windows 10 1909.

Nuget Package:
- [x] Uno.UI / Uno.UI.WebAssembly / Uno.UI.Skia
- [ ] Uno.WinUI / Uno.WinUI.WebAssembly / Uno.WinUI.Skia
- [ ] Uno.SourceGenerationTasks
- [ ] Uno.UI.RemoteControl / Uno.WinUI.RemoteControl
- [ ] Other:

Nuget Package Version(s):

Affected platform(s):

- [ ] iOS
- [ ] Android
- [x] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [x] Windows
- [ ] Build tasks
- [ ] Solution Templates

IDE:

- [ ] Visual Studio 2017 (version: )
- [x] Visual Studio 2019 (version: )
- [ ] Visual Studio for Mac (version: )
- [ ] Rider Windows (version: )
- [ ] Rider macOS (version: )
- [ ] Visual Studio Code (version: )

Relevant plugins:

- [ ] Resharper (version: )

**Comment by jeromelaban** [comment] 2020-11-25 01:41
Thanks for the report!

At this point, the WinUI navigation view is not yet implemented, though you can use the UWP `NavigationView`. This is a duplicate of #3942.

**Closed by jeromelaban** 2020-11-25 01:41 UTC
Labels: kind/bug, triage/untriaged
