### ISSUE TITLE
Cannot send client certificate from the IApiEndpointQueryContext / IServiceLocator ?

### ISSUE THREAD

**Issue by ac2021-June** [unoplatform/uno#7967] opened 2022-02-01 17:26 UTC
### Current behavior

Not able to send client certificate from the IApiEndpointQueryContext / IServiceLocator.

### Expected behavior

Should be able to send client certificate from the IApiEndpointQueryContext / IServiceLocator.

### Affected platforms

iOS, Android

### IDE

Visual Studio 2019

**Comment by jeromelaban** [comment] 2022-02-01 18:09
Closed as duplicate of https://github.com/unoplatform/uno/discussions/7966

**Closed by jeromelaban** 2022-02-01 18:09 UTC
Labels: kind/bug, triage/untriaged, difficulty/tbd
