### ISSUE TITLE
[Gallery][Android]MessageDialog- For Message dialog buttons are displaying as text.

### ISSUE THREAD

**Issue by sakshi173** [unoplatform/uno#8843] opened 2022-05-20 18:30 UTC
### Current behavior

![messagedialog issue](https://user-images.githubusercontent.com/74563602/169588836-ffcf7b92-f0bc-44ae-bac4-fc44d7fbb9ee.png)

### Expected behavior

![Message dialog](https://user-images.githubusercontent.com/74563602/169588851-da9db258-b336-4b10-804e-b91961d4c42e.png)

### How to reproduce it (as minimally and precisely as possible)

1. Open Uno Gallery APP
2. Tap Burger Menu on the left top right.
3. Tap "MessageDialog" from the "Features" list.
4. Tap on the "Content Only"  section.
5. Observe that the Close Button is displaying text and the Message and the buttons are not dividing with the line.

### Affected platforms

Android

**Comment by agneszitte-nventive** [comment] 2022-06-13 23:39
@sakshi173 This is not a bug as MessageDialog is using the native display and it's different depending on the platform. 
So for Android, it's supposed to look like that. Closing this bug.
(cc @jeromelaban)

**Closed by agneszitte-nventive** 2022-06-13 23:39 UTC
Labels: kind/bug, platform/android, triage/untriaged, area/canary, difficulty/tbd

**Comment by sakshi173** [comment] 2022-06-17 12:57
As @agneszitte-nventive suggested, this is not a bug, closing it.
