### ISSUE TITLE
Incremental loading collection does not work

### ISSUE THREAD

**Issue by ericleroy01** [unoplatform/uno#5982] opened 2021-05-11 07:56 UTC
## Describe the bug
incremental loading collection does not load item pages (only first one)

- [ ] Is this bug a regression in the toolkit?  If so, what toolkit version did you last see it work:

## Steps to Reproduce

- [ ] Can this be reproduced in the Sample App? (Either in a sample as-is or with new XAML pasted in the editor.) If so, please provide custom XAML or steps to reproduce. If not, let us know why it can't be reproduced (e.g. more complex setup, environment, dependencies, etc...) 

1. Create a new Uno project
2. Add PeopleSource.cs & Person.cs from Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Incremental Loading Collection samples
3. edit mainpage.xaml & add a Listview control

`<ListView x:Name="PeopleListView">
<ListView.ItemTemplate>
        <DataTemplate>
            <Grid>
              <TextBlock Grid.Column="1"
                           Margin="10"
                           VerticalAlignment="Center"
                           Foreground="White"
                           Text="{Binding Name}" />
            </Grid>
        </DataTemplate>
    </ListView.ItemTemplate>
</ListView>
`

4. edit mainpage.xaml.cs & modify contructor or OnNavigatedTo event (ex: Microsoft.Toolkit.Uwp.SampleApp/SamplePages/Incremental Loading Collection/IncrementalLoadingCollectionPage.xaml.cs)
`
            var collection = new IncrementalLoadingCollection<PeopleSource, Person>();
            PeopleListView.ItemsSource = collection;
 `
5. only 20 items are loading. scrolling does not add new items

## Environment

NuGet Package(s): 
- [X] Uno.UI 3.7.3
- [X] Uno.Microsoft.Toolkit 7.0.0
- [x] Uno.Microsoft.Toolkit.Uwp 7.0.0

Package Version(s): 

Device form factor:
- [ ] Windows
- [X] macOS
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms

Visual Studio 
- [ ] 2017 (version: )
- [X] 2019 for Mac (version: 8.9.8 build 7) 
- [ ] 2019 Preview (version: )

**Comment by jeromelaban** [comment] 2021-05-13 12:31
This issue is a duplicate of https://github.com/unoplatform/uno/issues/5763, which uses a shared codebase with WebAssembly and Skia based backends.

**Closed by jeromelaban** 2021-05-13 12:31 UTC
Labels: difficulty/medium, kind/bug, project/items
