### ISSUE TITLE
Implement Windows.Devices.Radios.GetRadios

### ISSUE THREAD

**Issue by pkar70** [unoplatform/uno#5660] opened 2021-04-02 15:03 UTC
## What would you like to be added:
Windows.Devices.Radios.GetRadios

## Why is this needed:
To check if Bluetooth (or other Radios) are available.

## For which Platform:

- [ ] iOS
- [X] Android
- [ ] WebAssembly
- [ ] WebAssembly renderers for Xamarin.Forms
- [ ] macOS
- [ ] Skia
  - [ ] WPF
  - [ ] GTK (Linux)
  - [ ] Tizen
- [ ] Windows
- [ ] Build tasks
- [ ] Solution Templates

**Comment by MartinZikmund** [comment] 2021-06-04 06:34
Duplicate of #3176

**Closed by MartinZikmund** 2021-06-04 06:34 UTC
Labels: difficulty/tbd, kind/enhancement, triage/untriaged
